freifunk-gluon/gluon

- docs/user/supported_devices.rst
- package/gluon-core/luasrc/usr/lib/lua/gluon/platform.lua
- targets/ath79-generic
> Add support for tp-link CPE510 V2

- package/gluon-mesh-batman-adv/files/lib/gluon/state/check.d/has_default_gw4
- package/gluon-mesh-batman-adv/files/lib/gluon/state/check.d/has_neighbours
This is a follow-up on #2245,
that contains the mesh-protocol dependent code that was split off it.
> gluon-mesh-batman-adv: implement checks

- package/gluon-status-page/files/lib/gluon/status-page/view/status-page.html
I fell like showing the Downstream Limit first is what most people would expect. 
Additionally, the ⌛ that would be created is more in line with what these settings are doing. ;)
cc @AiyionPrime (I think I had this comment before, but decided not to pursue it. Well, I guess that has changed now.)
> gluon-status-page: swap bandwidth limits

- docs/user/supported_devices.rst
- package/gluon-core/luasrc/usr/lib/lua/gluon/platform.lua
- targets/ath79-generic
Supported Since OpenWRT Commit: [4f86edf477edbc0f20b5a49a69f658fa82158284](https://git.openwrt.org/?p=openwrt/openwrt.git;a=commit;h=4f86edf477edbc0f20b5a49a69f658fa82158284)
- ssh into target device with recent (>= v1.6.0) firmware
- run `cliclientd stopcs` on target device
- upload factory image via web interface.
root@64xxx-60a4b76b1488:~# lua -e 'print(require("platform_info").get_image_name())'
tp-link-eap225-outdoor-v1
- led mapping
- radio leds _NONE_
- switchport leds _NONE_
cc @blocktrron
> ath79-generic: add support for TP-Link EAP225-Outdoor v1

- docs/user/supported_devices.rst
- targets/ipq40xx-generic
Tutorial in OpenWRT commit message https://git.openwrt.org/?p=openwrt/openwrt.git;a=commit;h=c6e972c8772a628a1a2f2e5590d7c6f4acef9ab0
root@Aruba-AP-303H:~# lua -e 'print(require("platform_info").get_image_name())'
aruba-ap-303h
- led mapping
- radio leds
- ToDo (upstream):
- enable PoE pass through on interface E3
system.poe_passthrough=gpio_switch
system.poe_passthrough.name='PoE Passthrough'
system.poe_passthrough.gpio_pin='446'
system.poe_passthrough.value='0' (0 is active)
> ipq40xx: add support for Aruba AP-303H / Instant ON AP11D

- docs/user/supported_devices.rst
- targets/ramips-mt76x8
Supported Since OpenWRT Commit: [b30f2281cce6649567e0194d203f06517d173115](https://git.openwrt.org/?p=openwrt/openwrt.git;a=commit;h=b30f2281cce6649567e0194d203f06517d173115)
root@ffrn-9483c409b99c:~# lua -e 'print(require("platform_info").get_image_name())'
gl.inet-microuter-n300
- led mapping
- radio leds
- switchport leds _NONE_
> ramips-mt76x8: add support for GL.iNet microuter-N300

- docs/user/supported_devices.rst
- targets/ath79-generic
The device appears to be working properly and the latest build is running on [http://[2a02:790:ff:1014:42a3:6bff:fec1:199b]/cgi-bin/status](http://[2a02:790:ff:1014:42a3:6bff:fec1:199b]/cgi-bin/status) in hanover.
_GitHubs IPv6-support appears to suck even more now..._
The device itself has no ethernet-port, but works as intended, when mounted on an expansionboard.
https://github.com/freifunk-gluon/gluon/commit/a44a5dce02de3738944b7ee742e5bc2fa068c939
I'm not sure, what configuration issues the ar71xx-variant had, but cannot confirm them in ath79, yet.
@NeoRaider do you remember, how to reproduce the error, looking at the mentioned commit?
If the removable ethernetport is alone enough to mark the device as broken,
we should add `broken = true, -- no Ethernet` to the device definition. …
> ath79-generic: add support for Onion Omega

- package/gluon-core/check_site.lua
- package/gluon-ebtables-source-filter/check_site.lua
- package/gluon-l3roamd/check_site.lua
- Move site check for prefix4 and extra_prefixes6 to gluon-core, so the
rules don't need to be duplicated in several packages. This also fixes
gluon-respondd not checking extra_prefixes6 at all when
gluon-ebtables-source-filter is not installed as well.
- A redundant check for prefix6 is removed from gluon-l3roamd (this was
already checked by gluon-core)
- A separate check for prefix4 remains in gluon-client-bridge, as the
setting in mandatory there
> treewide: clean up site checks for prefix[46] and extra_prefixes6

- contrib/ci/minimal-site/site.conf
- docs/site-example/site.mk
We saw a kconfig option that had no value set and we assume this is due to crypto (openssl?) in our site. Since this should be a reasonable default these days, let's enable OWE and WPA3 support in the minimal site used in the CI.
> SHA-224/SHA-256 digest algorithm (ARMv8 Crypto Extensions) (CRYPTO_SHA2_ARM64_CE) [N/m/y/?] (NEW) hexa@build:~$
> contrib/ci/minimal-site: build with owe and wpa3 support

- package/gluon-config-mode-geo-location/i18n/de.po
- package/gluon-config-mode-geo-location/i18n/fr.po
- package/gluon-web-wifi-config/i18n/de.po
- package/gluon-web-wifi-config/i18n/fr.po
Before this commit, some *.po files contained the same translation
twice within the same file. While this did not led to errors in
gluon yet, it is still invalid. This commit fixes that and removes
the duplicates.
> treewide: remove duplicate i18n translations

- docs/user/supported_devices.rst
- targets/ramips-mt7621
as described in openwrt commit https://git.openwrt.org/?p=openwrt/openwrt.git;a=commit;h=fb4d7a9680117a00721936c98ce41eeb2dea95c9
```
Installation
------------
1. Connect to the booted device at 192.168.1.20 using username/password
"ubnt".
2. Update the bootloader environment.
$ fw_setenv devmode TRUE
$ fw_setenv boot_openwrt "fdt addr \$(fdtcontroladdr);
fdt rm /signature; bootubnt"
$ fw_setenv bootcmd "run boot_openwrt"
3. Transfer the OpenWrt sysupgrade image to the device using SCP.
4. Check the mtd partition number for bs / kernel0 / kernel1
$ cat /proc/mtd
5. Set the bootselect flag to boot from kernel0
$ dd if=/dev/zero bs=1 count=1 of=/dev/mtdblock4
6. Write the OpenWrt sysupgrade image to both kernel0 as well as kernel1
$ dd if=openwrt.bin of=/dev/mtdblock6
$ dd if=openwrt.bin …
```
> ramips-mt7621: add support for Ubiquiti UniFi 6 Lite

- package/features
- package/gluon-mesh-vpn-core/files/lib/netifd/proto/gluon_wireguard.sh
- package/gluon-mesh-vpn-core/luasrc/lib/gluon/upgrade/500-mesh-vpn
- package/gluon-mesh-vpn-wireguard/Makefile
- package/gluon-mesh-vpn-wireguard/check_site.lua
- package/gluon-mesh-vpn-wireguard/files/lib/gluon/mesh-vpn/wireguard_pubkey.sh
- package/gluon-mesh-vpn-wireguard/luasrc/lib/gluon/upgrade/400-mesh-vpn-wireguard
- package/gluon-mesh-vpn-wireguard/luasrc/usr/lib/lua/gluon/mesh-vpn/provider/wireguard.lua
- package/gluon-mesh-vpn-wireguard/src/Makefile
- package/gluon-mesh-vpn-wireguard/src/respondd.c
- patches/openwrt/0005-package-uci-backport-cli-add-option-for-changing-save-path.patch
- patches/openwrt/0006-wireguard-tools-allow-generating-private_key-v3.patch
These patches implement wireguard vpn based on #2163 and the wgpeerselector in https://github.com/freifunk-gluon/packages/pull/240 .
Docs have not been written yet. This can be made up once the PR is approved. Some documentation regarding the wgpeerselector is available in https://github.com/freifunk-gluon/packages/pull/240 .
Related Work:
- https://github.com/freifunk-gluon/gluon/pull/1534
- https://github.com/freifunk-gluon/gluon/pull/2102
- https://github.com/freifunkMUC/community-packages/blob/gluon-mesh-vpn-wireguard-vxlan/gluon-mesh-vpn-wireguard-vxlan/files/lib/gluon/gluon-mesh-wireguard-vxlan/checkuplink
Feel free to discuss.
> Add package gluon-mesh-vpn-wireguard using wgpeerselector

- patches/openwrt/0020-ipq40xx-add-support-for-Plasma-Cloud-PA1200.patch
- patches/openwrt/0021-ipq40xx-add-support-for-Plasma-Cloud-PA2200.patch
It was noticed that various devices had not the correct board-2.bin installed. This was caused by a typo in the package name. The ath10k driver (unfortunately) is then loading a completely unrelated BDF from the ath10k-board-qca4019 board-2.bin. It is
usually a rather bad idea to use calibration data from a different board - but the effects depend on the actual device.
For the PA1200, it was mostly noticed by the bad 2.4GHz performance.
Upstream PR is https://github.com/openwrt/openwrt/pull/4538
> v2021.1.x: ipq40xx: Fix automatic ipq-wifi selection for Plasma Cloud devices

- .github/filters.yml
- Makefile
- contrib/actions/generate-target-filters.py
- targets/x86.inc
Since we're discarding the ext4 images anyways, we now stop building 
them as well and save a few seconds of build time.
> x86: don't build ext4 images

- docs/user/supported_devices.rst
- targets/ath79-generic
- led mapping
- radio leds
- switchport leds (none present)
- outdoor devices only (none)
> ath79-generic: add support for Enterasys WS-AP3705i

- package/gluon-ebtables-filter-ra-dhcp/luasrc/lib/gluon/ebtables/200-dir-dhcpv4
In meshes without VPN or supernodes, it may be desirable to connect a
router providing IPv4 addresses directly to a regular Gluon node. For
this to work, it was necessary to remove the gluon-ebtables-filter-ra-dhcp
package from the node, so the autoupdater also needed to be disabled.
To avoid this, make gluon-ebtables-filter-ra-dhcp disable the DHCPv4
filter rules when gw_mode is set to 'server'.
No solution is provided for RA/DHCPv6, but this seems less pressing for
local meshes, as nodes can already provide working IPv6 connectivity
by themselves through gluon-radvd.
> gluon-ebtables-filter-ra-dhcp: disable DHCPv4 filter when gw_mode == 'server'

- package/gluon-client-bridge/luasrc/lib/gluon/upgrade/320-gluon-client-bridge-wireless
- package/gluon-config-mode-outdoor/luasrc/lib/gluon/config-mode/wizard/0250-outdoor.lua
- package/gluon-core/luasrc/lib/gluon/upgrade/180-outdoors
- package/gluon-core/luasrc/usr/lib/lua/gluon/platform.lua
- package/gluon-core/luasrc/usr/lib/lua/gluon/wireless.lua
- package/gluon-web-private-wifi/luasrc/lib/gluon/config-mode/controller/admin/privatewifi.lua
- package/gluon-web-private-wifi/luasrc/lib/gluon/config-mode/model/admin/privatewifi.lua
- package/gluon-web-wifi-config/luasrc/lib/gluon/config-mode/controller/admin/wifi-config.lua
- package/gluon-web-wifi-config/luasrc/lib/gluon/config-mode/model/admin/wifi-config.lua
Implementation for #2311 + cleanup for a few things I noticed. Tested on an x86-64 VM without WLAN and a TL-WDR3600.
One downside of this change is that each time an Advanced Settings page is generated, two additional UCI contexts are created, each parsing `/etc/config/wireless`, as there is no common UCI context for gluon-web controllers. As the node is not under load in config mode, this should be fine - I haven't noticed any performance issues on the TL-WDR3600.
> Hide WLAN config on devices without WLAN + related cleanup

- package/gluon-config-mode-outdoor/luasrc/lib/gluon/config-mode/wizard/0250-outdoor.lua
- package/gluon-core/luasrc/lib/gluon/upgrade/005-wireless-migration
- package/gluon-core/luasrc/lib/gluon/upgrade/200-wireless
- package/gluon-core/luasrc/usr/lib/lua/gluon/wireless.lua
- package/gluon-web-wifi-config/luasrc/lib/gluon/config-mode/model/admin/wifi-config.lua
OpenWrt recently backported a number of changes to the wireless setup scripts to 21.02, breaking our wireless configuration.
- Change our code to use the new option (by @blocktrron, added commit message)
- Add migration code
> Adjust for OpenWrt hwmode -> band wireless config change

- package/gluon-ebtables-limit-arp/src/gluon-arp-limiter.c
- package/gluon-ebtables-limit-arp/src/gluon-arp-limiter.h
Declare the clock variable as extern in the header file.
Fixes compilation of gluon-ebtables-limit-arp with OpenWrt master:
multiple definition of `clock'; /gluon/openwrt/tmp/ccuynR0G.o:(.bss+0x230): first defined here
> gluon-ebtables-limit-arp: declare clock as extern

- package/gluon-respondd/luasrc/lib/gluon/upgrade/400-respondd-firewall
announced was renamed to respondd in 2016. Let's remove the obsolete
migration code.
> gluon-respondd: remove obsolete migration from upgrade script

- .editorconfig
- docs/dev/basics.rst
- docs/dev/debugging.rst
- docs/dev/packages.rst
- docs/features/autoupdater.rst
- docs/features/multidomain.rst
- docs/features/vpn.rst
- docs/package/gluon-mesh-batman-adv.rst
- docs/package/gluon-scheduled-domain-switch.rst
- docs/releases/v2015.1.rst
- docs/releases/v2016.1.5.rst
- docs/releases/v2019.1.1.rst
- docs/releases/v2019.1.2.rst
- docs/releases/v2019.1.3.rst
- docs/releases/v2019.1.rst
- docs/releases/v2020.1.1.rst
- docs/releases/v2020.1.2.rst
- docs/releases/v2020.1.3.rst
- docs/releases/v2020.1.rst
- docs/user/getting_started.rst
- docs/user/site.rst
RST files were using 1/2/3/4/7 spaces for indentation. 2 was the most common, so that is what I've changed the rest to.
> docs: consistent indentation + minor fixes

- README.md
Since hackint started offering a Matrix Bridge once again this should be documented as a contact option.
> README.md: add link to Matrix room

- scripts/container.sh
I'm sure there are better solutions. I just want to put the simplest and fastest one I can think of with the PR up for discussion. 
An interesting solution I could think of would be to get a hash of the Dockerfile and tag the container with it. But that would probably be a bit over engineered and in itself error prone.
resolves #2362
> scripts/container.sh: allow for empty Branch Names

- package/gluon-status-page/files/lib/gluon/status-page/view/status-page.html
The network.wireless status ubus call only returns the configured
channel from UCI, breaking the status page in outdoor mode, where the
configuration contains 'auto' instead of a number.
Fixes: 0d3fa6b59be7 ("gluon-status-page: use ubus to get radio channels")
Closes #2336
(apply on top of #2338 to get a usable configuration for testing)
> gluon-status-page: use UCI + iwinfo to get channel information

- Makefile
- docs/multidomain-site-example/site.mk
- docs/site-example/site.mk
- docs/user/getting_started.rst
- docs/user/site.rst
- scripts/target_lib.lua
- Remove obsolete `sysupgrade_image` and `factory_image` target DSL handlers
- Add default for GLUON_DEPRECATED
> Target build cleanup

- package/gluon-core/luasrc/usr/bin/gluon-info
- package/gluon-mesh-vpn-fastd/luasrc/usr/lib/lua/gluon/mesh-vpn/provider/fastd.lua
- package/gluon-mesh-vpn-wireguard/luasrc/usr/lib/lua/gluon/mesh-vpn/provider/wireguard.lua
- package/gluon-web-admin/files/lib/gluon/config-mode/view/admin/info.html
This copies the code from web-admin and uses it to create a neat 
cli-accessible summary about a node
This could also be extended or possibly have all the data the status 
page has (the one when the node is no longer in config mode9
Example
```
Hostname				gluon-b0a7b902343c
MAC address				b0:a7:b9:02:34:3c
Hardware model				TP-Link CPE210 v3
Gluon version / Site version		v2021.1-309-g9085237 / 8ed7e6a
Firmware release			0.0+exp20220109
Site					Funkfeuer Graz
Public VPN key				nil
```
(tabs display properly in terminal - in retrospect not sure if spaces would've been better)
> gluon-core: add gluon info binary

- docs/user/supported_devices.rst
- package/gluon-core/luasrc/lib/gluon/upgrade/010-primary-mac
- targets/ath79-generic
This is my first contribution, so please tell me if I did something incorrectly.
- led mapping
- radio leds
> ath79-generic: add support for TP-Link Archer A7 v5

- package/gluon-core/luasrc/lib/gluon/upgrade/020-interfaces
Swap the interfaces so than the PoE input port LAN0 is used for WAN and
config mode, and LAN1 becomes LAN.
To this end, the code previously used for ar71xx and removed in
commit 9fdc57c175b4 ("treewide: drop ar71xx platform specific code") is
reintroduced.
Fixes #2384
> ath79-generic: swap interfaces on TP-Link WBS210 v2

- .github/workflows/backport.yml
By applying a label `backport <branch>` the action will automatically
try to cherry-pick the change to the target branch after the pull
request was successfully merged.
> workflows: add backports action

- contrib/push_pkg.sh
- scripts/lint-sh.sh
Our CI currently uses shellcheck 0.7.0. shellcheck 0.7.1 (used by `make container`) and 0.7.2 (current version) report different errors each for some of our current scripts. Fix these issues (one by fixing the script, the other by ignoring certain warnings).
> lint-sh fixes

- .github/workflows/lint.yml
- package/gluon-web-admin/files/lib/gluon/config-mode/view/admin/upgrade.html
- package/gluon-web-admin/files/lib/gluon/config-mode/view/admin/upgrade_confirm.html
- package/gluon-web-model/files/lib/gluon/web/view/model/form.html
- package/gluon-web/luasrc/usr/lib/lua/gluon/web/dispatcher.lua
- package/gluon-web/luasrc/usr/lib/lua/gluon/web/http/protocol.lua
It is currently possible for malicious sites to inject POST requests, allowing to change settings on nodes in config mode that are reachable from the client's host. A simple PoC can be found under https://home.universe-factory.net/neoraider/gluon-cors.html (note that you will need to allow mixed content to make the HTTPS -> HTTP request work - an actual attacker would simply host the site on HTTP). My example simply changes the fastd mode from "security" to "performance", but uploading an SSH key would be just as simple.
I did not actually test the HTTPS code path, but I used curl to simulate various different Origin headers (including different ports and schemes) and tested using the config mode both without and with redirects TCP from Firefox and Chrome, including manual firmware …
> gluon-web: prohibit cross-origin POST requests

- targets/x86-64
- targets/x86-generic
For regular use, a full disk image is always recommended, as it is
required to support sysupgrades.
During development or for automated tests, separate images for the
kernel and rootfs may be useful to pass additional kernel cmdline or use
nfsroot/virtiofs. The rootfs is only available as a (squashfs)
filesystem image, not as a TAR archive (the TAR archive in OpenWrt's bin
directory does not contain DEVICE_PACKAGES, so it is missing most of
Gluon's packages).
As suggested in #2355.
> x86: copy separate kernel and rootfs images to "other" directory

- patches/packages/packages/0001-perl-don-t-build-in-parallel-and-bump-release.patch
Prevents spurious build failures.
Fixes: https://github.com/openwrt/packages/issues/8238
Upstream PR: https://github.com/openwrt/packages/pull/17274
> patches: build perl single-threaded

- docs/user/site.rst
- package/gluon-web-osm/luasrc/usr/lib/lua/gluon/web/model/osm.lua
The OpenLayers JS/CSS download URL is dead. Update it to make the map
work again:
- Update from OpenLayers 5.2.0 to 5.3.0
- Switch from the obsolete rawgit.com URL to jsdelivr.net (rawgit.com
was only redirecting to jsdelivr.net for the last few years anyways)
- Set a fixed commit in the URL, so the URL doesn't become outdated again
Reported-by: @AiyionPrime 
I have not looked into updating to a 6.x release yet. For a v2021.1.x backport, the minor 5.3.0 update makes more sense anyways.
> gluon-web-osm: update OpenLayers default URL to 5.3.0

- package/gluon-web-osm/files/lib/gluon/web/view/model/osm/map.html
When configuring osm and setting the `tile_layer` `attributions` value to a content that contains `"` the resulting config gets json encoded (as expected) which escapes it with `\"`, This seems to be invalid xhtml which can be fixed by wrapping the code in a `CDATA`.
example config:
```
geo_location = {
show_altitude = false,
osm = {
center = {
lat = 50.1103,
lon = 8.6821,
},
zoom = 11,
openlayers_url = 'https://firmware.ffffm.net/openlayers/v5.3.0',
tile_layer = {
type = 'XYZ',
url = 'https://tiles.ffm.freifunk.net/{z}/{x}/{y}.png',
attributions = '&#169; <a href="https://www.openstreetmap.org/copyright" target="_blank">OpenStreetMap</a> contributors.',
},
},
},
},
```
(Error in a up to date Firefox while trying to visit the initial config page)
> gluon-web-osm: Fix " rendering in attribution with CDATA tag

- package/gluon-config-mode-core/luasrc/lib/gluon/config-mode/model/gluon-config-mode/wizard.lua
The stdout output of gluon-web scripts is directly sent to uhttpd,
becoming a part of the HTML output or even replacing HTTP status or
headers. The output of gluon-reconfigure is not supposed to end up
there.
While we're at it, also add an exec to avoid an unnecessary shell
process.
Extracted from #2372, as we'll also want to backport this commit to v2021.1.x as soon as possible.
> gluon-config-mode-core: discard gluon-reconfigure output

- package/gluon-mesh-babel/check_site.lua
With Babel, wired meshing cannot run on the same logical interface as
non-mesh traffic, so using VXLAN is mandatory.
See https://github.com/freifunk-gluon/gluon/issues/2375#issuecomment-1015683959
> gluon-mesh-babel: do not allow disabling VXLAN

- docs/user/supported_devices.rst
- targets/ath79-generic
- ~~webinterface~~
- ~~tftp~~
- led mapping
- radio leds
- ~~outdoor devices only~~
- added board name to `is_outdoor_device` function in `package/gluon-core/luasrc/usr/lib/lua/gluon/platform.lua`
> ath79-generic: (re)add AVM Fritz!WLAN Repeater 450e

- docs/user/supported_devices.rst
- targets/ath79-generic
```
* QCA9557, 16 MiB Flash, 128 MiB RAM, 802.11n 2T2R
* QCA9882, 802.11ac 2T2R
* Gigabit LAN Port (AR8035), 802.3af PoE
* 3,5 x 1,35 mm DC plug (12V) alternative supply
```
- led mapping
- radio leds
Signed-off-by: Sebastian Schaper <openwrt@sebastianschaper.net>
> ath79-generic: add support for D-Link DAP-2660 A1

- .github/filters.yml
- contrib/actions/generate-target-filters.py
The scripts directory contains most of our build system, so changing it
should trigger a build of all targets.
> ci: build all targets on changes in scripts/

- scripts/target_config_lib.lua
- scripts/target_lib.lua
No legacy OpenWrt targets exist anymore which require the .config profile
name to differ from the image name.
> scripts: target_lib: remove profile override support

- package/gluon.mk
luasrcdiet will not print the name of its input file when an error
occurs. To facilitate debugging, echo the name before calling it, so it
is visible with V=s or BUILD_LOG=1.
> gluon.mk: print source file name in GluonSrcDiet

- docs/user/supported_devices.rst
- patches/openwrt/0005-ath79-Add-support-for-OpenMesh-A60.patch
- patches/openwrt/0006-ath79-Add-support-for-OpenMesh-A40.patch
- patches/openwrt/0007-ath79-Allow-to-set-spi-nor-mtd-name-via-devicetree.patch
- patches/openwrt/0008-ath79-Add-support-for-OpenMesh-OM2P-v1.patch
- patches/openwrt/0009-ath79-Add-support-for-OpenMesh-OM5P-AC-v1.patch
- patches/openwrt/0010-ath79-Add-support-for-OpenMesh-OM5P-AN.patch
- targets/ath79-generic
Support for the OpenMesh devices was dropped in the commit 9fdc57c175b4 ("treewide: drop ar71xx platform specific code"). These devices will now be introduced for the ath79-generic architecture.
Source of device support
========================
Upstream in OpenWrt 21.02
-------------------------
* MR600 (v1, v2)
* MR900 (v1, v2)
* MR1750 (v1, v2)
* OM2P (v2, v4)
* OM2P-HS (v1, v2, v3, v4)
* OM2P-LC
* OM5P
Upstream in OpenWrt master
-------------------------
* A40
* A60
* OM2P (v1)
* OM5P-AC (v1, v2)
* OM5P-AN
Pending fix for OpenWrt 21.02
-----------------------------
* OM5P-AC (v2) https://github.com/openwrt/openwrt/pull/4966
Image name changes
==================
The switch to OpenWrt 21.02 also changed some device names slightly. manifest_aliases were added for these (but the one for …
> ath79-generic: Re-add OpenMesh devices

- docs/user/supported_devices.rst
- package/gluon-core/luasrc/lib/gluon/upgrade/020-interfaces
- package/gluon-core/luasrc/usr/lib/lua/gluon/platform.lua
- targets/ath79-generic
- ~~other: <specify>~~
- led mapping
- radio leds
> ath79-generic: (re)add support for CPE210 v2.x

- docs/user/supported_devices.rst
- targets/ath79-generic
Has been tested by @lemoer, will verify the checklist tomorrow.
- ~~other: <specify>~~
- led mapping
- radio leds
- ~~outdoor devices only~~
- added board name to `is_outdoor_device` function in `package/gluon-core/luasrc/usr/lib/lua/gluon/platform.lua`
> ath79: (re)add support for tl-wr1043nd-v3

- docs/user/supported_devices.rst
- targets/ath79-generic
also add DAP-1365, which is a different case variant of DAP-1330
The checklist actually applies to all 3 devices; is it acceptable to have these within a single PR and/or should these be split into several PRs / commits?
- led mapping
- radio leds
Signed-off-by: Sebastian Schaper <openwrt@sebastianschaper.net>
> ath79: migrate D-Link DAP-1330 and DIR-550 from ar71xx

- docs/user/supported_devices.rst
- package/gluon-core/luasrc/lib/gluon/upgrade/020-interfaces
- package/gluon-core/luasrc/usr/lib/lua/gluon/platform.lua
- targets/ath79-generic
- ~~other: <specify>~~
- led mapping
- radio leds
> ath79-generic: (re)add support for CPE510 v1.x

- docs/user/supported_devices.rst
- package/gluon-core/luasrc/usr/lib/lua/gluon/platform.lua
- targets/ath79-generic
- ~~webinterface~~
- led mapping
- ~~radio leds~~
- ~~should map to their respective radio~~
- ~~should show activity~~
- ~~switchport leds~~
- ~~should map to their respective port (or switch, if only one led present) ~~
- ~~should show link state and activity~~
> ath79-generic: (re)add support for UniFi AC Mesh

- docs/user/supported_devices.rst
- package/gluon-core/luasrc/lib/gluon/upgrade/020-interfaces
- package/gluon-setup-mode/luasrc/lib/gluon/upgrade/320-setup-ifname
- targets/ath79-generic
The device appears to be working as expected.
This is ready for review.
Lastly the LED (the circle in the middle is off during normal operation).
- ~~webinterface~~
- led mapping
- ~~radio leds~~ (there are none)
- ~~switchport leds~~ (there are none)
- ~~outdoor devices only~~
> ath79-generic: (re)add support for UniFi AP PRO

- docs/user/supported_devices.rst
- targets/mpc85xx-p1010
This adds support for the Sophos RED 15w rev.1 gateway.
It is a branch-office SD-WAN device based on the P1014 networking SoC.
- led mapping
- radio leds
> mpc85xx-p1010: add Sophos RED 15w rev.1

- docs/user/supported_devices.rst
- targets/ath79-generic
> ath79-generic: (re)add support for GL-AR150

- docs/user/supported_devices.rst
- targets/ath79-generic
Just found it and quickly but thorughly tested everything.
- LED mapping
- Radio LEDs
- n/a Should map to their respective radio
- n/a Should show activity
- n/a Should map to their respective port (or switch, if only one led present) 
- n/a Should show link state and activity
- n/a Added board name to `is_outdoor_device` function in …
>  ath79-generic: (re)add support for tl-wr810n-v1

- docs/user/supported_devices.rst
- targets/ath79-generic
~~FunkyFreezer (hackint#freifunkh) offered to test this thursday.~~
@Dark4MD was faster, this is ready to merge:
> As i got one laying around doing nothing i tested and checked everything with a build by @AiyionPrime. Tested both an Upgrade from an older Build with ar71xx and Flash over the Stock Web IF.
_Usually means: Gluon profile name must match image name_
* Wired network
* On devices supplied via PoE, there is usually no explicit WAN/LAN labeling on the hardware.
* Wireless network (if applicable)
* LED mapping
* Power/sys LED
* Radio LEDs
* Switch port LEDs
* Outdoor devices only:
* n/a Added board name …
> ath79-generic: (re)add Archer C7 v5

- docs/user/supported_devices.rst
- targets/ath79-generic
- ~~other: <specify>~~
- led mapping
- radio leds
- ~~outdoor devices only~~
- ~~added board name to `is_outdoor_device` function in `package/gluon-core/luasrc/usr/lib/lua/gluon/platform.lua`~~
> ath79-generic: (re)add Archer C5 v1

- docs/user/supported_devices.rst
- package/gluon-core/luasrc/lib/gluon/upgrade/020-interfaces
- package/gluon-core/luasrc/usr/lib/lua/gluon/platform.lua
- targets/ath79-generic
I'll get the test device on saturday afternoon.
- LED mapping
- Radio LEDs
> ath79-generic: (re)add NanoStation M (XW)

- docs/user/supported_devices.rst
- targets/ath79-generic
> ath79-generic: (re)add support for GL-AR750

- docs/user/supported_devices.rst
- targets/ath79-generic
> ath79-generic: (re)add support for tl-wr1043nd-v2

- docs/user/supported_devices.rst
- targets/ath79-generic
- n/a webinterface
- n/a tftp
`My EOLO Edition of the 4020 has a Mac Address written on it that is different from the one that openwrt and gluon uses even before migration. In the bootloader it is labeled as macdsl and the one gluon uses is labeled as macwlan. The Mac Address that gluon uses is also found on the label but in the CWMP account (ID?) on my device.`
- led mapping …
>  ath79-generic: (re)add support for avm_fritz4020

- docs/user/supported_devices.rst
- targets/ath79-generic
> ath79-generic: (re)add support for tl-wr842nd-v3

- docs/user/supported_devices.rst
- targets/ath79-nand
@rotanid received the image for testing.
- LED mapping
- Radio LEDs
> ath79-nand: (re)add support for glinet_gl-ar300m

- docs/user/supported_devices.rst
- targets/ath79-generic
> ath79-generic: (re)add support for glinet_6416

- docs/user/supported_devices.rst
- package/gluon-core/luasrc/lib/gluon/upgrade/020-interfaces
- package/gluon-core/luasrc/usr/lib/lua/gluon/platform.lua
- targets/ath79-generic
Build is running, @rotanid found such a device near him.
~~Images will reach him soon.~~
He got the images yesterday and reported:
> check, done.
_in hackint#gluon_
(`lua -e 'print(require("platform_info").get_image_name())'`) - tp-link-wbs210-v1
- LED mapping …
> ath79-generic: (re)add support for wbs210v1

- package/gluon-core/luasrc/lib/gluon/upgrade/021-interface-roles
Make the code match the docs and check_site.lua by actually looking up
the "default_roles" field, not "roles".
> gluon-core: fix setting interface default roles from site.conf

- package/gluon-core/luasrc/usr/lib/lua/gluon/util.lua
The function failed when an interface has no roles assigned, breaking
several upgrade scripts.
Closes #2471
> gluon-core: fix gluon.util.get_role_interfaces() with empty role list

- docs/user/supported_devices.rst
- targets/ath79-generic
Testing the device this weekend.
easiest is using dd cause that even works with the newer OEM firmware versions:
https://wiki.freifunk.net/Ubiquiti_Unifi_AC/Flash-Anleitung
- [?] must have correct port assignment (WAN/LAN)
> Both Ports on the device are WAN/Config Mode Ports now
- led mapping
> After upgrade the LEDs are switched. ar71xx White was the Status LED, ATH79 the Blue one is. The ATH79 one is correct if you look at the …
> ath79-generic: (re)add support for unifiac-pro

- docs/user/supported_devices.rst
- targets/ath79-generic
Gone due to commit 45c84a117bf8 ("ar71xx: drop target")
- Other: <specify>
- LED mapping
- Radio LEDs
- Added board name to `is_outdoor_device` function in `package/gluon-core/luasrc/usr/lib/lua/gluon/platform.lua`
> ath79-generic: (re)add support for tl-wr1043n-v5

- package/gluon-core/luasrc/lib/gluon/upgrade/021-interface-roles
Instead of using roles.wan directly as the default for roles.single,
create a copy of the table, so subsequent modifications of roles.single
don't affect roles.wan as well.
Fixes migration of Mesh-on-WAN status when no default for "single"
interfaces is set in site.conf.
> gluon-core: use copy of "WAN" role list for "single" default

- docs/user/supported_devices.rst
- targets/ramips-mt76x8
With this PR I would like to propose TP-Link Archer C20 v5 support. Owning a C20 v5, based on @herbetom's commit, I did the device-Integration-checklist[1], please find it here:
-> Gluon profile name: tp-link-archer-c20-v5 (device name in ramips-mt76x8 target file)
-> Autoupdater image name: tp-link-archer-c20-v5 (via lua get_image_name())
-> /lib/gluon/core/sysconfig/primary_mac contains primary mac on device label
-> Wan: eth0.2 (SW Port 0), Lan: eth0.1 (SW Ports 1-4)
- LED mapping
- The device has no "sys" LED, so instead the power LED is flashing
- Radio LEDs
- only one LED present
One other thing to mention with this device, is that OpenWRT cannot build factory firmware[2], only sysupgrade. In …
> ramips-mt76x8: add support for TP-Link Archer C20 v5

- docs/user/supported_devices.rst
- targets/ath79-generic
[rabbit83](https://forum.freifunk.net/u/rabbit83/) intends to test this device.
He built and ran his own build based on 2021.1.1 a while ago, building on master failed for his local site, so he was provided an image.
- LED mapping
- …
> ath79-generic: (re)add support for wndr3700v2

- targets/ath79-generic
@rotanid intends to test this device
Its broken, as it will run out of memory, when the 5GHz interfaces are active.
I therefore did not add it to the supported list yet.
- LED mapping
(https://gluon.readthedocs.io/en/latest/features/configmode.ht …
> ath79-generic: (re)add support for archer-c25-v1

- docs/user/supported_devices.rst
The mpc85xx-generic target was renamed to mpc85xx-p1010 in OpenWrt
21.02. The target name in Gluon docs was never adjusted however.
> docs: fix mpc85xx-p1010 target name

- docs/user/supported_devices.rst
- targets/mpc85xx-p1020
- Web interface
- Other: <specify>
LAN 1 is WAN (eth1)
LAN 2 is LAN (eth0)
It is possible to supply the AP with power via either of the two ports. However, there is no seamless failover. Additionally there is a DC-IN.
- LED mapping
- Radio LEDs
- Added board name to …
> mpc85xx-p1020: add Extreme Networks WS-AP3825i

- docs/user/supported_devices.rst
- targets/ath79-generic
@rotanid intends to test this device.
He got the image a moment ago.
- LED mapping
- Radio LEDs
- Switch port LEDs - **device has no LAN ports**
- ~~Should map to their respective …
> ath79-generic: (re)add support for gl-usb150

- docs/user/supported_devices.rst
- targets/ath79-generic
- LED mapping
- Radio LEDs
did not test flashing from stock firmware
> ath79-generic: (re)add support for archer-c59-v1

- targets/ath79-generic
The device got even more sensitive regarding 5GHz environments.
As its already marked as broken for that very reason, this PR should be fine.
- LED mapping …
> ath79-generic: (re)add archer c60

- docs/user/supported_devices.rst
- targets/ath79-generic
- LED mapping
- Radio LEDs
-  ~~Added board name to `is_outdoor_device` function in `package/gluon-core/luasrc/usr/lib/lua/gluon/platform.lua`~~
> ath79-generic: (re)add support for tl-wdr3500-v1

- docs/user/supported_devices.rst
- targets/ath79-generic
I'll get the device from @gerhardt tomorrow, the image is built already and the migration expected to be a breeze, as revision two and five of the model did not cause any troubles either.
The test is scheduled for 15:30.
I wont test flashing from stock.
- ~~Must be flashable from vendor firmware~~
- ~~TFTP~~
- On devices supplied via PoE, there is usually no explicit WAN/LAN labeling on the …
> ath79-generic: (re)add Archer C7 v4

- docs/user/supported_devices.rst
- targets/ramips-mt76x8
@gerhardt tracked this device for a while now and lent me one to add it in gluon as well.
The device is expected to works good as revision five, which was added a few weeks ago.
Flashing the device must only be done via tftp from stock, if flashed via their UI the router is soft-bricked.
Test is scheduled for tomorrow 09:00.
- ~~Web interface~~ Does softbrick the device
- LED mapping …
> ramips-mt76x8: add support for TP-Link Archer C20 v4

- targets/generic
Remove a few features that became enabled by default since OpenWrt 19.07.
Disabling CONFIG_RELAY also reduces RAM usage.
Sysupgrade image size for TL-WDR3600 (content size, not padded to erase blocks):
- Before: 5221790
- After: 5066042
> generic: reduce kernel size some more

- package/gluon-mesh-wireless-sae/Makefile
- package/gluon-wireless-encryption/Makefile
WolfSSL has a significant lower flash footprint. Also, issues with OWE / SAE connections were fixed in OpenWrt a while ago.
See https://github.com/openwrt/openwrt/commit/ddcb970274c011d3db611ec39350ee4704ff0e02
```
Before: 6030120
After: 5636904
```
> treewide: switch crypto lib to WolfSSL

- patches/openwrt/0026-ath79-Joy-IT-OR750i-fix-UART.patch
The serial console on the Joy-IT OR750i doesn't work, because the UART
node is disabled in device tree. This also breaks sysupgrade.
The issue is already fixed upstream in OpenWRT by
7054721cf94f4aa8fe71ac4c28c922b19a69ba1d ("ath79: enable UART in SoC
DTSI files"), but since 19.07 doesn't support the OR750, we need our own
patch.
Signed-off-by: Nico Boehr <freifunk@nicoboehr.de>
> ath79: add patch to fix serial console and sysupgrade on OR750

- package/gluon-mesh-vpn-fastd-l2tp/Makefile
- package/gluon-mesh-vpn-wireguard/Makefile
This was removed in commit c23bc293ef99 ("treewide: remove
GLUON_SPECIALIZE_KERNEL").
> treewide: remove leftover GLUON_SPECIALIZE_KERNEL dependencies

- docs/user/supported_devices.rst
- targets/ath79-generic
@rotanid intends to test this device.
- LED mapping
- Radio LEDs
- ~~Added board name to `is_outdoor_device` function in …
> ath79-generic: (re)add support for wndr3700

- docs/user/supported_devices.rst
- package/gluon-core/luasrc/usr/lib/lua/gluon/platform.lua
- targets/ath79-generic
@moridius intends to test the device
- LED mapping
- Radio LEDs
> ath79-generic: (re)add CPE210v3

- docs/user/supported_devices.rst
- targets/ramips-mt7621
Test protocol created by the device owner.
https://meshviewer.darmstadt.freifunk.net/#!/en/map/74da88f287c3
- LED mapping
- Radio LEDs
> ramips-mt7621: add TP-Link RE650v1

- contrib/ci/minimal-site/site.conf
- docs/multidomain-site-example/site.conf
- docs/site-example/site.conf
- docs/user/site.rst
- package/gluon-mesh-vpn-core/check_site.lua
- package/gluon-mesh-vpn-core/luasrc/lib/gluon/upgrade/500-mesh-vpn
- package/gluon-mesh-vpn-fastd/check_site.lua
- package/gluon-mesh-vpn-fastd/luasrc/lib/gluon/upgrade/400-mesh-vpn-fastd
- package/gluon-mesh-vpn-fastd/luasrc/usr/lib/lua/gluon/mesh-vpn/provider/fastd.lua
- package/gluon-mesh-vpn-tunneldigger/check_site.lua
- package/gluon-mesh-vpn-tunneldigger/luasrc/usr/lib/lua/gluon/mesh-vpn/provider/tunneldigger.lua
- package/gluon-mesh-vpn-wireguard/check_site.lua
- package/gluon-mesh-vpn-wireguard/luasrc/usr/lib/lua/gluon/mesh-vpn/provider/wireguard.lua
If a community uses different vpn providers, they typically
assume the same MTU for the wan device underneath the VPN. As
different VPN providers however have different overhead, the MTU
of the VPN device differs for each provider. Therefore this
commit makes the MTU of the VPN device provider specific.
This has two advantages:
1. The same site.conf can used to bake firmwares for different
VPN providers (only by selecting a diferent vpn feature in the
site.mk).
2. We are coming closer to the option of integrating multiple VPN
providers into one firmware.
> RFC: gluon-mesh-vpn-*: make MTU of VPN device provider specific

- .github/filters.yml
- docs/user/supported_devices.rst
- targets/ath79-mikrotik
- targets/mikrotik.inc
- targets/targets.mk
- led mapping
- radio leds
- n/a should map to their respective radio
- n/a should show activity
- n/a added board name to `is_outdoor_device` function in `package/gluon-core/luasrc/usr/lib/lua/gluon/platform.lua`
Note that mikrotik was a target back in the days,
but that target was mostly a generic catch-all image
Now that …
> ath79-mikrotik: add support for Mikrotik RB951Ui-2nD

- docs/user/supported_devices.rst
- package/gluon-core/luasrc/lib/gluon/upgrade/020-interfaces
- package/gluon-core/luasrc/usr/lib/lua/gluon/platform.lua
- targets/ath79-generic
- ~[ ] webinterface~
- ~[ ] tftp~
- led mapping
- ~radio leds~
- ~[ ] should map to their respective radio~
- ~[ ] should show activity~
- ~switchport leds~
- ~[ ] should map to their respective port (or switch, if only one led present)~
- ~[ ] should show link state and activity~
As OpenWrt bridges the Ethernet ports by default, we …
> Re-add UniFi AP Outdoor+ support

- docs/user/supported_devices.rst
- package/gluon-core/luasrc/lib/gluon/upgrade/010-primary-mac
- targets/ramips-mt7620
The reasons for "broken" status (no 5 GHz WLAN, LEDs not working) are [fixed in OpenWRT.](https://openwrt.org/toh/asus/rt-ac51u) Only 5 GHz-LED isn't working at all.
- LED mapping …
> ramips-mt7620: remove "broken" status for ASUS RT-AC51U

- contrib/push_pkg.sh
Starting from OpenSSH 9.0p, scp started to use sftp in favor of the
scp protocol by default. As dropbear in OpenWrt currently does not
support sftp by default, we now use the fallback cli switch "-O"
to use the scp protocol for scp.
> push_pkg.sh: use scp protocol for openssh scp

- docs/user/supported_devices.rst
- targets/ath79-generic
also fix whitespace (tabs vs. spaces) my text editor messed up while migrating dir-505
- [-] TFTP
- [x Must keep/forget configuration (`sysupgrade [-n]`, `firstboot`)
- [-] Primary MAC address should match address on device label (or packaging)
_-> MAC address on map equals label mac - 1, consistent with ar71xx (will not spawn a new node on the map)_
_-> label mac -1 prevails even after reset_
- On devices supplied via PoE, there is usually …
> ath79-generic: migrate D-Link DIR-825 B1 from ar71xx

- docs/user/supported_devices.rst
- package/gluon-core/luasrc/usr/lib/lua/gluon/platform.lua
- targets/ath79-generic
Flashing back and forth to stock was not tested with gluon in ath79.
Flashing it to ar71xx worked.
- ~~Must be flashable from vendor firmware~~
- ~~TFTP~~
- LED mapping …
> ath79-generic: migrate  NanoBeam M5

- docs/user/supported_devices.rst
- targets/ath79-generic
The DTS model name has been changed to "TP-Link Archer C6 v2 (EU/RU/JP)"
to distinguish it from the US version.
Closes #2533
> ath79-generic: update Archer C6 v2 image name

- docs/conf.py
We are currently using Sphinx-5.0.0.
> [...]Since v5.0, `language = None` is not recommended. So please remove the configuration from these projects.
> Thank you for reporting.
_Originally posted by @tk0miya in https://github.com/sphinx-doc/sphinx/issues/10474#issuecomment-1140389657_
> docs: use default language 'en'

- targets/ath79-generic
- targets/ipq40xx-generic
- targets/ipq806x-generic
Use the candelatech firmware for the QCA4019 WiSoC.
The Qualcomm firmware used for this specific chip in OpenWrt in 22.03
is experiencing heavily degraded performance due to excessive
retransmits when using A-MSDU. Disabling VHT modes or switching to the
candelatech firmware circumvents this issue.
> ipq40xx: switch QCA4019 firmware to -ct

- targets/ath79-generic
@moridius intends to test this device.
The device is expected to not work properly due to 64M ath9k + ath10k.
Its marked as `BROKEN`, like it was in ar71xx.
@moridius please take special care regarding testing the primary mac.
- ~~Must be flashable from vendor firmware~~ **not tested, expected to work**
- ~~TFTP~~
- On devices supplied via PoE, there is usually no explicit WAN/LAN labeling on the …
> ath79-generic: (re)add Archer C58 v1

- targets/lantiq-xrx200
Talked with @Dark4MD about the device on Thursday and we came to the conclusion, that it could not be using all of it's available memory if it had the same image as `v1`/`sl`.
@grische from @freifunkMUC encountered an issue with the current implementation as well, as it's currently not flashable on their stable or next branch:
```console
root@OpenWrt:/tmp# sysupgrade -n gluon-ffmuc-v2022.5.2-next3-avm-fritz-box-7360-v2-sysupgrade.bin
Sat Apr 16 13:21:46 UTC 2022 upgrade: Device avm,fritz7360-v2 not supported by this image
Sat Apr 16 13:21:46 UTC 2022 upgrade: Supported devices: avm,fritz7360sl FRITZ7360SL
```
I think this would be sufficient, let me know if I forgot something.
I'll ask @grische to test the PR before opening it for merging.
> lantiq-xrx200: split 7360v2 into own device

- docs/user/supported_devices.rst
- package/gluon-core/luasrc/usr/lib/lua/gluon/platform.lua
- targets/ath79-generic
> Gone due to
"nordm4nn" from @freifunkMUC intends to test this device.
Will likely be done by tomorrow evening.
- ~~Must be flashable from vendor firmware~~ **wont test**
- ~~TFTP~~
- Wireless network (if …
> ath79-generic: (re)add support for NanoStation Loco M2 (XW)

- docs/user/supported_devices.rst
- package/gluon-core/luasrc/usr/lib/lua/gluon/platform.lua
- targets/ath79-generic
Works like a charm, ready to review.
- ~~Web interface~~ **OpenWrt commit says 'should work' but did not for me**
- LED mapping
- Radio LEDs
- Switch port …
> ath79-generic: add support for CPE710v1

- docs/user/supported_devices.rst
- package/gluon-core/luasrc/lib/gluon/upgrade/020-interfaces
- targets/ramips-mt7621
> rampis-mt7621: add support for Netgear WAC104

- docs/user/supported_devices.rst
- targets/ramips-mt7621
- LED mapping
- Radio LEDs (None available)
> rampis-mt7621: add support for Cudy WR2100

- docs/user/supported_devices.rst
- targets/ramips-mt7621
- LED mapping
- Radio LEDs
~~it seems there is still  a problem, and Cudy WR2100 doesn't have this problem despite it having exactly the …
> ramips-mt7621: add support for Netgear R6260

- package/gluon-client-bridge/luasrc/lib/gluon/upgrade/320-gluon-client-bridge-wireless
OpenWrt now allows to specify the ifname of the transition interface
instead of SSID and BSSID, internally automatically detecting these from
interfaces on the same PHY. Thus, these cross-VAP dependant
configuration can be omitted from UCI.
CUrrently blocked by #2549
> gluon-client-bridge: simplify OWE-TM configuration

- docs/user/supported_devices.rst
- targets/ath79-generic
@ce-4 intends to test this device.
> Both are effectively the same hardware, the latter being Bufalos
> replacement model.
> Gone due to
- ~~Must be flashable from vendor firmware~~ wonttest
- ~~TFTP~~
- …
> ath79-generic: (re)add wzr-hp-ag-300h / wzr-600dhp

- targets/ath79-generic
- [n/a] Other: <specify>
- LED mapping
- Radio LEDs
- [n/a] Added board name to `is_outdoor_device` function in …
> ath79-generic: (re)add TL-WR902AC v1

- docs/user/supported_devices.rst
- targets/ath79-generic
@Noodlesalat intends to test this.
- LED mapping
- Radio LEDs **do not exist, rssi works**
- ~~Should map to their respective radio~~
- …
> Ath79 migrate ubnt loco m5 xw

- contrib/actions/run-build.sh
- package/gluon-mesh-batman-adv/files/lib/netifd/proto/gluon_bat0.sh
- package/gluon-setup-mode/files/usr/bin/gluon-enter-setup-mode
`make lint` throws three errors, this should fix it.
I think `gluon-enter-setup-mode` never had `pipefail`-support, if we want to change that, I could implement that as well, but I suppose it's not necessary int this case, as its output appears to be not evaluated.
> Fix make lint

- package/gluon-core/luasrc/lib/gluon/upgrade/020-interfaces
- package/gluon-core/luasrc/lib/gluon/upgrade/115-swconfig
- package/gluon-setup-mode/luasrc/lib/gluon/upgrade/320-setup-ifname
This allows to split port assignments of devices, that were previously distinct and are now part of one `switch_vlan`.
Following the discussion in the latest meetup,
a variant of this should either be merged to account for #2439 before the next release,
or the other way around (reverting #2439).
I'll rebase #2462 onto this to show my intent.
Currently the statement to check, whether recreating the switch_vlans is necessary is not implemented. If you've got suggestions how to do it properly?
> gluon-core: split dual lan devices

- docs/user/supported_devices.rst
- targets/mediatek-mt7622
- LED mapping
- Radio LEDs (None available)
> mediatek-mt7622: add support for Linksys E8450

- docs/user/supported_devices.rst
- targets/mediatek-mt7622
https://openwrt.org/toh/xiaomi/ax3200#installation
https://forum.openwrt.org/t/adding-openwrt-support-for-xiaomi-redmi-router-ax6s-xiaomi-router-ax3200/111085/513
- LED mapping
- Radio LEDs (None available)
> mediatek-mt7622: add support for Xiaomi AX3200

- docs/user/supported_devices.rst
- package/gluon-core/luasrc/lib/gluon/upgrade/020-interfaces
- package/gluon-core/luasrc/usr/lib/lua/gluon/platform.lua
- targets/ath79-generic
> Gone due to
@dk8hc intends to test this device within the next two weeks.
- ~~Must be flashable from vendor firmware~~ **won't test**
- ~~TFTP~~
- LED mapping
- Power/system …
> ath79-generic: (re)add WBS510 v1

- targets/lantiq-xway
Gluon does not support usage of the integrated ADSL modem, thus
DSL-related packages can be removed.
> lantiq-xway: remove DSL specific packages

- package/gluon-core/luasrc/lib/gluon/upgrade/010-primary-mac
Depending on the source of the primary MAC address, uppercase digits
would be used on some devices. Convert the address to lowercase for
consistency.
We only change the case for newly configured nodes to avoid changing the
node ID and derives MAC addresses for existing installations.
The issue was reported in https://github.com/freifunk-gluon/gluon/pull/2406#issuecomment-1094058134.
> gluon-core: always store primary MAC address in lowercase hex digits

- docs/user/supported_devices.rst
- targets/ath79-generic
* SoC: AR7242 (Virian 400MHz)
* RAM: 64 MB DDR (W9751G6JB-25)
* Flash: 16MB SPI flash (S25FL129PIF)
* WiFi: AR9382 (2.4/5GHz)
* LAN: 1x1000M (PEF7071V)
The device has only one dual band radio and prefers the 5GHz band as described in the gluon documentation. The only RJ45 connector works as WAN.
Test Device https://map.chemnitz.freifunk.net/#!v:m;n:BC0543DBD8BD
Device Integration checklist
*avm-fritz-wlan-repeater-r300e* 
- led mapping
- power (_critical, because led definitions are setup on firstboot only_)
- radio leds
> ath79-generic: add AVM FRITZ!WLAN Repeater 300E support

- docs/user/supported_devices.rst
- package/gluon-core/luasrc/lib/gluon/upgrade/020-interfaces
- package/gluon-core/luasrc/lib/gluon/upgrade/115-swconfig
- package/gluon-core/luasrc/usr/lib/lua/gluon/platform.lua
- targets/ath79-generic
@udoschneider offered to test this migration.
The ath79 image can be found here: http://aiyionpri.me/shared/udoschneider/
A proper image to migrate from would be http://firmware.ffh.zone/vH21/sysupgrade/gluon-ffh-vH21-ubiquiti-unifi-ac-mesh-pro-sysupgrade.bin
- ~~TFTP~~
- …
> ath79-generic: (re)add support for UniFi AC Mesh Pro

- docs/user/supported_devices.rst
- package/gluon-setup-mode/files/lib/gluon/setup-mode/rc.d/S96led
- targets/ath79-generic
- u-boot web based recovery, accepts sysupgrade image: https://openwrt.org/toh/alfa_network/ap121f#recovery_through_u-boot
- should be available, but untested
- LED mapping
- N/A, no "led-running" assigned in DTS, LED with "V" icon reserved for …
> ath79-generic: (re)add support for ALFA Network AP121F

- docs/user/supported_devices.rst
- targets/ath79-nand
This contains a minor title-addition to ath79-nand.
~~freifunk-springe~~ @gRaSmOnStEr intends to test the device.
- LED mapping
- Radio LEDs
- Switch port …
> ath79-nand: migrate wndr3700v4

- docs/user/supported_devices.rst
- targets/ramips-mt7621
The `Xiaomi Mi Wi-Fi Router 3G v2` is basically the same as `Xiaomi Mi Router 4A (Gigabit Edition)`, only the bootloader is different
- LED mapping
- Radio LEDs
> ramips-mt7620: add support for xiaomi_mi-router-3g-v2

- package/gluon-mesh-vpn-fastd/src/respondd.c
When running "fastd -v" fails, line may be NULL, causing a segfault in
strncmp.
> gluon-mesh-vpn-fastd: fix respondd segfault under load

- package/gluon-web-admin/luasrc/lib/gluon/config-mode/controller/admin/upgrade.lua
This implements the same behavior as it is used in the autoupdater [1].
This is for example required to allow the manual installation of
firmware upgrades via the config mode on devices which where migrated
from swconfig to DSA. Otherwise the image will always be invalid.
[1] https://github.com/freifunk-gluon/packages/commit/b80428166454d184f356e5a14a144911d9ee11aa
> web-admin: always ignore minor compat-version on upgrade

- package/gluon-mesh-batman-adv/src/respondd-statistics.c
This new field reflects the TQ to the selected gateway.
Before this commit, if you had connectivity issues in a larger mesh,
it was a tedious task to understand which nodes are affected and which
are not. By providing this new value for each node, it becomes easier
to see which nodes are affected by the connectivity issues and which
are not.
The new field "gateway_tq" is located at the toplevel of the
statistics resource (next to "gateway" and "gateway_nexthop"):
gluon-neighbour-info -d ::1 -r statistics
{
...
"gateway": "02:a1:71:04:09:10",
"gateway_nexthop": "88:e6:40:20:90:10",
"gateway_tq": 193,
...
}
> gluon-mesh-batman-adv: add "gateway_tq" field to respondd statistics

- package/gluon-respondd/src/respondd-neighbours.c
The below mentioned commit introduced a regression, that the "wifi"
section of the request type "neighbours" was empty:
~# gluon-neighbour-info -d ::1 -r neighbours | ffh_pretty_json
{
"wifi": [
],
...
}
After this commit, the section (correctly) looks like this:
root@UFU-FWH-A272-Tresckowstr-GemR-vorne:~# gluon-neighbour-info -d ::1 -r neighbours | ffh_pretty_json
{
"wifi": {
"ca:38:7e:42:5f:21": {
"neighbours": {
"fe:9f:4d:01:ea:e1": {
"noise": -102,
"inactive": 50,
"signal": -84
},
"fe:df:b9:84:37:51": {
"noise": -102,
"inactive": 20,
"signal": -73
}
}
}
},
...
}
The issue was due to the fact, that the iteration over the (mesh) wifi interfaces
was broken. The code was assuming, that the section
config interface 'mesh_radio0'
option proto 'gluon_mesh'
in /etc/config/network contains an …
> gluon-respondd: fix missing section "wifi" for request type "neighbours"

- package/gluon-core/files/etc/hotplug.d/firmware/20-gluon-ath10k-fwcfg
- package/gluon-core/files/lib/gluon/ath10k-fwcfg.txt
Increase the peer limit for ath10k-ct from 32 to 96 STAs like it is set
for the non-ct firmware / driver. In order to make this work with the
memory constraints of the wireless platform, reduce the number of
concurrent vdevs to the maximum Gluon uses (4).
Closes #2604
> gluon-core: increase ath10k peer limit

- docs/user/supported_devices.rst
- targets/ramips-mt76x8
The following Tests were done by hdvalentin out of the FFRN community:
- [ , x] Must keep/forget configuration (`sysupgrade [-n]`, `firstboot`)
- [ x] must have correct port assignment (WAN/LAN)
- LED mapping …
> ramips-mt76x8: add support for Xiaomi Mi Router 4A (100M International Edition)

- docs/user/supported_devices.rst
- targets/ramips-mt7621
The only unusual thing i've noticed are some aitrime traces from time to time: https://gist.github.com/herbetom/6736717d35847f3d83623bdbd7871731
Checklist:
- LED mapping
- Radio …
> ramips-mt7621: add support for Netgear WAX202

- docs/features/wlan-configuration.rst
- package/gluon-core/luasrc/lib/gluon/upgrade/190-preserve-wireless-channels
- package/gluon-core/luasrc/usr/lib/lua/gluon/wireless.lua
The preserve_channels configuration option was moved to the gluon UCI
package without adding a proper migration.
Closes #2612 
> gluon-core: provide migration for preserve_channels

- docs/user/supported_devices.rst
- targets/ath79-generic
> Gone due to
@blocktrron intends to test this device
> ath79-generic: (re)add support for Ocedo Koala

- docs/features/vpn.rst
This moves the `Gateway / Supernode Configuration`. It didn't make much sense within the Configurable Method` section.
Additionally some recomendations for fastd l2tp offloading on Supernodes / Gateways were added. This should be linked from within the Relase Notes.
> docs: update fastd Gateway / Supernode Configuration

- Makefile
- scripts/target_config_lib.lua
See the commit message of patch 3 ("scripts: target_config_lib: prepend target default package list from openwrt/tmp/.targetinfo") for an explanation of the issue.
Patch 1 ("scripts: target_config_lib: remove handling for targets without devices") looks much more complex that it is due to unfortunate diffing - it only removes the obsolete `if #lib.devices > 0` check and the corresponding else branch.
I have diffed the generated `.config` for all targets with BROKEN=1 before and after the change (filtering out `CONFIG_GLUON_VERSION lines) with ~~a minimal site~~ the ffda site to ensure that these patches don't break any devices. The resulting diff looks good: [configs.diff.txt](https://github.com/freifunk-gluon/gluon/files/9410756/configs.diff.txt)
Closes #2619
> Include OpenWrt's target default package lists in config generation

- docs/features/wired-mesh.rst
- docs/user/site.rst
> - explain what happens on gluon-reconfigure
> - show workflow to alter the wired network config
> - update examples
> - update 'has changed in' section
> 
> resolves #2474 
@herbetom lets take this as a first draft. Let me know what you're missing or'd like to have changed.
> docs/features/wired-mesh: update to role-based configuration

- docs/user/supported_devices.rst
- targets/ramips-mt76x8
> ramips-mt76x8: add support for Netgear R6020

- .github/workflows/backport.yml
The checkout was too limited for the backport action to determine the
proper merge base.
> workflows: fix checkout in backports action

- docs/user/supported_devices.rst
- targets/ramips-mt76x8
(`lua -e 'print(require("platform_info").get_image_name())'`) = tp-link-re305-v1
- LED mapping
- Radio LEDs
> ramips-mt76x8: add support for TP-Link RE305 v1

- docs/user/supported_devices.rst
- targets/ramips-mt7621
> ramips-mt7621: add support for TP-Link RE500

- contrib/docker/Dockerfile
Among other things `git branch --show-current` from `scripts/update-modules.sh` didn't work with the git version (2.20.x) in buster, because it requires 2.22.0.
> localhost/gluon           docker-base     6d337bc0846e  4 seconds ago   451 MB
> Dockerfile: update base to ubuntu:jammy

- README.md
- docs/conf.py
- docs/features/vpn.rst
- docs/features/wired-mesh.rst
- docs/releases/index.rst
- docs/releases/v2022.1.rst
- docs/site-example/site.conf
- docs/user/getting_started.rst
This is still unfinished and will most likely not render correctly in ReadTheDocs.
But let's have a first cycle so we can push this through very soon.
Contains changes up to b8513546
> docs: Add v2022.1 release notes

- patches/openwrt/0007-kernel-bridge-Implement-MLD-Querier-wake-up-calls-Android-bug-workaround.patch
With the update to OpenWrt 21.02 the bridge MLD wakeup call feature was
removed. However the issue with Android devices and MLD is still
present. Therefore readding the bridge MLD wakeup call patch and porting
it to Linux 5.10 / OpenWrt 22.03.
Link: https://issuetracker.google.com/issues/149630944
Fixes: aab2b914b868 ("modules: switch to OpenWrt 21.02")
> kernel: bridge: readding MLD wakeup call feature

- patches/openwrt/0007-kernel-bridge-Implement-MLD-Querier-wake-up-calls-Android-bug-workaround.patch
This hopefully fixes the failing CI check https://github.com/freifunk-gluon/gluon/runs/8194673963
> patches: rebase MLD Querier wake up calls Android bug workaround

- targets/ath79-nand
> ath79-nand: add support for ZTE MF281

- docs/user/supported_devices.rst
- package/gluon-core/luasrc/lib/gluon/upgrade/010-primary-mac
- targets/rockchip-armv8
- No MAC on casing - MAC is stable derived from SD card ID
- LED mapping
- Radio LEDs
> rockchip-armv8: add support for NanoPi R4S

- docs/user/supported_devices.rst
- targets/ipq40xx-generic
- LED mapping
- Radio LEDs (No LEDs)
> ipq40xx-generic: add suppot for GL.iNet GL-AP1300

- package/gluon-core/luasrc/lib/gluon/upgrade/200-wireless
Use the country3 option implemented in OpenWrt's hostapd configuration handling instead of adding it as a custom option.
> gluon-core: use country3 UCI option

- targets/ath79-nand
Support for the device was (re)added in #2455
(merged as 94e04393b19e843cfe595558839ae0aced075127)
---
https://github.com/freifunk-gluon/gluon/blob/89dc6b203d4d4facd743b1b3f24a5c892bc67499/targets/ar71xx-generic#L118-L121
There also was a `gl-ar300m` alias. I don't know if and when that one could be required.
---
This should be backported to [v2022.1.x](https://github.com/freifunk-gluon/gluon/tree/v2022.1.x).
cc @AiyionPrime
> ath79-nand: fix upgrade from 19.07 for GL-AR300M

- docs/user/supported_devices.rst
- package/gluon-core/luasrc/usr/lib/lua/gluon/platform.lua
- targets/ath79-generic
- LED mapping
- Radio LEDs
Signed-off-by: Daniel Trautmann <freifunk@jdtr.de>
> ath79-generic: add support for TP-Link EAP225 Outdoor v3

- docs/user/supported_devices.rst
- package/gluon-core/luasrc/lib/gluon/upgrade/010-primary-mac
- targets/ath79-nand
- targets/ipq40xx-generic
- targets/rockchip-armv8
Backport device supported added to Gluon after the v2022.1 release. This Gluon release shares the OpenWrt base with current master, so the backport is a mere formality.
> [v2022.1.x] Backport device support introduced in master

- patches/openwrt/0008-hostapd-don-t-select-indoor-channel-on-outdoor-operation.patch
Don't select channels designated for exclusive-indoor use when the country3 element is set on outdoor operation.
This effectively prevents from using indoor-only channels in case outdoor-mode is activated. It can be seen as a safeguard from selecting inapprpriate channels in a site outdoor-chanlist.
>  hostapd: don't select indoor channel on outdoor operation

- docs/user/supported_devices.rst
- targets/ath79-generic
It's matching the `WLAN 1` MAC on the device. There also is a `LAN` and `WLAN 2` MAC.
- LED mapping
- Radio LEDs
- Added board name to `is_outdoor_device` function in `package/gluon-core/luasrc/usr/lib/lua/gluon/platform.lua`
> ath79: add support for Extreme Networks WS-AP3805i

- targets/ath79-generic
Ubiquiti Nanostation Loco M XW was renamed in v2022.1.x, but the alias to the old name was missing, so devices running the old release did not update.
Fixes #2663
> ath79-generic: Fix autoupdater for Loco M XW from v2021.1.x to v2022.1.x

- docs/user/supported_devices.rst
- targets/ramips-mt7621
- LED mapping
- Radio LEDs
- ~~[ ] Should map to their respective radio~~ has nonc
- ~~[ ] Should show activity~~
- ~~[ ] Should map to their respective port …
> ramips-mt7621: add support for ZyXEL NWA50AX

- README.md
- docs/conf.py
- docs/releases/index.rst
- docs/releases/v2022.1.1.rst
- docs/site-example/site.conf
- docs/user/getting_started.rst
This adds Release Notes for the Gluon v2022.1.1 release.
This is a quick take, I'd say it is kind-of-urgent given the recent publication of flaws in the wireless stack.
Not sure if we should explain the situation for older releases in this specific release notes, given 19.07 based Gluon is not affected.
> docs: add Gluon v2022.1.1 Release Notes

- package/gluon-core/luasrc/lib/gluon/upgrade/210-interface-mesh
This is an alternative approach to #2484.
It sets the `isolate` option for all mesh devices via uci and let's netifd handle the low level stuff.
The script is run on every gluon-reconfigure.
Isolation should be enabled when there are multiple (non-`uplink`) `mesh` Interfaces.
For devices which were already ported to **DSA** isolation is enabled for all indiviual Ports on that device.
For devices which are still configured via **swconfig** isolation between indivial physical ports isn't possible. 
On all devices isolation should be enabled between `mesh` VLANs and of course between those VLANs and phyiscal `mesh` Ports.
Show whether it's activated:
```
grep ^ /sys/devices/virtual/net/br-mesh*/brif/*/isolated
```
1 means it's enabled fo that interface, 0 that it's diabled.
> gluon-core: enable bridge port isolation for br-mesh_other interfaces

- docs/user/supported_devices.rst
- targets/ipq40xx-generic
AVM Fritz!Box 7520 and Fritz!Box 7530 use the same hardware platform and can only be distinguished by using the urlader partition or the fritz-tffs tools and read the ProductID (Fritz_Box_HW247).
> ipq40xx-generic: add AVM FRITZBox 7520 explicitely

- patches/openwrt/0009-xrx200-migrate-fritz7360-v2-using-incorrect-image.patch
This is a follow-up of https://github.com/freifunk-gluon/gluon/pull/2544 .
With the new Gluon release, there are dedicated images for 7360v1 and 7360v2 that each has their correct flash layouts. The main difference between v1 and v2 (w.r.t. Gluon) is the size of the flash (and not the flash vendor/model, see Details below).
In order to "fix" existing, and wrongly flashed, devices, I created a script that checks AVM's urlader partition (i.e. bootloader partition) and reads the size of the flash. Depending on the size of the flash, either sets the `model` and `board_name` to that of a [7360v1/sl](https://github.com/openwrt/openwrt/blob/v22.03.0/target/linux/lantiq/files/arch/mips/boot/dts/lantiq/vr9_avm_fritz7360sl.dts#L6-L7) or to that of a …
> xrx200: ensure the correct version for fritz7360

- package/gluon-core/luasrc/usr/lib/lua/gluon/platform.lua
- targets/ramips-mt7621
- LED mapping
- Radio LEDs
- Docs:
> ramips-mt7621: add support for ZyXEL NWA55AXE

- contrib/ci/minimal-site/site.conf
This updates the `site.conf` used in the CI based on docs/site-example/site.conf for Gluon v2022.1.
This update is mostly cosmetic, changing "ci" to "minimal-site-ci" and rearranging the content to be aligned with the current `docs/site-example/site.conf`.
Please let me know if you are interested in this kind of change.
> contrib: update minimal-site site.conf for v2022.1

- contrib/docker/Dockerfile
`apt-get clean` clears out the local repository of retrieved package files. It removes everything but the lock file from /var/cache/apt/archives/ and /var/cache/apt/archives/partial/.
> contrib: remove downloaded *.deb files from OCI container

- docs/features/wlan-configuration.rst
- package/gluon-core/luasrc/lib/gluon/upgrade/200-wireless
This adds the uci option 'gluon.wireless.preserve_htmode'. When set to true the channel width of wireless radios (htmode) is preserved during updates.
> gluon-core: preserve wireless channel width during updates

- targets/ath79-generic
fixes OOM reboots due too limited ram with ath10k 5Ghz enabled add some comments to describe the need for ath10k-ct replacement tested stable on an TP-Link Archer C25v1
more details
https://github.com/openwrt/openwrt/commit/694757a08f620a9f24b70003542d9dcd0abeac46
fix issue [Re-enable ath10k-ct-smallbuffers for 64M ath10k boards #2687](https://github.com/freifunk-gluon/gluon/issues/2687)
> Enable ath10k-smallbuffers for low memory ath10k boards

- patches/openwrt/0010-kconfig-abort-configuration-on-unset-symbol.patch
The GitHub actions pipeline is not interrupted for unset symbols due to OpenWrt not failing in all cases of unset symbols.
Adda patch to consistently fail for unset symbols.
Ref #2701 (build process is waiting for user input)
> openwrt: add patch to expose unset symbols

- docs/user/supported_devices.rst
- targets/ramips-mt76x8
Signed-off-by: Richard Fröhning <misanthropos@gmx.de>
- LED mapping
- Radio LEDs
- ~~Added …
> targets/ramips-mt76x8: add device TP-Link RE200 V3

- docs/user/supported_devices.rst
- targets/ath79-nand
> Gone due to
> commit 45c84a1 ("ar71xx: drop target")
~~"alexp" from hackint#ffda intends to test this device.~~
- Must be flashable from vendor firmware
- ~~TFTP~~
- Other: https://github.com/jclehner/nmrpflash
- LED mapping
- Power/system …
> ath79-nand: (re)add WNDR4300v1

- docs/user/supported_devices.rst
These devices use all LAN ports as a WAN bridge.
Closes #2721
> docs: add LAN-AS-WAN label to FB 7520/7530

- patches/openwrt/0007-kernel-bridge-Implement-MLD-Querier-wake-up-calls-Android-bug-workaround.patch
With the update to OpenWrt 21.02 the bridge MLD wakeup call feature was
removed. However the issue with Android devices and MLD is still
present. Therefore readding the bridge MLD wakeup call patch and porting
it to Linux 5.10 / OpenWrt 22.03.
Link: https://issuetracker.google.com/issues/149630944
Fixes: aab2b914b868 ("modules: switch to OpenWrt 21.02")
closes #2672
> [Backport v2022.1.x] kernel: bridge: readding MLD wakeup call feature

- package/gluon-web-model/luasrc/usr/lib/lua/gluon/web/model/classes.lua
- package/gluon-web-private-wifi/i18n/de.po
- package/gluon-web-private-wifi/i18n/gluon-web-private-wifi.pot
- package/gluon-web-private-wifi/luasrc/lib/gluon/config-mode/model/admin/privatewifi.lua
I was made aware of a bug when submitting the form while the element is
disabled based on it's dependencies
(disable "enabled" in "private wifi", then save, while having mesh on wan enabled)
The fix was to inherit from AbstractValue instead of just node
AbstractValue's AbstractValue:resolve_node_depends() in particular
solves the issue, but it made more sense to just use the full base class
Also includes translations
> gluon-web-model: resolve hang when submitting form with disabled element

- docs/index.rst
- docs/releases/index.rst
- docs/releases/v2022.1.1.rst
- docs/releases/v2022.1.rst
- docs/user/mtu.rst
This PR updates to match our editorconfig like @neoraider did before in https://github.com/freifunk-gluon/gluon/commit/854fef4e12c07751c4da78081ac534e87ade9afd.
The rendered docs do not change.
Not sure about the fixup though.
It appears the index files were not touched in @neoraiders commit.
Do we want the toc to stay three spaced?
If so, we'd need to add an exception to our editorconfig like this:
```
[docs/**/index.rst]
indent_size = 3
```
~~Please let me know, whether to include the exception or to squash the fixup.~~
**edit:** we don't bother much, as long as it's consistent either way.
We might change the indetation to three spaces one day to match sphinx' defaults, once we've got no other problems left.
> docs: consistently indent .rst files with 2 spaces

- .editorconfig
> 2 spaces
the hoodselector contains such in his docs
> editorconfig: add dia files

- package/gluon-mmfd/files/etc/init.d/mmfd
This fixes a bug in the gluon-mmfd init script. Waitforsocket() is being called without being specified.
This implements the missing functionality and resolves the problem.
> gluon-mmfd: add missing waitforsocket function

- docs/user/supported_devices.rst
- targets/ramips-mt7621
- LED mapping
- Radio LEDs
- Docs:
> ramips-mt7621: Add Xiaomi Mi Router 3G

- targets/x86.inc
The main difference between the non-EFI and EFI images generated by
OpenWrt is that the former uses an MS-DOS partition table, while the
latter uses GPT. The EFI images still have a BIOS-compatible MBR, so
they work fine on non-EFI systems.
Closes #2403
Draft PR for testing. Boot test in qemu was successful for x86-64 both with default BIOS and UEFI (OVMF). In particular it needs to be tested whether upgrading from a non-EFI image to an EFI image works smoothly - ideally replacing the partition table with GPT, so we don't need to think about upgrades from old systems using MS-DOS partitions forever...
> x86: switch to EFI-compatible images

- .editorconfig
- package/gluon-authorized-keys/luasrc/lib/gluon/upgrade/100-authorized-keys
- package/gluon-config-mode-mesh-vpn/luasrc/lib/gluon/config-mode/wizard/0300-mesh-vpn.lua
- package/gluon-core/luasrc/usr/lib/lua/gluon/util.lua
- package/gluon-mesh-vpn-wireguard/luasrc/lib/gluon/upgrade/400-mesh-vpn-wireguard
- package/gluon-neighbour-info/luasrc/lib/gluon/upgrade/400-neighbour-info-firewall
- package/gluon-node-info/luasrc/lib/gluon/upgrade/500-node-info-system
- package/gluon-wan-dnsmasq/luasrc/lib/gluon/wan-dnsmasq/update.lua
- package/gluon-web-autoupdater/luasrc/lib/gluon/config-mode/model/admin/autoupdater.lua
- package/gluon-web/luasrc/usr/lib/lua/gluon/web/dispatcher.lua
- package/gluon-web/luasrc/usr/lib/lua/gluon/web/template.lua
@tcatm's license text contained spaces for indentation.
Instead of fixing it, I swapped the whole license header to spdx as discussed in
> We have `*.c` files that include a LICENSE header that introduces mixed (space) indentation into files that otherwise use tabs. E.g. `package/libgluonutil/src/libgluonutil.c`. We could use the occasion to migrate to SPDX identifiers, no? @NeoRaider
and
> +1 for migrating to SPDX headers
_Originally posted by @mweinelt and @blocktrron in https://github.com/freifunk-gluon/gluon/issues/2116#issuecomment-691694201 and https://github.com/freifunk-gluon/gluon/issues/2116#issuecomment-695835779_
All other lua files have been indented to tabs. Compiled locally without errors.
> lua indentation

- docs/user/supported_devices.rst
- targets/ath79-generic
- LED mapping
- Radio LEDs
- Docs:
> ath79-generic: add support for Teltonika RUT230 v1

- package/gluon-core/luasrc/lib/gluon/upgrade/250-cellular
- package/gluon-core/luasrc/lib/gluon/upgrade/300-firewall-rules
- package/gluon-core/luasrc/usr/lib/lua/gluon/platform.lua
- package/gluon-web-cellular/Makefile
- package/gluon-web-cellular/i18n/gluon-web-cellular.pot
- package/gluon-web-cellular/luasrc/lib/gluon/config-mode/controller/admin/cellular.lua
- package/gluon-web-cellular/luasrc/lib/gluon/config-mode/model/admin/cellular.lua
Add support for cellular WWAN to Gluon. This allows users to utilize integrated WWAN cards of FWA or travel routers (e.g. Teltonika / GL.iNet).
This works by creating an abstraction layer into Gluon which takes common options (SIM PIN / APN) and translates it to modem-specific settings based on the specific device using. Doing so limits the use-case onto specific models (no LTE sticks possible) but provides a common interface.
The WWAN is assigned the firewall WAN zone and wires WAN can still be used, however without prioritization, so traffic path is not configured to prefer one uplink source or the other.
> gluon-core / web: add cellular WWAN support

- .editorconfig
- contrib/run_qemu.sh
- contrib/sign.sh
- contrib/sigtest.sh
- package/gluon-autoupdater/files/lib/gluon/autoupdater/lib.sh
- package/gluon-core/files/lib/netifd/proto/gluon_wired.sh
> to match the editorconfig
> 
> awk code in `contrib/sign.sh` and `contrib/sigtest.sh` reformatted as gawk does
The awk-code is now formatted the same way for both awk snippets,
I tested `contrib/sigtest.sh` on a manifest generated before this PR, does work as expected.
> treewide: fix indentation in .sh files

- docs/user/supported_devices.rst
- package/gluon-core/luasrc/lib/gluon/upgrade/250-cellular
- package/gluon-core/luasrc/usr/lib/lua/gluon/platform.lua
- targets/ramips-mt7621
- https://git.openwrt.org/?p=openwrt/openwrt.git;a=commit;h=dce66899bf243d78689afcc693340b891bbf4c2d
- LED mapping
- Radio LEDs (only 4G …
> Wavlink WS-WN572HP3 (4G)

- docs/user/site.rst
- package/gluon-l3roamd/Makefile
- package/gluon-l3roamd/check_site.lua
- package/gluon-l3roamd/files/etc/init.d/gluon-l3roamd
- package/gluon-mesh-babel/check_site.lua
- package/gluon-mesh-babel/luasrc/lib/gluon/upgrade/300-gluon-mesh-babel-mkconfig
- package/gluon-mesh-layer3-common/check_site.lua
- package/gluon-mesh-layer3-common/luasrc/usr/lib/lua/gluon/l3.lua
The site.node_client_prefix6() is only used internally by the l3roamd
protocol. Therefore it is unnecessary to expose it to an administrator.
Instead, if node_client_prefix6 is unspecified in the site, generate an
IPv6 Unique Local Address prefix from the site domain_seed.
This updates the site documentation as well and marks this setting as
both optional and deprecated.
Note: If you had the node_client_prefix6 specified before and want to
use the new autogeneration from the domain_seed instead then this will
break compatibility and will need a gluon-scheduled-domain switch.
> gluon-l3roamd: site: make node_client_prefix6 optional+deprecated

- .github/workflows/build-docs.yml
- .github/workflows/build-gluon.yml
- .github/workflows/check-patches.yml
- .github/workflows/labels.yml
- .github/workflows/lint.yml
Restrict the GitHub token permissions only to the required ones; this way, even if the attackers will succeed in compromising your workflow, they won’t be able to do much.
- Included permissions for the action. https://github.com/ossf/scorecard/blob/main/docs/checks.md#token-permissions
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions
https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs
[Keeping your GitHub Actions and workflows secure Part 1: Preventing pwn requests](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)
Signed-off-by: naveen <172697+naveensrinivasan@users.noreply.github.com>
> chore: Set permissions for GitHub actions

- targets/ramips-mt7621
- LED mapping
- Radio LEDs
- Docs:
> ramips-mt7621: add TP-Link Archer C6 v3

- .github/workflows/lint.yml
- contrib/docker/Dockerfile
> - [Release notes](https://github.com/editorconfig-checker/editorconfig-checker/releases)
> - [Commits](https://github.com/editorconfig-checker/editorconfig-checker/compare/2.6.0...2.7.0)
> 
> Signed-off-by: Jan-Niklas Burfeind <git@aiyionpri.me>
> workflows/docker: bump editorconfig-checker from 2.6.0 to 2.7.0

- docs/user/supported_devices.rst
- package/gluon-core/luasrc/lib/gluon/upgrade/010-primary-mac
- package/gluon-core/luasrc/lib/gluon/upgrade/020-interfaces
- targets/lantiq-xrx200
I have this device working and would like to integrate it into Gluon upstream
- DSL/WAN port works with LED: https://github.com/openwrt/openwrt/pull/11594
- LED mapping
- Radio LEDs
- this works very good
~~The LEDs for WLAN, Internet, Info are not active. Power-LED and plugged in LAN cables are working …
> targets/lantiq-xrx200: add device Arcadyan VGV7510KW22 aka o2 Box 6431

- README.md
- contrib/ci/minimal-site/site.conf
- docs/conf.py
- docs/releases/index.rst
- docs/releases/v2022.1.2.rst
- docs/site-example/site.conf
- docs/user/getting_started.rst
This adds Release-Notes for the Gluon v2022.1.2 bugfix-release.
This release only adds bugfixes to Gluons core functionality as well as build-process.
> Gluon v2022.1.2 Release Notes

- .ecrc
> while not present unless built, they are never meant to be checked
currently `cd docs; make html; cd ..; make lint-editorconfig`
results in about
```console
18208 errors found
```
on master.
After merging this, the editorconfig-checker ignores the docs folder properly.
> editorconfig: exclude docs/_built

- package/gluon-web-model/files/lib/gluon/web/view/model/warning.html
- package/gluon-web-model/luasrc/usr/lib/lua/gluon/web/model/classes.lua
- package/gluon-web-private-wifi/luasrc/lib/gluon/config-mode/model/admin/privatewifi.lua
The other bugfix which made this element inherit from AbstractValue
caused AbstractValue:validate() to be inherited aswell
Now added an if so validate only runs if a datatype is set
(since Element is meant as a generic way to extend web-model without
modifying web-model - also to add custom inputs - just hiding it behind an if sounds like a sane solution)
> gluon-web-model: fix issue with warning blocking save on private-wifi

- targets/ath79-generic
It looks like boot hangs on an AC-Mesh for unknown reasons. The last message seen on the console is:
[    0.000000] Inode-cache hash table entries: 8192 (order: 3, 32768 bytes, linear)
But interestingly, it seems like enabling AIO somehow works around this problem. Changing any off the following options seem to have the same effect at the moment for Linux 5.10.160+5.10.161
CONFIG_KERNEL_PROC_STRIPPED=y
Just enable CONFIG_AIO until the actual problem was fixed.
Related bug report: https://github.com/freifunk-gluon/gluon/issues/2784
> ath79-generic: Work around boot hang on Unifi AC-Mesh

- targets/ath79-generic
It looks like boot hangs on an AC-Mesh for unknown reasons. The last message seen on the console is:
[    0.000000] Inode-cache hash table entries: 8192 (order: 3, 32768 bytes, linear)
But interestingly, it seems like enabling AIO somehow works around this problem. Changing any off the following options seem to have the same effect at the moment for Linux 5.10.160+5.10.161
CONFIG_KERNEL_PROC_STRIPPED=y
Just enable CONFIG_AIO until the actual problem was fixed.
Link: https://github.com/freifunk-gluon/gluon/issues/2784
(cherry picked from commit 536c771f3fe56937e516b97c3e233afb02e39b82)
Manual backport to `v2022.1.x`, from #2791.
> [Backport v2022.1.x] ath79-generic: Work around boot hang on Unifi AC-Mesh

- package/gluon-core/files/etc/uci-defaults/zzz-gluon-upgrade
workaround for a timing issue during first boot on ath79-generic after sysupgrade from ar71xx-generic image
GitHub Issue: [#2779](https://github.com/freifunk-gluon/gluon/issues/2779)
> gluon-core:  sleep to wait for device initialisations

- targets/ath79-generic
- targets/ipq40xx-generic
- targets/ipq806x-generic
> This is a temporary measure that is related to #2692.
> 
> This reverts commit 15ef885836907b27b2c0481f7ea83d1dd504c5d5.
> Revert "ipq40xx: switch Wave2 firmware to -ct (#2541)"

- targets/ath79-generic
- targets/ipq40xx-generic
- targets/ipq806x-generic
> This is a temporary measure that fixes #2692.
> 
> This reverts commit 15ef885836907b27b2c0481f7ea83d1dd504c5d5.
> 
> (cherry picked from commit 22c47df2423e6149c4b37d5f70741adcf3365f5d)
This needed manual cherry-picking, I suggest we wait for the actions to run through, before merging.
> [Backport v2022.1.x] Revert "ipq40xx: switch Wave2 firmware to -ct (#2541)"

- package/gluon-core/luasrc/lib/gluon/upgrade/200-wireless
Currently the 'channels' setting of a 5G radio gets overwritten or deleted even if the 'preserve_channels' option is enabled. Only set the list of channels in outdoor mode if 'preserve_channels' is disabled and never delete the channel list (like for 2G radios).
> gluon-core: preserve channel list for 5G radios

- docs/user/supported_devices.rst
- package/gluon-core/luasrc/usr/lib/lua/gluon/platform.lua
- targets/ath79-generic
- ~~TFTP~~ untested
- *Web interface and TFTP should probably work, too, but were not tested yet.*
- **edit aiyion**: web interface works as well
**has no label, but at least is not random**
- *only tested 2.4 GHz*
- *only tested 2.4 GHz*
- LED mapping
- …
> ath79-generic: add LibreRouter v1

- README.md
- contrib/ci/minimal-site/site.conf
- docs/conf.py
- docs/releases/index.rst
- docs/releases/v2022.1.3.rst
- docs/site-example/site.conf
- docs/user/getting_started.rst
This adds Release-Notes for the Gluon v2022.1.3 bugfix-release.
This release only adds workarounds to Gluons core functionality.
Testing of the latest commit looks good in hanover and @rotanid reported no issues either.
> docs: Add v2022.1.3 release notes

- docs/user/supported_devices.rst
- targets/ramips-mt7621
Test Device: https://map.chemnitz.freifunk.net/#!v:m;n:9483c41c0a42
(`lua -e 'print(require("platform_info").get_image_name())'`) -> gl.inet-gl-mt1300
- LED mapping
- Radio LEDs (none)
- Switch port LEDs (none)
- Docs:
> ramips-mt7621: add GL.iNet MT1300

- docs/user/supported_devices.rst
- package/gluon-core/luasrc/lib/gluon/upgrade/250-cellular
- package/gluon-core/luasrc/usr/lib/lua/gluon/platform.lua
- package/gluon-setup-mode/files/lib/gluon/setup-mode/rc.d/S96led
- package/gluon-setup-mode/luasrc/usr/lib/lua/gluon/setup-mode.lua
- targets/ath79-nand
- LED mapping
- Radio LEDs
- 3G/4G LED
- Added board name to `is_outdoor_device` function in …
> ath79-nand: add support for GL.iNet GL-XE300

- targets/ath79-generic
The device was introduced in #2332 and merged in 102a4b9350c925cbbe15fdead43a370c445eacf8.
It appears that the autoupdater name wasn't correct and devices therefore don't receive updates.
```
root@64295-ggw3-20b399bb366f-132:~# lua -e 'print(require("platform_info").get_image_name())'
enterasys-ws-ap3705i
```
cc @blocktrron
> ath79-generic: fix WS-AP3705i autoupdater name

- .github/workflows/build-gluon.yml
- CONTRIBUTING.md
- docs/user/x86.rst
Fix also another sentence in `docs`.
> actions, docs: fix English typo, wording

- package/gluon-status-page/files/lib/gluon/status-page/view/status-page.html
Instead of checking for the deprecated sysfs entry `wireless` which no longer exists when running newer versions of openwrt, testing for `phy80211` can be used and works for old and new versions of openwrt.
> gluon-status-page: fix status display of wireless mesh for recent openwrt

- package/gluon-core/luasrc/lib/gluon/upgrade/110-network
Set the MAC-adress for the WAN interfacce in case it is defined in the board-data.
This commit fixes random MAC-Addresses on reboot in case OpenWrt stores them in the device network configuration.
Fixes #2808
> gluon-core: set WAN mac from board-data

- docs/user/supported_devices.rst
- targets/ramips-mt7621
- otherwise the first port should be delcared as WAN, all other ports LAN
- LED mapping
- Radio LEDs (NONE)
- Docs:
> ramips-mt7621: add support for Mercusys MR70X v1

- docs/user/supported_devices.rst
This device is already supported.
It's a lantiq device that was entered as ar71xx
in to the list of supported device and therefore
removed before the release of Gluon 22.
EDIT: https://github.com/freifunk-gluon/gluon/commit/003c90f0b20af7dc0f51893a3931ad8bada725d2
> docs: readd TP-Link TD-W8970 v1 

- targets/ipq40xx-mikrotik
The only device using the ATH10K_PACKAGES_IPQ40XX variable in ipq40xx-mikrotik (the MikroTik hAP ac2) has little RAM and is using ath10k-ct-smallbuffers by default at the moment. This is just a suggestion to rename the variable in-case the wifi driver ever has to be replaced by ath10k.
Analogue to 4a00b8aebba30cfd4d5aa691fb850cb6ab4152e7
> ipq40xx-mikrotik: rename ath10k_packages to smallbuffers

- docs/user/supported_devices.rst
- targets/ramips-mt7621
- press reset while powering the device
- connect yourself to the network port, configure ipv4 within 192.168.0.0/24
- device is reachable via http://192.168.0.50
- upload factory firmware image
Caveats:
- doesn't respond to pings
- error during uploads from browsers which aren't chromium based (worst case: we'll need some small application in the future which handles the upload in a way the device understands, for now chromium based browsers seem to work)
the setting from the old version …
> ramips-mt7621: add support for D-Link DAP-X1860 (A1)

- targets/ath79-generic
This partially reverts commit 22c47df2423e6149c4b37d5f70741adcf3365f5d.
Devices in ath79-generic like the TP-Link EAP225-Outdoor v1 are really unstable with the non -ct Wave2 firmware and regulary crash with 100% memory consumption when only a handful devices are connected via 5 GHz.
closes freifunk-gluon/gluon#2827
Both Variants aren't without issues, but i feel like this could be a bit less interruptive. The best approach would be probably to just disable the 5 GHz Radios as a fix seems unlikely.
> ath79-generic: switch Wave2 firmware to -ct

- docs/user/supported_devices.rst
- targets/ramips-mt7621
this backports three devices:
GL.iNet MT1300
https://github.com/freifunk-gluon/gluon/pull/2813
Mercusys MR70X v1
https://github.com/freifunk-gluon/gluon/pull/2831
D-Link DAP-X1860 (A1)
https://github.com/freifunk-gluon/gluon/pull/2830
( needs #2859 )
> v2022.1.x ramips-mt7621 hardware backports

- docs/conf.py
> Config Mode
> - http://192.168.1.1
> 
> (not existing) anchors on hackint used to join channels
> - https://webirc.hackint.org/#
Prior to this commit `make linkcheck; echo $?` returns non-zero in `docs/`
This change makes the return code of said command useful again and reduces its execution time drastically, as 192.168.1.1 is not tested until it timeouts after quite a while.
> docs: use linkcheck_ignore for unreachable links

- contrib/actions/install-dependencies.sh
- contrib/docker/Dockerfile
- docs/user/getting_started.rst
Target x86-64 does not build otherwise and does not show useful messages concerning the missing package either.
This issue was discussed on #gluon on IRC and was found by comparing the install docs to the `contrib/docker/Dockerfile`.
This PR updates the install dependencies and docs
* add missing libelf-dev dependency (to build x86-64)
* remove subversion dependency
* add rsync dependency
* add ecdsautils to docs (to sign firmware)
> [docs] improve build dependencies and docs

- package/libbatadv/src/batadv-genl.c
- package/libbatadv/src/batman_adv.h
`batadv_gw_modes` and `BATADV_ATTR_GW_MODE` were missing from the local version, so update it from upstream.
> libbatadv: Update UAPI from kernel 6.2

- patches/openwrt/0008-xrx200-migrate-fritz7360-v2-using-incorrect-image.patch
As mentioned in #2648 this backports the fritz 7360v2 migration to v2022.1.x branch
Migrate AVM FRITZ!Box 7360 v2 boards flashed with the incorrect v1 image to use the newly added v2 target image during the next upgrade. Using the v2 target image allows the boards to read the TFFS partition, which is misaligned when using the v1 image.
Co-authored-by: Jan-Niklas Burfeind <git@aiyionpri.me>
(cherry picked from commit e4ec16d9cd2e43f84ab0253025a7cd91316f5618)
> backport-v2022.1.x - xrx200: migrate fritz7360-v2 using incorrect image

- patches/openwrt/0011-ath79-combine-OCEDO-dual-firmware-partitions.patch
- patches/openwrt/0012-ath79-combine-UniFi-AC-dual-firmware-partitions.patch
Backport two patches combining dual-flash layouts of OCEDO as well as UniFi AC boards.
The two firmware partitions are already combined on OpenWrt master to prolong the life of these devices. It allows the device to store firmware images up to 14 MB compared to the previous 7 MB.
The intention behind backporting these patches is to allow these devices to have a wide update path to firmware-versions requiring this extra space. Otherwise a device might not be able to install an upgrade which exceeds a single firmware-partition.
For UniFi AC boards it should be noted that factory-installation will not be possible with an image exceeding a single firmware-partition. In this case, an older OpenWrt image that fits in a single partition and supports writing the enlarged partition space is …
> openwrt: backport combination of dual-flash partitions

- docs/features/vpn.rst
- package/gluon-mesh-vpn-wireguard/Makefile
- package/gluon-mesh-vpn-wireguard/luasrc/lib/gluon/upgrade/400-mesh-vpn-wireguard
- package/gluon-mesh-vpn-wireguard/src/Makefile
- package/gluon-mesh-vpn-wireguard/src/gluon-hex-to-b64.c
This reencodes an existing fastd private key as WireGuards private (X25519).
No key is migrated, when no fastd key exists.
We discussed whether it would be cleaner to put it in its own upgrade file, this would be one way of doing it, although writing to network-old appears bad to me. Open for discussion.
~~I have not tested the implementation of the upgrade yet.~~
Is tested. It updates missing or invalid WireGuard-keys based on the fastd secret key if it exists.
> gluon-mesh-vpn-wireguard: add fastd key migration

- docs/user/supported_devices.rst
- targets/ath79-nand
> ath79-nand: (re)add hiveap-121
>     
>     Gone due to
>     commit 45c84a117bf8 ("ar71xx: drop target")
> ath79-nand: add vendor to GL.iNet devices
@kpanic23 intends to test this device starting monday.
- ~~TFTP~~
- ~~Other: install via serial, and load via tftp following the commit message https://github.com/openwrt/openwrt/commit/62db255543c8fb5d1787caf36c6c7c9c51db71cd~~
- On devices supplied via PoE, there is …
> ath79-nand: (re)add hiveap-121

- docs/user/supported_devices.rst
- targets/ramips-mt7621
(`lua -e 'print(require("platform_info").get_image_name())'`) cudy-x6-v2
- ~~When re-adding a device that was supported by an earlier version of Gluon, a
the setting from the old version is not reset otherwise.~~
- ~~if there are multiple ports but no WAN port:~~
- ~~the PoE input should be WAN, all other ports LAN~~
- ~~otherwise the first port should be declared as WAN, all other ports LAN~~
- LED mapping
- Radio LEDs
- Docs: …
> ramips: add support for Cudy X6 v2

- docs/user/supported_devices.rst
I made the mistake of never looking at the rendered version
fixes 95e5d382ecc65ed68262b90e2fc5f2d8a13d464c
backport like 8b2cc206d30b7ca52d275b00bcde400102356a05 is optional
> docs: fix supported_devices (missing newline)

- targets/ath79-generic
> This partially reverts commit 22c47df2423e6149c4b37d5f70741adcf3365f5d.
> 
> Devices in ath79-generic like the TP-Link EAP225-Outdoor v1 are really unstable with the non -ct Wave2 firmware and regulary crash with 100% memory consumption when only a handful devices are connected via 5 GHz.
> 
> closes freifunk-gluon/gluon#2827
> 
> (cherry picked from commit 4badb2702edd396109038da129227413795f7a49)
> [Backport v2022.1.x] ath79-generic: switch Wave2 firmware to -ct

- README.md
- contrib/ci/minimal-site/site.conf
- docs/conf.py
- docs/releases/index.rst
- docs/releases/v2022.1.4.rst
- docs/site-example/site.conf
- docs/user/getting_started.rst
Add Release notes for the Gluon Release v2022.1.4.
The commit adding Release-Notes requires to be forward-ported to master.
> docs: Add v2022.1.4 release notes

- .readthedocs.yml
Docs builds currently fail with
Could not import extension sphinx.builders.linkcheck (exception: urllib3 v2.0 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with OpenSSL 1.0.2n  7 Dec 2017.
See: https://github.com/urllib3/urllib3/issues/2168)
The ~~Gluon~~ rtd issuetracker suggests specifying the build-container.
Link: https://github.com/readthedocs/readthedocs.org/issues/10290#issuecomment-1535120995
> readthedocs: specify build-container

- docs/user/supported_devices.rst
- targets/ramips-mt7621
(`lua -e 'print(require("platform_info").get_image_name())'`) cudy-wr1300
- ~~When re-adding a device that was supported by an earlier version of Gluon, a
the setting from the old version is not reset otherwise.~~
- ~~On devices supplied via PoE, there is usually no explicit WAN/LAN labeling on the hardware.
The PoE input should be the WAN port in this case.~~
- LED mapping
- Radio LEDs
- Docs:
> ramips: add support for Cudy WR1300 v1

- package/gluon-core/luasrc/usr/bin/gluon-info
- provides easier information of the currently active domain 
- tested by patching a running node
partially fixes #2790
> gluon-info: Add domain to gluon-info

- docs/user/supported_devices.rst
- targets/ramips-mt7621
Follow up on failed action
> Backport failed for `v2022.1.x`, because it was unable to cherry-pick the commit(s).
> 
> Please cherry-pick the changes locally.
> ```bash
> git fetch origin v2022.1.x
> git worktree add -d .worktree/backport-2794-to-v2022.1.x origin/v2022.1.x
> cd .worktree/backport-2794-to-v2022.1.x
> git checkout -b backport-2794-to-v2022.1.x
> ancref=$(git merge-base 918e3ce78470b6e7ee37ff00809fb2b398490311 e06e555ac22d17ac5c061c3783cc28300e42e68b)
> git cherry-pick -x $ancref..e06e555ac22d17ac5c061c3783cc28300e42e68b
> ```
> 
> 
_Originally posted by @github-actions[bot] in https://github.com/freifunk-gluon/gluon/issues/2794#issuecomment-1541052832_
> [Backport v2022.1.x] Backport Cudy WR1300 to v2022.1.x

- package/gluon-core/luasrc/lib/gluon/upgrade/010-primary-mac
- targets/ipq40xx-generic
This device was tested by someone in our community.
This looks good so far, we are still investigating the open issues and see if we can get support for 5GHz Wifi out of the box too.
#output is "meraki-mr33-access-point" - added to manifest_aliases
#eth0 MAC matches - set in 010-primary
- otherwise the first port should …
> ipq40xx-generic: add support for Meraki MR33

- docs/user/supported_devices.rst
- package/gluon-core/luasrc/usr/lib/lua/gluon/platform.lua
- targets/ath79-generic
> Gone due to
"nrb" intends to test this device "after sleeping".
- LED mapping
- Radio …
> ath79-generic: (re)add Rocket M2/M5 (XM)

- docs/user/supported_devices.rst
- package/gluon-core/luasrc/usr/lib/lua/gluon/platform.lua
- targets/ath79-generic
This reverts commit 97efc8abdbd6264a19cbe6c5b95851245f6b798a. (#2580)
Since the commit was drafted the device was moved from ath79-generic to ath79-tiny ([4b5bd15](https://github.com/openwrt/openwrt/commit/4b5bd1509195bc8f19999ebe481b59356b5c3512)).
Therefore the commit breaks builds of the ath79-generic target (`unable to enable device 'ubnt_rocket-m'`).
It might be possible to add support for the ath79-tiny target, and with it the Rocket M2/M5 (XM), in the future.
> Revert "ath79-generic: (re)add Rocket M2/M5 (XM)"

- patches/openwrt/0013-mac80211-mask-nested-A-MSDU-support-for-mesh.patch
This disables A-MSDU support on mesh-links. This restores throughput on mesh-links established between broken (ath10k) and correct (mt76) implementations of mesh A-MSDU.
This patch can be dropped when switching to the next OpenWrt release, as proper fixes have been applied.
Link: https://www.spinics.net/lists/linux-wireless/msg232410.html
Link: https://github.com/openwrt/mt76/issues/450
```
root@64367-4040:~# iperf3 -c 2001:67c:2ed8:100e:aa63:7dff:fe2e:9378
Connecting to host 2001:67c:2ed8:100e:aa63:7dff:fe2e:9378, port 5201
[  5] local 2001:67c:2ed8:100e:eadf:70ff:fe79:bbc1 port 43576 connected to 2001:67c:2ed8:100e:aa63:7dff:fe2e:9378 port 5201
[ ID] Interval           Transfer     Bitrate         Retr  Cwnd
[  5]   0.00-1.00   sec  86.1 KBytes   705 Kbits/sec   19   2.36 KBytes …
```
> openwrt: mask nested A-MSDU support for mesh

- docs/user/supported_devices.rst
- package/gluon-core/luasrc/lib/gluon/upgrade/250-cellular
- package/gluon-core/luasrc/usr/lib/lua/gluon/platform.lua
- targets/ramips-mt76x8
(`lua -e 'print(require("platform_info").get_image_name())'`) tp-link-tl-mr6400-v5
- ~~When re-adding a device that was supported by an earlier version of Gluon, a
the setting from the old version is not reset otherwise.~~
- ~~if there are multiple ports but no WAN port:~~
- ~~the PoE input should be WAN, all other ports LAN~~
- ~~otherwise the first port should be declared as WAN, all other ports LAN~~
- LED mapping
- Radio LEDs (there's one for 2.4GHz)
- Switch port LEDs (one wan and one lan …
> ramips-mt76x8: add support for TP-Link TL-MR6400 v5

- docs/user/supported_devices.rst
We support all revisions of v1
Even the one with the new eon/cfeon flash chip (support was added with openwrt 22.03.03)
v2 only exists in master currently and (apparently) has a different 5GHz flash chip (mt7663/mt7615) and a slightly different partition scheme (maybe there are further differences, I didn't notice):
https://github.com/openwrt/openwrt/pull/11803
> docs: support only for Xiaomi Mi Router 4A Gigabit v1

- docs/user/supported_devices.rst
- package/gluon-core/luasrc/lib/gluon/upgrade/020-interfaces
- targets/ramips-mt7621
`tp-link-eap615-wall-v1`
- LED mapping
- Radio LEDs
N/A, no radio LEDs
N/A, no switch port LEDs
- Outdoor …
> ramips-mt7621: Add support for TP-Link EAP615-Wall

- package/features
- package/gluon-mesh-olsrd/Makefile
- package/gluon-mesh-olsrd/luasrc/lib/gluon/upgrade/360-gluon-mesh-olsrd-setup-intf
- patches/packages/routing/0005-oonf-olsrd2-fix-building-with-multiple-plugins.patch
- patches/packages/routing/0006-oonf-olsrd2-add-missing-static-plugin-olsrv2_lan.patch
- patches/packages/routing/0007-oonf-olsrd2-change-to-git-version-from-2022-08-25.patch
- patches/packages/routing/0008-oonf-olsrd2-add-git-version-for-compile-in.patch
- patches/packages/routing/0009-oonf-olsrd2-a-usable-default-configuration.patch
Note: still need to test changes standalone, but this is more or less the working version from graz, so feel free to review.
All of the patches that are being pulled in are submitted upstream for review. The only thing I expect that might happen during review upstream is that some default-on for plugins get rejected, in which case we have to enable it via gluon.
> gluon-mesh-olsrd: support clientap

- package/gluon-core/luasrc/lib/gluon/upgrade/250-cellular
- package/gluon-wan-dnsmasq/files/etc/hotplug.d/iface/50-gluon-wan-dnsmasq
- package/gluon-wan-dnsmasq/files/lib/gluon/wan-dnsmasq/interface.d/050-gluon-wan-dnsmasq
Use DNS servers received from the cellular provider for the WAN dnsmasq instance.
This fixes resolving VPN endpoint DNS requests when using only cellular uplink.
Fixes #2849
> gluon-wan-dnsmasq: use cellular DNS servers

- docs/user/supported_devices.rst
- targets/ath79-nand
The ZTE MF281 was missing a reason why it is marked as broken.
We only support Unifi 6 LR v1 currently. v2 should work fine with the same image (small led related error in dmesg), but v3 has a different ethernet phy (1gbit/s instead of 2.5gbit/s) the device won't be accessible over ethernet after install (stuck in config mode)
OpenWrt doesn't support v3, yet. v2 could be added to the list but we probably expect people to run the check list again, therefore I'll leave it out.
There is no exact version number silkscreened on the board afaik. But you can still find out whether it's a v3 according to the [wiki](https://openwrt.org/toh/ubiquiti/unifi_6_lr).
> **Important** Devices with manufacturing date 2234 (34rd week of 2022) and later appear to be a version 3 hardware with a different (1 …
> docs: ath79-nand: small adjustments

- docs/user/supported_devices.rst
- package/gluon-core/luasrc/usr/lib/lua/gluon/platform.lua
- targets/ath79-generic
> ath79-generic: add support for Ubiquiti NanoBeam 5AC 19 (XC)

- .github/filters.yml
- contrib/docker/Dockerfile
Bookworm is now the stable debian version. We should let the CI validate that Gluon can be build there. Currently that does indeed [work for all targets](https://github.com/herbetom/gluon/actions/runs/5803545351).
> Dockerfile: update base to debian:bookworm-slim

- docs/user/supported_devices.rst
Since the device isn't marked as broken it should be mentioned in the docs as a supported device.
https://github.com/freifunk-gluon/gluon/blob/5e9afa33abcb2e7b6f28019b7532055000e43521/targets/ipq40xx-generic#L158-L163
> docs: supported_devices: add missing 8devices Jalapeno

- docs/user/supported_devices.rst
- targets/mediatek-filogic
- LED mapping
- Radio LEDs
- Docs:
> mediatek-filogic: add support for NETGEAR WAX220

- docs/user/supported_devices.rst
- targets/ramips-mt7621
Add support for ASUS RT-AX53U
- ssh > mtd-write factory image to Kernel-partition
[Wiki instructions](https://openwrt.org/toh/asus/rt-ax53u#installation_with_mtd-write)
- tftp via serial (requires opening the case)
[Wiki instructions](https://openwrt.org/toh/asus/rt-ax53u#installation_with_tftp)
- Asus Firmware Restoration Tool on Windows
Flash OpenWrt Kernel/initramfs first, then sysupgrade to Gluon
[Asus Instructions](https://www.asus.com/support/FAQ/1000814/)
[Download Firmware Restoration Tool](https://dlcdnets.asus.com/pub/ASUS/wireless/GT-AX6000/Rescue_2103.zip)
`asus-rt-ax53u`
Device has two MACs:
- 50:eb:f6:83:2c:14 (2.4GHz and LAN …
> ramips-mt7621: add ASUS RT-AX53U

- docs/user/supported_devices.rst
- targets/mediatek-filogic
- LED mapping
- Radio LEDs
- Docs:
> mediatek-filogic: add support for Cudy WR3000 v1

- docs/user/supported_devices.rst
- targets/ramips-mt7621
(soory for the spam, same as https://github.com/freifunk-gluon/gluon/pull/2962, thought I lost access to my account)
Better known as ZyXEL Multy M1
logread is full of `daemon.err hostapd: nl80211: kernel reports: integer out of range`, but that should be gone after [this](https://patchwork.ozlabs.org/project/openwrt/patch/20230830161559.10770-3-nbd@nbd.name/) is merged.
<details><summary>There are kernel warnings, I have no idea what they mean.</summary>
```
[  278.192368] WARNING: CPU: 2 PID: 6161 at backports-6.1.24/net/mac80211/mesh_hwmp.c:353 airtime_link_metric_get+0x110/0x724 [mac80211]
[  278.204640] Modules linked in: iptable_nat batman_adv xt_state xt_nat xt_conntrack xt_REDIRECT xt_MASQUERADE xt_CT wireguard nf_nat nf_conntrack mt7915e mt76_connac_lib mt76 mac80211 …
```
> rampis-mt7621: add support for ZyXEL WSM20

- .github/workflows/build-docs.yml
Replaces hard coded dependency.
Closes #2955
> docs: GH use `requirements.txt`

- .github/workflows/build-container.yml
This adds a workflow to push the build-container described in Gluons Dockerfile to the freifunk-gluon organizations container registry.
This will create a image
- For every push to master
- For every tagged version
> contrib: push Docker build-container to GitHub registry

- targets/x86.inc
This reverts commit 41b8ecd6177f3916ec2ad16bf0f1a1551e77bfd4.
Unbreak upgrades from OpenWrt 19.07 (Gluon 2021.1.x) by undoing the partition table change.
It should be noted that the EFI images generated by OpenWrt are slightly smaller than the non-EFI images for some reason (due to a smaller gap between the boot and root partitions), so upgrading a VM created using a Gluon 2023.1 (EFI) image to a newer non-EFI image will truncate the root partition.
Linux will warn about the truncation on boot ("sda: p2 size 212992 extends beyond EOD, truncated"), but it doesn't cause any other issues, as the root partitions of x86 squashfs images are mostly empty, and the overlay is created in the actual available space after the upgrade. The cosmetic issue will go away as soon as we switch to EFI again …
> Revert "x86: switch to EFI-compatible images"

- package/gluon-status-page/files/lib/gluon/status-page/view/layout.html
- package/gluon-status-page/files/lib/gluon/status-page/view/status-page.html
- package/gluon-status-page/files/lib/gluon/status-page/www/index.html
- package/gluon-status-page/files/lib/gluon/status-page/www/robots.txt
Disallow crawlers to crawl and index page.
Crawling causes traffic and high load.
Indexation max cause unintended attention, e.g. spam, ..
Reference:
https://developers.google.com/search/docs/crawling-indexing/robots-meta-tag
Closes #2952
> gluon-status-page: disallow crawler/robots to index

- contrib/docker/Dockerfile
- scripts/container.sh
For UIDs/GIDs other than 1000, `scripts/container.sh` was not working correctly, as the owner of the build directory mounted into the container did not match the UID running inside the container. Fix by making them match.
The PR also includes a commit from #2838 by @skorpy2009 with an updated commit message.
Supersedes #2838
Supersedes #2868
Supersedes #2870
> Fix Dockerfile / container.sh for UID/GID other than 1000

- contrib/docker/Dockerfile
Add ssh-client to enable deployment of the build output from CI.
> contrib: Dockerfile: install openssh-client

- .github/workflows/build-container.yml
The docker container on PR action is broken in case the PR is not opened within the Gluon project.
Remove the build on PR so the pipeline does not fail for third party PRs.
> workflow: don't push Docker container on PR

- package/gluon-mesh-vpn-tunneldigger/luasrc/usr/bin/tunneldigger-watchdog
The tunneldigger init script has been migrated to procd, so there is no PID file anymore. Remove the obsolete check altogether - it shouldn't be needed anymore, as procd will take care of crashes of tunneldigger by itself. This fixes the watchdog resetting tunneldigger every time it runs.
Closes #2977
> gluon-mesh-vpn-tunneldigger: tunneldigger-watchdog: remove broken restart check

- docs/_static/css/custom.css
- docs/releases/v2023.1.rst
Should be merged and backported only if we intend to merge #2972.
> docs: releases/v2023.1: add warning and known issue for v2021.1.x x86 upgrade

- package/gluon-wan-dnsmasq/files/etc/init.d/gluon-wan-dnsmasq
Rewrite the gluon-wan-dnsmasq initfile to use procd. This allows for configuring restart handling by procd in case of a crash.
While at it, disable the caching feature optionally used for the regular dnsmasq on the wan dnsmasq. This daemon is only for redirecting DNS requests to use local network resolvers, not introducing caching.
> gluon-wan-dnsmasq: rewrite initfile to use procd

- patches/openwrt/0004-ramips-mt7621-make-DSA-images-swconfig-upgradable.patch
Support for upgrading the device from an swconfig based image to an DSA based one was accidentally removed in [07e8343](https://github.com/freifunk-gluon/gluon/commit/07e83438c1b95a1f58d61ea1258496a083330714#diff-250261910203be4ae4259df3e6e6a1437df603706d598129ea9e808168cd11d6L20-L25).
This PR targets the v2023.1.x branch because we've since switched the OpenWrt Release in master and dropped the patch in the process.
cc @maurerle
> [v2023.1.x]: patches: make D-Link DIR-860L B1 upgradable from swconfig to DSA

- docs/_static/css/custom.css
Remove a workaround for a CSS issue in older Firefox versions, which was recently fixed (at some point between Firefox 102 and 108). Firefox 108+ now displays the bullet points at the right vertical position even without the hack in [1].
[1] https://gluon.readthedocs.io/en/latest/releases/v2018.1.html#site-conf
Opening as a draft for now, as the current Extended Support Release is Firefox 102. I propose to merge this as soon as all Firefox versions without the fix are EOL.
> docs: remove remaining CSS workaround

- docs/user/supported_devices.rst
- package/gluon-core/luasrc/lib/gluon/upgrade/010-primary-mac
- targets/mpc85xx-p1010
- LED mapping
- Radio LEDs
- Docs:
> mpc85xx-p1010: add support for Enterasys WS-AP3715i

- patches/openwrt/0014-Revert-mt76-update-to-the-latest-version-from-the-22.03-branch.patch
- patches/openwrt/0015-Revert-mt76-update-to-the-latest-version-from-the-22.03-branch.patch
The latest mt76 bump results in broken WLAN on the D-Link DAP-X1860 (#3003).
Reverting them works arround this for now.
> [v2023.1.x] patches: openwrt: revert latest mt76 bump

- .github/filters.yml
- .github/workflows/check-ci.yml
The filters generated by `generate-target-filters.py` did not match the actual filters, but the extraneous entry (added in c418b7bb16d54090e468cfb8a89d20655bd466a6) did not do what it was supposed to (as our CI builds do not use the Docker image).
Revert the change and introduce a CI check to prevent future inconsistencies.
> CI: Fix target filters, add CI check

- .github/filters.yml
- targets/targets.mk
lantiq-xrx200 is currently marked as source-only in OpenWrt 23.05, as the switch driver does not work correctly on Linux 5.15. Mark as broken in Gluon as well until the issue is fixed.
Upstream PR: https://github.com/openwrt/openwrt/pull/13200
> lantiq-xrx200: mark target as broken

- modules
- scripts/modules.sh
In Gluon v2023.1, our tunneldigger package in freifunk-gluon/packages got replaced with a new package in openwrt/packages, causing multiple bugs. To prevent similar issues in the future, reorder the list of feeds, resulting in the following order of precedence:
- OpenWrt base
- Gluon base
- (Site feeds)
- Gluon packages
- OpenWrt packages
- OpenWrt routing
Should be backported to v2023.1.x.
> Prefer packages from Gluon feeds to upstream feeds

- docs/user/supported_devices.rst
- targets/ath79-generic
- LED mapping
- Radio LEDs
- Docs:
Device's radio can be …
> ath79-generic: re-add support for TP-Link TL-WR2543N-ND

- .github/workflows/build-container.yml
Improve the build-process for the Docker container
- Only push to GitHub container registry when executed for the `freifunk-gluon` organization
- Build and tag docker container not only for master but also for release branches
- Enable building of the docker-container on pull-requests again
> actions: improve docker image build-process

- package/gluon-core/luasrc/lib/gluon/upgrade/250-cellular
- package/gluon-core/luasrc/usr/lib/lua/gluon/platform.lua
- targets/ipq40xx-generic
Also known in Germany as Gigacube CAT20
Added as Broken because you need to open the Device to access the Serial Console for flashing
- LED mapping
Device contains a Status LED inside which …
> ipq40xx-generic: add support for ZTE MF289F

- .github/filters.yml
- .github/workflows/build-gluon.yml
- contrib/actions/generate-target-filters.py
In https://github.com/freifunk-gluon/gluon/pull/2997 it was pointed out the current branch-trigger matches more
branches than the release-branches. Retrict the match-pattern to only
cover release-branches
Also only trigger builds on the next-branch and not branches prefixed
with this name.
Link: https://github.com/freifunk-gluon/gluon/pull/2997#issuecomment-1771076385
---
Add a workflow-dispatch trigger to the build-workflow to enable
triggering build-tests on branches not covered from the match
pattern.
---
It makes sense to run CI build-tests in case the CI itself is altered.
> ci: update branch-pattern matching

- Makefile
- scripts/basic_openwrt_config.sh
Upstream introduced two different methods for determining the state of a package within the OpenWrt buildsystem. While both are based around the md5 hash-function, one taks filename & mtime into account while the other one uses the actual md5 hash of the file-content.
Ever wondered why Gluon suddenly took considerably longer to build? The messy part is how the build-system chooses which method to use. This is based around the AUTOREMOVE configuration. Gluon sets this variable conditionally when built with GLUON_AUTOREMOVE set to 1.
Enter the Gluon build-system. It first compiles Lua, without the AUTOREMOVE configuration passed to OpenWrt. This compiles the packages with the old hash-method based around filename & mtime. Afterwards, it builds with AUTOREMOVE enabled, changing the …
> build: fix duplicate building of host-tools

- docs/user/supported_devices.rst
- targets/ath79-generic
This device was gone. I tried to use it with the smallbuffers wifi firmware and the device remained suprisingly stable. I whould also consider to add this at least with the broken flag, because I do not have a crowded test environment.
Test device: https://map.chemnitz.freifunk.net/#!v:m;n:50c7bf2cf5c8
(`lua -e 'print(require("platform_info").get_image_name())'`) -> tp-link-archer-c60-v1
- LED mapping
- Radio LEDs
- Docs:
> ath79-generic: (re)add support for archer-c60

- package/gluon-radv-filterd/src/gluon-radv-filterd.c
Allocation of the router structure for newly detected router advertisements was done using malloc and selectively clearing some of the structure fields. However the redirect boolean was never set to 0, which means that during update_redirect, we would depend on the random initialization value of the structure.
This means that sometimes ebtables-tiny wouldn't add the correct rules for the advertised routes.
> gluon-radv-filterd: replace malloc with calloc

- package/gluon-core/luasrc/lib/gluon/upgrade/010-primary-mac
- targets/mediatek-filogic
- LED mapping
- Radio LEDs
- Docs:
> mediatek-filogic: add support for ASUS TUF-AX4200

- docs/user/supported_devices.rst
- package/gluon-core/luasrc/usr/lib/lua/gluon/platform.lua
- targets/ath79-generic
* Note: direct vendor firmware to Gluon untested, device was originally flashed from vendor fw to vanilla OpenWrt
- ~~if there are multiple ports but no WAN port:~~
- ~~the PoE input should be WAN, all other ports LAN~~
- ~~otherwise the first port should be declared as WAN, all other ports LAN~~
- LED mapping …
> ath79-generic: add support for TP-Link EAP225-Outdoor v3

- targets/generic
OpenWrt does not ship with WolfSSL anymore. Instead mbedTLS is shipped by default.
We can remove the default removal of WolfSSL packages, as they are not included by default anymore.
> target: remove package-removal NOPs

- package/gluon-status-page/files/lib/gluon/status-page/view/layout.html
- package/gluon-status-page/files/lib/gluon/status-page/view/status-page.html
google-lighthouse:
Warning: Consider avoiding viewport values that prevent users from resizing documents.
Rule ID: meta-viewport
Accessibility:
Ruleset: axe-core 4.4
User Impact: Critical
Guidelines: WCAG 2.1 Best Practice, WCAG 2.0 Best Practice
Mentioned in #2953
> gluon-status-page: html: improve accessibility

- package/gluon-core/luasrc/lib/gluon/upgrade/021-interface-roles
In case no interface role was selected for a given interface, gluon-reconfigure currently fails with
```
Configuring: 021-interface-roles
/usr/bin/lua: /usr/lib/lua/gluon/util.lua:25: bad argument #1 to 'pairs' (table expected, got nil) stack traceback:
[C]: in function '?'
/usr/lib/lua/simple-uci.lua:22: in function 'foreach'
./021-interface-roles:47: in main chunk
[C]: ?
```
Check we actually have a role set before accessing the table.
> gluon-core: dont fail on unset interface role

- targets/generic
Package name of mbedtls is not 'mbedtls' but 'libmbedtls'.
> generic: fix removal of mbedtls

- package/gluon-mesh-vpn-core/luasrc/lib/gluon/upgrade/500-mesh-vpn
This code was added way back in 2017. We don't support updates from those old versions, so we can remove it.
> gluon-mesh-vpn-core: remove old migration code

- package/gluon-mesh-vpn-core/Makefile
- package/gluon-mesh-vpn-fastd/Makefile
- package/gluon-mesh-vpn-tunneldigger/Makefile
- package/gluon-mesh-vpn-wireguard/Makefile
The vpn-core package does not utilize simple-tc anymore. This is now up to the VPN implementations.
> gluon-mesh-vpn: depend on simple-tc in implementation

- targets/ath79-generic
This device has been successfully tested by @J0chn1
It works fine, but due to the small size I think it can only get BROKEN support due to smallbuffers?
- LED mapping …
> ath79-generic: add support for AVM Fritz!Repeater 1750e

- .github/workflows/build-gluon.yml
- contrib/actions/run-build.sh
- contrib/actions/show-system-info.sh
Despite what GitHub states in their documentation, the runners feature a
different core count. Automatically set the build thread-count by the
amount of available CPU cores.
Link: https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources
---
Collect some basic system information about the runners the CI jobs
run on. This is done iwth the intention to have diagnostics information
in advance in case builds fail spuriously in some instances.
> ci: dynamically set thread-count 

- docs/user/supported_devices.rst
- targets/mediatek-filogic
There is a new way to flash OpenWrt on the ASUS TUF AX4200 which does not require to open the device.
Link: https://github.com/blocktrron/openwrt-asus-filogic-factory/releases/tag/filogic-v1
> mediatek-filogic: remove broken flag for TUF AX4200

- docs/multidomain-site-example/domains/alpha_centauri.conf
The wifi channels in the multi domain example are somehow in the wrong section
> docs: move wifi channels in multi domain site example

- docs/user/supported_devices.rst
- package/gluon-core/luasrc/usr/lib/lua/gluon/platform.lua
- targets/ath79-mikrotik
[X] Must be flashable from vendor firmware
- LED mapping
- Radio LEDs
- Cellular …
> ath79-mikrotik: add support for MikroTik wAPR-2nD (wAP R)

- docs/user/supported_devices.rst
- targets/mediatek-filogic
- ~~if there are multiple ports but no WAN port:~~
- ~~the PoE input should be WAN, all other ports LAN~~
- ~~otherwise the first port should be declared as WAN, all other ports LAN~~
- LED mapping
- ~~Radio LEDs~~ No radio LED available
- ~~Switch port LEDs~~ No switch LED available
- Outdoor …
> mediatek-filogic: add support for GL.iNet GL-MT3000

- .github/filters.yml
- targets/targets.mk
This removes the BROKEN flag from the lantiq-xrx200 target. The issues with the switch-driver have been resolved upstream
Link: https://github.com/openwrt/openwrt/pull/13638
> lantiq-xrx200: remove BROKEN target-flag

- docs/user/supported_devices.rst
- targets/ath79-generic
Remove due to ticket #2939
These devices risk being bricked in a way that can not be recovered without running full TFTP or serial recovery, as the flash ends up in a read-only state with no way of upgrading to a fixed version.
Thus, remove the support for the time being. Don't just flag them as BROKEN, as this would deliberately brick these boards when installating such an image.
> ath79-generic: remove Ubiquiti AirMax targets

- package/gluon-mesh-wireless-sae/Makefile
- package/gluon-wireless-encryption-wpa3/Makefile
OpenWrt now uses the new mbedTLS implementation for hostapd as well as
wpa_supplicant.
In order to keep as close to upstream as possible, use these
derivations.
----
This PR depends on #3039 as well as #3047
> treewide: use mbedTLS hostapd / wpa_s instead of WolfSSL

- package/gluon-core/luasrc/lib/gluon/upgrade/020-interfaces
- package/gluon-core/luasrc/usr/lib/lua/gluon/platform.lua
The support for NanaStations was removed in v2022.1 https://gluon.readthedocs.io/en/latest/releases/v2022.1.html#removed-devices
The NanoBeam devices and the EnGenius device are missing in master.
> gluon-core: drop removed devices

- .github/labeler.yml
There is a typo in the CI label. Also some paths are outdated or have typos, too.
CI label with typo: https://github.com/freifunk-gluon/gluon/pulls?q=is%3Apr+label%3A%223.+topic%3A+continous+integration%22+
> github: fix typos in label paths and names

- package/gluon-core/luasrc/usr/lib/lua/gluon/util.lua
- package/gluon-mesh-vpn-fastd/luasrc/usr/lib/lua/gluon/mesh-vpn/provider/fastd.lua
- package/gluon-mesh-vpn-sqm/Makefile
- package/gluon-status-page/luasrc/lib/gluon/upgrade/500-status-page
Use CAKE for shaping ingress as well as egress bandwidth shaping.
CAKE allows to better shape egress as well as ingress bandwidth. It not
only performs bandwidth shaping but also flow-queueing.
This in conjunction with the batadv flow dissector allows us to utilize
CAKE for all mesh-implementations currently supported in Gluon.
> gluon-mesh-vpn-fastd: use CAKE as bandwidth-shaper

- .github/workflows/build-gluon.yml
- contrib/actions/install-dependencies.sh
Build the CI integration test in our own docker container. This way, we can make sure Gluon builds actually succeed there.
This also has the advantage of becoming independent from the host version of GitHubs CI runners.
> ci: build Gluon in own Docker image

- .github/workflows/build-docs.yml
- .github/workflows/build-gluon.yml
- .github/workflows/check-patches.yml
- .github/workflows/labels.yml
- .github/workflows/lint.yml
- contrib/actions/generate-actions.py
- docs/requirements.txt
GitHub updated the runner version of the latest tag to Ubuntu 22.04 while this CI was built for Ubuntu 20.04.
> ci: pin runner version to Ubuntu 20.04

- package/gluon-core/Makefile
- package/gluon-core/luasrc/usr/lib/lua/gluon/iputil.lua
- package/gluon-core/luasrc/usr/lib/lua/gluon/util.lua
- package/gluon-hoodselector/Makefile
- package/gluon-hoodselector/luasrc/usr/sbin/hoodselector
- package/gluon-mesh-babel/Makefile
`lua-bit32` is pulled in by `luaposix` anyways, and for our purposes these libraries can be used interchangeably. Get rid of the unneeded dependency.
> treewide: replace luabitops with lua-bit32

- patches/openwrt/0009-Revert-mt76-update-to-the-latest-version-from-the-22.03-branch.patch
- patches/openwrt/0010-Revert-mt76-update-to-the-latest-version-from-the-22.03-branch.patch
The latest mt76 bump results in broken WLAN on the D-Link DAP-X1860 (#3003).
Reverting them works arround this for now.
(cherry picked from commit a0324f772590b143970e896db499be62a9267d27)
> patches: openwrt: revert latest mt76 bump

- package/gluon-core/luasrc/lib/gluon/upgrade/021-interface-roles
In case no interface role was selected for a given interface, gluon-reconfigure currently fails with
```
Configuring: 021-interface-roles
/usr/bin/lua: /usr/lib/lua/gluon/util.lua:25: bad argument #1 to 'pairs' (table expected, got nil) stack traceback:
[C]: in function '?'
/usr/lib/lua/simple-uci.lua:22: in function 'foreach'
./021-interface-roles:47: in main chunk
[C]: ?
```
Check we actually have a role set before accessing the table.
(cherry picked from commit c4d370367ed66ad05f596c0ffafcf813afd76809)
---
Backport of #3050
Haven't tested it (yet). Will do that once Github has created some images. But i don't expect issues.
> [v2023.1.x] gluon-core: dont fail on unset interface role

- targets/x86.inc
Add MediaTek driver packages for MT7915 as well as MT7921 WiFi 6 cards.
In addition, fix the mt7615 package name, as the driver was separated into kernel and firmware packages.
> x86: add MediaTek drivers

- docs/releases/v2023.1.1.rst
Issue a warning and a known issue for AVM Fritz!Box 7520 and 7530 not booting on the latest release.
> docs: releases/v2023.1.1: add warning and known

- targets/targets.mk
_I formatted the less important prosa as quotes to highlight the more important info_
This PR fixes two bugs I encountered while improving our Makefile.
It calls Gluon's Makefile as a submake.
That's kind of relevant for the first commit.
> We reused the variable GLUON_TARGETS for limiting what GLUON_TARGET we build (for loop).
> All without knowing that this environment variable already exists within Gluon. (or FFMUC did, I'm not sure, we basically copied their nice makefile at some point)
> This was fine while MAKE didn't call $(GLUON_MAKE) as a sub make. I fixed this by adding a plus to the shell lines calling another MAKE process.
> Since GLUON_TARGET is a variable set on the command line it takes precendence over all occurences of the variable within all makefiles (atleast for make …
> Makefile fixes

- docs/multidomain-site-example/site.mk
This commit adds the `GLUON_FEATURES_standard` variable to the multidomain site example.
> docs: add GLUON_FEATURES_standard to multidomain site example

- Makefile
- docs/user/getting_started.rst
In case a community does not use Git for versioning it's site or using a different versioning scheme that do not have annotated tags on the master branch.
> build: allow overriding GLUON_SITE_VERSION

- package/gluon-core/luasrc/lib/gluon/upgrade/020-interfaces
This preserve configuration of MAC-addresses for each interface in case OpenWrt sets them using netifd.
This is done by preserving all device-configuration which does not define a bridge or the MAC-address of a bridge.
Closes ##3100
> gluon-core: preserve interface MAC-address configuration

- docs/user/supported_devices.rst
- targets/mediatek-filogic
- LED mapping
- Radio LEDs *NONE*
- Switch port LEDs *NONE*
- Docs:
> mediatek-filogic: add support for Ubiquiti UniFi 6 Plus

- package/gluon-core/luasrc/lib/gluon/upgrade/020-interfaces
Use a delete_call with a boolean parameter function instead of manually iterating over all devices.
Link: https://github.com/freifunk-gluon/gluon/pull/3102
> gluon-core: use delete_all instead of iterated delete

- .github/filters.yml
Update the filters to make the CI happy again.
This was not caught by the CI actions of #3027, as the PR had been open for too long.
> CI: update filters

- targets/bcm27xx-bcm2708
- targets/bcm27xx-bcm2709
- targets/bcm27xx-bcm2710
As the boardname-based image name setting was broken for bcm27xx due to the target rename, we need to keep the model-based names updated for now.
Add all model strings currently seen on the Multimeshviewer and update the comments accordingly.
---
Corresponding libplatforminfo fix: https://github.com/freifunk-gluon/packages/pull/270
> bcm27xx: update manifest aliases

- package/gluon-mesh-vpn-core/luasrc/lib/gluon/upgrade/500-mesh-vpn
Remove legacy migrations. These predate the currently supported upgrade path, therefore we no longer need them.
> mesh-vpn-core: remove old migrations

- docs/user/supported_devices.rst
- targets/ath79-generic
Device is very similar to Devolo Wifi Pro series of devices.
This is the second Device of the Series, i have tested. Sophos AP55c, AP100 and AP15 will follow soonish.
- LED mapping …
> ath79-generic: add support for Sophos AP100c

- .github/filters.yml
- targets/bcm27xx-bcm2711
- targets/bcm27xx.inc
- targets/targets.mk
- no buttons available (however with physical access the SD card can be updated on another device to reenable the config mode)
(https://gluon.readthedocs.io/en/latest/dev/hardware.html#hardware-support-in-
- no lable available, but MAC seems fixed/stable upon `firstboot -y` (here: dc:a6:32:0c:6f:25)
packages)
- Wireless network (if …
> bcm27xx: add support for Pi4 and switch bcm27xx from ext4 to squashfs

- docs/user/supported_devices.rst
- targets/ath79-generic
Device is very similar to Devolo Wifi Pro series of devices.
This is the third device of the series, I have tested. Sophos AP100 and AP15 will follow soonish.
- LED mapping …
> ath79-generic: add support for Sophos AP55c

- package/gluon-tls/Makefile
This package allows to easily select the correct libustream implementation without all communities having the need to manually change their included packages.
> add package gluon-libustream-tls

- .github/workflows/build-gluon.yml
Goal is to cancel Worfklows for Pull Request if they become obsolte due to new changes.
Without this workflows will continue running, wasting resources and delaying the run of relevant workflows.
This situation will typically occour if a author of a PR notices an error/typo/missing bit and pushes new changes to the branch.
This won't affect concurrent workflows for otherwise triggered workflows (push, workflow_dispatch, tag, ...).
Relevant Links:
- https://docs.github.com/en/actions/using-jobs/using-concurrency
- https://docs.github.com/en/actions/learn-github-actions/contexts#github-context
> github: build-gluon: cancel obsolete in progress workflows for PRs

- LICENSE
This adds a hint to the Repository on Github and makes it easier to recognize the license text
> Add license title BSD 2-Clause License

- docs/user/supported_devices.rst
- targets/ath79-generic
Basically the same device as an Sophos AP55, except for the radio being 3x3 instead of 2x2
-  Device does not have a reset button, however the serial port is directly accessible 
- LED mapping …
> ath79-generic: add support for Sophos AP100

- docs/user/supported_devices.rst
- targets/ath79-generic
Device is very similar to Devolo Wifi Pro series of devices.
This is the first Device of the Series, i have tested. Sophos AP55c, AP100 and AP100c will follow soonish.
-  Device does not have a reset button, however the serial port is directly accessible 
- otherwise the first port should be declared as WAN, all other …
> ath79-generic: add support for Sophos AP55

- README.md
This fixes #2662 and uses the last proposal from T-X, which I think is quite fitting.
> docs: Add description about what gluon is

- README.md
This removes the recently added link to the README again that was supposed to explain the the "merging of meshes" as it is very misleading concerning what Gluon can do.
And adjusts / tidies up the headings.
> docs: remove an unrelated/misleading link and fix headings

- targets/ath79-generic
Basically the same device as a Sophos AP55
- Device does _not_ have any buttons. 
Warning: Make sure to set up SSH remote access, otherwise the only option is to open up the case and use the UART header for console access.
- Wireless network (if …
> ath79-generic: add support for Sophos AP15

- contrib/ci/minimal-site/site.conf
- contrib/ci/olsr-site/site.conf
Drop the Gluon version reference from the site configuration used for the CI builds.
These version indicators were most likely just copied from the example site in the docs, where the version information makes sense. However, the CI site is always built for a specific Gluon version and therefor commit.
This avoids editing the version for each release.
> contrib: drop Gluon version from CI site

- .github/labeler.yml
The typo in the label name has been fixed, update the labeler config.
Previously suggested in #3072 I think? But this time I actually relabeled all old issues/PRs to use the fixed version of the label.
> labeler: update "continuous integration" label name

- docs/user/supported_devices.rst
- targets/ramips-mt7621
The COVR-X1860 is a wifi6 device quite similar to the DAP-X1860, which is not wall-plugged and has two Gigabit LAN ports.
It is already well tested with ~40 devices in FFAC.
- LED mapping …
> ramips-mt7621: add support for D-Link COVR-X1860 a1

- docs/user/supported_devices.rst
- package/gluon-core/luasrc/usr/lib/lua/gluon/platform.lua
- targets/ath79-generic
- LED mapping
- Radio LEDs
- Docs:
>  ath79-generic: add support for Ubiquiti UniFi Swiss Army Knife Ultra 

- modules
This fixes #2904  on the v2023.1.x branch too
```
a08553b3b3 ath79: read back reset register
debf4b56cd kernel: bump 5.10 to 5.10.206
6121581765 kernel: bump 5.10 to 5.10.203
17ee3e0b20 raimps: mtk_eth_soc: drop rst_esw from ESW driver
5ef01117b7 ramips: dts: mt7628an: reset FE and ESW cores together
b80c17b093 ramips: dts: rt5350: reset FE and ESW cores together
0c84a15288 ramips: dts: rt3050: reset FE and ESW cores together
37ed4c0ec2 ramips: dts: rt3352: reset FE and ESW cores together
8b4b924b85 ramips: mtk_eth_soc: wait longer after FE core reset to settle
ca942a5910 ramips: mtk_eth_soc: allow multiple resets
```
> [v2023.1.x] modules: update openwrt

- patches/openwrt/0007-mac80211-silence-warning-for-missing-rate-information.patch
Silence warnings for missing rate information.
These warnings do not provide value. Instead, they might rotate more crucial information out of the kernel message ringbuffer.
Closes https://github.com/freifunk-gluon/gluon/issues/3160
> mac80211: silence warning for missing rate information

- patches/openwrt/0008-tools-flex-disable-parallel-build.patch
SOmetimes the build of flex fails with erros like these:
./build-aux/config.sub: line 63: opying: command not found
Disable the parallel build of flex in order to avoid these issues from occuring.
This patch will be upstreamed once it did resolve our issue for some weeks.
> tools flex: disable parallel build

- README.md
- docs/conf.py
- docs/releases/index.rst
- docs/releases/v2023.1.2.rst
- docs/releases/v2023.2.1.rst
- docs/site-example/site.conf
- docs/user/getting_started.rst
Backport Release-Notes for the Releases
- v2023.1.2
- v2023.2.1
Update the docs to refer to the release with the most recent major release of the two.
> docs, readme: backport v2023.1.2 / v2023.2.1 release notes

- patches/openwrt/0027-kernel-bridge-mcast-fix-disabled-snooping-after-long-uptime.patch
The original idea of the delay_time check was to not apply multicast snooping too early when an MLD querier appears. And to instead wait at least for MLD reports to arrive before switching from flooding to group based, MLD snooped forwarding, to avoid temporary packet loss.
However in a batman-adv mesh network it was noticed that after 248 days of uptime 32bit MIPS based devices would start to signal that they had stopped applying multicast snooping due to missing queriers - even though they were the elected querier and still sending MLD queries themselves.
While time_is_before_jiffies() generally is safe against jiffies wrap-arounds, like the code comments in jiffies.h explain, it won't be able to track a difference larger than ULONG_MAX/2. With a 32bit large jiffies and one jiffies tick …
> [v2021.1.x] kernel: bridge: mcast: fix disabled snooping after long uptime

- targets/generic
We don't employ swap using zram anymore with Gluon. Thus, we can disable SWAP in the kernel.
> generic: disable kernel SWAP support

- docs/releases/v2023.2.rst
Must be ``GLUON_SITE_PACKAGES`` instead of ``GLUON_PACKAGES``
> docs: fix typo in v2023.2 release notes

- docs/user/supported_devices.rst
- targets/ath79-generic
The DAP-2680 is an AC1750 Wave 2 business Access Point (not previously added along with DAP-2660 since there was an issue with ath10k firmware package choice, meanwhile gluon points to a version of OpenWrt [that includes the fix](https://git.openwrt.org/?p=openwrt/openwrt.git;a=commit;h=0dc056eb66e1b3a4a6797bdf91f7362df6ced9c3)).
```
* QCA9558, 16 MiB Flash, 256 MiB RAM, 802.11n 3T3R
* QCA9984, 802.11ac Wave 2 3T3R
* Gigabit LAN Port (AR8035), 802.3at PoE
```
https://hannover.freifunk.net/karte/#!/de/map/f48ceb8a2cb0
- [-] TFTP
factory reset must be performed before …
> ath79-generic: add support for D-Link DAP-2680

- docs/user/supported_devices.rst
- targets/ath79-generic
- targets/ath79-nand
- targets/ipq40xx-generic
- targets/lantiq-xrx200
- targets/lantiq-xway
- targets/mediatek-filogic
- targets/mediatek-mt7622
- targets/mpc85xx-p1010
- targets/mpc85xx-p1020
- targets/ramips-mt7620
- targets/ramips-mt7621
- targets/ramips-mt76x8
- targets/x86-generic
This PR is mostly about some cleanups.
I propose dropping manifest aliases for unsupported upgrade paths (devices running pre OpenWrt 22.03)
This makes target files better to read and makes the manifests smaller.
I also make OEM naming a bit more consistent across targets and documentation and add a few new lines here and there.
And I gave two existing manifest-aliases their respective code comment (last OpenWrt release with that model name).
There were further manifest-aliases without code comments but I was able to drop those. (introduced for OpenWrt 21 or prior)
> Omit obsolete manifest-aliases / cleanups

- patches/openwrt/0008-net-vxlan-don-t-learn-non-unicast-L2-destinations.patch
See Gluon #3191
Link: https://github.com/freifunk-gluon/gluon/issues/3191
(cherry picked from commit 97b9fcc9ecdb7df17605c36501148822e75910c7)
> net vxlan: don't learn non-unicast L2 destinations

- docs/user/supported_devices.rst
- package/gluon-core/luasrc/lib/gluon/upgrade/020-interfaces
- targets/ath79-generic
split from #3190 
The DAP-2695 (better late than never) is an AC1750 Wave 1 Access Point in a plenum-rated metal case with RJ45 serial console port and six detachable antennas (single band, labelled accordingly).
```
DAP-2695 Specifications:
* SoC: Qualcomm Atheros QCA9558, 256 MiB RAM, 16 MiB SPI NOR
* Ethernet: 2x 10/100/1000 (1x 802.3at PoE-PD)
* WiFi 2.4GHz: Qualcomm Atheros QCA9558
* WiFi 5GHz: Qualcomm Ahteros QCA9880-2R4E
* LEDS: 1x 5GHz, 1x 2.4GHz, 1x LAN1(POE), 1x LAN2, 1x POWER
* UART: 1x RJ45 RS-232 Console port
* Plenum-rated metal case
```
https://hannover.freifunk.net/karte/#!/de/map/9cd6432cac70
https://hannover.freifunk.net/karte/#!/de/map/0cb6d2fd1570
Checklist (Tested for DAP-2695 A1 and A2) 
- [-] TFTP …
> ath79-generic: add support for D-Link DAP-2695

- patches/openwrt/0016-net-vxlan-don-t-learn-non-unicast-L2-destinations.patch
See Gluon #3191
Link: https://github.com/freifunk-gluon/gluon/issues/3191
(cherry picked from commit 97b9fcc9ecdb7df17605c36501148822e75910c7)
Closes #3191
> [v2023.1.x] net vxlan: don't learn non-unicast L2 destinations

- docs/releases/v2023.1.1.rst
`http://ftp.avm.de` seems to be unavailable. Update the url to the new (?) address.
> docs: fix AVM Recovery Tool url in v2023.1.1 release notes

- targets/ipq40xx-generic
- targets/lantiq-xrx200
I just noticed that lantiq removes dsl related packages. Let's do the same for the Fritz!Box 7520/7530.
And correct one package name for lantiq-xrx200 that was changed due to introduction of the vr11 modem.
And drop the new package ltq-dsl-base.
This PR hasn't been run-tested, yet.
_____
~~I removed `ltq-dsl-base` on my own accord. I have no clue whether removing this as well is a good idea or not. (EDIT: actually lantiq-xrx200 also has this package since 23.05; 22.03 didn't have this package)~~
https://github.com/freifunk-gluon/gluon/blob/d5a8f662d2d608097c3870b78a38acbd0e1bb332/targets/ipq40xx-generic#L66
~~should we also drop these?~~
```
kmod-atm - 5.15.146-1
linux-atm - 2.5.2-7
```
> Drop vdsl packages

- scripts/container.sh
We need to pass the `z` option with the volume mount so it gets labeled correctly and access is possible on SELinux-enabled systems. On systems without SELinux, the flag is a no-op.
Fixes #3199
> scripts/container.sh: fix rootless Podman on systems with SELinux

- targets/ath79-generic
upstream increased partition size to 7.625 MiB in openwrt-23.05
https://github.com/openwrt/openwrt/commit/aca8bb5cc332f0ffdf4249e76b0a56716f98bef0
I suggest removing class tiny for now.
This should be backported to v2023.2.x
> ath79-generic: dir-825-b1 drop class tiny

- targets/ath79-nand
fix 5deb3aaeffbd27880906e6b33ebc9cc39d2c4a23
This upgrade path never worked due to increase of the kernel partition size.
They dropped this name from SUPPORTED_DEVICES upstream to prevent devices from breaking: https://github.com/openwrt/openwrt/commit/0d28e5d6440d2a37841a207f943e6e5a23172883
Drop this, so devices stop trying to update every hour.
Devices need to be reinstalled manually with a factory image with tools like nmrpflash.
[instructions on the forum](https://forum.openwrt.org/t/updating-wndr3700v4-from-v17-lede/185510/14)
> ath79-nand: drop broken manifest alias

- .github/workflows/build-gluon.yml
Get rid of Node deprecation warnings.
Link: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/
> github: bump paths-filter version

- package/gluon-ebtables-limit-arp/files/usr/lib/autoupdater/abort.d/15start-arp-limiter
- package/gluon-ebtables-limit-arp/files/usr/lib/autoupdater/upgrade.d/05stop-arp-limiter
Stop and start the gluon-arp-limiter service before the network is brought down when commencing update.
Start the service after the network is brought back up when aborting.
> gluon-ebtables-limit-arp: stop for autoupdater

- scripts/image_customization_lib.lua
image-customization.lua has replaced GLUON_FEATURES and GLUON_SITE_PACKAGES, so the file is always required to build a useful Gluon image. In addition, not only 'file not found' errors were ignored, but also all other Lua load errors, resulting in a build with empty image customization when the file was not valid.
Closes #3218
> scripts: image_customization_lib.lua: fail build without valid customization file

- patches/openwrt/0008-mac80211-add-AQL-support-for-broadcast-multicast-packets.patch
Backport of #3208
Excessive broadcast traffic with little competing unicast traffic can easily flood hardware queues, leading to throughput issues. Additionally, filling the hardware queues with too many packets breaks FQ for broadcast data. Fix this by enabling AQL for broadcast packets.
Signed-off-by: Felix Fietkau <nbd@nbd.name>
(cherry picked from commit ea5ebd9c1b6365a63d18af1f5b6b76090e07105e)
> [v2023.2.x] mac80211: add AQL support for broadcast packets

- README.md
- docs/conf.py
- docs/releases/index.rst
- docs/releases/v2023.2.2.rst
- docs/site-example/site.conf
- docs/user/getting_started.rst
Let's do a Gluon v2023.2.2 and resolve the potentially mesh-breaking VxLAN bug.
> docs readme: Gluon v2023.2.2 

- docs/releases/v2023.1.1.rst
The soft brick warning of AVM Fritz!Box 7520 and 7530 is missing in the `v2023.1.x` branch / release notes.
> [v2023.1.x] add soft brick warning to v2023.1.1 release notes

- docs/user/supported_devices.rst
- targets/ath79-generic
- Doesnt have MAC printed on label or packaging
- LED mapping
- Radio LEDs
- [n/a] …
> re-add: ath79 NETGEAR WNDRMAC v2

- docs/user/supported_devices.rst
- package/gluon-core/luasrc/lib/gluon/upgrade/010-primary-mac
- targets/mediatek-filogic
- LED mapping
- Radio LEDs
- Added board name to `is_outdoor_device` function in …
> mediatek-filogic: add support for ASUS TUF-AX6000

- package/gluon-core/luasrc/usr/lib/lua/gluon/wireless.lua
find_phy() did not match OpenWrt's logic for PHY names anymore, and could not handle PHYs that don't match the 'phyX' naming scheme. Instead of trying to add more complex logic to our own code, simply do what OpenWrt does and use iwinfo to resolve UCI sections to PHY names.
Supersedes #3155
Closes #3020
Draft: This is entirely untested. Will test on an FB4040 tomorrow - would be great to get a test on a device with wifiX PHY names as well.
There is some subsequent cleanup possible by passing around only UCI section names instead of the whole section table (which may not even need to be queried at all in some cases), but that will happen as a separate PR, so this one can be backported to 2023.2.x.
> gluon-core: lua: wireless: use libiwinfo-lua for find_phy()

- package/gluon-core/luasrc/usr/lib/lua/gluon/wireless.lua
- package/gluon-web-wifi-config/luasrc/lib/gluon/config-mode/model/admin/wifi-config.lua
Two simple improvements I noticed when I implemented #3223.
Other refactoring like passing around only section names instead of whole radio config tables turned out to be not worthwhile, as we usually have the full config object from a `uci:foreach()` call anyways,
> Wifi-related code cleanup

- .github/workflows/bump-gluon.yml
Create a GitHub action to automatically create updates to the OpenWrt base-version on manual run.
This allows to create base-modules updates where Gluon patches did not change from the GitHub UI.
Skip PR creation. Automatically created PRs do not invoke subsequent actions, thus not creating build-tests.
> github: add action for OpenWrt base update

- .github/filters.yml
- package/gluon-core/luasrc/lib/gluon/upgrade/010-primary-mac
- targets/kirkwood-generic
- targets/targets.mk
- LED mapping
- Radio LEDs
- Docs:
> kirkwood: add support for Linksys E4200 v2

- docs/user/supported_devices.rst
- targets/ramips-mt7621
- LED mapping
- Radio LEDs
- Docs:
> ramips/mt7621: add D-Link Exo AC2600 DIR-882

- docs/user/supported_devices.rst
- targets/ramips-mt7621
- LED mapping
- Radio LEDs
- Docs:
> ramips/mt7621: add D-Link 878 A1

- targets/ath79-generic
The Archer C7 v2 needs a different factory image depending on the region (EU or US); this got lost during the ar71xx -> ath79 migration.
The OpenWrt factory image without a region suffix is only installable on very old TP-Link firmwares from before the region split was introduced. The region-specific firmware works for both old and new TP-Link firmwares.
Fixes: 8fdda51f9801 ("ath79-generic: (re)add support for archer-c7-v2 (#2437)")
> ath79-generic: TP-Link Archer C7 v2: Fix region selection for factory image

- docs/user/supported_devices.rst
- targets/mpc85xx-p1020
- LED mapping
- Radio LEDs
- Docs:
> mpc85xx-p1020: add support for Hewlett-Packard MSM460

- docs/user/supported_devices.rst
- targets/mpc85xx-p1020
(cherry picked from commit e0b723cef78b77be133afe0042e51eed9888d9f7)
- LED mapping
- Radio LEDs
- Outdoor …
> [v2023.2.x] mpc85xx-p1020: add support for Hewlett-Packard MSM460 (#3272)

- targets/ramips-mt7621
- Doesnt have MAC printed on label or packaging
--> marked as broken
- LED mapping
- Radio LEDs
- [n/a] Should map to their …
> ramips-mt7621: add dlink-dap-1620-b1

- docs/user/site.rst
I removed a comment from the site documentation citing, that fastd is the only vpn where `pubkey_privacy` has an effect.
I just verified by editing /lib/gluon/site.json and running gluon-reconfigure and reboot, that this settings also works for wireguard VPNs.
I'm not sure whether it works for **Tunneldigger**, so this documentation change requires further feedback.
Is there a fourth VPN provider we support?
> docs: site: pubkey_privacy works for wireguard

- .github/workflows/build-container.yml
- .github/workflows/build-gluon.yml
- .github/workflows/bump-gluon.yml
- CONTRIBUTING.md
- README.md
- docs/features/monitoring.rst
- docs/features/vpn.rst
- docs/index.rst
- docs/user/site.rst
Following the rename of master to main, update everything that references the branch.
> treewide: Update main branch name

- README.md
- docs/conf.py
- docs/releases/index.rst
- docs/releases/v2023.2.3.rst
- docs/site-example/site.conf
- docs/user/getting_started.rst
There were some fixes since the last v2023.2.x release in Gluon as well as upstream OpenWrt regarding device compatibility. Let's do another minor release.
```
068cca0e mpc85xx-p1020: add support for Hewlett-Packard MSM460 (#3275)
d0226591 Merge pull request #3273 from blocktrron/v2023.2.x-updates
71c91b9c modules: update routing
75c6d44b modules: update packages
bee44b93 modules: update openwrt
34b1eed7 ath79-generic: TP-Link Archer C7 v2: Fix region selection for factory image (#3260)
82822a56 Merge pull request #3256 from blocktrron/v2023.2.x-updates
fefdbd74 modules: update routing
e19f183c modules: update packages
32ebeb0e modules: update openwrt
00160f5b gluon-core: lua: wireless: use libiwinfo-lua for find_phy() (#3239)
83fb430e ath79-generic: add support for NETGEAR WNDRMAC v2 …
```
> docs: add Gluon v2023.2.3 release notes

- README.md
- docs/conf.py
- docs/releases/index.rst
- docs/releases/v2023.2.3.rst
- docs/site-example/site.conf
- docs/user/getting_started.rst
forward-port the release-notes of the v2023.2.3 release to the main branch.
> docs: add v2023.2.3 release notes

- targets/kirkwood-generic
The model name has a codename suffix:
https://git.openwrt.org/?p=openwrt/openwrt.git;a=blob;f=target/linux/kirkwood/files/arch/arm/boot/dts/kirkwood-e4200-v2.dts;h=bfd708a677c96a9f3bdf80ead2db4498487ac5f8;hb=refs/heads/openwrt-23.05#l6
See also: https://github.com/freifunkMUC/site-ffm/issues/415#issuecomment-2187154401
> kirkwood-generic: fix device name of Linksys E4200 v2

- Makefile
- docs/user/getting_started.rst
- targets/generic
Debugging binaries in images that are built with sstrip is extremely
annoying, as not even objdump will work on them.
Switching from sstrip to standard strip increases the ath79 image size
(for some usual Archer C7 v2 configuration I used for testing) by ~70KiB,
or 1.3% of the rootfs size (~1% of the total image size), which is
rarely worth the decreased debuggability.
Extend GLUON_DEBUG to not only distinguish 0 and 1, such that:
- 0 uses sstrip same as before
- 1 switches to regular strip; this is the new default
- 2 includes all debug info, like GLUON_DEBUG=1 did before
> build: extend GLUON_DEBUG with values 0, 1 and 2

- docs/user/supported_devices.rst
- targets/ramips-mt76x8
> ramips-mt76x8: add RE200 version 4

- package/gluon-private-wifi/luasrc/lib/gluon/upgrade/325-gluon-private-wifi
- package/gluon-web-private-wifi/luasrc/lib/gluon/config-mode/model/admin/privatewifi.lua
Currently, no device is affected, though it makes sense to improve the current situation by giving more meaningful ifnames anyway.
closes #3290
> private-wifi: rename ifname to wan_wifiX to not collide with openwrt devices with more than one wan port

- patches/openwrt/0010-mt76-include-fixes-for-MT7603-MT7612.patch
These fixes were developed for MT7603 and MT7612. Originally, we've discovered the TX-status reporting mishandles cases where continuous action frames are sent over a mesh-link but no actual data traffic is transmitted over the link.
This leads to a client "sticking" to the AP even if it already left the covered area.
In the process, we've discovered this patchset might(!) also help mitigate issues seen on MT7916 based platforms. Therefore, i think it is a good idea to open this PR as a draft to serve as a starting point for discussions on this matter.
I've rebased this patchset on current master, build testing by the CI runners now. We've tested fixes with the mt76 patches based on v2023.2.1 releases.
Dashboard: https://stats.darmstadt.freifunk.net/d/000000021/router-meshviewer-export?var …
> mt76: work around dropped TX status reporting

- package/gluon-mesh-vpn-wireguard/luasrc/lib/gluon/upgrade/400-mesh-vpn-wireguard
Before, we did only set the MTU on mesh-vpn (the vxlan interface), which has to be smaller than the set value on the wg_mesh (wireguard interface).
On WAN interfaces with an MTU of 1500, the default wireguard MTU of 1420 is optimal (as wireguard takes 80 Bytes).
Though it would be better for PPPoE interfaces (which typically have a MTU of 1496) to use a MTU of 1416 or less (1406 being a typical value, currently used by FFMUC, FFH and FFAC).
[The documentation](https://gluon.readthedocs.io/en/latest/user/mtu.html) mentions an optimal wireguard MTU of 1376.
This would then also work on WAN-interfaces with an MTU of 1436 on IPv4 respective 1462 for IPv6).
This PR changes the behavior for mesh-vpn-wireguard to set the correct MTU from the site.conf.
Curiously, this did never lead to any known …
> mesh-vpn-wireguard: actually set the mtu from the site.conf on the wireguard interface

- docs/user/supported_devices.rst
- targets/ramips-mt7621
Closes #3291
https://openwrt.org/inbox/toh/xiaomi/xiaomi_mi_router_4a_gigabit_edition#notes_on_firmware_exploit_procedure
xiaomi-mi-router-4a-gigabit-edition-v2
- LED mapping …
> ramips-mt7621: add support for Xiaomi Mi Router 4a Gigabit Edition v2

- docs/user/supported_devices.rst
- targets/ramips-mt7620
->  netgear-ex6130
- LED mapping
- Radio LEDs
- Docs:
closes …
> ramips-mt7620: add support for Netgear EX6130

- package/gluon-core/luasrc/usr/lib/lua/gluon/ethernet.lua
Switch config for swconfig can be found in the network, not the system config.
This resulted in `Switch type: none` beeing reported for swconfig devices.
cc @mkg20001
> gluon-core: fix swconfig detection in ethernet module

- docs/features/vpn.rst
- docs/user/mtu.rst
T-X created a pretty cool table to evaluate VPN uplink protocols used in gluon on this hedgedoc: 
https://md.chaotikum.org/zRkW6JXXQs-8WCnwdtig5w?view
To give it more visibility, I would like to add it to the docs as suggested somewhere.
I hope this is fine for you @T-X and @rotanid ?
> docs: vpn: Add documentation for evaluation of vpn protocols

- package/gluon-core/luasrc/lib/gluon/upgrade/250-cellular
- package/gluon-web-cellular/i18n/de.po
- package/gluon-web-cellular/i18n/gluon-web-cellular.pot
- package/gluon-web-cellular/luasrc/lib/gluon/config-mode/model/admin/cellular.lua
this should fixes #2750 by adding a dropdown menu for the auth methods.
atm it is untested, but we believe that this can be tested soon by someone from [ffmuc](https://github.com/freifunkMUC/site-ffm/pull/456).
More Infos:
https://openwrt.org/docs/guide-user/network/wan/wwan/ltedongle#qmi_protocol_configuration_parameters
> gluon-web-cellular: add auth option to GUI

- docs/user/supported_devices.rst
- package/gluon-core/luasrc/usr/lib/lua/gluon/ethernet.lua
- targets/ath79-generic
- targets/ramips-mt7620
- targets/ramips-mt7621
- targets/ramips-mt76x8
This PR collects multiple backports of added device support and bugfixes for v2023.2.x from Gluons master branch.
> [v2023.2.x] treewide: pending devices and bugfixes from master

- scripts/getversion.sh
This flag allows to get the latest non annotated tag in e.g. site repositories.
> scripts: add --tags to git describe in getversion.sh to include lightweighted tags

- scripts/default_feeds.sh
- scripts/lint-sh.sh
- scripts/module_check.sh
- scripts/modules.sh
- scripts/sha256sum.sh
- scripts/update.sh
This removes script-wide shellcheck excludes to avoid unintentional errors and moves the excludes to the scripts where they are necessary.
> scripts: remove scripts-wide shellcheck excludes

- scripts/container.sh
- scripts/patch.sh
- scripts/update-modules.sh
- scripts/update-patches.sh
As almost all variables are upper-case and do not follow the intention of https://github.com/koalaman/shellcheck/issues/1037#issuecomment-341288433 include checks for unassigned upper-case variables.
> scripts: enable checks for unassigned uppercase

- package/gluon-core/luasrc/lib/gluon/upgrade/020-interfaces
- package/gluon-core/luasrc/lib/gluon/upgrade/021-interface-roles
> With the switch to DSA on this device in openwrt 23.05, we can now utilize the ports of a 7520/7530 better, by splitting them according to their usage.
> Before, they had all LAN ports used as WAN - a behavior which can also be easily configured in config mode nowadays.
> 
> If I remember correctly, this also changes an existing configuration to LAN1 -> WAN and LAN2,3,4 -> LAN
> Therefore, the existing router owner need to make sure to plug the cable into Port1.
> 
> This patch has been tested with latest gluon and already is deployed on all affected FB7520/7530 in FFAC.
This is a new version of #3118 that includes a uci migration path for devices that were configured pre-DSA.
cc @maurerle
> fritzbox-7530/7520: utilize lan1 as wan, others as lan 

- targets/ath79-generic
The DLAN pro 1200+ WiFi ac is the same as the DLAN 1200+ WiFi ac (non-pro).
It is a wall plug device which still exposes the wall plug.
The powerline functionality does not work without additional firmware, which can not be shipped due to licensing issues - yet someone from our community wanted to use this device for FF and did test it.
Looks fine to me, except that there is no Power LED, just the House-LED (used for powerline) and the WIFI-LED (which works as expected)
`devolo-dlan-pro-1200+-wifi-ac`
factory reset must be performed before checking the primary MAC …
> ath79-generic: add support for DLAN (pro) 1200+ WiFi ac

- README.md
- docs/conf.py
- docs/releases/index.rst
- docs/releases/v2023.2.4.rst
- docs/site-example/site.conf
- docs/user/getting_started.rst
Based on the work done in https://md.darmstadt.ccc.de/gluon-v2023.2.4-rn
A preview can be found here: https://gluon--3345.org.readthedocs.build/en/3345/releases/v2023.2.4.html
Contains the following changes: https://github.com/freifunk-gluon/gluon/compare/v2023.2.3...8d04b5e4961e7c0a779bc8755142b65cca19f72e
> docs: add v2023.2.4 release notes

- package/gluon-core/luasrc/lib/gluon/upgrade/010-primary-mac
- targets/kirkwood-generic
- targets/targets.mk
The hardware is identical to the E4200 v2, and it's broken, so only minimal testing was done - this is added mostly because I have one lying around and its good to have some "supported" device for testing ARMv5.
> kirkwood-generic: update BROKEN reason, add Linksys EA4500

- scripts/getversion.sh
Backport of https://github.com/freifunk-gluon/gluon/pull/3310
As this has been bothering us on our end with the latest "show version" commands, we would like to see this backported at least to v2023.2.x
> [v2023.2.x] scripts: add --tags to git describe in getversion.sh to include lightweighted tags (#3310)

- CONTRIBUTING.md
- README.md
- docs/conf.py
- docs/dev/basics.rst
> [Network Notice] major - We will be transitioning from our current webchat (KiwiIRC) at webirc.hackint.org to The Lounge, accessible at chat.hackint.org. The old webchat will remain available until November 20, 2024. For more information, please visit our documentation at https://hackint.org/webchat.
> docs readme: update hackint webchat URL

- docs/user/supported_devices.rst
- targets/ramips-mt7621
Downgrade to [3.9.27](https://community.ui.com/releases/FIRMWARE-3-9-27-8537-for-UAP-USW-has-been-released-3-9-27-8537/e41acf46-de72-4336-8104-f6996c8d04d8) first (6.6.73 was tested and didn't work, it automatically reboots into tftp recovery) using this procedure [UniFi Recovery Mode > Access Points](https://help.ui.com/hc/en-us/articles/360043360253-UniFi-Recovery-Mode)
use pitch's [acProFlashtool](https://codeberg.org/pitch/firmwareloader_uap_ac_pro)
Give your device
static ip: 192.168.1.xxx (xxx being a number between 1 and 254 but not 20)
net mask 255.255.255.0
gateway 192.168.1.20 (optional)
on linux: chmod +x firmwareloader-linux
./firmwareloader-linux -f sysupgrade-file-name.bin
ubiquiti-unifi-nanohd …
> ramips-mt7621: add Ubiquiti UniFi nanoHD

- targets/generic
change the "OpenWrt" grub title to "Gluon"
https://github.com/freifunkMUC/site-ffm/pull/512
> generic: add gluon grub title

- docs/user/supported_devices.rst
- package/gluon-core/luasrc/lib/gluon/upgrade/020-interfaces
- targets/ipq806x-generic
- Install was executed on 6.6.73 (worked fine)
- use pitch's [acProFlashtool](https://codeberg.org/pitch/firmwareloader_uap_ac_pro)
- Give your device
> static ip: 192.168.1.xxx (xxx being a number between 1 and 254 but not 20)
> net mask 255.255.255.0
> gateway 192.168.1.20 (optional)
- on linux: `chmod +x firmwareloader-linux`
- `./firmwareloader-linux -f sysupgrade-file-name.bin`
ubiquiti-unifi-ac-hd
It the same as the one silkscreened onto the device: E063DA59853E
the setting from the …
> ipq806x-generic: add Ubiquiti UniFi AC HD

- package/gluon-mesh-batman-adv/files/lib/netifd/proto/gluon_bat0.sh
- patches/packages/routing/0002-batman-adv-Introduce-no-noflood-mark.patch
- patches/packages/routing/0003-batctl-Add-noflood_mark-command.patch
This reverts commit 702211ac5439f49b6dee6ec95f3eac6ad1a268a7.
And refreshes the according patches to OpenWrt 24.10 / batman-adv v2024.3.
> [OpenWrt 24.10] Revert "routing: remove noflood"

- patches/openwrt/0005-kernel-bridge-Implement-MLD-Querier-wake-up-calls-Android-bug-workaround.patch
With the update to OpenWrt 24.10 the bridge MLD wakeup call feature was removed. However the issue with Android devices and MLD is still present. Therefore readding the bridge MLD wakeup call patch and porting it to Linux 6.6 / OpenWrt 24.10.
Link: https://issuetracker.google.com/issues/149630944
Fixes: b7481fd08e44 ("modules: switch to OpenWrt 24.10")
> [OpenWrt 24.10] kernel: bridge: readding MLD wakeup call feature

- docs/user/supported_devices.rst
- package/gluon-core/luasrc/lib/gluon/upgrade/010-primary-mac
- targets/rockchip-armv8
- LED mapping
- Radio LEDs
- Docs:
> add support for NanoPi R3S

- package/libgluonutil/src/libgluonutil.c
The import of libgen.h required for basename() was missing. This lead to undesired behavior on 64 bit systems, where only the upper 32-bit of the returned pointer was used.
On ARM64 systems such as mediatek-filogic, this lead to a signed extend of the 32-bit address, leading to a crash of respondd.
> libgluonutil: add missing libgen import

- docs/user/supported_devices.rst
- targets/ath79-generic
- LED mapping
- Radio LEDs
- Docs:
See: …
> ath79: Add support for Sophos AP15C

- contrib/docker/Dockerfile
- docs/user/getting_started.rst
distutils is not required anymore by OpenWRT 24.10.
Distutils was deprecated and removed in Python 3.12, see https://peps.python.org/pep-0632/
This effectively reverts 2d4ab0f0c8dd909c622bbc49352aea729a0e021b
> Dockerfile: drop dependency on python3-distutils

- docs/user/supported_devices.rst
- targets/mediatek-filogic
- LED mapping
- Radio LEDs
- Docs:
> mediatek-filogic: Add support for D-Link AQUILA PRO AI M30 A1

- docs/user/supported_devices.rst
- package/gluon-core/luasrc/usr/lib/lua/gluon/platform.lua
- targets/mediatek-filogic
- LED mapping
- Radio LEDs
- Docs:
> mediatek-filogic: add Cudy AP3000 Outdoor v1

- targets/ipq40xx-generic
- LED mapping
- Radio LEDs
- Docs:
Primary MAC Adress is: …
> ipq40xx-generic: add extreme-networks-ws-ap3915i

- docs/user/supported_devices.rst
this is a fixup to #3396 in which initial support to the Extreme Networks AP3915i was added.
In this PR the addition to the supported_devices.rst was missing.
> docs: add AP3915i to supported_devices

- package/gluon-private-wifi/luasrc/lib/gluon/upgrade/325-gluon-private-wifi
- package/gluon-web-private-wifi/luasrc/lib/gluon/config-mode/model/admin/privatewifi.lua
I had a hard time finding information about psk3 in openwrt documentation as it is not mentioned here:
https://openwrt.org/docs/guide-user/network/wifi/basic#encryption_modes
I think the naming changed some time, so it makes sense to use the documented value of sae instead of psk3.
The functionality in openwrt is the same, so this does not change any functionality ~~and there is no good reason to migrate existing configs~~.
Though this helps to better find related documentation to the value set in `uci show wireless`
> gluon-private-wifi: rename psk3 to sae as it is used in openwrt that way

- patches/openwrt/0007-net-mac80211-override-incompatible-basic-rates-for-mesh.patch
Printing a warning everytime a rate mismatch is detected is a bit to much. With many mesh neighbors, this quickly results in the kernel log being spammed with these messages.
> mac80211: silence mesh rate mismatch warning

- docs/user/supported_devices.rst
- targets/mediatek-filogic
- LED mapping
- Radio LEDs
- Docs:
> mediatek-filogic: Add support for D-Link AQUILA PRO AI M60 A1

- docs/user/supported_devices.rst
in `docs/user/supported_devices.rst`
(@RolandoMagico: these devices had sneaked into the ath79 section)
> docs: move D-Link M30, M60 to mediatek-filogic section

- docs/user/supported_devices.rst
- targets/ramips-mt7621
this is the same device as the EAX 11 v2 and EAX 15 v2
(`lua -e 'print(require("platform_info").get_image_name())'`) `netgear-eax15`
- LED mapping
- Radio LEDs - no led per radio
- Switch …
> ramips-mt7621: add support netgear eax12

- targets/ramips-mt7621
(`lua -e 'print(require("platform_info").get_image_name())'`) `tp-link-archer-ax23-v1`
- LED mapping
- Radio LEDs
- Docs: …
> ramips-mt7621: add tp-link ax23

- package/gluon-core/luasrc/lib/gluon/upgrade/200-wireless
The RSSI LEDS on 5GHz in openwrt did not work for gluon as they were set to `wlan1` which does not exist.
For example the dap-x1860 profits from using its LEDs to show the mesh connectivity on 5GHz through the LEDs.
This of course is only limited to show the connectivity on radio1 if possible.
This might as well be misleading in situations where radio1 does not mesh and the turned off connectivity is interpreted wrongly.
Though I don't think there is a better approach than using it for mesh1 and I do think it is a nice feature and should be enabled by default :)
Tested on a DAP-X1860 in combination with a COVR-X1860 - works great to show if a neighbor on mesh1 is visible
> gluon-core: set 5GHz rssi leds to mesh1 connectivity

- .github/workflows/build-gluon.yml
- contrib/actions/free-runner-space.sh
Remove non-required packages in order to provide enought free space for the Gluon build process.
> actions: remove non-required packages

- docs/user/supported_devices.rst
- targets/mediatek-filogic
Specification:
- MT7981 CPU using 2.4GHz and 5GHz WiFi (both AX)
- 1GB RAM
- 16MB NOR
- 128MB NAND
- 3 LEDs (red, green, blue, white)
- 2 buttons (reset, user defined)
- 1 2.5Gbit WAN port (Airoha EN8811h)
- 1 1Gbit LAN ports
- 1 single lane M.2 SSD slot
- 1 mikroBus socket
- externel HW WDT (25s refresh time)
- i2c RTC (with battery backup)
Serial Interface
- UBS-C CDC-ACM
- 3 Pins GND, RX, TX
- Settings: 115200, 8N1
Test Device: https://map.chemnitz.freifunk.net/#!v:m;n:2005b6ff13f0
(`lua -e 'print(require("platform_info").get_image_name())'`) = openwrt-one
- 2.5G WAN / 1G LAN 
- LED mapping
- Power/system LED - green
- Docs:
> mediatek-filogic: add support for OpenWRT One

- patches/openwrt/0009-mt76-import-MT7915-recovery-fixes.patch
This is a draft-PR to fix the longstanding "Message timed out" errors with mt7915 based radios.
I've had positive experience with this patchset over the last 3 weeks and appreciate feedback from communities which frequently face this problem.
Sometimes, the node itself might crash when attempting recovery. I'm not entirely sure where this is happening, but it seems to be somewhere else in the mac80211 stack. The node comes back online by itself, so i still consider this an improvement over the current situation.
Log from a recovered node:
```
[1029591.814363] br-client: received packet on bat0 with own address as source address (addr:b8:ec:a3:e1:75:4f, vlan:0)
[1029592.855657] br-client: received packet on bat0 with own address as source address (addr:b8:ec:a3:e1:75:4f, vlan:0) …
```
> mt76: fix system recovery routine for MT7915

- docs/user/getting_started.rst
Changing the docs as well was missed in b1cdcc8784aa06fe22eff9aeb215244b8c429563
Reported-in: https://github.com/freifunk-gluon/gluon/pull/3414
Reported-by: 132701936+ChristianMiddendorf@users.noreply.github.com
> docs: user/getting_started: add dependencies

- package/gluon-web-network/luasrc/lib/gluon/config-mode/model/admin/network.lua
The Aruba AP-303H offers a switchable PSE output on ETH3. The power state is controlled using a GPIO pin like seen on CPE210 and Nanostation alike.
However, the PSE state is active low, which the current code handles as "Enable PoE Passthrough disable". This is not intuitive, thus support the active low case in the Gluon Web-UI.
> gluon-web-network: support handling of active-low PoE passthrough

- docs/user/supported_devices.rst
- targets/ath79-generic
(cherry picked from commit f2aeb4629741ddf6050b0248392bfc90bdbe6086)
Supersedes #3402, which I closed by accident.
> [v2023.2.x] ath79: Add support for Sophos AP15C

- .github/labeler.yml
The typo in the label name as been fixed, update the labeler config.
(cherry picked from commit 13dedfc234d6d505def21c66792e00a1a6c322e3)
---
With the typo fix backported to v2023.2.x and all issues relabeled a long time ago, we should be able to actually delete the old typoed label.
> labeler: update "continuous integration" label name (backport of #3152)

- docs/user/supported_devices.rst
- targets/ramips-mt76x8
- LED mapping
- Radio LEDs
- Docs:
> ramips-mt76x8: Add support for Xiaomi Mi Router 4A (100M International Edition v2 - R4ACv2) - closes #3183

- docs/multidomain-site-example/site.conf
- docs/site-example/site.conf
- docs/user/site.rst
- package/gluon-autoupdater/check_site.lua
- package/gluon-autoupdater/luasrc/lib/gluon/upgrade/500-autoupdater
- package/gluon-tls/Makefile
The autoupdater supports HTTPS when a ustream TLS backend is installed,
but we did not allow this in site.conf. However, just allowing HTTPS
URLs unconditionally is also a bad idea, as it might result in nodes
being unable to reach the mirror, in particular if the `tls` feature is
enabled only for some devices.
Solve this by allowing https:// URLs only if the marker file installed
by gluon-tls is found, failing the site check with an error message like
the following otherwise:
*** All of the following alternatives have failed:
1) site.conf error: expected autoupdater.branches.test.mirrors.1 to match pattern 'http://', but it is "https://..." (a string value)
2) site.conf error: expected autoupdater.branches.test.mirrors.1 to use HTTPS only if the 'tls' feature is enabled, but it is …
> gluon-autoupdater: add support for HTTPS and protocol-less URLs

- package/gluon-core/files/etc/init.d/gluon-core-reconfigure
- package/gluon-ebtables-limit-arp/files/etc/init.d/gluon-arp-limiter
- package/gluon-ebtables/files/etc/init.d/gluon-ebtables
- package/gluon-l3roamd/files/etc/init.d/gluon-l3roamd
- package/gluon-mmfd/files/etc/init.d/mmfd
- package/gluon-radv-filterd/files/etc/init.d/gluon-radv-filterd
- package/gluon-radvd/files/etc/init.d/gluon-radvd
- package/gluon-respondd/files/etc/init.d/gluon-respondd
- package/gluon-setup-mode/files/lib/gluon/setup-mode/rc.d/S13urngd
- package/gluon-setup-mode/files/lib/gluon/setup-mode/rc.d/S15gluon-setup-mode
- package/gluon-setup-mode/files/lib/gluon/setup-mode/rc.d/S50dropbear
- package/gluon-setup-mode/files/lib/gluon/setup-mode/rc.d/S96led
- scripts/lint-sh.sh
We did accidentally not lint initscripts. Extend the lint script, and fix or disable warnings in initscripts.
All scripts have been tested except for radv-filterd, l3roamd and mmfd.
> Fix linting for initscripts

- docs/user/site.rst
- package/gluon-mesh-layer3-common/check_site.lua
- package/gluon-mesh-layer3-common/luasrc/usr/lib/lua/gluon/l3.lua
This should have been removed with Babel; it was only left as deprecated to avoid breaking compatibility with existing Babel meshes. Drop support for overriding the prefix and always generate it from the domain seed.
> gluon-mesh-layer3-common: remove deprecated node_client_prefix6 from site

- package/gluon-core/files/lib/netifd/proto/gluon_mesh.sh
- package/gluon-core/files/lib/netifd/proto/gluon_wired.sh
- package/gluon-mesh-vpn-core/luasrc/lib/gluon/upgrade/500-mesh-vpn
- package/gluon-mesh-vpn-wireguard/files/lib/netifd/proto/gluon_wireguard.sh
this removes an obsolete network interface config option "transitive"
i'm not sure, if the line in gluon-mesh-vpn-wireguard is necessary though - this was not part of the discussion back in 2020 in #2081 as there was no wireguard in Gluon back then.
closes #2081
> core: remove transitive option from network interfaces

- package/gluon-mesh-vpn-wireguard/files/lib/netifd/proto/gluon_wireguard.sh
Fix previously disabled shellcheck warnings. There are a number of weird
issues in the script, possibly introduced due to copy and paste:
- PROTO_DEBUG and WG variables appear to be unused
- index and mtu proto parameters appear to be unused
It would be nice if someone could test this, as I don't know how to do it myself.
> gluon-mesh-vpn-wireguard: fix shellcheck warnings in netifd proto

- targets/generic
OpenWrt disabled ed25519 SSH keys for SMALL_FLASH targets back in 2020, however this now affects ramips-mt76x8 targets.
ALways compile dnsmasq with ed25519 support. Without this patch, previously working ed25519 keys would be unusable on said devices without this patch.
Link: https://github.com/openwrt/openwrt/commit/d0f295837a03f7f52000ae6d395827bdde7996a4
Link: https://github.com/openwrt/openwrt/commit/fd46680966e9b9bc282b665282e2e6a22a27c26e
> generic: enable dnsmasq ed25519 keys regardless of target

- docs/user/supported_devices.rst
- targets/mediatek-filogic
- LED mapping
- Radio LEDs (not present)
- [-] Should map to their respective radio
- [-] Should show activity …
> mediatek-filogic: add support for Cudy TR3000 v1

- docs/user/supported_devices.rst
- targets/ramips-mt76x8
- LED mapping
- Radio LEDs
- Docs:
> ramips-mt76x8: add support for TP-Link TL-WR902AC v4

- package/gluon-core/luasrc/lib/gluon/upgrade/250-cellular
- package/gluon-core/luasrc/usr/lib/lua/gluon/platform.lua
- targets/ath79-nand
The gl-e750 is a portable travel router that gives you safe access to the internet while traveling.
- SoC: Qualcomm Atheros AR9531 (650MHz)
- RAM: 128 MB DDR2
- Flash: 16 MB SPI NOR (W25Q128FVSG) + 128 MB SPI NAND (GD5F1GQ4UFYIG)
- Ethernet: 10/100: 1xLAN
- Wireless: QCA9531 2.4GHz (bgn) + QCA9887 5GHz (ac)
- USB: 1x USB 2.0 port
- Switch: 1x switch
- Button: 1x reset button
- OLED Screen: 128*64 px
MAC addresses based on vendor firmware:
LAN *:a0 art 0x0
2.4GHz *:a1 art 0x1002
5GHz *:a2 art calculated from art 0x0 + 2
The device itself does work and needs a lot of time to boot. It takes less time to boot when the RJ45 adapter is connected to USB-C. The device itself has no LEDs, so there is no indication about the setup mode possible. I would be happy to get some feedback …
> ath79-nand:  add support for GL.iNet E750

- docs/user/supported_devices.rst
- targets/mediatek-filogic
(`lua -e 'print(require("platform_info").get_image_name())'`) --> `gl.inet-gl-mt2500`
- LED mapping
- Radio LEDs
- Docs:
> mediatek-filogic: add GL.iNet GL-MT2500

- docs/user/supported_devices.rst
- targets/ramips-mt76x8
`cudy-tr1200-v1`
- LED mapping
- Radio LEDs (No Radio LEDs preset)
- Switch port LEDs (No switch port LEDs present)
- Outdoor …
> ramips-mt76x8: add support for Cudy TR1200 v1

- package/gluon-respondd/src/respondd-nodeinfo.c
For most devices it's quite clear which target they belong to via external information.
For x86 hoewer it's not visible from the outside (besides during upgrades via the webserver logs) which target a device belongs to.
> package/gluon-respondd: add target information

- docs/package/gluon-web-network.rst
enumerations in rst require to have an additional space
Otherwise it is all printed into a single line.
See: https://gluon.readthedocs.io/en/latest/package/gluon-web-network.html#configuration-options
> docs: gluon-web-network: fix  enumerations

- package/gluon-respondd/src/respondd-nodeinfo.c
Backport of #3496
```console
$ ssh fd01:67c:2ed8:100d::1:1 "gluon-neighbour-info -d ::1 -p 1001 -r nodeinfo" | jq
```
```json
{
"software": {
"autoupdater": {
"branch": "testing",
"enabled": false
},
"batman-adv": {
"version": "2023.1-openwrt-10",
"compat": 15
},
"fastd": {
"version": "v23",
"enabled": true,
"public_key": "724259408885162fb5843095d0c99c9287700e3f21ed5c2eb529e0d718bfeaf8"
},
"firmware": {
"base": "gluon-v2023.2-142-gca9dcd5",
"release": "3.0.6~20250505",
"target": "ramips",
"subtarget": "mt7621",
"image_name": "xiaomi-mi-router-4a-gigabit-edition"
}
},
"network": {
"addresses": [
"fd01:67c:2ed8:100d:3ecd:57ff:fe72:ff17",
"fe80::3ecd:57ff:fe72:ff17"
],
"mesh": {
"bat0": {
"interfaces": {
"wireless": [
"3e:cd:57:72:ff:19",
"ca:40:f6:4a:16:a9"
],
"other": [ …
```
> [v2023.2.x] package/gluon-respondd: add target information

- package/gluon-core/i18n/de.po
- package/gluon-core/i18n/fr.po
- package/gluon-core/i18n/gluon-core.pot
- package/gluon-core/luasrc/usr/bin/gluon-info
- package/gluon-core/luasrc/usr/lib/lua/gluon/info.lua
- package/gluon-web-admin/files/lib/gluon/config-mode/view/admin/info.html
- package/gluon-web-admin/i18n/de.po
- package/gluon-web-admin/i18n/fr.po
- package/gluon-web-admin/i18n/gluon-web-admin.pot
The Lua code was moved, but the translations were not - so regenerating
POT files using i18n-scan.pl would have broken them on the next msgmerge.
Generate new POT files for both gluon-core and gluon-web-admin, msgmerge
the existing translations for both, and adjust gluon.info to request
i18n data from gluon-core.
Noticed during review of #3484.
> gluon-core, gluon-web-admin: move translations for gluon-info strings to gluon-core

- docs/user/supported_devices.rst
- targets/mediatek-filogic
- LED mapping
- Radio LEDs
- Docs:
> mediatek-filogic: add ASUS RT-AX52

- docs/user/supported_devices.rst
- targets/ramips-mt7621
- LED mapping
- Radio LEDs
- Docs:
> ramips-mt7621: add support for Genexis Pulse EX400

- package/gluon-setup-mode/files/lib/gluon/setup-mode/rc.d/S11bootcount
Currently Gluon does not execute the bootcount scripts when booting in setup-mode.
While this is usually not issue after the first installation ahs completed, it might lead to devices with an A/B partition layout to switch active partitions after the device has been rebooted multiple times before the initial configuration.
Fix this by executing the bootcount reset initscript.
> gluon-setup-mode: execute bootcount initscript in setup-mode

- contrib/actions/free-runner-space.sh
- contrib/actions/show-system-info.sh
- contrib/depdot.sh
- contrib/lsupgrade.sh
- scripts/feeds.sh
- scripts/module_check.sh
- scripts/patch.sh
- scripts/update-patches.sh
- scripts/update.sh
> in order to increase portability across systems where /bin/ does not contain bash.
> scripts: Alter shebangs to /usr/bin/env bash

- docs/user/supported_devices.rst
- package/gluon-setup-mode/files/lib/gluon/setup-mode/rc.d/S11bootcount
- patches/openwrt/0008-ramips-mt7621-add-support-for-Genexis-Pulse-EX400.patch
- patches/openwrt/0009-ramips-add-Semtech-SX9512-touch-input-driver.patch
- patches/openwrt/0010-Input-sx951x-make-Kernel-5.15-compatible.patch
- patches/openwrt/0011-ramips-pad-EX400-kernel-partition-to-retain-web-recovery.patch
- targets/ramips-mt7621
This backports the Genexis EX400 access point to v2023.2.x.
We we're given a large batch of them to redistribute to Freifunk Communities, hence the backport.
If you wish to be sent some, contact me by E-Mail (david@darmstadt.freifunk.net) or IRC.
Depends on #3508
> [v2023.2.x] ramips-mt7621: add support for Genexis EX400

- docs/releases/v2023.2.5.rst
Just a small typo fix (lead -> led).
---
I think it would be nice to fix the typo before #3517.
> docs: releases/v2023.2.5: fix typo

- package/gluon-setup-mode/files/etc/hotplug.d/button/50-gluon-setup-mode
The Genexis Pulse EX400 has a capacitive WPS button. This button is prone to errorous presses, as it is likely to be pressed when picking up or touching the device.
The device in question has a recessed hardware reset switch for entering setup-mode. Ignore the capacitive touch button on the device in order to avoid unwanted activation of setup-mode.
> gluon-setup-mode: ignore capacitive buttons on Pulse EX400

- package/gluon-state-ntpd-check/Makefile
- package/gluon-state-ntpd-check/files/etc/hotplug.d/ntp/21-gluon-state-check
- package/gluon-state-ntpd-check/files/usr/bin/gluon-ntp-info
> a hotplug for busybox ntpd, which provides the current ntp sync state as a gluon-state-check.
> 
> This check is particularly interesting in WireGuard based communities.
> 
> Originally suggested by hexa, thanks!
This package provides two state-checks:
- `has_ntp_sync` in case the last NTP sync was successful
- `has_lost_ntp_sync` in case it wasn't.
Furthermore the modification times get updated by subsequent events
and this package provides `gluon-ntp-info` a command which interprets the creation and modification times of the two flags and produces human readable output like this:
```console
NTP has been unsynced for 706 seconds (last checked 46 seconds ago).
```
> gluon-state-ntpd-check: Add package

- docs/user/faq.rst
> At the GPN I learned a lot about others Gluon setups and how their settings would sometimes get lost after an upgrade, which was why they'd avoid them in the past.
> 
> This should clarify which settings are usually retained and migrated, and which are not.
This aims to resolve #2469.
It furthermore resolves #2159, unless @yanosz objects as I documented in that issue.
[This section](https://github.com/freifunk-gluon/gluon/pull/3530/files#diff-6eb68cf3015124e96821d08dd1dade74c4239aa8e2c39abad0d216698c4a289bR54-R58) is taken straight from @neocturne's introducing commit.
> docs: Add FAQ sections for setting retention and gluon_preserve

- package/gluon-l3roamd/files/etc/init.d/gluon-l3roamd
after commit 085250c l3roamd does not start anymore
and remove the quotes seems fix the issue.
> gluon-l3roamd: startup fix

- Makefile
- docs/site-example/image-customization.lua
- docs/user/site.rst
- scripts/image_customization_lib.lua
Add a simple way to include image customization Lua snippets.
Can be used to split long files, to include the same options multiple
times in different conditional branches, or even to pass values back to
the including file using return.
Relative paths are interpreted relative to the site root (where
image-customization.lua is located). Relative includes would become
confusing when subdirectories are involved (as they are still interpreted
relative to the site root, and proper tracking of current directory for
each include seems fairly complex for a very niche use case), so we simply
reject this case for now; this way, we can implement this however we
want in the future if deemed necessary, without a breaking change.
Suggested by @T-X
> Image customization: add include() function

- docs/index.rst
- docs/package/gluon-harden-dropbear.rst
- package/gluon-harden-dropbear/Makefile
- package/gluon-harden-dropbear/files/lib/gluon/upgrade/105-harden-dropbear
> Upon gluon-reconfigure, this package disables password-based SSH access, if the account root is locked. It furthermore disables the dropbear service if neither passwords nor authorized keys are present.
This intends to resolve #686.
I think `gluon-reconfigure` is a decent compromise between not having to fiddle with the dropbear settings manually and us definitely not wanting to patch the init script of dropbear.
I intend to take a look at also closing the firewall port if dropbear is offline.
> gluon-harden-dropbear: Add package

- docs/package/gluon-scheduled-domain-switch.rst
- package/gluon-autoupdater/check_site.lua
- package/gluon-scheduled-domain-switch/Makefile
- package/gluon-scheduled-domain-switch/check_site.lua
- package/gluon-scheduled-domain-switch/luasrc/usr/bin/gluon-check-connection
I'd like to touch a relict again, now that we've got ntp checks.
As @mweinelt put it a few days ago:
> [...] irgendeine Kombination aus den folgenden Dinge prüfen
> 
> kein ntp sync
> kein batman gateway
> keine ipv6 route
This intends to resolve #2231 eventually.
This was accepted in https://github.com/freifunk-gluon/gluon/issues/2231#issuecomment-857192174.
> gluon-scheduled-domain-switch: Replace ping with gluon-state checks

- docs/user/supported_devices.rst
- targets/ath79-generic
- ~TFTP~ **not tested**, but works according to openwrt
- ~Other: <specify>~
- LED mapping
- Radio LEDs
- …
> ath79-generic: add support for GL.iNet GL-AR300M16

- docs/user/getting_started.rst
This PR adds a copy-paste line to install the dependencies for building Gluon. It furthermore changes the Debian distribution to Bookworm since Buster is near EOL. The command is tested on Debian Bookworm.
> docs: Add install command and change debian release

- docs/package/gluon-mesh-batman-adv.rst
- package/gluon-core/files/lib/netifd/proto/gluon_mesh.sh
- package/gluon-core/files/lib/netifd/proto/gluon_wired.sh
- package/gluon-core/luasrc/lib/gluon/upgrade/210-interface-mesh
- package/gluon-mesh-batman-adv/files/lib/netifd/proto/gluon_bat0.sh
- package/gluon-mesh-vpn-core/luasrc/lib/gluon/upgrade/500-mesh-vpn
set this using
uci set gluon.batadv_hop_penalty=batadv_hop_penalty
uci set gluon.batadv_hop_penalty.mesh_vpn='20'
uci set gluon.batadv_hop_penalty.mesh_radio0='20'
uci set gluon.batadv_hop_penalty.mesh_other='20'
uci commit gluon
run
gluon-reconfigure
service network restart
and check using
batctl hardif mesh0 hop_penalty
closes #2754
> gluon-core: add hop penalty per hardif setting

- docs/user/supported_devices.rst
- package/gluon-core/luasrc/usr/lib/lua/gluon/platform.lua
- targets/ath79-generic
I recently got an request to create a gluon firmware for this device from a node owner of our community. I will test the whole checklist as soon as I get the device.
(`lua -e 'print(require("platform_info").get_image_name())'`) --> tp-link-cpe710-v2
- LED mapping
- Radio LEDs
- Docs:
TP-Link CPE710-v2 is an outdoor wireless CPE for 5 GHz with one Ethernet port based on the AP152 reference board. Compared to the CPE710-v1, the only change observed in hardware is that the mdio address of the ethernet physical changed from 0x4 to 0x0.
- SoC: QCA9563-AL3A MIPS 74kc @ 775MHz, AHB @ 258MHz
- RAM: 128MiB DDR2 @ 650MHz
- Flash: 16MiB SPI NOR Based on the GD25Q128
- …
> ath79-generic: add support for TP-Link CPE710-v2

- docs/user/supported_devices.rst
- targets/mediatek-filogic
SoC: MediaTek MT7981B 2x A53
Flash: ESMT F50L1G41LB 128MB
RAM: NT52B128M16JR-FL 256MB
Ethernet: 4x 10/100/1000 Mbps
Switch: MediaTek MT7531AE
WiFI: MediaTek MT7976C
The initial OpenWRT install is described in the OpenWRT wiki https://openwrt.org/inbox/toh/xiaomi/ax3000t
(`lua -e 'print(require("platform_info").get_image_name())'`) -> xiaomi-mi-router-ax3000t
- the first port should is declared as WAN, all other ports LAN (like in vanilla OpenWRT)
- LED mapping
- Power/system LED (only one LED present)
- Docs:
> mediatek-filogic: add support for Xiaomi AX3000T

- .github/filters.yml
- docs/user/supported_devices.rst
- targets/mvebu-cortexa53
- targets/targets.mk
We recently got an request to create a gluon firmware for this device from a node owner of our community. the node owner will test the whole checklist as soon as possible
Test Device: https://map.ffmuc.net/#!/de/map/9483c400f884
OpenWrt sites: 
https://openwrt.org/toh/hwdata/gl.inet/gl.inet_gl-mv1000_brume
https://openwrt.org/toh/gl.inet/gl-mv1000
- https://forum.gl-inet.com/t/installing-openwrt-23-05-on-brume-1/33477 			
- https://openwrt.org/toh/gl.inet/gl-mv1000#uboot_method
- firstboot
(`lua -e 'print(require("platform_info").get_image_name())'`) -> `gl.inet-gl-mv1000`
factory reset must be performed before checking the …
> cortexa53: add support for GL.iNet GL-MV1000

- package/gluon-mesh-batman-adv/files/lib/gluon/state/check.d/has_default_gw4
before, the script did land in exit 2 as $out is not empty
this fixes a bug introduced in #3556 which led to the ssid-changer always showing the offline SSID on current gluon main.
Also checking the `gw_mode` is only of interest if no `batctl gwl` exists.
And if the gw_mode is set to server, we should return with exit 0.
> gluon-mesh-batman-adv: fix has_default_gw4

- docs/index.rst
- docs/package/gluon-state-check.rst
> which is already present in the makefile but was lacking in the docs.
this resolves #3558
> gluon-state-check: Provide documentation

- docs/features/multidomain.rst
- docs/user/site.rst
- package/gluon-mesh-vpn-core/check_site.lua
- package/gluon-mesh-vpn-wireguard/check_site.lua
- package/gluon-mesh-vpn-wireguard/src/respondd.c
> which implies a usefulness for WireGuard.
> 
> Contrary to fastd WireGuard itself is identity hiding; which means: As long as neither of the two peers is compromised, the identity if the initiator will not be revealed to third parties.
> 
> The claim can be found on https://www.wireguard.com/protocol/ under 'Key Exchange and Data Packets':
> `- Identity Hiding`
> 
> The explanation of it and the whole exchange in detail can be found in this blog post:
> https://icandothese.com/docs/tech/networking/noise_and_wireguard/#identity-hiding
> 
> In order to support mixed setups, where one domain is using e.g. fastd - where the privacy setting is useful - and another domain is using WireGuard, this commit removes the limitation to only set `pubkey_privacy` in the `site.conf`.
> mesh-vpn: Remove `pubkey_privacy` setting for WireGuard
