freifunk-gluon/gluon

docs/user/site.rst
wrong formating due to a missing space
=> site.rst -> Fix Göttingen

targets/ar71xx-generic/profiles.mk
basic wifi meshing with neighbouring nodes
tested, with TL-WDR4300 (both bands working)
client WLAN (if applicable)
works
client lan on LAN ports (if applicable)
works
mesh-vpn on WAN port
works
mesh-on-wan
Not tested
re-entering configmode by pressing the button for >3 seconds
works
entering failsafe mode
works
whether the MAC address seen by Gluon is the one printed on the device
yes
lua -e "print(require('platform_info').get_image_name())"
netgear-wndr3700v2
=> Add support for Netgear WNDR3700/3800

docs/site-example/site.conf, docs/site-example/site.mk
- generalize, to make it more clear that the site config
needs to be adapted to the local community.
- remove some host names and public keys used in Lübeck
- suggest private space mac adresses
- change fastd method to salsa2012+umac, which is the recommended default
- add config for a fastd peer reachable by both ipv4 and ipv6
- order GLUON_SITE_PACKAGES alphabetically
=> docs/site-example: cleanup

targets/ar71xx-generic/profiles.mk
Everything works as expected. Only the MAC-Address is off by one compared to the address on the sticker.
=> Adding support for D-Link DIR-615 C1

targets/ar71xx-generic/profiles.mk
Built, flashed and successully tested. This patch takes advantage of patch freifunk-gluon@e93173c which solved issue freifunk-gluon#226 by introducing "GluonProfileFactorySuffix". Packages are separated by a space, not a comma. The ALL0315N initially has a OpenWRT based firmware and there is no need for a factory image. The sysupgrade can be flashed instantly.
=> Add support for ALLNET ALL0315N

targets/ar71xx-generic/profiles.mk
This commit enables the support for the TP-Link TL-MR3220 v2 router.
All Gluon features tested successfully (MAC, WIFI, LAN/WAN ports, mesh, reset button, config mode, mesh-on-wan). Also a 4-weeks long-term test was passed.
=> ar71xx-generic: add support for TP-Link TL-MR3220 v2

docs/site-example/site.conf, docs/user/site.rst, package/gluon-mesh-batman-adv-core/check_site.lua, package/gluon-mesh-batman-adv-core/files/lib/gluon/upgrade/320-gluon-mesh-batman-adv-core-wireless
This Option allows the "disabled"-option in "/etc/config/wireless" to survive updates or specify it in the site.conf.
The new code looks, weather the network is disabled, if not it looks for the site-option. In case none of those options is set it enables the network.
The site-options have to look like this, both options can be true or false.
```
client_disabled = true,
mesh_disabled = false,
```
=> make wireless-disable state survive updates and allow site option

targets/ar71xx-generic/profiles.mk
Signed-off-by: Alex Eickhoff <alex@artbanause.de>
WNDRMACv2
Router Firmware Version
V1.0.0.20
Flashed via Netgear Web-Config
Gluon Master 0b6a0be15299d6e5ebdb607c2ab66b590f97c623
* basic wifi meshing with neighbouring nodes
* Tested with TP-Link TL-WDR3600 v1
* client WLAN (if applicable)
* client lan on LAN ports (if applicable)
* mesh-vpn on WAN port
* mesh-on-wan
* re-entering configmode by pressing the button for >3 seconds
* Power Led is blinking slowly
* [*]                                               
* entering failsafe mode                    
* whether the MAC address seen by Gluon is the one printed on the device
* lua -e "print(require('platform_info').get_image_name())"
* netgear-wndrmacv2
=> remove broken flag for Netgear WNDRMACv2

docs/site-example/site.conf, docs/user/site.rst, package/gluon-mesh-vpn-fastd/check_site.lua, package/gluon-mesh-vpn-fastd/files/lib/gluon/announce/statistics.d/mesh_vpn, package/gluon-mesh-vpn-fastd/files/lib/gluon/upgrade/400-mesh-vpn-fastd
This extends the `fastd_mesh_vpn` block in the `site.conf` to allow configuration of multiple and nested peer groups. This requires moving the `backbone` table into a new table `groups` in existing site configurations. The name `backbone` isn't a keyword anymore, any other group name might be used as well.
Example:
fastd_mesh_vpn = {
methods = {'salsa2012+umac'},
mtu = 1426,
groups = {
backbone = {
limit = 2,
peers = { ... },
groups = { ... subgroups ... },
}
}
}
Fixes #354
=> gluon-mesh-vpn-fastd: extend site configuration to allow multiple and nested peer groups

package/gluon-mesh-batman-adv-core/check_site.lua
As we changed the ```check_site.lua``` I forgot to change the data types of the ```mesh_disabled``` and the ```client_disabled``` lines. This mistake stopped gluon from compiling, when using this options. This PR fixes the data types to boolean.
=> gluon-mesh-batman-adv-core: fix the data types in the check_site.lua

package/gluon-mesh-batman-adv-core/files/lib/gluon/announce/nodeinfo.d/network/mesh/bat0/interfaces, package/gluon-status-page/files/lib/gluon/status-page/www/cgi-bin/status
This will introduce a new nodeinfo object, network.mesh.bat0.interfaces,
containing any of the the following subordinated objects:
- wireless
- tunnel
- other
Each of these objects contains a (possibly empty) list of MAC addresses
(lowercase, colon-notation) corresponding to a interface of the given
class. Combined with a batman graph it is thus possible to mark
sub-graphs as "wireless" or "vpn".
The previously used object mesh_intefaces is superseded by this new
object structure and mesh_interfaces will be removed in a future Gluon
release.
=> nodeinfo: mesh interface classes (wireless, tunnel, other)

docs/features/autoupdater.rst
Change the modal verb to avoid confusion, as this is not really optional if one wants to use the autoupdater, as nodes without IPv4 connectivity (which can only be gained via WAN) are left out.
=> docs/autoupdater: depends on ipv6 reachable update-servers

targets/ar71xx-generic/profiles.mk
final image name is shown as tp-link-tl-wa830re-v10
primary mac is the one printed on the case
=> add support for TP-LINK TL-WA830RE v1.0

modules
As Gluon currently won't build if the openssl*.tar.gz is missing under openwrt/dl
mkdir -p /var/lib/jenkins/workspace/gluon/gluon/build/ar71xx-generic/openwrt/dl
/var/lib/jenkins/workspace/gluon/gluon/build/ar71xx-generic/openwrt/scripts/download.pl "/var/lib/jenkins/workspace/gluon/gluon/build/ar71xx-generic/openwrt/dl" "openssl-1.0.2a.tar.gz" "a06c547dac9044161a477211049f60ef" "http://www.openssl.org/source/" "ftp://ftp.funet.fi/pub/crypt/mirrors/ftp.openssl.org/source" "ftp://ftp.sunet.se/pub/security/tools/net/openssl/source/"
--2015-06-14 00:52:06--  http://www.openssl.org/source/openssl-1.0.2a.tar.gz
Resolving www.openssl.org (www.openssl.org)... 194.97.150.234
Connecting to www.openssl.org (www.openssl.org)|194.97.150.234|:80... connected.
HTTP request sent, awaiting response... …
=> updated openwrt commit, to include openssl patch

package/gluon-announce/files/usr/lib/lua/gluon/announce.lua, package/gluon-mesh-batman-adv-core/files/lib/gluon/announce/neighbours.d/batadv, package/gluon-mesh-batman-adv-core/files/lib/gluon/announce/neighbours.d/wifi, package/gluon-mesh-batman-adv-core/files/lib/gluon/announce/nodeinfo.d/network/mesh/bat0/interfaces
Always output empty objects or nothing at all where objects are expected, but
no elements exist.
Also remove a few unneeded "requires", a few basic modules are provided by
announce.lua by default.
=> gluon-announce, ...: don't output empty lists where not appropriate

package/gluon-status-page/Makefile, package/gluon-status-page/files/lib/gluon/announce/nodeinfo.d/software/status-page, package/gluon-status-page/files/lib/gluon/status-page/www/cgi-bin/dyn/neighbours-batadv, package/gluon-status-page/files/lib/gluon/status-page/www/cgi-bin/dyn/neighbours-nodeinfo, package/gluon-status-page/files/lib/gluon/status-page/www/cgi-bin/dyn/stations, package/gluon-status-page/files/lib/gluon/status-page/www/cgi-bin/dyn/statistics, package/gluon-status-page/files/lib/gluon/status-page/www/cgi-bin/interfaces, package/gluon-status-page/files/lib/gluon/status-page/www/cgi-bin/nodeinfo, package/gluon-status-page/files/lib/gluon/upgrade/500-status-page
This adds the API used for the new status page. It doesn't yet add the frontend but it will allow the frontend running on other nodes to access data from this node. The total number of concurrent connections is limited to 12, limiting the number of users to about 2 or 3 (~4 connections per user).
Later versions of the should probably convert scripts to pure C to further reduce load.
=> gluon-status-page: API

package/gluon-neighbour-info/src/gluon-neighbour-info.c
error() is a glibc specific function and should not be used in
code meant to be portable.
Fixes build on musl-libc.
=> Do not use error() in gluon-neighbour-info

docs/user/site.rst
see: http://gluon.readthedocs.org/en/latest/releases/v2014.3.html
Signed-off-by: Alexander Dahl <alex@netz39.de>
=> doc: remove "probability" from site doc (was removed in v2014.3)

targets/ar71xx-generic/profiles.mk
Access Point is running and stable:
https://freifunk-ingolstadt.de/map/#!v:m;n:a0f3c1957d4a
=> TP-Link TL-WA701ND v2: remove BROKEN

package/gluon-mesh-batman-adv-core/files/lib/gluon/announce/nodeinfo.d/network/addresses
The nodeinfo/network/addresses announcement included deprecated and
tentative addresses, which it clearly shouldn't as the host doesn't want
to be contacted on those addresses. They are now filtered out.
=> gluon-mesh-batman-adv-core: Only announce valid IPv6 addresses

targets/ar71xx-generic/profiles.mk
This PR adds support for the device TP-Link TL-WR710N v2.
Current OpenWRT Chaos Calmer has added support for this device. I have taken the current gluon master branch and built an image successfully.
The device could be flashed and configured correctly and is up and running now without any problems.
If I should provide some more information about the device like CLI output of any kind please let me know.
The image I used is available [here](http://pudding.freifunk-mwu.de/_archive/0.2-exp-wr710n-v2-20150806/factory/gluon-ffwi-0.2-exp-wr710n-v2-20150806-tp-link-tl-wr710n-v2.bin).
=> Add support for TP-Link TL-WR710N v2

package/gluon-wan-dnsmasq/files/etc/init.d/gluon-wan-dnsmasq
Using service_start requires exporting of environment variables.
Fixes #397
=> gluon-wan-dnsmasq: fix usage of libpacketmark

docs/site-example/site.conf, docs/user/site.rst, package/gluon-mesh-batman-adv-14/files/lib/gluon/upgrade/350-gluon-mesh-batman-adv-14, package/gluon-mesh-batman-adv-15/files/lib/gluon/upgrade/350-gluon-mesh-batman-adv-15, package/gluon-mesh-batman-adv-core/check_site.lua, package/gluon-mesh-batman-adv-core/files/lib/gluon/upgrade/320-gluon-mesh-batman-adv-core-wireless, scripts/check_site_lib.lua
This is a site.conf-breaking change in regard to the wireless config.
Make sure to read http://gluon.readthedocs.org/en/latest/user/site.html
and update your site.conf accordingly!
Support for 802.11s mesh interfaces has been added. Gluon now supports
three interface types: ap, ibss and mesh. All of them are now optional
and may be configured independently in site.conf.
A sample site.conf may look like this:
wifi24 = {
channel = 1,
htmode = 'HT40+',
ap = {
ssid = 'luebeck.freifunk.net',
},
ibss = {
ssid = '02:d1:11:37:fc:38',
bssid = '02:d1:11:37:fc:38',
mcast_rate = 12000,
},
mesh = {
id = 'ffhl-mesh',
mcast_rate = 12000,
},
},
=> mesh-batadv-core: introduce 11s mesh, refactor wireless config

docs/index.rst, docs/package/gluon-radio-config.rst, package/gluon-core/files/usr/lib/lua/gluon/util.lua, package/gluon-mesh-batman-adv-core/Makefile, package/gluon-mesh-batman-adv-core/check_site.lua, package/gluon-mesh-batman-adv-core/files/lib/gluon/upgrade/320-gluon-mesh-batman-adv-core-wireless, package/gluon-radio-config/Makefile, package/gluon-radio-config/check_site.lua, package/gluon-radio-config/files/lib/gluon/upgrade/250-gluon-radio-config
Split basic radio configuration from gluon-mesh-batman-adv as this will
be required for virtually any wireless mesh protocol.
This package takes care of setting:
- wireless channel,
- htmode and
- regulatory domain
gluon-mesh-batman-adv-core depends on this package.
Fixes #437
=> gluon-radio-config: basic wireless configuration

package/gluon-mesh-batman-adv-core/files/lib/gluon/announce/statistics.d/clients
It might be nice to distinguish how many clients are connected to a node via 2.4 GHz and 5 GHz, so we could gather information about the usage of the 5 GHz band if available.
While the actual implementation is rather easy (we already used [a hackish version](https://github.com/FreifunkBremen/ffhb-packages/blob/breminale/ffhb/ffhb-breminale/files/lib/gluon/announce/statistics.d/clients) that simply parses the output of `iw dev ... station dump`), we should probably first fix the output format in the JSON. Currently, we have:
"clients": {
"wifi": 3,
"total": 3
},
I would propose the following format, which obviously isn't backwards compatible:
"clients": {
"wifi24": 2,
"wifi50": 1,
"other": 0
},
Having a "total" field doesn't make much sense when having more than one other field, I think, …
=> Announce client count separated by frequency

CONTRIBUTING.md
I think Gluon could need some general contribution guidelines. As I wrote in the draft, "[t]o ease the work for the maintainers and to reduce the frustration of contributors".
I wrote down what came to my mind, but of course it is essential that the maintainers decide on something. This PR is just in case they are too lazy to write it down and I captured everything necessary (probably not the case).
=> RFC: Add contribution guidelines

package/gluon-mesh-batman-adv-core/files/lib/gluon/announce/neighbours.d/wifi, package/gluon-mesh-batman-adv-core/files/lib/gluon/announce/nodeinfo.d/network/mesh/bat0/interfaces, package/gluon-mesh-batman-adv-core/files/lib/gluon/announce/nodeinfo.d/network/mesh_interfaces, package/gluon-mesh-batman-adv-core/files/lib/gluon/announce/statistics.d/gateway, package/gluon-mesh-batman-adv-core/files/usr/lib/lua/gluon/batman_adv.lua
In particular this means to generate the list of mesh interfaces in lua (done in new module `gluon.batman_adv` by globbing `/sys/class/net/bat0/lower_*`) and to open `/sys/kernel/debug/batman_adv/bat0/gateways` instead of calling `batctl gateways`.
This PR contains the changes from #461
=> Don't fork batctl from announce scripts

package/gluon-luci-portconfig/files/usr/lib/lua/luci/model/cbi/admin/portconfig.lua, package/gluon-mesh-batman-adv-core/files/lib/gluon/upgrade/310-gluon-mesh-batman-adv-core-mesh, package/gluon-mesh-batman-adv-core/files/lib/gluon/upgrade/340-gluon-mesh-batman-adv-core-mesh-on-lan, patches/packages/luci/0005-model.uci-add-add_to_set-remove_from_set.patch
Convert option ifname in br-client to use a list instead. This
simplifies adding and remove interfaces:
uci:add_to_set("network", "client", "ifname", "eth0")
uci:remove_from_set("network", "client", "ifname", "eth0")
An option ifname will be automatically converted to a list when
performing an upgrade.
Packages affected: gluon-mesh-batman-adv-core, gluon-luci-portconfig
---
I have tested it as follows:
- upgrade from master
- check portconfig to work (both enabling and disabling mesh-on-lan)
- check initial setup (i.e. sysupgrade -n) with mesh_on_lan = false
- check initial setup with mesh_on_lan = true
=> br-client: convert option ifname to list ifname

contrib/sigtest.sh
Because the author of #250 seems to have vanished, and I'd like to have that script merged, here is a version of the signature testing script that incorporates all issues mentioned in #250. Also, it doesn't output anything anymore (except errors from ecdsaverify), but instead indicates success via exit code.
=> contrib/sigtest.sh - testing signature

package/gluon-mesh-batman-adv-core/files/lib/gluon/upgrade/320-gluon-mesh-batman-adv-core-wireless
keep macfilter and maclist config after fw-update
=> gluon-mesh-batman-adv-core: prepare for 802.11s mesh

docs/user/site.rst, include/gluon.mk, package/gluon-core/Makefile, package/gluon-core/check_site.lua, package/gluon-core/files/lib/gluon/upgrade/500-opkg
The new options allow specifying custom repositories and are evaluated
in an upgrade script, not during build.
=> gluon-core: replace opkg configuration in site.conf by more flexible options

docs/site-example/site.conf
I guess this is some copy and paste mistake which makes the example an
invalid site.conf. In my case merging the changes of the example into
our actual site.conf lead to an error because this line was merged to.
=> doc: remove double opening next_node line in site.conf example

docs/user/getting_started.rst, docs/user/site.rst
This commit basically does two things: it urges users always to use an own
git repository to manage the site configuration, and it removed all
mentions of "communities" from the "Getting started" page, as it was too
Freifunk-specific.
Other documentation pages (especially the site configuration docs) should
probably be adjusted as well.
=> docs: improve user/getting_started, some minor fixes in user/site

package/gluon-ebtables-filter-multicast/files/lib/gluon/ebtables/110-mcast-allow-icmp, package/gluon-ebtables-filter-multicast/files/lib/gluon/ebtables/110-mcast-allow-icmpv6
in a layer 2 mesh network, pings to ff02::1 (all-nodes) and ff02::2 (all-routers) cause a lot of traffic in the network, significantly increasing the 'background noise' (= Grundrauschen) and stressing nodes in the network.
picture shows increased background noise (peaks on the right) in the network (~850 nodes, 1500 clients at that moment) generated by pings to ff02::1.
a solution would be the switch to a layer 3 mesh, but this is not a possible short-term change.
@T-X stated, that there should be no problems by blocking this: "ja, denke, ICMPv6 echo-req. nach ff02::1 und ff02::2 sollte man blockieren. habe noch keinen RFC gefunden, der damit probleme hätte"
=> gluon-ebtables-filter-multicast: drop icmpv6 echo-requests to all-nodes & all-routers

package/gluon-mesh-batman-adv-core/files/lib/gluon/upgrade/320-gluon-mesh-batman-adv-core-wireless
Is makes sense to always look for both ibss_radio* and mesh_radio* sections
to determine if the meshing should be enabled when regenerating these
sections. Doing this, the disabled state will survive updates changing the
section name (either updating from pre-2015.2 while keeping IBSS, or
changing from IBSS to 11s or vice-versa).
If both ibss_radio* and mesh_radio* sections exist, the disabled state will
be kept correctly for each section, the behaviour is changed only when
creating a section that didn't exist before.
Fixes #549
=> gluon-mesh-batman-adv-core: keep disabled state even when the mesh interface section name is changed

patches/openwrt/0043-OpenSSL-Added-source-old-to-PKG_SOURCE_URL.patch
OpenSSL moves old versions of the library from http://www.openssl.org/source/
to http://www.openssl.org/source/old/1.0.2/ breaking the old links. That
behavior breaks the OpenWRT-build every time OpenSSL releases a new version.
This patch adds http://www.openssl.org/source/old/1.0.2/ to the PKG_SOURCE_URL
of OpenSSL to avoid breaking the build whenever OpenSSL releases a new
version.
=> OpenSSL: Added source/old to PKG_SOURCE_URL

docs/features/wired-mesh.rst
The last occurance of the 'Export Mode'
=> docs: fix typo

targets/ar71xx-generic/profiles.mk
This commit enables the support for the D-Link DIR-505 router.
All Gluon features tested successfully (MAC, WIFI, WAN ports (only 1 eth), mesh, reset button, config mode, mesh-on-wan).
=> ar71xx-generic: add support for D-Link DIR-505

package/gluon-status-page-api/src/stations.c
In communities having their batman-adv mesh inside a VLAN on ibss interface simply throwing the batman-adv lower-interface at libiwinfo won't work as that's not a wireless interface.
Recurse down to the lowest interface before calling iwinfo_backend.
=> gluon-status-page-api: support batadv-in-VLAN on ibss interface

targets/ar71xx-generic/profiles.mk
Tests done to verify that this worked as intended:
* checked plattform_info image_name
* checked primary_mac
* does appear in ffmap-d3
* does mesh
* does fastd-VPN
=> Added Support for TP-Link WR843ND

package/gluon-neighbour-info/Makefile, package/gluon-neighbour-info/files/lib/gluon/upgrade/400-neighbour-info-firewall
If the query was via multicast, the response isn't matched by
--state ESTABLISHED,RELATED
This fixes #619
=> gluon-neighbour-info: Open firewall on WAN for respondd replies

package/gluon-respondd/files/lib/gluon/upgrade/400-respondd-firewall
Restrict to link-local addresses to prevent amplification attacks from
outside the mesh, or such attacks affecting the outside world.
Fixes #637
=> gluon-respondd: restrict queries from the mesh to link-local addresses

docs/features/wlan-configuration.rst, package/gluon-core/files/etc/config/gluon-core, package/gluon-core/files/lib/gluon/upgrade/200-wireless
**Old description:**
This changes introduces the new uci section 'gluon-core.wireless' with a preserve_channel option per radio:
* preserve_channel_radio0 (boolean)
* preserve_channel_radio1 (boolean)
By setting these options to true the wifi channel of the regarding radio will be preserved during upgrades.
**New description:**
This change introduces the new uci section 'gluon-core.wireless' with a preserve_channels option:
* preserve_channels (boolean)
By setting this option to 1 (true) wifi channels will be preserved during upgrades.
=> gluon-core: add preserve wifi channel feature

targets/ar71xx-generic/profiles.mk
Please add this patch to enable FF-images for TP-Link MR13U, a device very similar to MR3020 but with a big internal battery. I have heavily tested the device with fastd-VPN and/or as mesh-device with the munich site-config. Throughput is comparable to MR3020.
MR13U is supported by OpenWrt for a while already: https://wiki.openwrt.org/toh/tp-link/tl-mr13u
=> ar71xx-generic: add support for TP-Link MR13U

package/gluon-status-page/src/js/lib/gui/statistics.js, package/gluon-status-page/src/js/lib/helper.js
Avoid using Intl and Set.
Is now working nicely in Firefox & Chrome on desktop and Android, default WebView of Android 5.0 and Safari on an outdated MacOS X 10.9. I suspect it might also work on iPhones, but I haven't tested it.
=> Status page compatiblity improvements (and some misc. improvements)

package/gluon-core/files/lib/gluon/upgrade/110-network, package/gluon-mesh-batman-adv-core/files/lib/gluon/upgrade/310-gluon-mesh-batman-adv-core-mesh
This pull request adds two patches mandatory for bridge multicast snooping. For now, as multicast snooping is still disabled, they are basically a no-op.
Ref.:  #278 (#402), #674
=> Preparations for Multicast Snooping

docs/index.rst, targets/ar71xx-generic/profiles.mk
The Hornet UB is sold at least in the varieties. Without case it is a Hornet UB, with case and without connected USB port it is called AP121. If the USB port is present this device is called AP121U.
We have a AP121U in our mesh http://meshviewer.chemnitz.freifunk.net/#!v:m;n:00c0ca6efffa
=> Add Support for the ALFA Hornet UB and similar devices

patches/openwrt/0018-x86-fix-platform_export_bootpart-for-Xen-virtual-disks.patch
Patch tested on v2016.1.x branch with Freifunk Magdeburg firmware on
Debian Jessie amd64 Xen host. See the same patch in our gluon fork here:
https://github.com/FreifunkMD/gluon/blob/fix-sysupgrade-xen/patches/openwrt/0058-x86-fix-platform_export_bootpart-for-Xen-virtual-disks.patch
Sysupgrade was tested successfully by manually making the change before
upgrading in the filesystem of the running node and upgrading to the
fixed FFMD experimental build in config mode via expert settings in
webgui.
Patch also submitted to OpenWRT trunk already.
Signed-off-by: Alexander Dahl <alex@netz39.de>
=> openwrt: add patch fixing sysupgrade on Xen DomU

targets/ar71xx-generic/profiles.mk
Some TP-Link models were renamed within OpenWRT 15.05 (commit [0fd48fd7dab066db8a46e51775579c9ef507ca25](https://git.openwrt.org/?p=15.05/openwrt.git;a=commit;h=0fd48fd7dab066db8a46e51775579c9ef507ca25)). This updates the corresponding naming within Gluon.
=> ar71xx-generic: update profiles.mk to match new naming

docs/index.rst, targets/ar71xx-generic/profiles.mk
This patch brings the work of @tcatm with @Garunda on support for the CISCO Meraki series for Gluon in sync with OpenWRT as distributed with 2016.1.x. That latest redistributed OpenWRT release has accepted the patch that the two had previously applied for their cause and thus this merge basically removes the patch to OpenWRT while leaving the build-invocation by Gluon intact.
OpenWRT not only supports the MR12 (similar to the MR62) but also the MR16 (similar to the MR66). The firmware was successfully tested by @Garunda for the MR62. Gluon images for the MR16 were added to the patch of @tcatm. The confirmation of the functionality of the image for the MR66 is still pending.
The devices are of interest to the community as they are perceived as "enterprise class" hardware (makes a …
=> Tcatm's meraki branch merged

CONTRIBUTING.md
link "packages" instead of "community repositories"
add link for rejected features to bottom link list
link "#gluon" to webirc
link the mentioned commit 2a93c58
=> CONTRIBUTING.md: update links

package/gluon-mesh-batman-adv-core/files/lib/gluon/upgrade/310-gluon-mesh-batman-adv-core-mesh
These are supposed to be the last two patches necessary before re-activating multicast snooping.
The first one lowers the query intervals for br-client, the second one increases the robustness against potential packetloss on the wifi.
For now, as multicast snooping is still disabled, they are basically a no-op.
Ref.: #674, #675, #278 ( #402)
=> Preparations for Multicast Snooping Final

docs/index.rst, package/gluon-core/files/lib/gluon/upgrade/010-primary-mac, targets/ar71xx-generic/profiles.mk
Device information can be found at:
http://www.8devices.com/products/carambola-2
https://wiki.openwrt.org/toh/8devices/carambola2
I only did some minimal testing of gluon on the carambola 2 development
board:
- Config mode works
- Connects to Wifi Mesh
- Allows clients to connect
Notably, autoupgrade has not yet been tested.
Change to 010-primary-mac is necessary as the mac address printed
on the sticker is the one of eth0, not the wifi mac.
=> Add support for carambola 2 board

package/gluon-client-bridge/files/lib/gluon/upgrade/320-gluon-client-bridge-wireless, package/gluon-core/Makefile, package/gluon-core/files/lib/gluon/upgrade/010-primary-mac, package/gluon-core/files/usr/lib/lua/gluon/util.lua, package/gluon-mesh-batman-adv-core/files/lib/gluon/upgrade/300-gluon-mesh-batman-adv-core-wan, package/gluon-mesh-batman-adv-core/files/lib/gluon/upgrade/320-gluon-mesh-batman-adv-core-wireless, package/gluon-mesh-batman-adv-core/files/lib/gluon/upgrade/340-gluon-mesh-batman-adv-core-mesh-on-lan, package/gluon-mesh-vpn-fastd/files/lib/gluon/upgrade/400-mesh-vpn-fastd
The VIF mac addresses in the ralink-rt305x chip must be sequential in
the last bits, since they are using a hardware mac filter.
1. Hash the original primary mac, since the addresses of devices bought
together could be sequential in the last byte.
2. Increment the last byte for the VIF on the vocore (```generate_mac``` routine)
Implements #648
=> Fix ralink-rt305x/vocore mac schema generation.

package/gluon-config-mode-mesh-vpn/files/lib/gluon/config-mode/reboot/0100-mesh-vpn.lua
The user may enter contact-information within the config-mode. This information can for example be provided for a node-registration-link on the reboot-page.
In our community we had some confusion about asking for contact-information two times (in the config-mode and at node-registration).
=> provide contact-information for reboot-page

package/gluon-node-info/files/lib/gluon/upgrade/520-node-info-whitespace-fix
This fixes #703 
First version, this may be improved by iterating through the listed items within _gluon-node-info_ - _location_, instead of hard coded stuff.
=> gluon-node-info: add a script to fix whitespaces within the coordinates

docs/index.rst, package/gluon-luci-admin/files/usr/lib/lua/luci/controller/admin/upgrade.lua, targets/ar71xx-generic/profiles.mk
Following hardware was tested with gluon-2016.1.4
- MR600
- MR600v2
- MR900
- MR900v2
- OM2P
- OM2P-HS
- OM2P-HSv2
- OM2P-LC
- OM2Pv2
- OM5P
- OM5P-AN
OpenMesh hardware is for example used at https://meshviewer.chemnitz.freifunk.net/#!v:m;n:ac867400ec02
----
The gluon-luci-admin change itself is a fix but there will be also a patch for OpenWrt/LEDE to modify the behavior of `platform_check_image_openmesh`
=> Add support for OpenMesh hardware available in OpenWrt CC

docs/user/getting_started.rst
Trivial patch fixing a single typo in documentation.
=> docs: typo repositoy -> repository

targets/ar71xx-generic/profiles.mk
The returned name for OpenMesh devices with a an extra vX when calling
lua -e 'print(require("platform_info").get_image_name())'
doesn't contain a dash between the vX and the device name. Thus the image
should also not contain a dash.
=> ag71xx-generic: Remove extra dash between v2 and OpenMesh device name

package/gluon-core/files/lib/gluon/upgrade/010-primary-mac
The OpenMesh devices have a sticker with the eth0 mac address on the bottom. Also all other mac addresses are calculated based on this address. Therefore, it is better to use this as primary mac address instead of the WiFi mac address.
=> ar71xx-generic: Use eth0 as OpenMesh primary mac address

package/gluon-mesh-batman-adv-core/src/respondd.c, package/gluon-mesh-vpn-fastd/src/respondd.c, package/gluon-node-info/src/respondd.c, package/gluon-respondd/src/respondd.c, patches/openwrt/0080-libjson-c-Add-support-for-custom-format-strings-for-doubles.patch
Most doubles that are delivered via respondd have limited input
precision, but are converted with up to 17 digits of precision. That can
cause ugly blowups like 0.2800000000000001 in the output, which is
avoided by specifying better format strings (like "%.2f" in most cases).
=> respondd modules: Use proper formatting of doubles

patches/openwrt/0095-ar71xx-add-GL-AR150-support.patch, targets/ar71xx-generic/profiles.mk
I added support for GL-AR150 because a friend bought such a device and wanted to use it with Freifunk.
The device worked with branch v2016.1.x, and the same patch also applies to master. Unfortunately, he broke the router (via static discharge, not software-related), so I'm unable to test it with a current gluon version. Therefore, for now, I marked the device as 'BROKEN'.
=> ar71xx: add GL-AR150 support

docs/index.rst, package/gluon-core/files/lib/gluon/upgrade/010-primary-mac, patches/openwrt/0097-ar71xx-add-kernel-support-for-the-OpenMesh-OM2P-HSv3.patch, patches/openwrt/0098-ar71xx-add-user-space-support-for-the-OpenMesh-OM2P-HSv3.patch, patches/openwrt/0099-ar71xx-enable-sysupgrade-for-the-OpenMesh-OM2P-HSv3.patch, patches/openwrt/0100-package-om-watchdog-add-OpenMesh-OM2P-HSv3-support.patch, patches/openwrt/0101-package-uboot-envtools-add-OpenMesh-OM2P-HSv3-support.patch, patches/openwrt/0102-ar71xx-add-OM2P-HSv3-to-the-OM2P-profile.patch, patches/openwrt/0103-ar71xx-add-kernel-support-for-the-OpenMesh-MR1750v2.patch, patches/openwrt/0104-ar71xx-add-user-space-support-for-the-OpenMesh-MR1750v2.patch, patches/openwrt/0105-ar71xx-enable-sysupgrade-for-the-OpenMesh-MR1750v2.patch, patches/openwrt/0106-package-om-watchdog-add-OpenMesh-MR1750v2-support.patch, patches/openwrt/0107-package-uboot-envtools-add-OpenMesh-MR1750v2-support.patch, patches/openwrt/0108-ar71xx-extract-ath10k-wifi-board.bin-for-the-OpenMesh-MR1750v2-board.patch, patches/openwrt/0109-ar71xx-add-MR1750v2-to-the-MR1750-profile.patch, targets/ar71xx-generic/profiles.mk
The new OM2P-HSv3/MR1750v2 device support is only available in LEDE master. The relevant patches had to be backported to add support for them in Gluon.
All patches were also forwarded to OpenWrt for inclusion in CC and trunk.
=> ar71xx-generic: Add support for OpenMesh OM2P-HSv3/MR1750v2

patches/packages/routing/0004-batman-adv-Fix-speedy-join-in-gateway-client-mode.patch
Speedy join only works when the received packet is either broadcast or an 4addr unicast packet. Thus packets converted from broadcast to unicast via the gateway handling code have to be converted to 4addr packets to allow the receiving gateway server to add the sender address as temporary entry
to the translation table.
Not doing it will make the batman-adv gateway server drop the DHCP response in many situations because it doesn't yet have the TT entry for the destination of the DHCP response.
=> batman-adv: Fix speedy join in gateway client mode

targets/ar71xx-generic/profiles.mk
The Tube2H is a cheap Bullet-Clone.
It is supported barely undocumented by openwrt.
So it's a good point to add Gluon support to it.
I am testing it on the small 8M version and runs quiet well and stable.
The only ToDo is enhance the implementation of the rf chip. It's actually not possible to set txpower.
MultiSSID is working and default txpower seems to be normal compared to the possible range.
=> Added support for ALFA Networks Tube2H

targets/ar71xx-generic/profiles.mk
Add Buffalo WZR-HP-G300NH2 to Makefile, device is already supported in OpenWrt and LEDE.
Verified functionality with actual device.
=> Add support for Buffalo WZR-HP-G300NH2

package/gluon-luci-private-wifi/luasrc/usr/lib/lua/luci/model/cbi/admin/privatewifi.lua
=> gluon-luci-private-wifi: limit ssid to 32 characters

modules
This does not work though, but the original git is down and I've no idea how to specify the remote ref correctly so feel free to fix it.
=> modules: change url from openwrt.org to github one

targets/ar71xx-generic/profiles.mk
I've bought a couple of those devices from Senetic GmbH.
https://www.senetic.de/product/TL-WR842N
They have 16 MB of Flash and 64 MB of RAM. Platform support works fine,
I've also tested a little with Ethernet (since I saw some regressions on
OpenWRT/LEDE with 841v11), no problems.
Therefore, lets remove the broken mark.
Signed-off-by: Simon Wunderlich <sw@simonwunderlich.de>
=> ar71xx-generic: remove broken mark for wr842n-v3

package/gluon-mesh-batman-adv-core/luasrc/lib/gluon/upgrade/310-gluon-mesh-batman-adv-core-mesh
The mesh side has become fairly huge in many communities. Up to
a few thousand entries can currently be found in the forwarding
database (fdb) of a bridge for its bridge port bat0.
The bridge fdb is kind of redundant to the batman-adv global translation
table here. Therefore this patch tries to reduce memory footprint by
following an approach similar to the IGMP/MLD split patchset approach:
Make the bridge oblivious not only regarding multicast listeners towards
the mesh but with this patch unicast hosts on the mesh, too.
If the destination of an ethernet frame is known by the bridge to be a
local one, then the frame is forwarded to the according port. If it is
unknown, then the frame is forwarded to the wifi AP interface and bat0.
mac80211 and batman-adv then know whether to drop or …
=> gluon-mesh-batman-adv-core: disable bridge port learning on bat0

package/gluon-core/luasrc/lib/gluon/upgrade/110-network, package/gluon-mesh-batman-adv-core/luasrc/lib/gluon/upgrade/310-gluon-mesh-batman-adv-core-mesh
This commit enables multicast snooping on br-wan and br-client again.
Should be pulled only _after_ #674  and #679 got merged. This PR is rebased onto #679 for easier merging, the according two commits are identical to the ones in #679 .
Ref.: #278 (#402)
=> Enable multicast snooping

docs/site-example/site.conf, docs/user/site.rst, package/gluon-core/check_site.lua, package/gluon-core/luasrc/lib/gluon/upgrade/200-wireless, package/gluon-mesh-batman-adv-core/check_site.lua, scripts/check_site_lib.lua
First commit adds a new function to check_site_lib.lua, to check whether a value is included in a given array. This is needed, to check that the list of wifi rates only contains unprohibited values.
Second commit adds the functionality to specify a list of allowed wifi rates within site.conf, which was already discussed in #467. Additionally this should fix all issues mentioned by @NeoRaider in #808.
Thanks to:
@RubenKelevra
@Brother-Lal
@rotanid
=> gluon-core: make wifi rates configurable

docs/index.rst, targets/ar71xx-generic/profiles.mk
+ added profile for these devices
+ added entry in the docs for these devices plus the missing alfa tube
=>  ar71xx-generic: add support for ALFA N2 and N5

CONTRIBUTING.md
Github by now allows project maintainers to squash PRs with a few clicks, thus imposing the squashing onto contributors isn't really necessary anymore in my opinion.
=> Remove squashing from contribution guidelines

package/gluon-status-page/src/css/animation.css, package/gluon-status-page/src/css/menu.css
None of them are used by modern browsers anymore, so it's safe to remove them.
=> gluon-status-page: removed obsolete css prefixes

docs/index.rst, targets/ar71xx-generic/profiles.mk
The MR1750 and OM5P-AC devices are based on ath9k SoCs and an external ath10k chip. All devices which are using ath10k should be marked as broken due to deficits in their IBSS support.
=> ar71xx-generic: Mark MR1750 and OM5P-AC devices as BROKEN

docs/user/getting_started.rst
Tested build on a minimal Ubuntu 16.04 container image without wget.
Also applies to 2016.x.
```
make[7]: Entering directory '/home/build/site-ffm/gluon-build/openwrt'
Checking 'working-make'... ok.
Checking 'case-sensitive-fs'... ok.
Checking 'gcc'... ok.
Checking 'working-gcc'... ok.
Checking 'g++'... ok.
Checking 'working-g++'... ok.
Checking 'ncurses'... ok.
Checking 'zlib'... ok.
Checking 'libssl'... ok.
Checking 'tar'... ok.
Checking 'find'... ok.
Checking 'bash'... ok.
Checking 'patch'... ok.
Checking 'diff'... ok.
Checking 'cp'... ok.
Checking 'seq'... ok.
Checking 'awk'... ok.
Checking 'grep'... ok.
Checking 'getopt'... ok.
Checking 'stat'... ok.
Checking 'md5sum'... ok.
Checking 'unzip'... ok.
Checking 'bzip2'... ok.
Checking 'wget'... failed.
Checking 'perl'... ok.
Checking …
```
=> docs: mention dependency on wget

package/gluon-status-page/src/js/main.js
If cookies are disabled, the Statuspage only displays an empty ("Not connected")
This checks if the localStorage API is available and working and only uses it in this case
Also allows better backwards compatibility.
=> gluon-statuspage: fix error if cookies are disabled

package/gluon-status-page/src/index.html.m4, package/gluon-status-page/src/js/main.js
The current statuspage is completely empty if JS is disabled.
This at least displays a message to please enable JS in the case its disabled.
=> gluon-status-page: add info if javascript is disabled to enable it

docs/site-example/site.conf, docs/user/site.rst, package/gluon-mesh-vpn-fastd/check_site.lua, package/gluon-mesh-vpn-fastd/luasrc/lib/gluon/upgrade/400-mesh-vpn-fastd
it is easy to set this to a higher value again if needed. This will prevent fastd from flooding the log ringbuffer, even when it is not needed/no uplink via fastd. 
This log - flooding raise with every peer known from site.conf.
Fixes #896
=> Make fastd syslog level configurable

targets/x86-64/profiles.mk, targets/x86-generic/profiles.mk
this PR sorts the list of network modules integrated in x86 images and adds the 3 new modules kmod-igb, kmod-sky2, kmod-tulip
=> X86 network drivers

patches/openwrt/0076-x86-64-add-pata-drivers.patch, patches/openwrt/0077-x86-add-mmc-drivers-to-generic-64.patch
first, this PR adds the PATA driver modules in x86-generic config also to the x86-64 target
second, it adds support for booting from a sdcard to x86-generic and x86-64
=> pata and mmc drivers for x86 targets

patches/openwrt/0081-kernel-add-at803x-fix-for-sgmii-mode.patch
Some (possibly broken) bootloaders (e.g. Ubiquiti UAP-AC-LITE) incorrectly initialize the at8033 phy. This breaks auto-negotation on these SGMII devices. The mode has therefore to be set back in to a valid configuration by Linux.
Fixes #911
----
This is just a possible fix for the problem from #911. I am still waiting for confirmation. But at least I could see a working uplink on http://vogtland.freifunk.net/map/#!v:m;n:802aa848b87c
=> kernel: add at803x workaround for sgmii mode

patches/openwrt/0081-kernel-add-at803x-fix-for-sgmii-mode.patch
Some (possibly broken) bootloaders (e.g. Ubiquiti UAP-AC-LITE) incorrectly initialize the at8033 phy. This breaks auto-negotation on these SGMII devices. The mode has therefore to be set back in to a valid configuration by Linux.
Fixes #911
----
This is just a possible fix for the problem from #911. I am still waiting for confirmation. But at least I could see a working uplink on http://vogtland.freifunk.net/map/#!v:m;n:802aa848b87c
=> v2016.2.x: kernel: add at803x workaround for sgmii mode

patches/openwrt/0034-ar71xx-update-QCA956x-support.patch
The  assignment of the gpio_count and reg_base in ath79_gpio_output_select
takes care that only supported platforms can use ath79_gpio_output_select.
But the rebase of the patches after the last OpenWrt base update
accidentally added an extra check for the SoC which was missing support
soc_is_qca955x().
Boots on QCA955X devices which were using ath79_gpio_output_select ended
with an
Kernel bug detected[#1]:
[...]
Call Trace:
[<803e6174>] ath79_gpio_output_select+0x30/0xe8
[<803ed590>] om5p_acv2_setup+0x24/0x200
[<803e4dc0>] ath79_setup+0x28/0x38
[<80069ac8>] do_one_initcall+0x148/0x1ec
[<803e2cc4>] kernel_init_freeable+0x150/0x208
[<80065218>] kernel_init+0x10/0x114
[<80060878>] ret_from_kernel_thread+0x14/0x1c
Fixes: a22c1d5670c1 ("Update OpenWrt base")
Signed-off-by: Sven Eckelmann …
=> openwrt: Remove extra soc check in ath79_gpio_output_select

package/gluon-mesh-batman-adv-core/files/lib/gluon/respondd/client.dev, package/gluon-respondd/files/etc/hotplug.d/iface/10-gluon-respondd, package/gluon-respondd/files/etc/init.d/gluon-respondd, package/gluon-respondd/files/lib/gluon/core/mesh/setup.d/10-gluon-respondd
this PR will make babel firmware able to run respondd while not breaking compatibility with batman.
This is done by making device detection independent of batman-specific calls. 
This has been tested in a batman network
=> make respondd initialisation mesh protocol agnostic

package/gluon-mesh-batman-adv-core/Makefile, package/gluon-mesh-batman-adv-core/src/Makefile, package/gluon-mesh-batman-adv-core/src/batadv-netlink.c, package/gluon-mesh-batman-adv-core/src/batadv-netlink.h, package/gluon-mesh-batman-adv-core/src/batman_adv.h, package/gluon-mesh-batman-adv-core/src/respondd.c, package/gluon-status-page-api/Makefile, package/gluon-status-page-api/src/Makefile, package/gluon-status-page-api/src/batadv-netlink.c, package/gluon-status-page-api/src/batadv-netlink.h, package/gluon-status-page-api/src/batman_adv.h, package/gluon-status-page-api/src/neighbours-batadv.c
This is a follow up pull request of RFC #916 
----
The batadv debugfs requires large memory blocks to write the text debug tables. This is inefficient for large tables like the global translation table or the originators table.
The memory requirement can be reduced by using netlink. It copies smaller packets in a binary format to the userspace program. gluon can therefore parse larger originator tables without causing an OOM on systems which are tight on memory.
----
This pull request is not about providing a generic way to access batman-adv netlink. This could be done by an interested third party. Important for a library which basically only provides `batadv_nl_query_common` and `batadv_netlink_policy` would be:
* batadv-netlink.c has to be integrated in a new/existing library
* …
=> Switch from batman-adv v14/v15 debugfs to netlink

patches/openwrt/0094-mac80211-Allow-switching-of-the-ath-regulatory-domain.patch
ath10k has to switch the regulatory domain when switching the default country when ATH_USER_REGD is enabled. This is for example important when switching from country US (FCC) to DE (ETSI). The ath implementation will use ath_reg_dyn_country_user_allow to check if this is allowed.
Unfortunately, this function always seems to return false to ath_reg_notifier_apply even when ATH_USER_REGD is enabled [1]. But it must actually always accept the requests from the user (when ATH_USER_REGD is enabled) to correctly set the conformance test limits in the ath10k binary
blob.
Not doing it will sometimes allow too high transmit powers on edge channels for correctly calibrated devices outside their default regulatory domain.
[1] Assuming that ATH_REG_DYNAMIC_USER_REG_HINTS is disabled (as it is in …
=> mac80211: Allow switching of the ath10k regulatory domain

docs/features/dns-cache.rst, package/gluon-core/check_site.lua, package/gluon-core/luasrc/lib/gluon/upgrade/820-dns-config, package/gluon-mesh-batman-adv-core/luasrc/lib/gluon/upgrade/330-gluon-mesh-batman-adv-core-local-node
as dns server any server in the network can be used. for example an anycast-ip-address where dns is served ie on all gateways.
=> add gluon-dns-config: a package that enables the next node to be used as dns cache

targets/ramips-mt7628, targets/targets.mk
This change adds the VoCore2 to the devices which are gluon ready. The VoCore2 was also able to handle ibss, 802.11s and the client net at the same time. Unfortunately the stability is not so good. 
Test device: https://meshviewer.chemnitz.freifunk.net/#!v:m;n:b8d81267052b
=> ramips-mt7628: add new platform and vocore2

docs/releases/v2016.1.rst
adds missing trailing `,` in simple_tc section and changes the order of ingress and egress to default format used by Gluon
=> docs: fix typos in 2016.1 release notes

package/gluon-status-page-api/Makefile, package/gluon-status-page-api/luasrc/lib/gluon/status-page/www/cgi-bin/interfaces
This PR will make /lib/gluon/status-page/www/cgi-bin/interfaces mesh-protocol-agnostic by utilizing gluon-util.get_mesh_devices()
Also indents will be fixed via a separate commit.
=> babel statuspage-api: make interfaces mesh protocol agnostic

package/gluon-mesh-vpn-fastd/Makefile
This prepares the gluon-mesh-vpn-fastd package for babel-use.
=> gluon-mesh-vpn-fastd: do not depend on mesh-protocol batman

targets/ar71xx-tiny
fixes https://github.com/freifunk-gluon/gluon/issues/894
As far as I know the sysupgrade is broken on 7510N. I expect that it is broken on 7210N, too.
The patch has not been tested on a device.
=> add support for TP-Link TL-WA7210N

package/gluon-mesh-vpn-fastd/check_site.lua
lua can not match `(ipv4|ipv6)?` or similar, so I decided to match `[ipv46 ]*`, one can also match `i?p?v?[46]?%s?` and I would change this PR accordingly if requested.
depends on #1016
=> [RFC] gluon-mesh-vpn-fastd: improve check_site

targets/mvebu
As for [sunxi](https://github.com/freifunk-gluon/gluon/blob/master/targets/sunxi#L9) wpad-mini conflicts with hostapd-mini.
=> mvebu: remove wpad-mini

package/gluon-status-page-api/files/lib/gluon/upgrade/500-status-page-api
this will limit the uhttp max_requests to 16 saving even  slow tl-wr740 from being overloaded by statuspage-traffic.
This addresses one consideration in #1032
=> gluon-status-page-api: limit uhttp max_requests to 16 on devices with <48MB RAM (part 1/2  #1032)

targets/ar71xx-generic
The current LEDE build is working fine on a Ubiquiti Rocket M2 Titanium.
But the rocket-m-ti images are missing from a recent gluon build.
Is this commit sufficient to build working images?
This PR is related to #943
=> ar71xx-generic: Added Ubiquiti Rocket M2 Titanium to profiles.

targets/brcm2708-bcm2708
This should fix the following error, as it did for sunxi and mvebu.
```
Collected errors:
* check_data_file_clashes: Package wpad-mini wants to install file /scratch/hexa/build/gluon/lede/build_dir/target-arm_arm1176jzf-s+vfp_musl-1.1.16_eabi/linux-brcm2708_bcm2708/target-dir-2fbc7ff2/usr/sbin/hostapd
But that file is already provided by package  * hostapd-mini
* opkg_install_cmd: Cannot install package wpad-mini.
```
=> bcm2708: prevent wpad-mini from conflicting with hostapd-mini

targets/ar71xx-tiny
The WR940n doesn't has detachable antennas.
=> fixed: image file name creation for tp-link-tl-wr940n

package/gluon-mesh-vpn-core/luasrc/lib/gluon/upgrade/400-mesh-vpn
VPN daemons were always disabled
This fixes the issue that was left in the previous pull request without moving the code to a new file or creating skeleton configs.
has_fastd and has_tunneldigger were incorrectly  used twice in defining the enabled variables and when setting the final value in UCI.
=> gluon-mesh-vpn-core: Fixed conditions for migration code

package/gluon-core/luasrc/lib/gluon/upgrade/200-wireless
Nodes which upgraded from 2015.X in the past, kept old VLAN interface definitions in /etc/config/network.
This lead to a VLAN interface on mesh0 as the adhoc interfaces had the same name in the past.
This issue is only surfacing when migrating from adhoc to 802.11s and the nodes had 2015.X running in the past. I suspect that this bug is also present in 2016.2.X
=> gluon-core: Fixed bug which kept legacy VLAN interface definitions

package/gluon-core/luasrc/lib/gluon/upgrade/500-opkg
With LEDE the content of `/etc/openwrt_version` changed. It no longer contains a version string like `17.01` as it was with OpenWrt.
```
BusyBox v1.25.1 () built-in shell (ash)
_________
/        /\      _    ___ ___  ___
/  LE    /  \    | |  | __|   \| __|
/    DE  /    \   | |__| _|| |) | _|
/________/  LE  \  |____|___|___/|___|                      lede-project.org
\        \   DE /
\    LE  \    /  -----------------------------------------------------------
\  DE    \  /    Reboot (17.01-SNAPSHOT, r3290+11-1b94737824)
\________\/    -----------------------------------------------------------
root@LEDE:~# cat /etc/openwrt_version 
r3290+11-1b94737824
```
=> gluon-core: fix variable %v

docs/package/gluon-ebtables-source-filter.rst, package/gluon-ebtables-source-filter/Makefile, package/gluon-ebtables-source-filter/check_site.lua, package/gluon-ebtables-source-filter/files/lib/gluon/ebtables/100-local-forward-chain, package/gluon-ebtables-source-filter/files/lib/gluon/ebtables/110-local-forward-allow-arp, package/gluon-ebtables-source-filter/files/lib/gluon/ebtables/110-local-forward-allow-ipv4, package/gluon-ebtables-source-filter/files/lib/gluon/ebtables/110-local-forward-allow-ipv6, package/gluon-ebtables-source-filter/files/lib/gluon/ebtables/300-local-forward-rules
First draft to port ffho-ebtables-net-rules to Gluon
depends on #1016
fixes #541
decision needed:
**=> gluon-ebtables-source-filter it is**
`rule 'SOURCE -p IPv6 --ip6-src ::/128 --ip6-protocol ipv6-icmp --ip6-icmp-type 131 -j RETURN'`
`rule 'SOURCE -p IPv6 --ip6-src ::/128 --ip6-protocol ipv6-icmp --ip6-icmp-type 135 -j RETURN'`
`rule 'SOURCE -p IPv6 --ip6-src ::/128 --ip6-protocol ipv6-icmp --ip6-icmp-type 143 -j RETURN'`
instead of: `rule 'SOURCE -p IPv6 --ip6-src ::/128 -j RETURN'` **=> keep it as it is**
One can find the original package under the following links:
https://git.c3pb.de/freifunk-pb/ffho-packages/tree/master/ffho/ffho-ebtables-net-rules
https://github.com/FreifunkHochstift/ffho-packages/tree/master/ffho/ffho-ebtables-net-rules
=> [RFC] add package gluon-ebtables-source-filter

docs/index.rst
The current structure of the _gluon-web_ documents creates a very unintuitive menu on the left (see screenshot). And as "Config Mode" already exists we now have to sections with the same name. To solve this I merged it in one file.
I also added a missing link to the _gluon-ebtables-source-filter_ package which was only discoverable via the search function.
=> docs: improve sidebar structure

targets/ar71xx-generic
Fixes #1084
Hardware is very similar to Archer C5v1 and C7v2.
Tested factory install and autoupdater.
IBSS Mesh on 2.4 and 5 GHz is working fine.
The only Ethernet Port is used for config mode and afterwards handled
as WAN Port.
=> Add Support for TP Link RE 450

docs/site-example/site.mk
The comment had a typo, it was unclear to what it was referring and was positioned poorly.  
The new position is just slightly better, but everything else is fixed.
=> docs, site-example/site.mk: improve comment about variables

patches/openwrt/0098-udp-properly-support-MSG_PEEK-with-truncated-buffers.patch
Add upstream patch to fix CVE-2016-10229
This just adds a commit from upstream linux v3.18.45, which should fix CVE-2016-10229 (https://nvd.nist.gov/vuln/detail/CVE-2016-10229).
Before merging, this patch should get some testing. By now, I only checked that ar71xx-generic still builds - not even tried to flash the resulting firmware.
This patch _may_ also be necessary for master (LEDE), if there are any relevant architectures still using 3.18. Architectures using 4.4 should be fine, as it contains the fix since v4.4.21.
=> CVE-2016-10229: udp: properly support MSG_PEEK with truncated buffers

package/gluon-client-bridge/luasrc/lib/gluon/upgrade/300-gluon-client-bridge-network, package/gluon-core/luasrc/lib/gluon/upgrade/110-network
LEDE recently disabled multicast snooping by default:
https://git.lede-project.org/?p=project/netifd.git;a=commitdiff;h=52541140f8138e31958cdc3d7e42a4029fa6bbc9
Reenable it for Gluon as there have been no confirmed issues for
LEDE and no negative reports concerning Gluon v2016.2.x so far.
Closes #1025.
=> LEDE: reenable multicast snooping

docs/features/dns-cache.rst
Now its clear that upstreams severs normally means "community gateways".
=> better upstream server description

docs/index.rst, targets/ar71xx-generic
The Airgateway LR is the same device as the normal Airgateway but with an detachable antenna. The Pro version is a cheap dual band device with only one radio. By default it uses the 2.4GHz config für the community. 
Test Device: https://meshviewer.chemnitz.freifunk.net/#!v:m;n:0418d6e6ad0d
=> ar71xx: added profile for UBNT Airgateway Pro and alias for Airgateway LR

package/gluon-mesh-batman-adv/luasrc/lib/gluon/radvd/arguments
This allows us to resolve nextnode even if there is no upstream connection.
Also this allows us to use an ipv6 dns cache in l2 networks.
=> gluon-mesh-batman-adv: announce dns server if dns cache was configured

docs/site-example/site.conf, docs/user/site.rst
The SSID for the mesh network should be cryptic, otherwise some users will try to connect to that network and get a bad user experience.
=> DOCS: site-example with cryptic SSID for mesh

package/gluon-web-mesh-vpn-fastd/luasrc/lib/gluon/web/controller/admin/mesh_vpn_fastd.lua, package/gluon-web-network/luasrc/lib/gluon/web/controller/admin/network.lua, package/gluon-web-node-role/luasrc/lib/gluon/web/controller/admin/noderole.lua, package/gluon-web-private-wifi/luasrc/lib/gluon/web/controller/admin/privatewifi.lua
This will give some space to put new models between existing ones.
The new Order will be:
WLAN - Private WLAN - Network - Mesh VPN - Node role
=> Fix menu order in Advanced Settings

targets/ramips-rt305x
Add support for A5-V11, a cheap chinese miniature router sold as "Mini 3G/4G Router"
Was already supported by LEDE.
Tested with 11s, seems to work flawlessly with gluon.
=> ramips-rt305x: Add support for A5-V11

Makefile
`make gluon-release` can be used to discover the current release in scripts.
=> build: add gluon-release make target

targets/ar71xx-generic
This PR adds support vor the GL-AR300M. The device has two flash chips, a 16MB NOR flash and a 128MB NAND flash. Currently only the NOR flash can be used with LEDE (and therefore Gluon) as support for the NAND flash is still missing.
After I applied the settings in the config mode I got these errors:
However, everything seemed to be working fine after the node rebooted itself. It meshed instantly with my other node.
=> Add support for GL.INet GL-AR300M

Makefile, docs/dev/feature-flags.rst, docs/index.rst, docs/site-example/site.mk, docs/user/site.rst, package/features, scripts/features.sh
To reduce the number of packages that need to be listed in
GLUON_SITE_PACKAGES, this adds a new variable GLUON_FEATURES. Sets of
packages are enabled automatically based on the combination of listed
feature flags.
Site-specified package feeds can provide their own feature flag
definitions.
=> build: introduce GLUON_FEATURES

targets/brcm2708-bcm2710, targets/targets.mk
This device has built in wifi we should include it at least for experiments.
=> brcm2708: add target and platform for raspi3

targets/brcm2708-bcm2710
Should correct this issue:
```
Collected errors:                                                 
* check_data_file_clashes: Package wpad-mini wants to install file /scratch/hexa/build/gluon/lede/build_dir/target-arm_cortex-a53+neon-vfpv4_musl-1.1.16_eabi/linux-brcm2708_bcm2710/target-dir-2fbc7ff2/usr/sbi
n/hostapd                                              
But that file is already provided by package  * hostapd-mini
* opkg_install_cmd: Cannot install package wpad-mini.   
```
=> brcm2708: drop wpad-mini as it clashes with hostapd-mini

docs/features/dns-cache.rst
The next_node name should be a name with a dot in it to avoid (mobile) browsers interpreting "nextnode" as searchphrase. (You need to enter http://manually.. nobody wants this ;)
Another suggestion was to change it to gluon.nextnode, but that would be longer,
=> Update dns-cache.rst: name should contain a dot.

package/gluon-mesh-vpn-fastd/src/respondd.c
=> gluon-mesh-vpn-fastd: make respondd module compile again

package/gluon-web-theme/sass/cascade.scss
With the limited `width` selectboxes did not resize to the maximum width if there were options that are longer than 20em
=> config allow more width in style for input fields and selectboxes

docs/site-example/site.conf, docs/user/faq.rst, docs/user/site.rst
It is known that a fastd MTU of 1280 bytes will cause excessive fragmentation for full packets on networks that advertise to transport payloads of 1280 bytes, because it neglects the headers that are being added by the batman-adv encapsulation.
The following graphic is widely recognized as factually correct and it depicts this issue quite well.
I therefore think the default documentation should reflect this by at least recommending a MTU value that allows for unfragmented IPv6 communication to pass the network, decreasing the burden on all of our embedded routers.
This will in turn allow new communities, who certainly heavily rely on gluons documentation, to make better choices when setting up their networks.
Thanks to @ohrensessel and others who didn't let the MTU discussion die, so we …
=> docs: fastd: recommend better default mtu

targets/ramips-mt7621
This PR adds support for the ZBT-WG3526 to the ramips-mt7621 target
> Dual-Band Router
> CPU: MediaTek MT7621AT (2* 880MHz)
> RAM: 512 MB
> Flash: 16 MB
> Wifi 1: MT7603E 2x2 2.4Ghz bgn
> Wifi 2: MT7612E 2x2 5GHz an+ac
> NET: 5x 10/100/1000 Mbps Ethernet
> 4 external antennas (2 for each band)
> USB3 port
i did a build and run test.
this patch could be easily cherry-picked to the v2017.1.x branch
this PR is closely related to #962, which is about the 32MB version of this device
=> ramips-mt7621: add support for ZBT-WG3526

docs/user/site.rst
Backport to v2017.1.x
(cherry picked from commit 56d74e41c1c24421dae8799bc03811966d38dee0)
=>  docs: update ffho site repo

targets/ramips-rt305x
We have an ISP around Chemnitz who gave out these routers years ago. We got a request to support these for freifunk. Here it is: http://map.chemnitz.freifunk.net/#!v:m;n:002401c1a16c
=> ramips-rt305x: add D-Link DIR-615 rev D1-D4

package/gluon-web-network/i18n/de.po, package/gluon-web-network/i18n/fr.po, package/gluon-web-network/i18n/gluon-web-network.pot, package/gluon-web-network/luasrc/lib/gluon/web/model/admin/network.lua
Naming of POE passthroug section changed from `gpio_switch_poe_passthrough` (in OpenWRT) to `poe_passthrough` (in Lede). Therefore it is not possible to enable POE passthroug on a node which was initaly setup with Lede based gluon. (This is a bug in v2017.1.x)
This pull request fixes that issue and prepares `gluon-web-network` for future devices like the ubnt-erx-sfp, which has multiple POE ports.
=> [RFC] gluon-web-network: make poe_passthrough more generic

package/gluon-respondd/src/respondd.c
This will add the current time to the respondd-provided data.
This will make sure we can detect from outside if a node has issues synchronizing its time.
=> add current unix time to respondd statistics

package/gluon-respondd/luasrc/lib/gluon/upgrade/400-respondd-firewall
at the moment the rule is broken because it refers to a zone that does not exist meaning that respondd cannot be queried directly from the client-zone.
This PR changes that.
=> gluon-respondd: firewall should allow access for devices in zone local_client

modules
this will allow us to build master again.
=> modules: update url to lede-project git repository after upstream move

modules
due to the LEDE / OpenWRT merge the original chaos calmer branch was moved to a separate git repository. this commit updates the url to fix the build process
=> modules: update url to chaos calmer git repository after upstream move

package/gluon-core/luasrc/lib/gluon/upgrade/010-primary-mac, patches/lede/0046-ar71xx-add-support-for-TP-LINK-Archer-C7-v4.patch, patches/lede/0047-ar71xx-fix-TP-Link-Archer-C7-v4-switch-LEDs.patch, patches/lede/0048-ar71xx-fix-Archer-C7-5GHz-MAC-address.patch, targets/ar71xx-generic
This adds support for the TP-Link Archer C7 v4.
Device has no known issue with Gluon. Example Device in the Darmstadt network: https://meshviewer.darmstadt.freifunk.net/#/en/map/50c7bffeba88
closes #1252
=> ar71xx: add support for Archer C7 v4

package/gluon-core/luasrc/lib/gluon/upgrade/010-primary-mac, patches/lede/0050-ar71xx-add-support-to-TP-Link-Archer-C59v1-and-C60v1.patch, patches/lede/0051-ar71xx-fix-lan-ports-on-archer-C59-and-C60.patch, patches/lede/0052-ar71xx-add-support-for-TP-Link-Archer-C58-v1.patch, patches/lede/0053-ath10k-firmware-update-repository.patch, patches/lede/0054-ath10k-firmware-add-qca9888-firmware.patch, patches/lede/0055-ar71xx-fix-board.bin-used-by-QCA9886-in-Archer-C58-C59-C60.patch, patches/lede/0056-ar71xx-Archer-C58-C59-C60-fix-qca9886-wireless-interface.patch, patches/lede/0057-ath10k-firmware-qca9888-firmware-remove-board.bin.patch, patches/lede/0058-ar71xx-C58-C59-fix-LAN1-working-incorrectly.patch, patches/lede/0059-ar71xx-omit-VLAN-from-Archer-C58-C59-LAN-interface.patch, patches/lede/0060-ar71xx-increase-kernel-partition-size-for-some-TP-Link-boards.patch, targets/ar71xx-generic
Reopened due to accidental branch-deletion, see #1275 
This adds support for Archer C58/C59/C60.
Archer C58/C60 marked as broken, due to frequent crashing on activated 5GHz related to insufficient RAM. Working fine with disabled 5GHz.
Archer C59 not affected (128MB instead of 64MB RAM)
closes #1122
Currently not working:
- IBSS meshing on 5GHz (possibly fixed in my ibss branch, needs testing)
=> ar71xx: add support for Archer C58/C59/C60

patches/lede/0064-ramips-mtd-spi-nor-add-support-for-switching-between-3-byte-and-4-byte-addressing-on-w25q256-flash.patch, patches/lede/0065-ramips-prepare-ZBT-WG3526-for-hardware-variants.patch, patches/lede/0066-ramips-rename-Digineo-AC1200-Pro-to-ZBT-WG3526-32MB.patch, targets/ramips-mt7621
Depends on #1300.
As I don't have one of those devices, please consider this as untested.
Unfortunately I grasped a similar patch exists in #962 ~which might even be identical~ too late. 
The general flash issue (32MB) was discussed [here](https://gist.github.com/dmke/d389bc364b3f73f525076eaee0019dc1).
The resulting patch was following:
http://lists.infradead.org/pipermail/linux-mtd/2016-December/070889.html
[Another patch](https://github.com/lede-project/source/commit/22d982ea003360d86ff1fef5114fb41dfa09ce9b#diff-3835f027e16e6416090c1833bc732af3) by nbd168 added the required mtd read operations for supporting ZBT-WG3526-32M and Digineo AC1200 Pro.
~This patch hopefully also resolves the [mt76](https://github.com/openwrt/mt76/issues/62) issue by bumping it to a new version.~ (Patch split …
=> mt7621: Add support for ZBT-WG3526-32M

targets/sunxi, targets/targets.mk
Since the crashes described in https://github.com/freifunk-gluon/gluon/issues/680 are fixed I tested all three Banana Pi Models and everything looks fine. As the WiFi chip of the Pro model is not supported and IBSS/11s is not working with the R1 Model they are still marked as BROKEN.
=> sunxi: LeMaker Banana Pi: remove BROKEN

package/gluon-core/luasrc/lib/gluon/upgrade/220-interface-lan
When running gluon-reconfigure (and not upgrading from 2017.1.x) the removed line leads to legacy=0.
fixes #1322
=> gluon-core: fix issue with legacy mesh on mesh_lan

package/gluon-ebtables-limit-arp/Makefile, package/gluon-ebtables-limit-arp/files/etc/init.d/gluon-arp-limiter, package/gluon-ebtables-limit-arp/files/lib/gluon/ebtables/100-arp-limit-chains, package/gluon-ebtables-limit-arp/files/lib/gluon/ebtables/320-arp-limit-rules, package/gluon-ebtables-limit-arp/src/LICENSE, package/gluon-ebtables-limit-arp/src/Makefile, package/gluon-ebtables-limit-arp/src/addr_store.c, package/gluon-ebtables-limit-arp/src/addr_store.h, package/gluon-ebtables-limit-arp/src/gluon-arp-limiter.c, package/gluon-ebtables-limit-arp/src/gluon-arp-limiter.h, package/gluon-ebtables-limit-arp/src/lookup3.c, package/gluon-ebtables-limit-arp/src/lookup3.h, package/gluon-ebtables-limit-arp/src/mac.c, package/gluon-ebtables-limit-arp/src/mac.h, patches/lede/0061-kernel-bridge-ebtables-Avoid-resetting-limit-rule-state.patch
This package adds filters to limit the amount of ARP Requests
devices are allowed to send into the mesh. The limits are 6 packets
per minute per client device, by MAC address, and 1 per second per 
node in total.
A burst of up to 50 ARP Requests is allowed until the rate-limiting
takes effect (see --limit-burst in the ebtables manpage).
Furthermore, ARP Requests with a target IP already present in the 
batman-adv DAT Cache are excluded from the rate-limiting,
both regarding counting and filtering, as batman-adv will respond
locally with no burden for the mesh. Therefore, this limiter
should not affect popular target IPs, like gateways.
However it should mitigate the problem of curious people or
smart devices scanning the whole IP range. Which could create
a significant amount of overhead …
=> gluon-ebtables-limit-arp: a package for ARP rate-limiting

package/gluon-l3roamd/files/etc/init.d/gluon-l3roamd, package/gluon-l3roamd/luasrc/lib/gluon/upgrade/380-gluon-l3roamd-route
Also this means we are not using special routing tables any more.
l3roamd now cleans up after itself.
=> This will adjust the l3roamd startup parameters to the latest l3roamd needs

package/gluon-client-bridge/luasrc/lib/gluon/upgrade/310-gluon-client-bridge-local-node, package/gluon-mesh-batman-adv/luasrc/lib/gluon/upgrade/320-gluon-mesh-batman-adv-client-bridge
This patch moves the prefix4 subnet route from the local-node veth
device to br-client (while keeping the next node ipv4 address on the
local node device).
This is in preparation to allow routing over the br-client interface
later.
=> gluon-client-bridge: move IPv4 local subnet route to br-client

docs/index.rst, targets/ar71xx-generic
Add alias for Ubiquiti unifi AP AC LR
close #1114
=> ar71xx-generic: set unifi-ac-lr alias on ac-lite

package/gluon-config-mode-hostname/i18n/de.po, package/gluon-config-mode-hostname/i18n/fr.po, package/gluon-config-mode-hostname/i18n/gluon-config-mode-hostname.pot, package/gluon-config-mode-hostname/luasrc/lib/gluon/config-mode/wizard/0100-hostname.lua
Maybe I can also get the name of the community in a variable? And is there a way to get the ssid here? So I could write this also in the hint.
This is just a first stub, I will enhance this later. also in the english version then.
=> gluon-config-mode-hostname: clarify the use of the nodename

patches/packages/routing/0003-batman-adv-multicast-TT-fixes-and-cleanups.patch
The first one adds a fix that might potentially result in multicast packet
loss once we would enable multicast_mode again.
The second one avoids some small but unnecessary overhead. More
importantly though, it is supposed to ease further multicast improvements
later (e.g. no need for a multicast sending node to determine overlap
between WANT_ALL_IPV4/6 flags and TT entries while on fast-path).
=> batman-adv: multicast TT fixes and cleanups

package/gluon-ebtables-limit-arp/src/gluon-arp-limiter.c, package/gluon-ebtables-limit-arp/src/mac.h
With the batman-adv multicast support compiled back in again we end up
with multicast addresses in the batman-adv translation table.
Currently we wrongly interpret multicast addresses returned by TT as a
unique host, too, which adds them with a source address filter to
ebtables as well. However, the source address of an ethernet frames is
never supposed to be a multicat one.
This leads to unnecessary entries in ebtables. Fixing this by ignoring
those MAC addreses returned by TT which have the multicast bit set.
=> gluon-ebtables-limit-arp: do not add multicast addresses to filter

targets/x86-64, targets/x86-generic
as we have enough space on x86 devices (but no individual profiles) i'd like to add some packages to the x86 target which are useful especially for the pcengines APU2 device.
those are build and run tested on this device.
i'm not really interested in discussions about single packages, so please just name the ones i have to remove from the pull request, if you have doubts about some.
=> x86: add packages: leds, sensors, gpio, usb, wifi and tools

package/gluon-respondd/src/respondd.c
This commit adds information about:
- how cpu time is spent since boot in jiffies (1/100*sek) (cpu)
- the value is summed for all cores, so in 10 seconds the
summed values will increase by 4000, if the cpu has
4 cores
- context switches since boot (ctxt)
- interrupt counters since boot (intr, softirq)
- forks since boot (processes)
``` json
{ "stat": {
"cpu": {
"user": 219403,
"nice": 1714,
"system": 75159,
"idle": 2727739,
"iowait": 2943,
"irq": 0,
"softirq": 571
},
"intr": 8426340,
"ctxt": 50992590,
"processes": 10549,
"softirq": 5161884
} }
```
=> gluon-respondd: add information from /proc/stat to "statistics"

docs/index.rst
This PR adds 2 devices to the docs that were recently added.
Devices are:
- GL Innovations GL-AR300M
- Ubiquiti UniFi AC Mesh
- TP-Link TL-WR940N v5
- TP-Link TL-WR1043N/ND
=> v2017.1.x: docs: add missing devices

docs/index.rst
there are some devices which we already support for a while but aren't mentioned in the list of supported devices.
these are devices which don't support IBSS, but only 802.11s based meshing
EDIT: update description of this PR to match it's current content.
some comments in this PR might relate to its old description
=> Hardware docs

docs/index.rst, patches/lede/0085-ar71xx-add-support-for-TP-Link-TL-WR940N-v6.patch, targets/ar71xx-tiny
This PR backports support for TP-Link TL-WR940N v6 to master.
As of now, this PR is untested, as my device is still on its way.
=> ar71xx: add support for TP-Link TL-WR940N v6

package/gluon-config-mode-mesh-vpn/luasrc/lib/gluon/config-mode/reboot/0100-mesh-vpn.lua
This commit adds the ability to show information about the platform on
config-mode reboot.
This can be used to integrate the model in the displayed key-message.
=> gluon-config-mode: add platform on config-mode reboot

docs/index.rst, patches/lede/0086-ar71xx-set-status-led-for-the-gl-boards.patch, patches/lede/0087-ar71xx-add-support-for-GL.iNet-GL-AR750.patch, patches/lede/0088-uboot-envtools-add-support-for-GL.iNet-GL-AR750.patch, targets/ar71xx-generic
This PR backports hw support for GL.iNet GL-AR750.
The backport against 2017.1.x got already tested by @Commifreak and he will test this patchset asap. As of now, this is should be seen as untested until he reports back.
Fixes #1378
=> ar71xx-generic: Add support for GL.iNet GL-AR750

docs/index.rst, package/gluon-core/luasrc/lib/gluon/upgrade/010-primary-mac, patches/lede/0044-ar71xx-add-support-for-TP-LINK-Archer-C7-v4.patch, patches/lede/0045-ar71xx-fix-TP-Link-Archer-C7-v4-switch-LEDs.patch, patches/lede/0046-ar71xx-fix-Archer-C7-5GHz-MAC-address.patch, targets/ar71xx-generic
Backports support for WR1043N v5, Archer C7 v4 and patches for QCA953x/956x rx buffer stalls to v2017.1.x.
=> v2017.1.x: Backport support for Archer C7 v4

docs/index.rst, patches/lede/0047-ar71xx-add-support-for-TP-Link-TL-WR940N-v6.patch, targets/ar71xx-tiny
This PR backports support for TP-Link WR940n ~~v5 &~~ v6 to v2017.1.x.
~~v5 just adds an alias to v4. The commit got cherry-picked from master.~~
v6 got backported from openwrt master.
My v6 device is still on its way, thus meaning this PR is untested as of now.
=> v2017.1.x: Add support for TP-Link WR940n v6

docs/index.rst, patches/lede/0048-ar71xx-set-status-led-for-the-gl-boards.patch, patches/lede/0049-ar71xx-add-support-for-GL.iNet-GL-AR750.patch, patches/lede/0050-uboot-envtools-add-support-for-GL.iNet-GL-AR750.patch, targets/ar71xx-generic
This PR backports hw support for GL.iNet GL-AR750 to v2017.1.x.
This PR got already tested by @Commifreak as can be seen in ticket #1378. The master backport still awaits his testing.
=> 2017.1.x: ar71xx-generic: Add support for GL.iNet GL-AR750

patches/lede/0085-ar71xx-add-support-for-TP-Link-TL-WR940N-v6.patch, patches/lede/0086-ar71xx-set-status-led-for-the-gl-boards.patch, patches/lede/0087-ar71xx-add-support-for-GL.iNet-GL-AR750.patch
I forgot to run "make update-patches" after rebasing.
This PR fixes the indexes and line numbers of the patch files in question.
=> Fix lede patch indexes and line numbers

patches/lede/0044-ar71xx-add-support-for-TP-LINK-Archer-C7-v4.patch, patches/lede/0047-ar71xx-add-support-for-TP-Link-TL-WR940N-v6.patch, patches/lede/0048-ar71xx-set-status-led-for-the-gl-boards.patch, patches/lede/0049-ar71xx-add-support-for-GL.iNet-GL-AR750.patch
I forgot to run "make update-patches" after rebasing.
This PR fixes the indexes and line numbers of the patch files in question.
=> v2017.1.x: Fix lede patch indexes and line numbers

patches/lede/0089-ar71xx-add-model-detection-for-UBNT-AC-Mesh.patch
This PR adds board detection for Ubiquiti AC Mesh devices.
This patch got applied to v2017.1.x already and I forgot to submit it to master as well.
=> ar71xx: add model detection for UBNT AC-Mesh

docs/index.rst, targets/ar71xx-generic
Adds support for Alfa AP121F USB powered travel router (looks like an USB ethernet adapter).
It has 16 MB flash and 64 MB memory and low power consumption. There is only a sysupgrade file for it. The description of the flashing procedure is in the commit message.
Everything seems to work and the primary MAC is correct, but maximum TX power is 17 dBm and wireless has 1x1 chains (max. 150 MBit/s).
The case be opened easily to access the UART interface.
=> ar71xx: add support for Alfa AP121F

patches/packages/routing/0002-batman-adv-Fix-best-gw-refcnt-after-netlink-dump.patch
This fixes a problem similar to the one described in #1258.
This patch will not apply on 2017.1.x. An adjusted version can be found in https://github.com/FreifunkVogtland/gluon/tree/batadv/gw_refcnt_fix-2017.1.x
----
A reference for the best gateway is taken when the list of gateways in the mesh is sent via netlink. This is necessary to check whether the currently dumped entry is the currently selected gateway or not. This information is then transferred as flag BATADV_ATTR_FLAG_BEST.
After the comparison of the current entry is done, batadv_*_gw_dump_entry() has to decrease the reference counter again. Otherwise the reference will be held and thus prevents a proper shutdown of
the batman-adv interfaces (and some of the interfaces enslaved in it).
=> batman-adv: Fix best gw refcnt after netlink dump

patches/lede/0091-mac80211-initialize-sinfo-in-cfg80211_get_station.patch
Most of the implementations behind cfg80211_get_station will not initialize sinfo to zero before manipulating it. For example, the member "filled", which indicates the filled in parts of this struct, is often only modified by enabling certain bits in the bitfield while keeping the remaining bits in their original state. A caller without a preinitialized sinfo.filled can then no longer decide which parts of sinfo were filled in by cfg80211_get_station (or actually the underlying implementations).
cfg80211_get_station must therefore take care that sinfo is initialized to zero. Otherwise, the caller may tries to read information which was not filled in and which must therefore also be considered uninitialized. In batadv_v_elp_get_throughput's case, an invalid "random" expected throughput may …
=> mac80211: initialize sinfo in cfg80211_get_station

patches/lede/0051-mac80211-initialize-sinfo-in-cfg80211_get_station.patch
Most of the implementations behind cfg80211_get_station will not initialize sinfo to zero before manipulating it. For example, the member "filled", which indicates the filled in parts of this struct, is often only modified by enabling certain bits in the bitfield while keeping the remaining bits in their original state. A caller without a preinitialized sinfo.filled can then no longer decide which parts of sinfo were filled in by cfg80211_get_station (or actually the underlying implementations).
cfg80211_get_station must therefore take care that sinfo is initialized to zero. Otherwise, the caller may tries to read information which was not filled in and which must therefore also be considered uninitialized. In batadv_v_elp_get_throughput's case, an invalid "random" expected throughput may …
=> v2017.1.x: mac80211: initialize sinfo in cfg80211_get_station

docs/index.rst, patches/lede/0097-ar71xx-add-support-for-TP-Link-TL-WA901ND-v5.patch, targets/ar71xx-tiny
This PR backports support for TP-Link TL-WA901ND v5.
@MPW1412 wants to use some of those devices in his community and asked me if i could add support for it to gluon. One of his communitiy members tested the backport and i was told it's working fine.
This will be my last device backport for 2018.1, i promise :smile:
=> ar71xx: add support for TP-Link TL-WA901ND v5

docs/user/site.rst
We are moving stuff away from GitHub, therefore here the update url to our site repository.
=> docs: update site url for darmstadt

patches/packages/routing/0006-batman-adv-add-patches-from-2018.1-maint-2018-06-12.patch
* Avoid storing non-TT-sync flags on singular entries too
* Fix multicast TT issues with bogus ROAM flags
----
The cfg80211_get_station workaround was removed from this backport because gluon already contains the proper fix (#1421) in the mac80211 package. There are already two PRs in openwrt-routing for the next/master branch in gluon.:
* openwrt-routing master: https://github.com/openwrt-routing/packages/pull/385
* openwrt-routing openwrt-18.06: https://github.com/openwrt-routing/packages/pull/385
According to T_X, this PR is related to #1419
=> v2017.1.x: batman-adv: add patches from 2018.1-maint 2018-06-12

docs/index.rst, targets/ar71xx-nand
As promised no backport this time ;)
This device comes with OpenWrt by default, is supported for ages and has still [decent internals](https://openwrt.org/toh/hwdata/zyxel/zyxel_nbg6716_a01).
I've tested everything thats on the [proposed checklist](https://github.com/freifunk-gluon/gluon/issues/1434#issuecomment-399168117) except autoupdate. Filename looks good tho.
Test node can be found here: https://meshviewer.chemnitz.freifunk.net/#!v:m;n:5cf4aba7d9fd
=> ar71xx: add support for ZyXEL NBG6716

targets/ar71xx-generic
The dependency line was lost during the rebase of the current master version.
Fixes: 9d719a2e572c ("ar71xx: add support for OpenMesh A40/A60 (#1424)")
=> ar71xx: add ath10k packages for OpenMesh A40/A60

docs/index.rst, patches/lede/0098-ar71xx-disable-40Mhz-refclk-for-QCA953x.patch, patches/lede/0099-ar71xx-Add-TP-Link-Pharos-v2-board-detection.patch, patches/lede/0100-ar71xx-Add-support-for-TP-Link-CPE210-v2.patch, targets/ar71xx-generic
This is the backport of the work by @adrianschmutzler, @robimarko and me. The OpenWrt patches are 
* https://github.com/openwrt/openwrt/commit/b1d57dadb2da0e010e157fd2383523578c9dcc2e ("ar71xx: disable 40Mhz refclk for QCA953x")
* https://github.com/openwrt/openwrt/commit/2524febf7927a1bf430d64b7790feb126023e3d1 ("ar71xx: Add TP-Link Pharos v2 board detection")
* https://github.com/openwrt/openwrt/commit/5c5bf8b8658a588423f6ec445d7ef6a36f99a396 ("ar71xx: Add support for TP-Link CPE210 v2")
=> ar71xx: Add support for TP-Link CPE210 v2

docs/user/getting_started.rst
With all the packages being built it seems that 10GB are not enough anymore.
This commit increases the recommendation for reserved disk space
for each target to a generally required free disk space size of 5GB
with additionally required 10GB per target.
=> docs: increase recommended disk space

docs/features/private-wlan.rst
@rotanid noticed that a command  is missing in the docs to set the MAC address of the private WLAN when it is being configured manually. 
This commit adds the missing command to set the special Gluon MAC address of the private WLAN interface to the documentation.
=> docs: private-wlan: add uci command to set MAC

docs/releases/v2018.1.rst
The release notes for v2018.1 state that the _Lambo R1_ is now a stable/supported model but it should be the _Banana Pi (M1)_. I also set the brand to _LeMaker/SinoVoip_ as it is sold by two different companies.
=> docs: fix wrong Banana Pi model in v2018.1 release notes

targets/ar71xx-generic
Support is marked as broken because this device is sold in two variants,
one with 64M RAM and another with 128M. As of now 64M is not enough
for ath10k with 5GHz enabled.
As there is no indication known which variant one will get better mark
it as broken.
=> ar71xx: add support for TP-Link RE355

docs/index.rst, package/gluon-core/luasrc/lib/gluon/upgrade/010-primary-mac, scripts/update-patches.sh, targets/ipq40xx, targets/targets.mk
This PR adds support for the new IPQ40xx series of internet processors from Qualcomm.
Note that this PR is not ready for merging. Following things need to be done to fully support Gluon features:
Fritz!Box 4040
```
root@64367-fritzbox:~# lua -e 'print(require("platform_info").get_image_name())'
avm-fritz-box-4040
```
GL-iNet B1300
```
root@64367-ranzbox:~# lua -e 'print(require("platform_info").get_image_name())'
gl.inet-gl-b1300
```
NETGEAR EX61xxV2
```
root@64367-brick:~# lua -e 'print(require("platform_info").get_image_name())'
netgear-ex6150v2
```
ZyXEL NBG6617
```
root@64xxx-b8eca3d6884c:~# lua -e 'print(require("platform_info").get_image_name())'
zyxel-nbg6617
```
ZyXEL WRE6606
```
root@61381-wireless-ranz-extender:~# lua -e 'print(require("platform_info").get_image_name())' …
```
=> ipq40xx: add target

package/gluon-client-bridge/luasrc/lib/gluon/upgrade/310-gluon-client-bridge-local-node, package/gluon-mesh-batman-adv/files/lib/gluon/ebtables/250-next-node, package/gluon-mesh-batman-adv/luasrc/lib/gluon/upgrade/320-gluon-mesh-batman-adv-client-bridge
The commit b3762fc61cca ("gluon-client-bridge: move IPv4 local subnet route to br-client (#1312)") moves the IPv4 prefix from the local-port interface to br-client. A client requesting an IPv4 connection to the IPv4 anycast address of the node (the device running gluon) will create following packets:
1. ARP packet from client to get the MAC of the mac address of the anycast IPv4 address
2. ARP reply from node to client with the anycast MAC address for the IPv4 anycast address
3. IPv4 packet from client which requires reply (for example ICMP echo request)
4. ARP request for the client MAC address for its IPv4 address in prefix4 (done with the mac address of br-client and transmitted over br-client)
5. IPv4 packet from node (transmitted over br-client with br-client MAC address) as reply …
=> Filter IPv4 anycast specific ARP packets from/to bat0 and always use anycast MAC address for them

package/gluon-client-bridge/luasrc/lib/gluon/upgrade/310-gluon-client-bridge-local-node, package/gluon-mesh-batman-adv/files/lib/gluon/ebtables/250-next-node, package/gluon-mesh-batman-adv/luasrc/lib/gluon/upgrade/320-gluon-mesh-batman-adv-client-bridge
The commit b3762fc61cca ("gluon-client-bridge: move IPv4 local subnet route to br-client (#1312)") moves the IPv4 prefix from the local-port interface to br-client. A client requesting an IPv4 connection to the IPv4 anycast address of the node (the device running gluon) will create following packets:
1. ARP packet from client to get the MAC of the mac address of the anycast IPv4 address
2. ARP reply from node to client with the anycast MAC address for the IPv4 anycast address
3. IPv4 packet from client which requires reply (for example ICMP echo request)
4. ARP request for the client MAC address for its IPv4 address in prefix4 (done with the mac address of br-client and transmitted over br-client)
5. IPv4 packet from node (transmitted over br-client with br-client MAC address) as reply …
=> 2018.1.x: Filter IPv4 anycast specific ARP packets from/to bat0 and always use anycast MAC address for them

docs/index.rst, targets/ramips-mt76x8
This PR adds support for TP-Link Archer C50 v3.
TP-Link Archer C50 v3
```
root@64367-mediadreck:~# lua -e 'print(require("platform_info").get_image_name())'
tp-link-archer-c50-v3
```
=> ramips: add support for TP-Link Archer C50 v3

docs/index.rst, targets/ramips-mt76x8
This PR adds support for TP-Link TL-WR841N v13.
Note that this PR is not ready for merging. Following things need to be done to fully support Gluon features:
TP-Link TL-WR841N v13 #1392 (calling everyone!)
=> ramips: add TP-Link TL-WR841N v13

package/gluon-web-admin/files/lib/gluon/config-mode/view/admin/info.html, package/gluon-web-admin/i18n/de.po, package/gluon-web-admin/i18n/fr.po, package/gluon-web-admin/i18n/gluon-web-admin.pot
This will enable the communities to add links to their build structure and repositories to the info page.
(Tested on a build on tag 2018.1.x)
=>  gluon-web-admin: add site-commit to info page 

targets/ar71xx-generic
- removes cryptic debug messages from kernel ring buffer and
- reduces memory usage by as much as 20-25 MiB 
resolves #1495
=> ar71xx-generic: prefer kmod-ath10k for 802.11s mesh

docs/index.rst
Addition of the OCEDO Koala to the supported devices in the docs was
forgotten in 52bc028.
=> docs: add OCEDO Koala to supported devices

package/gluon-respondd/src/respondd.c, package/gluon-status-page/javascript/status-page.js
This commit changes the way gluon estimates memory-usage on the status-page. Currently memory consumption in percent gets calculated using
> MEM = 1-(free+cached+buffers)/total
This commit (https://github.com/torvalds/linux/commit/34e431b0ae398fc54ea69ff85ec700722c9da773) suggests that this might not the best way to calculate such an estimation.
**TL-MR3020 v1**
```
MemTotal:          27368 kB
MemFree:            4508 kB
MemAvailable:       8368 kB
Buffers:            1940 kB
Cached:             4108 kB
```
Old: `1-((4508+1940+4108)/27368) = 61.42%`
New: `1-(8368/27368) = 69.42%`
**TL-WR1043 v3**
```
MemTotal:          60000 kB
MemFree:           29280 kB
MemAvailable:      23388 kB
Buffers:            2672 kB
Cached:             4108 kB
```
Old: `1-((29280+2672+4108)/60000) = 39.90%` …
=> [RFC] gluon-status-page: update memory usage estimation

targets/targets.mk
=> ipq806x: mark as broken because of unstable wifi drivers (v2018.1.x)

docs/index.rst, targets/ar71xx-generic
This adds the AVM FRITZ!WLAN Repeater 450E. (QCA9556/16M/64M)
The two patches are needed to circumvent the SOCs hardware bug described [here](https://git.openwrt.org/?p=openwrt/openwrt.git;a=commit;h=f4f99ec9737c653815268f2efad0210caaa32e2d).
In case @NeoRaider sees a success chance in backporting these two needed patches to 18.06, we can also try to go that route to not add kernel patches.
Personally i think these devices are perfectly fine (although i wouldn't pick them as "recommended") as people tend to have these kind of devices lying around.
Hardware wise, except for the RSSI LEDs everything is working fine (WPS button, other LEDs, ethernet, wifi).
```
root@64293-switchboard2:~# lua -e 'print(require("platform_info").get_image_name())'
avm-fritz-wlan-repeater-450e …
```
=> ar71xx: add AVM FRITZ!WLAN Reapeater 450E

package/features
This MR is an alternative idea for #1418
The gluon-ebtables-limit-arp is selected as default when the batman package is selected.
For communities who don't want this package, the can deselect it as described below:
```
GLUON_SITE_PACKAGES := \
-gluon-ebtables-limit-arp
```
=> package/features: add gluon-ebtables-limit-arp on batman packages as Opt out

docs/user/site.rst
Latitude and longitude was swapped and the example Layer URL is not reacheable so it should be set in comments.
=> docs: enhance  example values for gluon-config-mode-geo-location-osm

docs/user/site.rst, package/gluon-config-mode-hostname/check_site.lua, package/gluon-config-mode-hostname/luasrc/lib/gluon/config-mode/wizard/0100-hostname.lua
Before 7827f89, mandatory hostname field in config mode was pre-filled with the default hostname.
This commit adds the config_mode.hostname.prefill option for controlling the default value.
=> gluon-config-mode-hostname: add option to use default hostname

targets/targets.mk
The MT76x8 is currently not stable enough for worry-free use with Gluon.
It suffers from reboots in intervals as little as 12 hours or WiFi
freezes for several hours.
It may be unflagged as soon the situation with mt76 got better.
=> mt76x8: flag target as broken

patches/lede/0102-ar71xx-flag-FritzBox-4020-buttons-as-active-low.patch
This is a pull request for the current Gluon stable branch. It is not against Gluon master as @NeoRaider might want to consider cherry-picking this commit for the openwrt-18.06 branch, making a downstream patch obsolete.
---
Buttons of AVM FritzBox 4020 are incorrectly flagged as active high.
This was an oversight as RFKill button was working as expected even
with incorrectly flagged GPIO.
Config mode is still accessable but will start on any button press, not
only for the ones >= 10 seconds.
This commit corrects this behavior to the expected one (10 second long
press necessary to enter config mode).
=> ar71xx: flag FritzBox 4020 buttons as active low

modules
8baadecb16 ar71xx: flag FritzBox 4020 buttons as active low
cd12c91dde kmod-sched-cake: don't gso fixup on fixed kernels
670f14ce67 kerneL: bump 4.14 to 4.14.73
23bd33c5a3 kernel: bump 4.9 to 4.9.130
2163b4936e mt76: update to the latest version, fixes mt76x2 beacon issue
b115fcaa86 mac80211: fix management frame protection issue with mt76 (and possibly other drivers)
Includes the 4020 buttons fix and the mt76 beacon issue for secondary vifs.
I already compiled and tested these changes on my DIR860L.
=> modules: update OpenWrt

targets/ar71xx-generic
This removes the BROKEN flag for the TP-Link TL-WR810N v1 as it is verified to be working by @Marssl78
Fixes #856
=> ar71xx: remove BROKEN flag for TL-WR810N v1

docs/index.rst, patches/openwrt/0012-ramips-fix-leds-on-GL.iNet-GL-MT300N-V2.patch, targets/ramips-mt76x8
I'm currently evaluating this device with a colleague and will update the checklist when I hear back from him.
https://meshviewer.darmstadt.freifunk.net/#/de/map/e4956e442864
---
- led mapping
- radio leds
=> mt76x8: add support for GL.iNet GL-MT300N-V2

docs/features/multidomain.rst
The page looked a bit strange with one line in bold and the list-items were moved more to the right than the others above.
=> docs: multidomain: fix indentation

package/gluon-core/Config.in
The redirect and dnat target are needed for gluon-alt-esc-client to forward frames to the selected, alternative gateways.
=> gluon-ebtables: build kernel with ebt_dnat and ebt_redirect

docs/features/autoupdater.rst, docs/features/multidomain.rst, docs/user/site.rst
Since https://gluon.readthedocs.io is always built on this branch, I think we should backport all fitting docs changes here too
=> docs: cherry-pick from master of all relevant changes for 2018.1.x

package/gluon-mesh-babel/src/respondd.c
Noticed the following issues with the help of cppcheck, not sure if these are 'real' issues or changing the code will break other things.
```
$ cppcheck --enable=all package/gluon-mesh-babel/src/respondd.c 
Checking package/gluon-mesh-babel/src/respondd.c ...
[package/gluon-mesh-babel/src/respondd.c:355] -> [package/gluon-mesh-babel/src/respondd.c:358]: (style) Variable 'uret' is reassigned a value before the old one has been used.
[package/gluon-mesh-babel/src/respondd.c:598]: (style) Unsigned variable 'total' can't be negative so it is unnecessary to test it.
[package/gluon-mesh-babel/src/respondd.c:562]: (error) Common realloc mistake: 'buf' nulled but not freed upon failure
(information) Cppcheck cannot find all the include files (use --check-config for details)
```
=> gluon-mesh-babel: fix several issues reported by cppcheck

docs/features/monitoring.rst, docs/releases/v2016.2.6.rst, docs/releases/v2016.2.rst, docs/releases/v2017.1.2.rst, docs/releases/v2017.1.3.rst, docs/releases/v2017.1.rst, docs/site-example/site.conf, docs/user/faq.rst, docs/user/getting_started.rst
* `wiki.openwrt.org` seems to redirecting to `https://oldwiki.archive.openwrt.org/` which is not usable, lately
* `https://git-scm.com/book/en/Git-Basics-Tagging` redirects to `https://git-scm.com/book/en/v2/Git-Basics-Tagging`
Q: not sure if we should keep the link or use version 2?
* Some links where upgraded to https
Q; Is that useful at all?
* Also noted some of the issues are linked as pull requests in the release notes or the other way round, e.g.
`https://github.com/freifunk-gluon/gluon/issues/1097` -> `https://github.com/freifunk-gluon/gluon/pull/1097` or
`https://github.com/freifunk-gluon/gluon/pull/864` -> `https://github.com/freifunk-gluon/gluon/issues/864`
Q: Should that be fixed?
=> docs: fix some old urls or 'upgrade' to https

package/gluon-core/luasrc/lib/gluon/upgrade/500-opkg
$VERSION_ID is a lowercase value
=> gluon-core: fix pattern %v in opkg URLs

package/gluon-mesh-babel/luasrc/lib/gluon/upgrade/300-gluon-mesh-babel-mkconfig
log-file /dev/stderr is broken for babeld as it eats log messages for debug log.
This commit gets rid of the option. This allows -d N to be used as babeld command
line option.
=> gluon-mesh-babel: remove broken log-file option from config

package/gluon-client-bridge/luasrc/lib/gluon/upgrade/300-gluon-client-bridge-network
Allow odhcp6c to fork the script to handle router
advertisments in 30 seconds intervals. This is the value
that was previously used in Gluon v2018.1 / LEDE 17.06.
The default value is 3 seconds and while it is RFC compliant
it can put alot of pressure on even moderately sized devices.
Signed-off-by: Martin Weinelt <martin@darmstadt.freifunk.net>
---
The following was observed on a CPE210 device. The load penalty occured when updating from v2018.1.x to master, the load fell when this changed was introduced.
=> gluon-client-bridge: set ra_holdoff interval to 30 seconds

CONTRIBUTING.md, README.md, docs/features/monitoring.rst
Update the readthedocs links to `https://gluon.readthedocs.io` and fix a broken alfred readme link
=> docs: update some old urls

docs/index.rst, patches/openwrt/0013-ar71xx-add-support-for-UniFi-AC-Mesh-Pro.patch, targets/ar71xx-generic
This PR adds proper support/detection for the UniFi AC Mesh Pro devices. These devices are hardware clones of the UniFi AC Pro but with an outdoor casing.
This PR is compile-tested only because I don't have a device on hand anymore. I've used the original backport successfully on 5 devices back in july last year though.
I will update the checklist from time to time once testusers report back:
- led mapping
- radio leds
- no radio ledss present
- no switch leds
[1]
`root@C-Henrietten24TestMeshPro:~# lua -e 'print(require("platform_info").get_ima
ge_name())'
ubiquiti-unifi-ac-mesh-pro`
Signed-off-by: Christoph Krapp <achterin@googlemail.com>
=> ar71xx: add support for UniFi-AC-Mesh-Pro

docs/user/getting_started.rst
I just followed this document on a Debian Stretch, and it worked out of
the box. So let's use Debian's current stable release here.
=> docs: getting_started: Update to Debian Stretch

docs/index.rst, targets/ar71xx-generic
- led mapping
- radio leds
[1] `root@nbg6616-test:~# lua -e 'print(require("platform_info").get_image_name())' 
zyxel-nbg6616`
Test device can be found here: http://[2001:bc8:3f13:ffc2:92ef:68ff:fe7e:ac3d]/cgi-bin/status
Signed-off-by: Christoph Krapp <achterin@googlemail.com>
=> ar71xx: add support for ZyXEL NBG6616

docs/index.rst, patches/openwrt/0012-ramips-mt7621-fix-5GHz-WiFi-LED-on-ZBT-WG3526.patch, targets/ramips-mt7621
- led mapping
- radio leds
to fix the devices 5GHz radio LED it needs three additional lines in the file `target/linux/ramips/dts/ZBT-WG3526.dtsi`
which i submitted as a patch upstream ( https://patchwork.ozlabs.org/patch/1018892/ )
=> ramips-mt7621: remove BROKEN flag for ZBT WG3526-16M & WG3526-32M

package/gluon-core/luasrc/lib/gluon/upgrade/200-wireless
This commit distributes dualband radios evenly on 2.4 GHz and 5GHz with 2.4 GHz being prioritised higher than 5 GHz.
This means in case a device has only a single radio and this radio supports operation in both bands, it will be set to 2.4 GHz.
#1604 depends on this PR
=> gluon-core: distribute dualband radios

docs/index.rst, targets/ar71xx-generic
Signed-off-by: Martin Weinelt <martin@darmstadt.freifunk.net>
Slight issue: The radio is dualband and is currently autoconfigured for 5 GHz. We are lacking a sane default and/or a toggle.
```
root@64283-fritz300e:~# uci show wireless
wireless.radio0=wifi-device
wireless.radio0.type='mac80211'
wireless.radio0.hwmode='11a'
wireless.radio0.path='pci0000:00/0000:00:00.0'
wireless.radio0.htmode='HT20'
wireless.radio0.country='DE'
wireless.radio0.channel='48'
wireless.mesh_radio0=wifi-iface
wireless.mesh_radio0.ifname='mesh0'
wireless.mesh_radio0.network='mesh_radio0'
wireless.mesh_radio0.device='radio0'
wireless.mesh_radio0.mesh_fwding='0'
wireless.mesh_radio0.mesh_id='ffda-mesh-dom1'
wireless.mesh_radio0.mcast_rate='12000'
wireless.mesh_radio0.mode='mesh'
wireless.mesh_radio0.disabled='0' …
```
=> ar71xx: add support for FRITZ!Repeater 300E

docs/index.rst, targets/ramips-mt76x8
This commit removes the broken flag from all devices in the mt76x8
subtarget.
The stability of the mt76 driver for the mt7628 and mt7612 has greatly
improved in the last half-year. It might be still behind ath9k and
ath10k but it is suitable for daily use.
This affects the following devices:
- GL.iNet MT300N v2
- TP-Link Archer C50 v3
- TP-Link TL-WR841 v13
=> ramips-mt76x8: remove broken flag

targets/ar71xx-generic
```
root@ffac-Bergdriesch-GL-AR750:~# lua -e 'print(require("platform_info").get_image_name())'
gl.inet-gl-ar750
```
Not sure if this is the way it should be fixed, but this way the manifest file is accepted by the autoupdater.
=>  ar71xx: fix incorrect gl-ar750 image name

package/gluon-core/luasrc/lib/gluon/upgrade/010-primary-mac
also sort by target and board_name
Tested on
```sh
root@64283-cccda-w:~# cd /lib/gluon/core/sysconfig
root@64283-cccda-w:/lib/gluon/core/sysconfi# cat primary_mac
f0:9f:c2:de:c4:c5
root@64283-cccda-w:/lib/gluon/core/sysconfig# cp primary_mac primary_mac.bak
root@64283-cccda-w:/lib/gluon/core/sysconfig# rm primary_mac
root@64283-cccda-w:/lib/gluon/core/sysconfig# /lib/gluon/upgrade/010-primary-mac 
root@64283-cccda-w:/lib/gluon/core/sysconfig# cat primary_mac
f0:9f:c2:dc:c4:c5
root@64283-cccda-w:/lib/gluon/core/sysconfig# mv primary_mac.bak primary_mac
```
This change only affects newly flashed devices.
fixes #1629
=> gluon-core: fix primary mac selection on unifiac devices

targets/x86-64, targets/x86-generic, targets/x86-geode
This allows for smaller firmware images and makes it possible to reset a
device via firstboot command.
closes #1596
=> target x86-*: change from ext4 to squashfs

README.md, docs/dev/basics.rst
I saw T_X referencing our chatroom in https://github.com/freifunk-gluon/gluon/pull/1201#issuecomment-460985739 and the documentation for it could benefit from some improvement to allow for easier onboarding.
=> docs: improve references to the IRC chatroom

targets/ar71xx-generic
In current Gluon versions the content of the manifest file does not match with the device identifier of a GL.iNet GL-AR150. To solve this issue the manifest content and device identifier must be correspond.
Solution:
This commit adjusted the GL-AR150 Gluon profile name which is used to refer to the device and image name.
=> ar71xx: fix incorrect GL.iNet image names

docs/index.rst, patches/openwrt/0012-tools-mktplinkfw2-add-split-uboot-layout.patch, patches/openwrt/0013-ramips-add-support-for-Archer-C50-v4.patch, targets/ramips-mt76x8
This backports the TP-Link Archer C50 v4.
We are dropping the following upstream commits. They add support for the
TP-Link recovery-flag which enabled the web-recovery. As they are not
needed for the router to work, we drop them for now.
28cd2ca base-files: sysupgrade: support additional mtd options
1e06482 mtd: add logic for TP-Link ramips recovery magic
----
```
root@64xxx-0c80637f6a04:~# lua -e 'print(require("platform_info").get_image_name())'
tp-link-archer-c50-v4
```
- led mapping
- radio leds
=> ramips-mt76x8: add support for TP-Link Archer C50 v4

targets/ramips-mt7620
This device is based on the MediaTek MT7620A with 580MHz, 16MB Flash and 64MB RAM. The radios are MediaTek MT7620A and MediaTek MT7610E. 
For now this device should remain as broken. The LED config is not correct and the 5GHz is not working. Test device: http://map.chemnitz.freifunk.net/#!v:m;n:708bcdea0a38
* wired network  
* led mapping
* radio leds
=> ramips-mt7620: add support for ASUS RT-AC51U as broken

patches/openwrt/0014-mac80211-ath10k-support-for-multicast-and-management-rate-control.patch, patches/openwrt/0015-ath10k-ct-support-for-multicast-and-management-rate-control.patch
Drivers with software rate control can directly use the selected multicast rate for multicast/broadcast frames and the minimal basic rate for management frames. But drivers with offloaded rate control algorithms must be informed about such upper layer decisions to configure the hardware/firmware.
A new BSS_CHANGED_MCAST_RATE is introduced in mac80211 to automatically inform all drivers. ath10k can detect this event and forward it via WMI to the driver. The already existing BSS_CHANGED_BASIC_RATES can be used to select the management rate.
Without the WMI commands, a low rate (not necessarily one from the basic rates) is used for bcast/mcast/management frames. This means that the /etc/config/wireless settings basic_rate and mcast_rate would have no effect on the rates selected by this …
=> ath10k/ath10k-ct: support multicast and management rate control

docs/features/multidomain.rst
The example to switch the domain via commandline doesn't commit the uci changes and a node would fall back to its previous domain after a reboot.
=> docs: missing uci commit in gluon-reconfigure example

package/gluon-core/luasrc/usr/lib/lua/gluon/util.lua
Disclaimer
----
We should not be affected by this bug yet as there are (on first sight) no affected MediaTek devices with the affected driver in Gluon. I ran into the Bug using an Archer C2 v2 on next.
Commit-message
----
Gluon has multiple ways to obtain unique MAC-addresses. They are either
provided by the WiFi driver or derived from the primary MAC-address.
Quoting the same file:
> It's necessary that the first 45 bits of the MAC address don't
> vary on a single hardware interface, since some chips are using
> a hardware MAC filter. (e.g 'rt305x')
This currently fails in case the rt35xx based chips mac address differs
from the primary MAC. In this case, the MAC address for the client0 radio
(vif 1) comes from the WiFi driver. As there is only a single
MAC-address provided by …
=> gluon-core: assert WiFi driver provides 4 MAC-addresses

docs/package/gluon-scheduled-domain-switch.rst, package/gluon-core/check_site.lua, package/gluon-core/luasrc/usr/lib/lua/gluon/util.lua, package/gluon-scheduled-domain-switch/Makefile, package/gluon-scheduled-domain-switch/check_site.lua, package/gluon-scheduled-domain-switch/luasrc/lib/gluon/upgrade/950-gluon-scheduled-domain-switch, package/gluon-scheduled-domain-switch/luasrc/usr/bin/gluon-check-connection, package/gluon-scheduled-domain-switch/luasrc/usr/bin/gluon-switch-domain, scripts/check_site.lua
This package allows to automatically switch to another domain, either at a given point in time or after the node was offline long enough.
It's primary goal is to allow for communities which still use IBSS to migrate over to 802.11s without having to run both protocols at the same time, which might lead to overloaded routers.
Depending how #1377 is scoped, this might close it.
=> gluon-scheduled-domain-switch: add package

docs/index.rst, patches/openwrt/0016-ramips-add-support-for-Netgear-R6120.patch, patches/openwrt/0017-tools-add-zip-utility.patch, patches/openwrt/0018-firmware-utils-add-sercomm-netgear-tool.patch, targets/ramips-mt76x8
MT7628/MT7612 based dualband-ac WiFi router. Very similar to the Archer C50 v3/v4 but with double the Flash (16MiB instead of 8 MiB).
This is also the first MT7628 based dualband device which can be flashed directly from the Vendor Web-Interface.
Price:
- [New: ~40€ ](https://geizhals.de/netgear-r6120-r6120-100pes-a1624501.html)
- [Refurbished (Amazon WHD): 30€](https://www.amazon.de/gp/offer-listing/B071HWVV5J/ref=dp_olp_used?ie=UTF8&condition=used)
-----
```
root@64xxx-b039560bc5ab:~# lua -e 'print(require("platform_info").get_image_name())'
netgear-r6120
```
- led mapping
(https://gluon.readthedocs.io/en/latest/features/configmode.html …
=> ramips-mt76x8: add support for Netgear R6120

contrib/sign.sh, contrib/sigtest.sh, docs/index.rst, docs/releases/v2017.1.3.rst, package/gluon-ebtables-limit-arp/src/lookup3.c, package/gluon-radv-filterd/src/gluon-radv-filterd.c
just some minor changes
* ecdsa utils new home (?) https://github.com/freifunk-gluon/ecdsautils
* update some urls by following 301 'moved permanently' redirects
* switch http to https
=> Minor changes of web references

package/gluon-mesh-batman-adv/src/respondd.c
Previously the content of "/proc/net/if_inet6" was parsed to acquire the
nodes IPv6 addresses. With this commit, IPv6 addresses are acquired
using getifaddrs() as proposed by neoraider in #1615.
Fixes  #1615
=> gluon-mesh-batman-adv: get IPv6-addresses via netlink

package/gluon-web-node-role/i18n/de.po, package/gluon-web-node-role/i18n/fr.po, package/gluon-web-node-role/i18n/gluon-web-node-role.pot, package/gluon-web-node-role/luasrc/lib/gluon/config-mode/model/admin/noderole.lua
By commit 91ae553c93670dcd1dca2f73466be960580a0231 the translation of the package `gluon-web-node-role` was adjusted but the change missed the source file `noderole.lua`, i guess.
In addition i noticed that the role descriptions from a site translation where not used at the config page, instead the id e.g. `gluon-web-node-role:role:node`, `gluon-web-node-role:role:backbone`, .. where displayed, only. (added `site_i18n` to fix that)
Also executed the following commands (mentioned in the docs https://gluon.readthedocs.io/en/latest/dev/web/i18n.html) to update the translation files. Those commands updated the line and string order of the pot file and po files but the text is untouched (not sure if those changes should be undone).
```
../../../contrib/i18n-scan.pl ../files ../luasrc > …
```
=> gluon-web-node-role: Fix i18n role translation

patches/openwrt/0019-ath10k-ct-fix-incorrect-multicast-broadcast-rate-setting.patch, patches/openwrt/0020-mac80211-ath10k-fix-incorrect-multicast-broadcast-rate-setting.patch
If no mcast_rate is set for the wifi-iface then there is no rate_idx (0)
set for the bss. This breaks for example 5GHz meshpoint interfaces because
0 maps to a CCK rate (11Mbit/s).
It must also be avoided that the ath10k-ct internal state for the rates is
not synced with the mac80211 rates state. Otherwise, the user specified
rate (e.g. a wifi-iface mcast_rate for a meshpoint interface) will only be
set on startup. And a short while after that, ath10k-ct specific code in
ath10k_check_apply_special_rates is missing a valid rate in its own
structures and is then recalculating a new default rate. This default rate
is in most situations not the requested rate.
Fixes: a399b607357b ("ath10k/ath10k-ct: support multicast and management rate control")
Forwarded: …
=> ath10k/ath10k-ct: fix incorrect multicast/broadcast rate setting

docs/index.rst
Can't find a device called Picostation M5. Only a Picostation M2 is available.
TL-WR710N v1, v2.1 are part of ar71xx-generic not ar71xx-tiny
```
$ grep wr710n targets/*
targets/ar71xx-generic:device tp-link-tl-wr710n-v1 tl-wr710n-v1
targets/ar71xx-generic:device tp-link-tl-wr710n-v2.1 tl-wr710n-v2.1
targets/ar71xx-tiny:device tp-link-tl-wr710n-v2 tl-wr710n-v2
```
=> docs: remove unavailable devices (Picostation M5 and TL-WR710N v1/v2.1)

docs/index.rst, targets/ar71xx-generic
* led mapping
* radio leds
Tested by Sebastian Schaper: (not running at the moment)
https://hannover.freifunk.net/karte/#/de/map/e46f132a097b
=> ar71xx: add support for D-Link DAP-1330

package/gluon-mesh-batman-adv/src/respondd.c
The amount of local wifi clients is currently counted by two different ways:
* asking the kernel wifi layer for the number of of clients on 2.4GHz and  5GHz band
* asking batman-adv for the number of non-timed out entries in the local translation table with WiFi flag
The number of wifi24+wifi5 and the number of TT wifi client counts are reported via respondd to various consumers. The ffrgb meshviewer is displaying these values as:
* 2,4 GHz: wifi24
* 5 GHz: wifi5
* other: (TT local wifi+non-wifi clients) - (wifi24 + wifi5)
But the local translation table is holding entries much longer than the wifi layer. It can therefore easily happen that a wifi client disappears in the kernel wifi layer and batman-adv still has the entry stored in the local TT.
The ffrgb meshviewer would then show this …
=> gluon-mesh-batman-adv: Only use local TT to count non-wifi clients

docs/dev/web/view.rst
the tag was added by dd23a805c2a1edf7f1df293dd03a542f3b2b3d9e
=> docs: add new <%| tag for escaped expressions

docs/index.rst
target ipq806x was marked as broken because of #1505 
target sunxi was renamed to sunxi-cortexa7 via 210d97c53eb147ad9519118634c71e28eace4694
=> docs: update targets

package/gluon-core/luasrc/lib/gluon/upgrade/010-primary-mac, targets/ipq806x, targets/targets.mk
```
root@64367-nighthawk-x4s:~# lua -e 'print(require("platform_info").get_image_name())'
netgear-nighthawk-x4s-r7800
```
- led mapping
- radio leds
=> ipq806x: add support for NETGEAR R7800

package/gluon-core/luasrc/lib/gluon/upgrade/010-primary-mac, targets/ramips-mt7620
Mesh is working but it depends on PR #1626 to get it working on both radios, without it only mesh on radio0 (the extra wifi chip) is working.
This is the cleaned up PR of #1627 
* There are two ways to flash. Both are written in the OpenWRT Wiki. One via an Code Injection Bug and one via an Account on miwifi.com
* https://openwrt.org/toh/xiaomi/mini#quick_openwrt_installation
* WiFi on 2.4GHz is Unstable most of the time for now.
* led mapping
* radio leds
* device has only one LED for power status
* device has only one LED for power status
* it just have …
=> ramips-mt7620: add support for Xiaomi MiWifi Mini

docs/user/faq.rst
A table with hardware supported by Gluon can be found on the OpenWrt Wiki. This commit adds a corresponding FAQ entry.
=> docs: faq: add note for supported hardware

package/gluon-mesh-batman-adv/src/respondd.c, package/gluon-status-page-mesh-batman-adv/src/neighbours-batadv.c
Links between two direct neighbors are not always the best route between
these devices. The flag BATADV_ATTR_FLAG_BEST would not be set for these
originator entries and the respondd module would just ignore this entry.
This causes missing links in meshviewer and similar tools. And when the
link quality is nearly equal and but fluctuates slightly, these links will
from time to time appear and disappear on the map.
Or ff these neighbors are not accepted and returned to the status page then
some of the neighbor entries will show a name, (acceptable) signal strength
and mac address but no TQ value.
=> gluon-*batman-adv: Also list neighbors with non-best direct link

package/gluon-config-mode-mesh-vpn/luasrc/lib/gluon/config-mode/wizard/0300-mesh-vpn.lua
fix limit_ingress default value in case of default disabled simple-tc for tunneldigger.
In case if 'limit_bw_down' set for tunneldigger should simple-tc still be enabled?
If simple-tc enabled by default via site.conf the script '500-mesh-vpn' from 'gluon-mesh-vpn-core' will set 'limit_ingress' to 0 and also enabled simple-tc. Does 0 have a special meaning in this situation like "ignore it"?
Bug appears here: #1460 
Related to #1447 
Thanks to @lrnzo 
Signed-off-by: Jan-Tarek Butt <tarek@ring0.de>
=> Bugfix: gluon-config-mode-mesh-vpn: 0300-mesh-vpn.lua limit_ingress 

docs/releases/v2018.2.rst
A diff might describe it better
https://github.com/freifunk-gluon/gluon/commit/210d97c53eb147ad9519118634c71e28eace4694#diff-0d44e6a3fa2aba2dc4a79afbfcc4ab1fR78
A cherrypick to v2018.2.x might be useful.
=> docs: add notice for opkg repo change

docs/index.rst, targets/ar71xx-tiny
TP-Link TL-WR840N v2: https://openwrt.org/toh/hwdata/tp-link/tp-link_tl-wr840n_v2
- led mapping
- radio leds
=> ar71xx: add support for TP-Link TL-WR840N v2

package/gluon.mk
The luci modules where updated (c919f5fd29aeb37e6a7a50d6834fa338e7328dfd)
And there is a luasrcdiet update included `b5d5e5bf1 luci-base: update luasrcdiet` (https://github.com/openwrt/luci/commit/b5d5e5bf13e572af7f1589a01bfd338691d5f063)
I noticed some `bash: LuaSrcDiet: command not found` in the `make V=s` output and updated the luasrcdiet call
Could someone check a Gluon build if the result of the luasrcdiet output is as expected?
=> gluon.mk: fix reference to LuaSrcDiet binary

targets/ipq40xx
product page: https://www.8devices.com/products/jalapeno
openwrt page: https://openwrt.org/toh/hwdata/8devices/8devices_jalapeno
usually means: gluon profile name must match image name
> root@testing-8devices-jalapeno:~# lua -e 'print(require("platform_info").get_image_name())'
> 	8devices-jalapeno
> device has no LEDs for that, only for ETH and serial interface
> device has no radio LEDs
> Device have 2 Buttons one is a hard reset Butten and the other is user defined.
Signed-off-by: Jan-Tarek Butt <tarek@ring0.de>
=> targets/ipq40xx: add support for jalapeno from 8devices

docs/user/getting_started.rst
GLUON_DEBUG was added by #1028 
Default setting: `GLUON_DEBUG ?= 0` faceb3932c741aec6314639164404e9c4d3fcd01
=> docs: add GLUON_DEBUG

patches/openwrt/0021-ramips-fix-R6120-factory-image.patch
The factory firmware omits the JFFS2 end-marker while flashing via
web-interface. Add a 64k padding after the marker fixes this problem.
When the end-marker is not present, OpenWRT won't save the overlayfs
after initial flash.
This patch is currently pending upstream (see https://patchwork.ozlabs.org/patch/1097561/)
This should probably also land in v2018.2.
=> ramips: fix R6120 factory image

package/gluon-config-mode-outdoor/luasrc/lib/gluon/config-mode/wizard/0250-outdoor.lua, package/gluon-core/luasrc/lib/gluon/upgrade/180-outdoors, package/gluon-core/luasrc/lib/gluon/upgrade/200-wireless
**gluon-config-mode gluon-core: fix incorrect gluon.platform reference**
The is_outdoor function is placed inside the gluon.platform module, not
the platform_info module. Currently, the outdoor-mode wizard component
and the upgrade script fail due to nil-value calls.
**gluon-core: fix mesh radios not being created**
This commit fixes a bug where on first setup, mesh interfaces won't be
created for 2.4GHz radios.
=> gluon-core gluon-config-mode: fix two bugs in WiFi configuration

package/gluon-l3roamd/Makefile
uc is used in the initscript. It must be set as dependency
=> gluon-l3roamd: add missing uc dependency

package/gluon-mesh-batman-adv/luasrc/lib/gluon/upgrade/310-gluon-mesh-batman-adv-mesh, patches/packages/routing/0003-batman-adv-update-to-current-openwrt-routing-batman-adv-v2019.2.patch
This updates the batman-adv OpenWrt package to the current version provided in the master branch of the openwrt-routing packages repository (minus config changes).
The second patch then enables the batman-adv multicast optimizations again.
=> batman-adv: update to current openwrt-routing / batman-adv v2019.2

package/gluon-mesh-vpn-core/luasrc/usr/bin/gluon-wan
./gluon-wan:25:1: (W122) setting read-only field ? of global arg
./gluon-wan:29:1: (W311) value assigned to variable ok is unused
=> gluon-mesh-vpn-core: fix luacheck warnings

package/gluon-core/luasrc/usr/lib/lua/gluon/platform.lua
The board names for CPE510, Nanostation Loco M5 and Nanostation M5 are incorrect.
I've personally verified the names against a CPE510 v1.1 and a Nanostation Loco M2 (XM).
Sorry for the mess.
=> gluon-core: fix outdoor board names

patches/packages/routing/0004-batctl-upgrade-package-to-latest-release-2019.2.patch
Tested with both batman-adv and batman-adv-legacy in an x86 VM setup.
=> batctl: upgrade package to latest release 2019.2

.luacheckrc
In the mumble developer meeting the lua linter `luacheck` was suggested for the CI pipeline.
As i played around with it, and already have some `.luacheckrc` snippets for Gluon i want to add the config file and try to fix warnings found by luacheck.
In the `check_site.lua` files the following issues where fixed
* `line is too long (137 > 120)` -> what is the maximum line length that should be used in Gluon? 120 is the default by luacheck
* `unused loop variable k, v` -> replaced by `_`
* `setting non-standard global variable from, to` -> add `local`
* `line contains trailing whitespace` -> removed
=> Add luacheck config

package/gluon-config-mode-mesh-vpn/luasrc/lib/gluon/config-mode/wizard/0300-mesh-vpn.lua, package/gluon-mesh-vpn-core/luasrc/lib/gluon/mesh-vpn/update-config, package/gluon-mesh-vpn-core/luasrc/lib/gluon/upgrade/500-mesh-vpn
More testing is welcome - in particular, I didn't do any actual testing with tunneldigger. Of course, migration from old configs needs to work correctly as well.
The first two commits should also be cherry-picked for v2018.2.x.
Fixes #1736.
=> gluon-mesh-vpn-core: move common VPN config to gluon UCI package

contrib/Dockerfile
This will be a useful precursor for continuous integration.
I'm running NixOS at home and I use this container to build OpenWrt and Gluon.
Once merged we should set up automatic builds in the Docker Hub.
=> Add minimal docker environment

docs/dev/basics.rst
I think on Docker hub we will test with Jenkins if the commit is valid and throw errors automatically. A user that want s to contribute should be able to do so before they commit, and check in their own dockerhub instance beforehand.
This PR can be added more optins, when the Jenkins tests (#1759) are finished and we have a running build  check there
=> docs: Add information, how to automatically check your code

docs/index.rst, patches/openwrt/0022-firmware-utils-tplink-safeloader-Add-CPE210-v3.patch, patches/openwrt/0023-ar71xx-Add-support-for-TP-Link-CPE210-v3.patch, targets/ar71xx-generic
Since the PR seemed to be blocked by git problems, I just re-did it.
This is not tested, and I did not check whether the patches are correctly rebased (currently they apply onto openwrt-18.06.2).
Follows up:
https://github.com/freifunk-gluon/gluon/pull/1695
https://github.com/freifunk-gluon/gluon/pull/1588
https://github.com/freifunk-gluon/gluon/pull/1445
Other changes compared to first v3 PR:
- Added entry in docs/index.rst
- Removed BROKEN in targets/ar71xx-generic
=> ar71xx-generic: Add support for TP-Link CPE210 V3

docs/dev/packages.rst
$(TOPDIR) does not contain a trailing slash.
Thus the 'gluon.mk'-include must include
the trailing slash. (Just like the link to
$(INCLUDE_DIR)/package.mk does.)
Signed-off-by: Chris Fiege <chris@tinyhost.de>
=> doc/dev/package: Fix path to gluon.mk

docs/index.rst, targets/ramips-mt76x8
- led mapping
- radio leds
how to restore to stock:
use stock image without its first 512 bytes and do tftp
=> ramips-mt76x8: add support for TP-Link TL-MR3420 v5

patches/openwrt/0024-ramips-add-support-for-ASUS-RT-AC57U.patch, targets/ramips-mt7621
The ASUS RT-AC57U is a relatively new device (~4 Months on the German market)with a MT7621 2C/4T CPU and Dualband AC Wave 1 2x2 WiFi.
`asus-rt-ac57u`
- led mapping
- radio leds
=> ramips: add support for ASUS RT-AC57U

CONTRIBUTING.md
The labels where changed a while ago, the link to the list of rejected features in the `CONTRIBUTING.md` need to be updated.
I hope the special characters are replaced, correctly. (the link is just copied&pasted from the browser)
=> CONTRIBUTING.md: fix link to list of rejected features

targets/ar71xx-generic
The profile for GL.iNet AR750 currently selects ATH10K_PACKAGES, but this device actually has a QCA9887 which needs another driver.
This commit fixes the issue by setting ATH10K_PACKAGES_QCA9887 instead.
=> ar71xx-generic: Fix packages for GL.iNet AR750

docs/index.rst, targets/ramips-mt7621
The initial patch didn't add the device to the Documentation and lacked the broken flag for IBSS, as IBSS is not yet tested on the MT7603/MT7612.
=> ramips-mt7621: fixes for ASUS RT-AC57U

scripts/update.sh
This displays the branch, repo and commitID that was attempted to update to but
failed. Users then can compare this output to the configuration they meant to
activate in modules and hopefully better find their typos.
=> scripts/update.sh: add verbose error message when commit cannot be found

package/gluon-core/luasrc/usr/lib/lua/gluon/iputil.lua
mac_to_ip() implements a special case, generating an ip6 address from, a
hwaddress. For wireguard we will use specially crafted addresses that
are not based on a mac address.
This commit allows to re-use the code by implementing
generate_ip_from_prefix() in a generic way, reusing it in mac_to_ip()
without breaking the existing interface.
=> gluon-core: implement generic generate_ip_from_prefix(), use it in mac_to_ip()

package/gluon-l3roamd/check_site.lua, package/gluon-l3roamd/files/etc/init.d/gluon-l3roamd, package/gluon-mesh-babel/Makefile, package/gluon-mesh-babel/luasrc/lib/gluon/upgrade/300-gluon-mesh-babel-mkconfig
this fixes two issues:
* redistribute the routes towards the internet
* correctly check for and use values from site.conf: prefix4 prefix6 and client_node_prefix6
=> redistribute routes toward internet, utilize missing values from site

targets/ramips-rt305x
reduce size by removing dispensable packages,
to fix builds of this target in most cases.
result of discussion in #1782 
this PR has been build-tested
=> ramips-rt305x: remove opkg and USB packages from 4M flash boards

docs/user/supported_devices.rst
Reason:
* the device is part of the target `ramips-mt7621` (not `ar71xx-generic`)
* the device is marked as broken https://github.com/freifunk-gluon/gluon/blob/master/targets/ramips-mt7621#L18
=> docs: remove Netgear WNDR3700 v5

docs/user/supported_devices.rst, targets/ar71xx-generic
As per https://github.com/freifunk-gluon/gluon/pull/1791#issuecomment-533021677
https://shells.darmstadt.ccc.de/~hexa/gluon/1822/user/supported_devices.html
=> docs, targets: mark and document several targets and devices as deprecated

package/gluon-mmfd/Makefile, package/gluon-mmfd/files/etc/init.d/mmfd
This adds the gluon integration needed for mmfd when using the socket features avoiding restarts of mmfd on every (attempted) mesh interface change.
=> gluon-mmfd: add package

targets/ar71xx-generic
The OCEDO Koala was missing the correct package definition. Because of
this, firmware is potentially built with the wrong ath10k firmware /
driver.
=> ar71xx-generic: add ath10k packages to OCEDO Koala

docs/features/roles.rst
`alfred` is outdated, I hope, the wording is correct now.
=> docs: replace alfred with respondd

targets/ar71xx-generic
This adds previously absent ath10k packages definitions. This way,
devices correctly select CandelaTech firmware correctly, when
GLUON_WLAN_MESH is set to IBSS.
This is also necessary for all devices, when OpenWrt is switched to
19.07.
=> ar71xx-generic: add missing ath10k packages

docs/user/supported_devices.rst, targets/ramips-mt76x8
GL.iNet VIXMINI is a 300M router based on MT7628 with 8M Flash and 64M RAM. Currently, it can only be bought from china for 20$ either on [AliExpress](https://de.aliexpress.com/wholesale?SearchText=Vixmini) or [GL.iNet shop](https://store.gl-inet.com/collections/all-wifi-devices/products/vixmini-mini-travel-router).
> root@64367-vixmini:~# lua -e 'print(require("platform_info").get_image_name())'
> gl.inet-vixmini
- led mapping
- radio leds
=> ramips-mt76x8: add support for GL.iNet VIXMINI

docs/user/supported_devices.rst, modules, targets/ipq806x-generic, targets/targets.mk
The NETGEAR R7800 was previously only supported as BROKEN in Gluon. With OpenWrt 19.07, the remaining bugs are ironed out, so the broken flag for target as well as device can be removed.
> root@64367-r7800:~# lua -e 'print(require("platform_info").get_image_name())'
> netgear-nighthawk-x4s-r7800
- led mapping
- radio leds
=> ipq806x-generic: add full support for NETGEAR R7800

docs/features/configmode.rst, package/gluon-setup-mode/files/etc/hotplug.d/button/50-gluon-setup-mode
many AVM devices do not have RESET/WPS buttons. So use the otherwise unused DECT/PHONE button to boot the device into setup mode.
This patch allows to enter the setup-mode by pressing the phone button
(often labeled as DECT) in addition to WPS and reset button.
This patch is necessary to allow supporting boards without a WPS and reset
button (e.g. AVM FRITZ!Box 7312).
=> gluon-setup-mode: allows DECT button to enter setup mode

docs/user/supported_devices.rst, targets/lantiq-xway, targets/targets.mk
- [?] must have working autoupdate
- led mapping
- radio leds
~
=> lantiq-xway:  support for AVM FRITZ!Box 7312

targets/ar71xx-generic
ar71xx-generic: consolidate Ubiquiti UniFi AC images
OpenWrt generated images for the following devices are identical:
- UniFi AC Lite / UniFi AC Mesh / UniFi AC LR
- UniFi AC Pro / UniFi AC Mesh Pro
Gluon currently outputs devices as a separate image. However, as the
model detection is done at run-time, a symlink to one image would have
the same effect.
To save some space, create aliases for the devices instead of dedicated
profiles.
-------
ar71xx-generic: add alias for UniFi AC LR
As upstream now has model detection for the Ubiquiti UniFi AC LR, we
need to provide an autoupdater image matching the expected filename.
Closes #1834
=> ar71xx-generic: refactor image profiles / add alias for UniFi AC-LR

docs/user/supported_devices.rst, modules, targets/ramips-mt7621
The NETGEAR R7800 was previously only supported as BROKEN in Gluon. With OpenWrt 19.07, the remaining bugs are ironed out, so the broken flag for target as well as device can be removed.
> netgear-r6220
- led mapping
- radio leds
=> ramips-mt7621: add support for Netgear R6220

docs/user/supported_devices.rst, patches/openwrt/0006-ipq-wifi-add-AVM-FRITZ-Repeater-1200-bdf.patch, patches/openwrt/0007-ipq40xx-add-support-for-AVM-FRITZ-Repeater-1200.patch, targets/ipq40xx-generic
The AVM FRITZ!Repeater 1200 is an IPQ4019 based WiFI Repeater / Access Point. It features 256M of RAM and 128M of NAND flash at a price point of ~55 Euro (< 50€ when on sale). Thus it should qualify for a backport.
> avm-fritz-repeater-1200
- led mapping
- radio leds
=> ipq40xx: add support for AVM FritzRepeater 1200

docs/user/supported_devices.rst, targets/ath79-generic
> devolo-wifi-pro-1200i
- led mapping
- radio leds
- All MAC addresses are printed on the label - 5GHz MAC matches primary MAC
=> ath79-generic: add support for devolo WiFi pro 1200i

docs/user/supported_devices.rst, package/gluon-core/luasrc/lib/gluon/upgrade/010-primary-mac, targets/ath79-generic
> ocedo-raccoon
- led mapping
- radio leds
=> ath79-generic: add support for OCEDO Raccoon

docs/user/supported_devices.rst, targets/ath79-generic
`devolo-wifi-pro-1750i`
- All MAC addresses are printed on the housing, it is identical to the MAC address of the 5Ghz Wifi.
- led mapping
- radio leds
- NO radio leds
-  NO switchport leds
=> ath79-generic: add support for devolo WiFi pro 1750i

docs/user/supported_devices.rst, targets/ath79-generic
> devolo-wifi-pro-1750c
- led mapping
- radio leds
- All MAC addresses are printed on the label - 5GHz MAC matches primary MAC
=> ath79-generic: add support for devolo WiFi pro 1750c

package/gluon-mesh-babel/Makefile, package/gluon-mesh-babel/luasrc/lib/gluon/upgrade/300-gluon-mesh-babel-mkconfig
when there is dual-stack on wan packets might leak out there that should be routed through the Freifunk. iNow that we have babeld 1.9 we can utilize the respective babeld feature and fix that issue.
=> gluon-mesh-babel: Fix packets leaving wrong interface

docs/user/supported_devices.rst, package/gluon-core/luasrc/usr/lib/lua/gluon/platform.lua, targets/ath79-generic
- matches 5Ghz Wifi mac adress 
- led mapping
- radio leds
=> ath79-generic: add support for devolo WiFi pro 1750x

docs/user/supported_devices.rst, targets/ath79-generic
- led mapping
- radio leds
- no radio led
- no switchport leds
Has the same "issues" regarding the LAN Port mappings as the Devolo WiFi pro 1200e.
See #1882
=> ath79-generic: add support for devolo WiFi pro 1750e

docs/user/supported_devices.rst, targets/ath79-generic
- all mac addresses are printed on the label, matches 5Ghz wifi mac
- led mapping
- radio leds
- no radio leds
- no switchport leds
While the port assignment on the device is correct by policy (there are 2 LAN Ports an no WAN Ports), this however is not the behavior I would expect as a user. Especially since only the first LAN port supports PoE. Two WAN ports are not very useful for devices with only two ports, because they …
=> ath79-generic: add support for devolo WiFi pro 1200e

targets/ar71xx-generic
We've got a device which is an regular Netgear netgear-wndr3800 on the outside, but call themself: wndr3800chmychart
I did copy the netgear-wndr3800 lines from the manifest, to add netgear-wndr3800chmychart entries:
https://github.com/ffac/manifest/commit/60d352fa559a9e1fe0aae66c84a4c3d462eafa55#diff-b2c233cac29bcba7ef1003550f02bc94
That worked as expected, the device accepted the netgear-wndr3800 firmware and is now online with the new firmware:
https://map.aachen.freifunk.net/#!/en/map/08bd43baa736
=> ar71xx-generic: add alias for wndr3800chmychart

docs/dev/wan.rst, docs/user/supported_devices.rst
At the December 2019 review day, the behavior for LAN only devices was defined. Such devices will use each LAN port as WAN.
=> docs: clarify WAN port on LAN-only devices

docs/user/supported_devices.rst, targets/lantiq-xrx200
* [?] must have working autoupdate
* [n/a]  primary mac should match address on device label (or packaging) (https://gluon.readthedocs.io/en/latest/dev/hardware.html#notes)
* led mapping
* power/sys led (_critical, because led definitions are setup on firstboot only_)
* radio leds
* [n/a]  should map to their respective port (or switch, if only one led present)
* [n/a]  should show link state and activity
* outdoor devices only
* [n/a]  added board name to `is_outdoor_device` function in `package/gluon-core/luasrc/usr/lib/lua/gluon/platform.lua`
~
=> lantiq-xrx200: add support for AVM FRITZ!Box 7362 SL

docs/user/supported_devices.rst, targets/lantiq-xrx200
* [?] must have working autoupdate
* [n/a]  primary mac should match address on device label (or packaging) (https://gluon.readthedocs.io/en/latest/dev/hardware.html#notes)
* led mapping
* power/sys led (_critical, because led definitions are setup on firstboot only_)
* radio leds
* [n/a]  should map to their respective port (or switch, if only one led present)
* [n/a]  should show link state and activity
* outdoor devices only
* [n/a]  added board name to `is_outdoor_device` function in `package/gluon-core/luasrc/usr/lib/lua/gluon/platform.lua`
~
All three versions …
=> lantiq-xrx200: add support for AVM FRITZ!Box 7360 (v1, v2) and 7360 SL

docs/user/supported_devices.rst, targets/lantiq-xway
* [?] must have working autoupdate
* [n/a]  primary mac should match address on device label (or packaging) (https://gluon.readthedocs.io/en/latest/dev/hardware.html#notes)
* led mapping
* power/sys led (_critical, because led definitions are setup on firstboot only_)
* radio leds
* [n/a]  should map to their respective port (or switch, if only one led present)
* [n/a]  should show link state and activity
* outdoor devices only
* [n/a]  added board name to `is_outdoor_device` function in `package/gluon-core/luasrc/usr/lib/lua/gluon/platform.lua`
~
All three versions …
=> lantiq-xway: add support for AVM FRITZ!Box 7320, 7330 and 7330 SL

docs/user/supported_devices.rst, targets/mpc85xx-p1020
The Enterasys / Extreme Networks WS-AP3710i is a ceiling / wall mount PoE powered access point.
It has a dual-core PowerPC processor and dualband WiFi radios.
It can be acquired for cheap (~15 Euros) second hand from IT redistributors.
*enterasys-ws-ap3710i*
- Reset button recessed at the bottom of the device
- all mac addresses are printed on the label, matches Radio 1 (5 GHz) wifi mac
- led mapping
- radio leds
=> mpc85xx-p1020: add support for Enterasys WS-AP3710i

docs/dev/hardware.rst
The docs previously only listed ath9k and ath10k based chipsets as fully
supported by Gluon, however we also support mt76.
=> docs: add mt76 to supported chipsets

patches/openwrt/0007-ipq-wifi-add-BDF-for-Aruba-AP-303.patch, patches/openwrt/0008-ipq40xx-add-support-for-Aruba-AP-303.patch, targets/ipq40xx-generic
this commit adds support for the Aruba AP-303 Wireless access point. The device is as well amrketed as the Aruba InstantOn AP11 for around 70 Euro.
As the Device supports 802.11ac Wave 2 MU-MIMO, has a Quad-Core IPQ4029 ARM SoC and 512 MB (!) of DDR3 RAM, it is a compelling alternative to the Ubiquiti UniFi AC Lite.
Installation instructions are available at the OpenWrt Wiki: https://openwrt.org/toh/aruba/aruba_ap-303
-----
> aruba-ap-303
- led mapping
- radio leds
=> ipq40xx: add support for Aruba AP-303

targets/ipq40xx-generic
The Aruba Instant On AP11 is the Aruba AP-303 with a stripped-down firmware.
Add an alias for the device to remove confusion about the different naming.
=> ipq40xx-generic: add alias for Aruba Instant On AP11

docs/user/supported_devices.rst, targets/ramips-mt7620
WiFi driver is stable now.
Router is running for 8 days now and both WiFi radios still work.
The running device:
https://hannover.freifunk.net/karte/#/de/map/6409807bbc0e
There are two ways to flash. Both are written in the OpenWRT Wiki. One via an Code Injection Bug and one via an Account on miwifi.com
https://openwrt.org/toh/xiaomi/mini#quick_openwrt_installation
autoupdater name is still the same when checked with the lua command.
After fresh reset with firstboot and Install of a fresh build it is still the correct mac address as seen on the device.
- led mapping …
=> ramips-mt7620: remove broken flag for Xiaomi MiWifi Mini

docs/user/supported_devices.rst
Just saw a small typo i made in the Xiaomi Mi Wifi Mini PR. This PR Corrects this.
=> docs: supported_devices: fix small typo

docs/user/supported_devices.rst, package/gluon-core/luasrc/lib/gluon/upgrade/010-primary-mac, targets/ramips-mt7620
- [no] webinterface
- [no] other: <specify>
- led mapping
- radio leds (only one)
- [n/a] added board name to `is_outdoor_device` function in `package/gluon-core/luasrc/usr/lib/lua/gluon/platform.lua`
=> ramips-mt7620: add support for TP-Link Archer C2 v1

docs/user/supported_devices.rst, package/gluon-core/luasrc/lib/gluon/upgrade/010-primary-mac, targets/ramips-mt7620
- [no]  other
- [?] must have working autoupdate
- led mapping
- radio leds
- [n/a]  added board name to `is_outdoor_device` function in `package/gluon-core/luasrc/usr/lib/lua/gluon/platform.lua`
~
Instructions on how to Upgrade are described here:
https://forum.openwrt.org/t/lede-on-tp-link-archer-c50-but-the-install-instructions-is-in-polish/3446/2
=> ramips-mt7620: add support for TP-Link Archer C50 v1

docs/user/supported_devices.rst, targets/ramips-mt76x8
`root@ffc-d80d170318c4:~# lua -e 'print(require("platform_info").get_image_name())'
tp-link-tl-wr902ac-v3
root@ffc-d80d170318c4:~# 
`
* wired network  
* wifi
* led mapping
* radio leds
* [?]  should show link state and activity -- the LED at the RJ45 connector shows the link state but no activity
=> ramips-mt76x8: add support for TP-Link TL-WR902AC v3

docs/user/supported_devices.rst, package/gluon-core/luasrc/lib/gluon/upgrade/010-primary-mac, targets/ramips-mt7620
- [no]  other
- [?] must have working autoupdate
- led mapping
- radio leds
- [n/a]  added board name to `is_outdoor_device` function in `package/gluon-core/luasrc/usr/lib/lua/gluon/platform.lua`
~
=> ramips-mt7620: add support for TP-Link Archer C20i

package/gluon-mesh-babel/src/Makefile, package/gluon-mesh-babel/src/respondd.c, package/gluon-mesh-batman-adv/src/Makefile, package/gluon-mesh-batman-adv/src/respondd-common.h, package/gluon-mesh-batman-adv/src/respondd-neighbours.c, package/gluon-mesh-batman-adv/src/respondd-nodeinfo.c, package/gluon-mesh-batman-adv/src/respondd-statistics.c, package/gluon-mesh-batman-adv/src/respondd.c, package/gluon-respondd/src/Makefile, package/gluon-respondd/src/respondd-common.h, package/gluon-respondd/src/respondd-neighbours.c, package/gluon-respondd/src/respondd-nodeinfo.c, package/gluon-respondd/src/respondd-statistics.c
Following up on #1512, this is a first step of implementing my suggestion to move common parts of the gluon-mesh-* respondd providers into gluon-respondd. Much more cleanup is necessary in the Babel respondd provider, but I ignored most of that for now to allow easier rebases of #1799 onto this.
In addition, this reverts some of #1676, which means that connected, but inactive wifi clients will disappear from the "total" client count again. One option would be to drop the "total" altogether and only let the mesh protocol provider add a "wired" client count, but I'm not sure if l3roamd can even distinguish wired and wireless clients at the moment.
I've also noticed that there are currently way too many different ways to iterate over mesh interfaces in these providers: UCI, ubus calls to …
=> gluon-mesh-* respondd cleanup (part 1?)

docs/user/supported_devices.rst, targets/ramips-mt76x8
- led mapping
- radio leds
- no outdoor devices
Running test device: http://[2001:678:6e3:1110:724f:57ff:fe86:4c72]/cgi-bin/status
Not beautiful, but no functional impact: The lock LED (green/red) at the front stays red whenever the device is running. If there are objections I can look further into this, but I would need some help with that, at least pointing me into the right direction.
Fixes #1906
=> ramips-mt76x8: add support for TP-Link TL-WA801ND v5

docs/user/supported_devices.rst, package/gluon-core/luasrc/lib/gluon/upgrade/010-primary-mac, targets/ramips-mt7620
'tp-link-archer-c20-v1'
* wired network  
* wifi
* led mapping
* radio leds
=> ramips-mt7620: add support for tp-link archer c20 v1

docs/user/supported_devices.rst, targets/ramips-mt7621
*usually means: gluon profile name must match image name* model name: *netgear-ex6150*
- led mapping
- radio leds
=> ramips-mt7621: add support for Netgear EX6150

docs/user/supported_devices.rst, modules, targets/ramips-mt76x8
- led mapping
- radio leds
- no outdoor device
running test device: http://[2001:678:6e3:1110:ae84:c6ff:fe6b:4edc]/cgi-bin/status
=> ramips-mt76x8: add support for TP-Link TL-MR3020 v3

docs/user/supported_devices.rst, targets/ar71xx-generic, targets/ath79-generic, targets/ramips-mt7620
=> ath79-generic: add support for GL-iNet GL-AR300M-Lite

docs/releases/v2019.1.rst
This remark would have saved us an hour or two of wondering why things do not work any more with the new address.
=> docs: add a note that hopglass-server needs an update to work with the new respondd address

README.md, docs/index.rst, docs/releases/v2019.1.2.rst, docs/site-example/site.conf, docs/user/getting_started.rst
Two security vulnerabilities were announced in OpenWrt last friday (CVE-2020-7982 & CVE-2020-7248).
While Gluon seems to be mostly unaffected in it's core components, there's still a possibility of being remotely exploitable, depending on the communities selected package set.
=> release: Gluon v2019.1.2

targets/brcm2708-bcm2710
It's the same Device as the others so it is still broken because of not working mesh on wifi but this rev is missing an alias so an nightly build could not update itself.
> autoupdater: warning: no matching firmware found (model raspberry-pi-3-model-b-rev-1.2)
=> brcm2708-bcm2710: add manifest_alias for raspberry-pi-3-model-b-rev-1.2

docs/user/supported_devices.rst, package/gluon-core/luasrc/usr/lib/lua/gluon/platform.lua, targets/ipq40xx-generic
```
root@ffka-lr-naturbursche:~# lua -e 'print(require("platform_info").get_image_name())'
engenius-ens620ext
```
- led mapping
- radio leds
As I wrote above, there are two different factory images because the format changes with vendor firmware 3.5.
I could not find a similar case for current devices so my proposal: ~~Use image for versions below 3.5 as the default since the ap should come preinstalled with this version. Offer the other one as "other" image.~~ Let's …
=> ipq40xx-generic: add support for EnGenius ENS620EXT

package/gluon-core/luasrc/lib/gluon/upgrade/010-primary-mac, package/gluon-core/luasrc/usr/lib/lua/gluon/platform.lua
- Remove redundant code by switching to a match table listing the targets and boards for each candidate for the primary MAC interface.
- Add some flexiblity by allow to switch out the sysfs file data source for the MAC address (needed for #1955)
=> Primary MAC logic refactoring

docs/user/supported_devices.rst, package/gluon-core/luasrc/lib/gluon/upgrade/010-primary-mac, targets/lantiq-xway
not a great device, but someone had it laying around.
**TODO: the primary mac should be read from /sys/class/net/eth0.1/address which is currently not working, maybe someone has a clue?**
- led mapping
- radio leds
- [-] added board name to `is_outdoor_device` function in `package/gluon-core/luasrc/usr/lib/lua/gluon/platform.lua`
=> lantiq-xway: add support for NETGEAR DGN3500B

docs/releases/v2020.1.rst
In 9e4eb182908320cb94974663c7d201ce792eea78 I missed adding information wrt to #1937, that should be fixed with this PR.
As the issue is not actionable to us I will close it after this gets merged and backported.
Resolves #1937
=> docs: v2020.1: add Edgerouter X NAND driver problem to known issues

targets/x86.inc
This commit adds packages for supporting common wireless adapters for Raspberry Pi and x86 platforms.
People often want to attach USB adapters to such platforms (whether or not this is a rational thing to do). Currently the packages have to installed after the initial boot process, which breaks Gluons initialization.
As those platforms have enough storage, include common USB adapter driver packages by default. Also extend the list of PCIe driver packages on x86 to include drivers and firmware for more WiFi cards available on the market.
This PR is not yet compile nor run-tested (as i do not own such adapters). So feel free to provide your experiences.
=> add common WiFi packages to relevant targets

Makefile, docs/dev/hardware.rst, docs/features/private-wlan.rst, docs/user/site.rst, docs/user/supported_devices.rst, package/features, package/gluon-core/luasrc/usr/lib/lua/gluon/platform.lua, package/gluon-core/luasrc/usr/lib/lua/gluon/util.lua, package/gluon-web-private-wifi/i18n/de.po, package/gluon-web-private-wifi/i18n/fr.po, package/gluon-web-private-wifi/i18n/gluon-web-private-wifi.pot, package/gluon-web-private-wifi/luasrc/lib/gluon/config-mode/model/admin/privatewifi.lua, package/gluon-wireless-encryption/Makefile, scripts/target_config_lib.lua, scripts/target_lib.lua, targets/ar71xx-generic, targets/ar71xx-tiny, targets/ipq40xx-generic, targets/ramips-rt305x
This commit adds WPA3 encryption for Gluon's Private WiFi feature.
It allows node operators to select between three encryption modes:
- WPA2 (old standard - no MFP)
- WPA2/WPA3 mixed-mode (optional MFP)
- WPA3 (mandatory MFP)
MFP is supported by all drivers which are currently fully supported by Gluon (rt2800, mt76, ath9k, ath10k).
As we need to include a OpenSSL library for WPA3, this PR also includes a mechanic to define a featureset. This way, packages can be included at compile-time as well as the featureset retrieved at run-time to decide, which functions can be supported in a devices featureset.
This Pull-Request still needs documentation written, so It's labeled as RFC.
fixes #1826
=> gluon-private-wifi: add support for WPA3 encryption

.luacheckrc, scripts/target_config_lib.lua, scripts/target_lib.lua, targets/x86.inc
When adding device classes, targets without devices such as x86 were not
handled. As site and feature packages are included on such a per-device
decision, x86 images ended up without most packages.
Include a class setting for a target and include the class-packages
target-wide when this setting is configured.
Fixes 9c52365077be ("build: introduce device classes")
=> build: add class-packages for targets without devices

docs/site-example/site.conf, docs/user/site.rst, package/gluon-client-bridge/check_site.lua, package/gluon-client-bridge/luasrc/lib/gluon/upgrade/320-gluon-client-bridge-wireless, package/gluon-respondd/src/respondd-statistics.c, package/gluon-web-wifi-config/luasrc/lib/gluon/config-mode/model/admin/wifi-config.lua
This PR adds support for an additional WPA3 Enhanced Open Clients radio.
Enhanced Open provides an encrypted connection, leading to data transferred between the node and client device being protected against passive packet sniffing. It also makes use of mandatory MFP, eliminating deauthentication attacks.
Enahnced Open is fully supported on Android 10, so adoption will most likely increase in the next 1-3 years. 
On the AP side, OWE is (due to enforced MFP) supported on the following chipsets:
* ath9k (exceptions apply for early draft-N chips)
* ath10k
* mt76
Blocked by #1876
=> gluon-client-bridge: add WPA3 Enhanced Open client radio support

.github/workflows/build-gluon.yml, contrib/actions/generate-actions.py, contrib/actions/run-build.sh, modules
This PR enables build-testing all targets using GitHub actions.
GitHub provides runners for public projects free of charge. This way, we are able to build-test all Targets simultaneously, which allows to have a PR built this way in under 2 hours.
The Goal of this PR is not to remove the existing Jenkins CI, as a lock-in to GitHub is not desirable. However we are not able to gather enough resources to host this functionality ourselves.
Demo runs can be found here: https://github.com/blocktrron/gluon/actions
=> github: build-test all targets using GitHub actions

package/gluon-respondd/luasrc/lib/gluon/upgrade/400-respondd-firewall
Fixes #1959
Would probably a good idea to backport this fix.
=> gluon-respondd: allow queries from extra_prefix6

targets/x86-geode
x86-geode does not include the common x86 target-settings. Thus we need
to specify the device class in order to build images with all necessary
packages included.
=> x86-geode: add target class

contrib/ci/jenkins-community-slave/README.md
The gluon build user (`uid=1000(gluon) gid=1000(gluon) groups=1000(gluon)`) is unprivileged in the container which is why mounting the directory with `:rw` is not sufficient, we need a matching UID/GID or chmod 0777. I think the latter is worse.
=> ci: add chmod step to resolve permissions on openwrt dl cache

docs/user/supported_devices.rst, package/gluon-core/luasrc/lib/gluon/upgrade/010-primary-mac, patches/openwrt/0009-ath79-enable-GL-AR750S-NOR-variant-from-master.patch, targets/ath79-generic
```
root@ffka-lr-minimesh:~# lua -e 'print(require("platform_info").get_image_name())'
gl.inet-gl-ar750s-nor
```
- led mapping
- radio leds
- switchport leds: device has only power and radio leds
- n/a should map to their respective port (or switch, if only one led present) 
- n/a should show link state and activity
- n/a added board name to `is_outdoor_device` function in `package/gluon-core/luasrc/usr/lib/lua/gluon/platform.lua`
Running test device: …
=> ath79-generic: add support for GL.iNet GL-AR750S

.github/workflows/build-gluon.yml, contrib/actions/generate-actions.py
This enables build-testing only on master as well as next and release branches.
Pull requests done from source branches of this repository are still built.
Previously, those builds were redundant.
=> github: actions: only build certain branches

.editorconfig, contrib/ci/Jenkinsfile, contrib/ci/jenkins-community-slave/Dockerfile, contrib/ci/jenkins-community-slave/README.md, tests/test_gluon-reconfigure.py, tests/test_respondd.py
This is a preview for QEMU/KVM based testing of Gluon images using https://github.com/lemoer/pynet.
We're still in the process of finding a good structure to define test cases and do proper partioning of the QEMU driver, the DSL and the test cases.
The test cases should be part of the Gluon repository, while the QEMU driver and DSL should reside in the pynet package, which is due to go upstream to pypi with some proper versioning.
We introduce a new `gluon-docker-v2` label, that marks nodes that have updated to the latest Docker image. This change requires runners to have acces to `/dev/kvm` and mount it into the container.
=> CI: Add test stage

docs/user/supported_devices.rst, targets/ramips-mt76x8
* led mapping
* power/sys led (_critical, because led definitions are setup on firstboot only_)
_Power LED Does never blink, maybe hardwired_
*   [x]  **should display config mode blink sequence** <-- Not entirely sure, as power led never blinks, but the WPS LED does it's job during config mode
* radio leds
---------------------
https://hannover.freifunk.net/karte/#/en/map/b44bd6224ebc
=> targets/ramips-mt76x8: add support for Cudy WR1000

patches/openwrt/0010-mac80211-ath10k-increase-rx-buffer-size-to-2048.patch
Before, only frames with a maximum size of 1528 bytes could be transmitted between two 802.11s nodes.
For batman-adv for instance, which adds its own header to each frame, we typically need an MTU of at least 1532 bytes to be able to transmit without fragmentation.
This patch now increases the maxmimum frame size from 1528 to 1656 bytes.
Tested with two ath10k devices in 802.11s mode, as well as with batman-adv on top of 802.11s with forwarding disabled.
Fix originally found and developed by @greearb and is already part of ath10k-ct
Link: https://github.com/greearb/ath10k-ct/issues/89
Link: https://github.com/greearb/ath10k-ct/commit/9e5ab25027e0971fa24ccf93373324c08c4e992d
Forwarded: https://github.com/openwrt/openwrt/pull/2959
=> mac80211: ath10k: increase rx buffer size to 2048

scripts/copy_output.lua, scripts/generate_manifest.lua, scripts/target_lib.lua
Moving images instead of copying them saves some disk space and there is probably no reason to keep the images in the OpenWrt buildroot.
Additionally the hope is that this will save enough disk space to have ar71xx-generic build through GitHub Actions.
=> scripts: move output files instead of copy

package/gluon-web-autoupdater/luasrc/lib/gluon/config-mode/model/admin/autoupdater.lua
Use the value of the `name` site.conf field as label (it was
accidentally unused before).
Our site.conf currently doesn't define a specific order for the branch
entries. To avoid changing branch orders, sort entries by this label.
Fixes: #1961
=> gluon-web-autoupdater: use human-readable names as branch labels, sort by label

docs/user/supported_devices.rst, targets/lantiq-xway
This device has broken Ethernet on both ports.
Remove support for those devices. for now, as there was no feedback from
the original author.
Closes #1943
=> lantiq-xway: remove support for AVM FRITZ!Box 7320 7330 7330SL

docs/user/supported_devices.rst, targets/ath79-generic
=> ath79-generic: add support for TP-Link CPE220 v3

docs/user/supported_devices.rst
I notices these two are missing in the docs.
=> docs: add Aruba AP-303 and Instant On AP11 to supported devices list

patches/openwrt/0010-kernel-backport-slub-prefetch-fix-from-v4.19.patch
This patch fixes a regression introduced in kernel v4.14. While the
commit message only mentions a performance penalty, the issue is
suspected to be the cause of spurious data bus errors on MIPS CPUs
(ar71xx target).
Fixes: #1982
My test device has completed more than 350M cycles of the test program posted in #1982 without issues. Needs more testing on a wider variety of hardware.
=> kernel: backport slub prefetch fix from v4.19

tests/test_batctl_tpmeter.py, tests/test_respondd.py
In https://github.com/freifunk-gluon/gluon/commit/a070e688498b7ab79cba5c9e8126d2a787a92f68 batman-adv was updated to emit correct exit codes when running tpmeter, which should make this test case work.
cc @lemoer
=> tests: add batctl tpmeter test case

docs/multidomain-site-example/site.mk, docs/site-example/site.mk, package/gluon-autoupdater/files/usr/lib/autoupdater/abort.d/90gluon-autoupdater, package/gluon-autoupdater/files/usr/lib/autoupdater/download.d/10gluon-autoupdater, package/gluon-setup-mode/files/lib/gluon/setup-mode/rc.d/S13haveged, package/gluon-setup-mode/files/lib/gluon/setup-mode/rc.d/S13urngd
OpenWRT 19.07 enables urngd by default, so haveged is redundant.
=> docs: examples: remove haveged from GLUON_SITE_PACKAGES

.luacheckrc, docs/index.rst, docs/package/gluon-logging.rst, package/gluon-logging/Makefile, package/gluon-logging/check_site.lua, package/gluon-logging/luasrc/lib/gluon/upgrade/040-syslog, scripts/check_site.lua
Allows configuration of remote syslog from site.conf.
Conflicts with `gluon-web-logging` as only one of them can control the remote syslog destination.
Resolves #1845. <s>Untested.</s>
=> Add gluon-logging package

targets/generic
We already recommend the use of haveged, making urngd redundant. To avoid
incompatible site changes in v2020.1.x, disabled urngd for now.
As proposed in https://github.com/freifunk-gluon/gluon/pull/2001#issuecomment-622031073
=> generic: disable urngd by default (v2020.1.x)

Makefile, scripts/copy_output.lua, scripts/target_config_lib.lua, scripts/target_lib.lua, targets/x86-geode, targets/x86.inc
The precedence of different package lists was broken since #1876,
disallowing removal of GLUON_FEATURES packages via GLUON_SITE_PACKAGES.
Including all package selections, both implicit defaults and explicit
handling in Gluon, the order of precedence is now the following:
1.  OpenWrt defaults (including target-specific defaults)
2.  Device-specific packages from OpenWrt
3.  Generic default packages (from target/generic)
4.  Target default packages (target/$(GLUON_TARGET))
5.  Removal of opkg for tiny targets
6.  Packages derived from GLUON_FEATURES + GLUON_FEATURES_$(class)
7.  GLUON_SITE_PACKAGES
8.  GLUON_SITE_PACKAGES_$(class)
9.  Device-specific packages from target/$(GLUON_TARGET)
10. Device-specific packages from GLUON_$(device)_SITE_PACKAGES
This also contains various pieces of …
=> Fix package selection precedence

package/gluon-core/luasrc/lib/gluon/upgrade/010-primary-mac, targets/ipq40xx-generic
successfully built, flashed and ran a device based on this
=> add hardware: Linksys EA6350 v3

docs/user/site.rst, package/gluon-mesh-vpn-fastd/luasrc/lib/gluon/upgrade/400-mesh-vpn-fastd
The 'preserve' flag can be used to mark a peer so it is not removed or
modified on upgrades. In addition, groups containing preserved peers are
not removed.
Fixes: #557
=> gluon-mesh-vpn-fastd: clean up peers and groups on update

package/gluon-mesh-batman-adv/luasrc/lib/gluon/upgrade/330-gluon-mesh-batman-adv-mac-addresses
As a partial fix to #496, do not touch the MAC address of the WAN interface when using VXLANs (as only the MAC address of the VXLAN interface matters to batman-adv).
A downside of this change is that it will modify the WAN MAC address of existing Gluon setups, but this seems much cleaner than the alternatives...
=> gluon-mesh-batman-adv: do not override WAN MAC address with VXLAN

scripts/default_feeds.sh
The OpenWrt feeds.conf.defaults contains some feeds that are commented out and not active. 
But this feeds are returned by the default_feeds.sh script anyway. Limit the script to only return
active feeds, by filtering out lines starting with '#'.
=> build: ignore deactivated feeds

.github/workflows/build-gluon.yml, targets/targets.mk, targets/x86-legacy
As x86-generic is compiled to pentium4 (and newer) there is a need for
a subtarget for older devices. The x86-legacy subtarget is set to
compile to pentium (and newer) and should support even very old devics.
Comments welcome.
Closes: #2009
=> RFC: add x86-legacy subtarget

package/gluon-client-bridge/luasrc/lib/gluon/upgrade/320-gluon-client-bridge-wireless
This will remove some unnecessary conditions, and save some characters in an encapsulated and-statement for a consecutive or-statements
=> gluon-client-bridge: simplify boolean expressions

package/gluon-client-bridge/luasrc/lib/gluon/upgrade/320-gluon-client-bridge-wireless, package/gluon-core/luasrc/lib/gluon/upgrade/200-wireless, package/gluon-core/luasrc/usr/lib/lua/gluon/platform.lua, package/gluon-core/luasrc/usr/lib/lua/gluon/util.lua, package/gluon-core/luasrc/usr/lib/lua/gluon/wireless.lua, package/gluon-mesh-wireless-sae/luasrc/lib/gluon/upgrade/205-wireless-mesh-sae, package/gluon-web-private-wifi/luasrc/lib/gluon/config-mode/model/admin/privatewifi.lua, package/gluon-web-wifi-config/luasrc/lib/gluon/config-mode/model/admin/wifi-config.lua
Seperate wireless-related helper methods from the util package into a
new wireless package. This keeps them seperated, as the amount of
wireles helpers increased in the past, justifying a seperate package.
=> gluon-core: move wireless-related utils to gluon-wireless

package/gluon-core/luasrc/lib/gluon/upgrade/010-primary-mac
In #2008, some confusion was caused by the fact that eth0/eth1 MAC addresses can be overridden by *board.json* after Gluon's upgrade scripts run, making `eth()` return the wrong address.
Clean this up by always looking up logical interface names through board.json, thus avoiding future confusion.
=> Look up primary MAC address through board.json for LAN/WAN

docs/user/site.rst, package/gluon-core/check_site.lua, package/gluon-core/luasrc/lib/gluon/upgrade/200-wireless
This adds support for the beacon interval to be set on a per-band base.
This has the potential to reduce the amount of airtime used up for
sending beacon frames.
=> gluon-core: add support for configuring the beacon interval

package/gluon-core/luasrc/lib/gluon/upgrade/140-firewall-rules
This allows for multiple mesh legs out of one box. Useful for offloaders
and networks using vlan for separate mesh transport.
This fixes #1479
=> Add all mesh interfaces to firewall rule wired_mesh

contrib/ci/jenkins-community-slave/slave.py
I don't have access to a slave setup, so I could test this only superficially.
Fixes: #1997
=> jenkins-community-slave: fix slave.py HTTPS warnings

.github/workflows/build-docs.yml
This adds a new workflow for building the Gluon documentation.
In contrast to the existing build workflow, the documentation
is built for every branch, as it only takes around two minutes
to render the HTML documentation.
=> actions: build documentation

package/gluon.mk
- If luasrcdiet fails for a Lua script, this is a bug that should be
noticed rather than including the unminified script
- Use .tmp suffix for temporary file rather than .o
- Replace chmod + stat + mv with simpler cp + rm to overwrite file while
preserving file mode
=> build: make GluonSrcDiet simpler and more robust

package/gluon-config-mode-outdoor/luasrc/lib/gluon/config-mode/wizard/0250-outdoor.lua, package/gluon-core/luasrc/lib/gluon/upgrade/200-wireless, package/gluon-web-wifi-config/luasrc/lib/gluon/config-mode/model/admin/wifi-config.lua
When looking into #2048 (fixed by the first commit of this PR), I noticed another issue in the outdoor mode setting: The advanced WLAN config page required an additional reload to update the mesh iface option visibility after changing the outdoor mode setting. This is fixed by the subsequent commits.
Fixes:  #2048
=> Fix /etc/config/network commit for outdoor mode change, and related fixes

scripts/target_config_check.lua
Always allow options set to builtin (=y) when modular setting (=m) is
expected. This can happen when a package is added explicitly (in a
target defintion or site.mk) that is also pulled in as a dependency of
another builtin package.
Fixes: 9e23534ec365 ("build: rework config generation")
Fixes: #2046
=> build: target_config_check: make check more lenient

scripts/target_config_lib.lua, targets/generic
Normally, we build all nonshared packages (which includes all kernel
modules) to generate an opkg feed for later package installations by
users. On targets without opkg, this just wastes time - disable it.
This also reduced the size of the base kernel by a lot, as interfaces only needed by optional modules can be removed as well - saving more than 64KB on ar71xx-tiny!
This is something I wanted for some time now, and with #2037 it's finally easily possible.
I propose we also backport this to v2020.2.x.
=> build: target_config_lib: do not build unused packages for targets without opkg

package/gluon-config-mode-outdoor/luasrc/lib/gluon/config-mode/wizard/0250-outdoor.lua, package/gluon-core/luasrc/lib/gluon/upgrade/200-wireless, package/gluon-web-wifi-config/luasrc/lib/gluon/config-mode/model/admin/wifi-config.lua
In both places where the outdoor mode can be disabled, we would leave the mesh interfaces disabled by default after #2049. This is a problem for the wizard in particular, as there is no way to enable the mesh interfaces at all without switching to the advanced settings.
While fixing this, I also noticed that we were ignoring the `disabled` site.conf flag for mesh interfaces since Gluon v2017.1... This is fixed as well.
Fixes: #2053
Completely untested so far, @rotanid please test! I'll give it a few test runs tomorrow.
=> Enable 5GHz mesh interfaces when disabling outdoor mode, fix default status from site.conf

package/gluon-mesh-batman-adv/files/lib/gluon/core/mesh/teardown.d/70-gluon-mesh-batman-adv
With very bad timing, it is possible that the teardown script of a
gluon_mesh interface runs when bat0 was just created, but primary0 is not
yet added to it. Although there is no hardif to remove in this case,
bat0 will still be deleted, because there is no hardif in bat0.
Disable the interface removal logic by passing `-M` to `batctl interface`.
This was reported by @rotanid and @mbaumga
=> gluon-mesh-batman-adv: do not delete bat0 during hardif teardown

package/gluon-core/luasrc/usr/lib/lua/gluon/platform.lua, patches/openwrt/0012-mac80211-rt2800-enable-MFP-support-unconditionally.patch
With this backported patch, rt2x00 will automatically fall back to software crypto in case MFP is used on the link.
Enable WPA3 features for the mt7620 target, as WPA3-SAE as well as OWE are working now.
This might also be possible for the rt305x subtarget, however I'm not in the possession of such a device.
=> mac80211: rt2800: enable MFP support unconditionally

package/gluon-config-mode-outdoor/luasrc/lib/gluon/config-mode/wizard/0250-outdoor.lua, package/gluon-core/luasrc/lib/gluon/upgrade/200-wireless, package/gluon-core/luasrc/usr/lib/lua/gluon/wireless.lua, package/gluon-web-wifi-config/luasrc/lib/gluon/config-mode/model/admin/wifi-config.lua
This will hide the outdoor mode setting on compatible devices in case
the defined channels should be preserved.
Otherwise a user might be under the impression their device is compliant
with out door operation when in reality it still uses prohibited
channels.
=> gluon-web: don't display outdoor mode on preserve_channels

docs/features/wlan-configuration.rst
Document the behavior of the Outdoor mode when preserve_channels is
enabled.
=> docs: wlan-configuration: document outdoor mode behavior

.github/workflows/build-gluon.yml, contrib/actions/generate-actions.py
This adds the ability to cache OpenWrt dependencies on a per-target
base. Artifacts over 10MB are excluded, as GitHub imposes a limit of 5G
of available space per repository cache. This affects mostly
linux(-firmware) and gcc / gdb.
The goal is to reduce the total amount of requests necessary to fetch
dependencies.
=> actions: cache OpenWrt DL folder

patches/openwrt/0014-mac80211-create-channel-list-for-fixed-channel-operation.patch, patches/openwrt/0015-hostapd-enter-DFS-state-if-no-available-channel-is-found.patch
This backports two fixes related to operation on DFS-required
channels.
When a DFS-required channel was selected as the regular
(non-outdoor-mode) 5 GHz channel, hostapd would switch to a non-DFS
channel as OpenWrt did not pass a chanlist of allowed ACS channels.
When hostapd is given a single channel for the chanlist or there's no
available channel left (all allowed channels are in the no-occupancy
period), hostapd prints "no DFS channels left, waiting for NOP to
finish" to the syslog but never stopped transmitting on this channel,
still sending out beacon frames and allowing client data transfer.
=> openwrt: backport DFS fixes

docs/_static/css/custom.css, docs/conf.py
Fix a number of issues related to the vertical alignment and margins of list elements.
readthedocs.io currently uses outdated versions of both Sphinx and the ReadTheDocs theme, but these changes seem to look fine (and are definitely an improvement) both locally and on the website.
Before: https://gluon.readthedocs.io/en/latest/releases/v2018.1.html#site-conf
After: https://gluon.readthedocs.io/en/doc-css-fixes/releases/v2018.1.html#site-conf
=> docs: add a number of CSS fixes

package/gluon-status-page/files/lib/gluon/status-page/view/status-page.html, package/gluon-status-page/i18n/de.po, package/gluon-status-page/i18n/gluon-status-page.pot
This adds the wireless client count for 2.4GHz and 5 GHz radios to the status page.
Previously, only the total client count advertised by the mesh protocol was visible.
=> gluon-status-page: add wireless client count

package/gluon-mesh-babel/src/respondd.c, package/gluon-mesh-batman-adv/src/respondd-nodeinfo.c, package/libgluonutil/src/libgluonutil.c, package/libgluonutil/src/libgluonutil.h
As noted in #1783, Wireguard and L2TP interfaces are not correctly detected as tunnels in our current respondd nodeinfo providers. To fix this, use the DEVTYPE value of the interface `uevent` as an additional data source. I did not check my code in an actual tunneldigger or wireguard setup (as I don't have access to one), but I checked the DEVTYPE of l2tpeth interfaces created using `ip l2tp`, and looked at the wireguard kernel code.
To avoid code duplication between the batadv and babel providers, this function is implemented in libgluonutil. A helper to get the base interface of VLAN/VXLAN/... interfaces  is added as well.
The first patch of this series is some cleanup of the link-local address function in the mesh-babel code. The mesh-babel changes are compile-tested only - a test in …
=> Fix tunnel interface detection in respondd nodeinfo

package/gluon-core/luasrc/lib/gluon/upgrade/020-interfaces
Use the WAN port of switch0 instead of `dsl0` on lantiq devices where available. It would be great if we could test this on a few of our existing lantiq devices - I don't have any.
See also: https://github.com/freifunk-gluon/gluon/pull/2006#issuecomment-643479894
=> Use LAN/WAN interfaces from board.json, add lantiq special case

targets/lantiq-xrx200
The packages necessary to get the DSL modem working increase the
squashfs size by around 1MB.
Remove them from Gluon, as this functionality is not supported.
=> lantiq-xrx200: remove modem packages from image

docs/dev/build.rst, docs/dev/debugging.rst, docs/dev/packages.rst, docs/dev/wan.rst, docs/features/vpn.rst, docs/package/gluon-hoodselector.rst, docs/releases/v2015.1.rst, docs/releases/v2018.2.1.rst, docs/releases/v2020.1.1.rst, docs/releases/v2020.1.2.rst, docs/releases/v2020.2.rst, docs/user/site.rst
=> docs: fix small typos and use common used notation

scripts/target_lib.lua
site_code is evaluated early during config generation, so a site.conf
without site_code would hit this assertion that just printed 'Assertion
failed'. Add a proper error message to tell users what went wrong.
The inner assert() is removed, as it should never be hit (as site.conf
syntax will have already been validated when this script runs), and it
doesn't add anything (even without the assert, the attempt to index a
nil value would throw an error).
=> scripts/target_lib.lua: print a meaningful error message for missing site_code

package/gluon-site/Makefile
We already have a proper message when the creation of an alias fails
because of a name conflict. Also add a message when the primary filename
of a domain config is already occupied by another domain's alias.
Also add an 'Error:' prefix to the existing message to easier to see.
=> gluon-site: print better error message for domain code conflicts

Makefile, docs/features/autoupdater.rst, docs/site-example/site.conf, docs/user/getting_started.rst, docs/user/site.rst, package/gluon-autoupdater/Config.in, package/gluon-autoupdater/Makefile, package/gluon-autoupdater/check_site.lua, package/gluon-autoupdater/luasrc/lib/gluon/upgrade/500-autoupdater, targets/generic
The old setting is still supported, but will emit a deprecation warning.
Also, make the branch setting in `site.conf` optional.
Closes: #1236
=> Replace GLUON_BRANCH with GLUON_AUTOUPDATER_BRANCH and GLUON_AUTOUPDATER_ENABLED

Makefile, scripts/module_check.sh
Forgetting to `make update` or leaving uncommitted changes in the
repositories managed by Gluon is a recurring cause of confusion, even
for experienced developers. Let's print an obvious warning message in
this case.
=> build: check for unsynced feeds before build

package/gluon-wireless-encryption/Makefile
This switches hostapd variant used for SAE and OWE from hostapd-openssl
to hostapd-wolfssl.
The bug shich one broke the wolfssl implementation was resolved upstream
with commit 631c437a91c2 ("hostapd: backport wolfssl bignum fixes").
This particular commit also got backported to OpenWrt 19.07.
The Image size is reduced by around 600KB.
=> gluon-wireless-encryption-wpa3: switch to hostapd-wolfssl

package/gluon-mesh-wireless-sae/Makefile
In #2042 we're switch our hostapd variant to wolfSSL. I've tested the functionality of the `gluon-mesh-wireless-sae` package.
I've reported my success in https://github.com/freifunk-gluon/gluon/pull/2042#issuecomment-674456189.
=> gluon-mesh-wireless-sae: switch to wpa-supplicant-mesh-wolfssl

docs/releases/v2020.2.rst
we forgot issues marked as known issue in the last release's release notes, forgot to mention the issue with upgrades for ER-X and can remove an issue that seems to be obsolete starting with v2020.1
=> docs: fixes for v2020.2 release notes

package/gluon-ebtables-filter-multicast/luasrc/lib/gluon/ebtables/110-mcast-allow-respondd
This allows running a respondd querier and map server behind a Gluon
node.
For instance at Freifunk Lübeck we now moved the map server
behind a Gluon VM and removed batman-adv and fastd from the
map server VM to reduce the maintenance work.
Increased multicast overhead should be minimal / non existent, as it is
unlikely to accidentally have respondd queriers running behind a Gluon
node.
=> gluon-ebtables-filter-multicast: allow respondd queries

docs/user/supported_devices.rst, targets/ar71xx-generic
A small, USB powered wifi router from GL-iNet, with network-over-USB support. Handy for Gluon development on-the-go.
https://openwrt.org/toh/hwdata/gl.inet/gl.inet_gl-usb150
https://www.gl-inet.com/products/gl-usb150/
*usually means: gluon profile name must match image name* -> checked that Lua platform info matched
- led mapping
- radio leds
=> ar71xx-generic: Add support for GL-iNet Microuter (GL-USB150)

.luacheckrc, docs/dev/packages.rst, package/features, scripts/feature_lib.lua, scripts/target_config_lib.lua
This fixes two major bugs in the new feature definition handling, both leading to non-existent packages like `gluon-web-advanced` to be added to the package list when the corresponding feature flags are set in GLUON_FEATURES. In particular, it was more or less impossible to define a custom `features` file in a feed because of the second issue.
Reported by @T-X
=> Fix two feature handling bugs

package/gluon-client-bridge/luasrc/lib/gluon/upgrade/300-gluon-client-bridge-network, package/gluon-core/luasrc/lib/gluon/upgrade/300-firewall-rules, package/gluon-core/luasrc/lib/gluon/upgrade/820-dns-config, package/gluon-mesh-babel/luasrc/lib/gluon/upgrade/310-gluon-mesh-babel-firewall, package/gluon-respondd/luasrc/lib/gluon/upgrade/400-respondd-firewall, package/gluon-status-page/luasrc/lib/gluon/upgrade/500-status-page
This renames the local_client zone to loc_client, as local_clint exceeds
the maximum zone length allowed for firewall3, which is 11 bytes.
This worked previously due to firewall3 using unsafe string operations.
Now creation of the chain fails (latest OpenWrt master).
=> treewide: rename local_client zone

package/gluon-client-bridge/luasrc/lib/gluon/upgrade/300-gluon-client-bridge-network, package/gluon-core/files/lib/gluon/upgrade/100-core-reset-sysctl, package/gluon-core/luasrc/lib/gluon/upgrade/300-firewall-rules
this PR removes parts of two files, which were marked as "can be removed" a few years ago, one of which even wasn't part of any Gluon release.
also, it removes a single file marked as deletable a while ago.
=> clean up old cleanup code lines

.github/workflows/build-gluon.yml, contrib/actions/generate-actions.py
The performance benefit the cache brought was due to a broken sources
CDN mirror handling in OpenWrt.
The cache brings no measurable performance benefit. Disable it to slim
down the pipeline steps.
=> github: remove GitHub actions cache

docs/user/supported_devices.rst, targets/ar71xx-generic
This follow up the discussion done in #2070 by not  creating a symlink
for the Rocket M5. Images for the Rocket M2 can still be flashed on a
Rocket M5.
This change will prevent the Rocket M5 from appearing in Firmware
selectors. Existing devices will still receive updates, as the device
name is still referenced for the device name expected by the M5.
Closes #2070
=> ar71xx-generic: only create manifest alias for Rocket M5

docs/user/supported_devices.rst, targets/ipq40xx-generic
- [] primary mac should match address on device label (or packaging) (https://gluon.readthedocs.io/en/latest/dev/hardware.html#notes) No primary MAC on device
- led mapping
- radio leds
=> ipq40xx-generic: add support for AVM FRITZBox 7530

patches/openwrt/0016-kernel-bridge-Implement-MLD-Querier-wake-up-calls-Android-bug-workaround.patch, patches/packages/routing/0002-batman-adv-compat-remove-ip_mc_check_igmp-ipv6_mc_check_mld.patch
Implement a configurable MLD Querier wake-up calls "feature" which
works around a widely spread Android bug in connection with IGMP/MLD
snooping.
Currently there are mobile devices (e.g. Android) which are not able
to receive and respond to MLD Queries reliably because the Wifi driver
filters a lot of ICMPv6 when the device is asleep - including
MLD. This in turn breaks IPv6 communication when MLD Snooping is
enabled. However there is one ICMPv6 type which is allowed to pass and
which can be used to wake up the mobile device: ICMPv6 Echo Requests.
If this bridge is the selected MLD Querier then setting
"multicast_wakeupcall" to a number n greater than 0 will send n
ICMPv6 Echo Requests to each host behind this port to wake
them up with each MLD Query. Upon receiving a matching ICMPv6 Echo …
=> kernel: bridge: Implement MLD Querier wake-up calls / Android bug workaround

Makefile, scripts/update-patches.sh
This PR adds a new `refresh-patches` step to the project Makefile which allows to apply and update all patches to feeds and OpenWrt without installing feed packages to the OpenWrt buildsystem.
This reduces the time necessary for refreshing patches when updating feeds or the OpenWrt base.
This PR will also print the commit title for every patch created when updating patches. This was previously only done when applying    patches.
=> build: improve refreshing patches

patches/openwrt/0017-mt76-mt7603-add-additional-EEPROM-chip-ID.patch
Some newer MT7628 based routers (notably the TP-Link Archer C50 v4) are
shipped with a chip-id of 0x7600 in the on-flash EEPROM. Add this as a
possible valid ID.
This fixes unstable WiFi on some units of the TP-Link Archer C50 v4.
=> mt76: mt7603: add additional EEPROM chip ID

patches/openwrt/0027-kernel-mtd-add-support-for-EN25QH64-in-spi-nor.c.patch, patches/openwrt/0028-tplink-safeloader-expand-support-list-for-TP-Link-CPE210-v3.patch, patches/openwrt/0029-Backport-en25qh64-from-4.14-to-4.9.patch
This pull request backports changes from OpenWrt into the v2019.1.x maintainance branch that allow us to use the CPE210 v3.2.
The PR contains two parts:
a) Allow the SPI-NOR driver to bind for the NOR used inside the CPE210 V3.2. This change was made for 4.19 and 4.14 in OpenWRT upstream. This patch packports the crucial change from there to 4.9 (that is used for ar71xx-generic in v2019.1.x).
The upstream commit was:
https://github.com/openwrt/openwrt/commit/359f5e539036db4f7ac69a6d1c3fb7fe70266ffd
b) Add the needed sugar to the TP-Link safeloader.
The upstream commit was:
https://github.com/openwrt/openwrt/commit/4a2380a1e778a8f8e0bfb0a00f2996ed0aab58d8
I hope this kind of backporting of Upstream Changes to older branches is OK. This way this hardware can be supported in all the …
=> ar71xx-generic: add support for TP-Link CPE210 v3.20

.github/workflows/check-patches.yml
Add a workflow to verify all patches to OpenWrt and the packages feeds
are refreshed.
If they are not, the workflow fails.
=> github: add workflow for checking patch status

targets/ramips-mt7620
Use a manifest alias for the autoupdater image string of the Netgear
EX3700 / EX3800. This way, no unnecessary symlink is created and the
autoupdater functionality is preserved.
=> ramips-mt7620: use manifest alias for EX3700/EX3800

package/gluon-core/luasrc/lib/gluon/upgrade/010-primary-mac, targets/ath79-generic
https://openwrt.org/toh/tp-link/tp-link_archer_c2_ac900
64M RAM, guess we'll mark it as TINY/BROKEN.
```
tp-link-archer-c2-v3
```
- led mapping
- radio leds
- <s>outdoor devices only</s>
=> ath79-generic: add support TP-Link Archer C2 v3

docs/user/site.rst
The map is generated from EUMETNET data, it's source code can be
found at https://gitlab.com/aaaaalbert/wxr-channel-map.
The project was presented on Battlemesh v13 earlier today.
=> docs: reference weather radar map for europe for outdoor_chanlist

patches/openwrt/0027-scripts-download.pl-retry-download-using-filename.patch
This fixes OpenWrts handling of some assets in case they have to be pulled from OpenWrt's sources mirror.
This ensures that images can still be built in case the original mirror goes down.
```
With this commit, the download script will try downloading source files
using the filename instead of the url-filename in case the previous
download attempt using the url-filename failed.
This is required, as the OpenWrt sources mirrors serve files using the
filename files might be renamed to after downloading. If the original
mirror for a file where url-filename and filename do not match goes
down, the download failed prior to this patch.
Further improvement can be done by performing this only for the
OpenWrt sources mirrors.
```
=> [2019.1.x] scripts: download.pl: retry download using filename

contrib/ci/jenkins-community-slave/README.md
There is a small typo in contrib/ci/jenkins-community-slave/README.md.
Should read `notify` rather than `notifiy`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md
=> docs: fix simple typo, notifiy -> notify

package/gluon-core/luasrc/usr/lib/lua/gluon/util.lua, package/gluon-hoodselector/luasrc/usr/lib/lua/hoodselector/util.lua, package/gluon-hoodselector/luasrc/usr/sbin/hoodselector
This commit introduces a simple function for writing to the syslog and replaces the custom function used by gluon-hoodselector.
=> packages: introduce syslog function in gluon.util

.github/workflows/build-docs.yml, .github/workflows/build-gluon.yml, .github/workflows/check-patches.yml, contrib/actions/generate-actions.py
Builds are often unnecessarily queuing up, so this is basically what I had in mind in #2004 ported to actions.
=> actions: run tasks based on set of modified paths

package/gluon-core/files/lib/gluon/label_mac.sh, package/gluon-core/luasrc/lib/gluon/upgrade/010-primary-mac
This adds the OpenWrt label-mac device selection as the most preferred
fallback.
While this is only used on OpenWrt 19.07 for backports, we can also use
the label-mac device when backporting device support. This way, we have
to deal with less device-sepcific code downstream.
=> gluon-core: use OpenWrt label-mac as fallback

package/gluon-respondd/src/respondd-statistics.c, package/libgluonutil/src/libgluonutil.h
Fix two issues (that should have been obvious if anyone were looking at compiler warnings...)
The first issue causes a crash on 64bit archs in multidomain setups. The second issue is harmless.
Affects Gluon next, master and v2020.2.x.
Closes #2173
=> gluon-respondd: fix crash on 64bit archs (+ one unrelated issue)

docs/user/supported_devices.rst, package/gluon-core/luasrc/usr/lib/lua/gluon/platform.lua, patches/openwrt/0018-ath79-Fix-fallback-to-bootloader-cmdline-on-empty-DT-bootargs.patch, patches/openwrt/0019-ath79-Add-support-for-Plasma-Cloud-PA300.patch, patches/openwrt/0020-ath79-Add-support-for-Plasma-Cloud-PA300E.patch, targets/ath79-generic
* Check the separate patches for the Forwarded: information
* Two devices are in this PR do avoid the conflicts between two independent PRs which depend on the same base modifications
- led mapping
- radio leds (**none available**)
- switchport leds (**none available**)
=> ath79: Add support for Plasma Cloud PA300(E)

docs/user/supported_devices.rst, package/gluon-core/luasrc/lib/gluon/upgrade/010-primary-mac, package/gluon-core/luasrc/usr/lib/lua/gluon/platform.lua, patches/openwrt/0021-ipq40xx-Change-name-for-openmesh.sh-to-vendor-free-name.patch, patches/openwrt/0022-ipq40xx-add-support-for-Plasma-Cloud-PA1200.patch, patches/openwrt/0023-ipq40xx-add-support-for-Plasma-Cloud-PA2200.patch, targets/ipq40xx-generic
* Check the separate patches for the Forwarded: information
* Two devices are in this PR do avoid the conflicts between two independent PRs which depend on the same base modifications
PA1200
======
- led mapping
- radio leds (**not available**)
- switchport leds (**not available**)
PA2200
======
- led mapping
- power/sys led (_critical, because led …
=> ipq40xx: Add support for Plasma Cloud PA1200 and PA2200

patches/openwrt/0024-kernel-bridge-Fix-a-deadlock-when-enabling-multicast-snooping.patch
[ Upstream commit 851d0a73c90e6c8c63fef106c6c1e73df7e05d9d ]
From: Joseph Huang \<Joseph.Huang@garmin.com\>
When enabling multicast snooping, bridge module deadlocks on multicast_lock
if 1) IPv6 is enabled, and 2) there is an existing querier on the same L2
network.
The deadlock was caused by the following sequence: While holding the lock,
br_multicast_open calls br_multicast_join_snoopers, which eventually causes
IP stack to (attempt to) send out a Listener Report (in igmp6_join_group).
Since the destination Ethernet address is a multicast address, br_dev_xmit
feeds the packet back to the bridge via br_multicast_rcv, which in turn
calls br_multicast_add_group, which then deadlocks on multicast_lock.
The fix is to move the call br_multicast_join_snoopers outside of the
critical section. …
=> kernel: bridge: Fix a deadlock when enabling multicast snooping

package/gluon-neighbour-info/src/gluon-neighbour-info.c
This is has been compiled and tested.
Results of `time ./gluon-neighbour-info -s neighbour -d ff02::2:1001 -p 1001 -r nodeinfo`
before and after:
`real	0m3,013s`
and
`real	0m0,168s`
> End the process after one result in case  is not given.
> Reduces singleshot execution time from timeout seconds to around 150ms.
> 
> resolves #2184
=> gluon-neighbour-info: end before timeout

contrib/actions/install-dependencies.sh
apt does not have a stable CLI interface. Don't use it in scripts.
=> contrib/actions: use apt-get instead of apt

contrib/Dockerfile
* apt is meant for user interactive usage. apt does not guarantee a stable CLI.
* set DEBIAN_FRONTEND=noninteractive to tell apt-get that no user interaction is wanted
=>  contrib/Dockerfile: use apt-get instead of apt

package/gluon-status-page/files/lib/gluon/status-page/view/status-page.html, package/gluon-status-page/i18n/de.po, package/gluon-status-page/i18n/gluon-status-page.pot, package/gluon-status-page/i18n/ru.README
Implements the next open crumb of #1415.
=> gluon-status-page: add role to status-page

package/gluon-core/luasrc/lib/gluon/upgrade/010-primary-mac, targets/ath79-generic
=> targets/ath79-generic: add archer-D50 v1

docs/features/autoupdater.rst
We were surprised when we saw most nodes update overnight to a new firmware that was supposed to be released slowly over a 7 day window in the future, so I believe that the behaviour should be documented.
I do not see any obvious way to build the documentation, so I hope the output is fine, but I was not able to verify it.
=> autoupdater: document behaviour if manifest DATE is in the future

package/gluon-mesh-batman-adv/files/lib/netifd/proto/gluon_bat0.sh
With batman-adv 2020.4 and the according backports to batman-adv v2019.2
several more bugs were found and fixed regarding the batman-adv
multicast optimizations feature.
Also a "wakeup-call" feature was added to the Linux bridge IGMP/MLD
snooping code in Gluon to work around issues with Android devices.
With batman-adv now at v2019.2, multicast-to-multi-unicasts conversion
is supported, too. Which means that even if there are a few outdated nodes
these and all other recipients will be served multicast packets via unicast,
too, as long as the sum of receiving nodes does not exceed the multicast
fanout setting (default: 16). If is exceeded, then batman-adv will revert
back to broadcast flooding automatically.
Long story short, with all these extra measures in place, let's reenable
the …
=> gluon-mesh-batman-adv: reenable batman-adv multicast optimizations

package/gluon-web-admin/luasrc/lib/gluon/config-mode/controller/admin/upgrade.lua
The rudimentary flash size determination function expects the partition
for the devices firmware to be called "linux" while it is (since quite
some time) "firmware".
Fix this error to display available flash size as well as more useful
error message in case the uploaded firmware image exceeds the flash
space.
=> web-admin: fix firmware partition name

.github/workflows/build-gluon.yml, contrib/actions/generate-actions.py
Currently we do not perform CI firmware builds on the next-2102 branch.
Build Gluon for all branches starting with "next" to increase the
coverage of our build tests.
=> actions: build gluon for next sub-branches

package/gluon-mesh-wireless-sae/luasrc/lib/gluon/upgrade/205-wireless-mesh-sae
Drop these unused parameters in the function description, as only the
first parameter is referenced within the function block.
=> mesh-wireless-sae: drop unused function parameters

package/gluon-private-wifi/Makefile, package/gluon-private-wifi/luasrc/lib/gluon/upgrade/325-gluon-private-wifi, package/gluon-web-private-wifi/Makefile, package/gluon-web-private-wifi/luasrc/lib/gluon/config-mode/model/admin/privatewifi.lua
Set the ifname for the WAN radio (Private WLAN) to wanX, X being the
radio index.
All other radios created by Gluon already have their ifname defined
following this pattern.
=> gluon-web-private-wifi: define ifname for WAN radio

package/gluon-core/files/lib/netifd/proto/gluon_wired.sh, package/gluon-core/luasrc/lib/gluon/upgrade/210-interface-wan, package/gluon-core/luasrc/lib/gluon/upgrade/220-interface-lan
These are two small patches to allow using the `gluon_wired.sh` proto for the `mesh_vpn` interface.
This works for layer 2 and layer 3 vpns:
- In case of a layer 2 vpn, this just adds the `gluon_mesh.sh` proto as before.
- In case of a layer 3 vpn, creates an intermediate vxlan interface on top of the interface before applying the `gluon_mesh.sh` proto.
Furthermore an additional setting `vxpeer6addr` is added to the gluon_wired.sh proto, which is only used, if a vxlan layer is added. It can be used to control the peer address of vxlan.
This is preparatory to support wireguard in a clean way.
=> Generalize proto "gluon_wired.sh"

package/gluon-status-page/files/lib/gluon/status-page/view/status-page.html, package/gluon-status-page/i18n/de.po, package/gluon-status-page/i18n/gluon-status-page.pot, package/gluon-status-page/i18n/ru.README
This is a draft to show the deployed mesh protocol as well as its version on the routers statuspage.
Its addresses another open point on the agenda of #1415.
An example router can be found at http://lilienstra-e.n.ffh.zone/, or in case our dns misbehaves http://[2001:678:978:114:b64b:d6ff:fe20:2778]/cgi-bin/status .
=> gluon-status-page: add mesh protocol to status-page

package/gluon-config-mode-contact-info/luasrc/lib/gluon/config-mode/wizard/0500-contact-info.lua, package/gluon-config-mode-core/luasrc/lib/gluon/config-mode/model/gluon-config-mode/wizard.lua, package/gluon-config-mode-domain-select/luasrc/lib/gluon/config-mode/wizard/0200-domain-select.lua, package/gluon-config-mode-geo-location/luasrc/lib/gluon/config-mode/wizard/0400-geo-location.lua, package/gluon-config-mode-hostname/luasrc/lib/gluon/config-mode/wizard/0100-hostname.lua, package/gluon-config-mode-mesh-vpn/luasrc/lib/gluon/config-mode/wizard/0300-mesh-vpn.lua, package/gluon-config-mode-outdoor/luasrc/lib/gluon/config-mode/wizard/0250-outdoor.lua, package/gluon-web-model/luasrc/usr/lib/lua/gluon/web/model/classes.lua
- Add a write() to form sections, so the wizard sections can call `save()` on the UCI cursor themselves
- Always run reconfigure after the wizard. This commits all packages.
This also avoids the `uci_sections()` handling in #2102.
=> Simplify save/commit handling of config wizard sections

package/gluon-config-mode-mesh-vpn/luasrc/lib/gluon/config-mode/reboot/0100-mesh-vpn.lua, package/gluon-config-mode-mesh-vpn/luasrc/lib/gluon/config-mode/wizard/0300-mesh-vpn.lua, package/gluon-mesh-vpn-core/luasrc/lib/gluon/mesh-vpn/update-config, package/gluon-mesh-vpn-core/luasrc/lib/gluon/upgrade/500-mesh-vpn, package/gluon-mesh-vpn-core/luasrc/usr/lib/lua/gluon/mesh-vpn.lua, package/gluon-mesh-vpn-fastd/luasrc/lib/gluon/upgrade/400-mesh-vpn-fastd, package/gluon-mesh-vpn-fastd/luasrc/usr/lib/lua/gluon/mesh-vpn/provider/fastd.lua, package/gluon-mesh-vpn-tunneldigger/luasrc/lib/gluon/upgrade/400-mesh-vpn-tunneldigger, package/gluon-mesh-vpn-tunneldigger/luasrc/lib/lua/gluon/mesh-vpn/provider/tunneldigger.lua, package/gluon-web-admin/files/lib/gluon/config-mode/view/admin/info.html
This fully abstracts VPN methods, making gluon-mesh-vpn-fastd and
gluon-mesh-vpn-tunneldigger completely self-contained.
Provide a LUA interface for generic interacting with VPN methods in
gluon-mesh-vpn-core and web packages.
This also adds the ability to install tunneldigger and fastd to the same
image, selecting the VPN method based on the selected domain.
=> mesh-vpn: fully abstract VPN methods

package/gluon-mesh-vpn-core/src/Makefile, package/gluon-mesh-vpn-core/src/respondd.c
Adds another provider to the same nodeinfo branch as #2216,
adds the fields `enabled` (bool) and `active` (string).
The contents of are taken from @blocktrron s lua api implemented in #2102 and therefore depends on it.
The code compiled and runs on http://meshvpnabstracttest.n.ffh.zone/
This is an excerpt from its nodeinfo:
```json
"mesh_vpn": {
"active": "fastd",
"enabled": false
},
```
This resolves another part of #644.
=> gluon-mesh-vpn-core: respondd active, enabled

package/gluon-status-page/files/lib/gluon/status-page/view/status-page.html
This reimplements the `Mesh VPN`-section on the statuspage in order to close another part of #1415.
Currently the section shows up, if fastd is installed.
Other providers are ignored.
The reimplementation takes whatever vpn-provider is configured as active and shows it below the info whether mesh-vpn is enabled. Both values are provided by respondd since the merge of #2219.
The current implementation is available for feedback on http://meshvpnabstracttest.n.ffh.zone/
=> gluon-status-page: vpn protocol

package/gluon-mesh-vpn-core/src/Makefile, package/gluon-mesh-vpn-core/src/respondd.c
Implements a respondd provider for bandwidth limits using simple-tc.
Due to their static nature, I added the limits to nodeinfo.
This is what the network tree looks like after merging this:
**this was edited**
```
"network": {
"addresses": [
"2a02:790:ff:714:b64b:d6ff:fe22:4ebc",
"2a02:790:ff:914:b64b:d6ff:fe22:4ebc",
"2a02:790:ff:1014:b64b:d6ff:fe22:4ebc",
"2001:678:978:114:b64b:d6ff:fe22:4ebc",
"2a02:790:ff:514:b64b:d6ff:fe22:4ebc",
"fdca:ffee:8:14:b64b:d6ff:fe22:4ebc",
"fe80::b64b:d6ff:fe22:4ebc"
],
"mesh": {
"bat0": {
"interfaces": {
"wireless": [
"b6:4b:d6:22:4e:c0",
"9a:62:78:2a:dd:59"
],
"tunnel": [
"9a:62:78:2a:dd:5f"
],
"other": [
"9a:62:78:2a:dd:5b"
]
}
}
},
"mesh_vpn": {
"bandwith_limit": {
"enabled": true,
"ingress": 5000,
"egress": 800
}
},
"mac": "b4:4b:d6:22:4e:bc"
},
``` …
=> gluon-mesh-vpn-core: respondd bandwidth_limit

package/gluon-status-page/files/lib/gluon/status-page/view/status-page.html, package/gluon-status-page/i18n/de.po, package/gluon-status-page/i18n/fr.README, package/gluon-status-page/i18n/gluon-status-page.pot, package/gluon-status-page/i18n/ru.README
**blocked** by #2216
There will be a bandwidth limit on the statuspage, eventually.
And likewise this might finally resolve #1415 .
This router has the necessary commits applied:
http://meshvpnabstracttest.n.ffh.zone/cgi-bin/status or
http://[2001:678:978:114:b64b:d6ff:fe22:4ebc]/cgi-bin/status
I implemented a bit-formatting function that looks like this, whether this should go in statuspage or a util file is up to decide.
```lua
local function formatBits(v, factor)
--to format a value given in kilobits use a factor of 1000
factor = factor or 1
units = {'k', 'M', 'G'}
units[0] = ''
bits = math.max(0, v*factor)
pow = math.floor(math.log(bits)/math.log(1000))
known_pow = math.min(pow, #units)
bits = bits/1000^known_pow
return string.format('%s%sbit', bits, units[known_pow])
end
```
This is …
=> gluon-status-page: add bandwidth limit

package/gluon-ebtables-filter-multicast/luasrc/lib/gluon/ebtables/355-mcast-drop, package/gluon-mesh-batman-adv/files/lib/netifd/proto/gluon_bat0.sh, patches/packages/routing/0003-batman-adv-Introduce-no-noflood-mark.patch, patches/packages/routing/0004-batctl-Add-noflood_mark-command.patch
Allow the transmission of IPv6 multicast packets as long as they are not flooded through the whole mesh.
This is achieved by adding a small "noflood mark" patch to batman-adv. With that multicast packets can be marked by iptables/ip6tables/ebtables as: "Please drop me, batman-adv, if I you'd flood me through the whole mesh."
That way it is now possible to send IPv6 packets with a link-local multicast if less than 16 nodes signed up for it (16 = batman-adv multicast fanout default).
This implements the remaining part of #1357.
=> gluon-ebtables-filter-multicast: relax IPv6 multicast firewall rules

README.md, docs/conf.py, docs/index.rst, docs/releases/v2021.1.rst, docs/site-example/site.conf, docs/user/getting_started.rst
release-notes for v2021.1
related to #2107
=> docs: Add v2021.1 release notes

package/gluon-mesh-vpn-core/src/respondd.c
In case the limit_ingress or limit_egress options are not present in
gluon's mesh_vpn section the respondd provider compares a string literal
with a NULL pointer, crashing respondd.
Check both pointers prior to comparing them in order to mitigate this
issue.
Suggested-by: Matthias Schiffer <mschiffer@universe-factory.net>
-----
read_stdout can return NULL and thus the return value need to be checked
prior to accessing it.
=> gluon-mesh-vpn-core: fix potential null pointer dereferences

docs/user/supported_devices.rst, package/gluon-core/luasrc/lib/gluon/upgrade/010-primary-mac, targets/ramips-mt76x8
INSTALLATION:
1. Connect to the serial port of the router and power it up.
If you get a prompt asking for boot-mode, go to step 3.
2. Unplug the router after
> Erasing SPI Flash...
> raspi_erase: offs:20000 len:10000
occurs on the serial port. Plug the router back in.
3. At the prompt select option 2 (Load system code then
write to Flash via TFTP.)
4. Enter 192.168.1.1 as the device IP and 192.168.1.2 as the
Server-IP.
5. Connect your computer to LAN1 and assign it as 192.168.1.2/24.
6. Rename the sysupgrade image to test.bin and serve it via TFTP.
7. Enter test.bin on the serial console and press enter.
https://github.com/acecilia/OpenWRTInvasion
You need to get the "stok" on the same machine that runs the exploit.
And in my case if Windows wont work, try a linux system.
*think …
=> ramips-mt76x8: add Xiaomi Mi Router 4A (100M Edition)

docs/user/supported_devices.rst, targets/ramips-mt76x8
As described here:
https://github.com/acecilia/OpenWRTInvasion
You need to get the "stok" on the same machine that runs the exploit.
And in my case if Windows wont work, try a linux system.
- led mapping
- radio leds
- [n/a] should map to their respective radio
- [n/a] should show activity
- [n/a] added board name to `is_outdoor_device` function in `package/gluon-core/luasrc/usr/lib/lua/gluon/platform.lua`
Device is running here: …
=> ramips-mt76x8: add Xiaomi Mi Router 4C

docs/user/supported_devices.rst, targets/ramips-mt7621
As described here:
https://github.com/acecilia/OpenWRTInvasion
You need to get the "stok" on the same machine that runs the exploit.
And in my case if Windows wont work, try a linux system.
- led mapping
- radio leds
- [n/a] should map to their respective radio
- [n/a] should show activity
- [n/a] added board name to `is_outdoor_device` function in `package/gluon-core/luasrc/usr/lib/lua/gluon/platform.lua`
Device is running here: …
=> ramips-mt7621: add Xiaomi Mi Router 4A (Gigabit Edition)

docs/user/supported_devices.rst
Fixes commit 89dc6b203d4d ("ramips-rt305x: drop devices with insufficient flash")
=> docs: remove dropped hardware from docs

modules
The OpenWrt routing feed was moved to the OpenWrt GitHub org.
Update the URL, as the old one might not work in the future.
=> modules: update routing feed URL

package/gluon-core/luasrc/usr/lib/lua/gluon/util.lua
The file_contains_line helper function was not testing whether a file
exists or not prior attempting to read from it.
Add this check to circumvent errors on the private WiFi config in
case the hwflags file is missing.
Reported-by: Tom Herbers <freifunk@tomherbers.de>
Tested-by: Tom Herbers <freifunk@tomherbers.de>
=> gluon-core: util: check if file exists prior to reading

docs/user/supported_devices.rst, targets/ath79-generic
` siemens-ws-ap3610`
- led mapping
- radio leds
=> ath79-generic: add support for Siemens WS-AP3610

package/gluon-status-page/luasrc/lib/gluon/status-page/controller/status-page.lua
It was found that a one second timeout for nodeinfo data may be too low,
so that when a node is otherwise occupied that timeout may be reached
too often.
The nodeinfo query response is also vital to the status-page base
template, so that when it times out, the site will be turned in a broken
state, that it cannot recover from.
Fixes: #2256
=> gluon-status-page: relax nodeinfo query timeout

package/gluon-core/luasrc/lib/gluon/upgrade/020-interfaces
Delete all default network device sections upon first boot.
Only LAN & WAN networks are defined at this point. We are using the
legacy way of definiting bridges via the interface sections ifname
option.
The prior filtering was based upon a single device and didn't take into
consideration that DSA interface names can be named arbitrarily.
=> gluon-core: delete all network device sections

package/gluon-core/luasrc/usr/lib/lua/gluon/wireless.lua
The PHY lookup helper "find_phy_by_path" could not lookup the PHY name
for paths from multi-phy devices.
An example for such a path would be:
'1e140000.pcie/pci0000:00/0000:00:01.0/0000:02:00.0+1'
The integer after the plus (+) character determines the PHY index of the
specific device in relation to the PHY with the lowest index of the
device.
For example, if the device provides phy2 and phy3, the above path would
describe phy3. In case the device provides phy0 and phy1, it would
describe phy1.
Rewrite the "find_phy_by_path" function to support those paths as well
as regular device paths in a universal manner.
=> gluon-core: wireless: support PHY lookup for multi-PHY devices

package/gluon-core/luasrc/lib/gluon/upgrade/020-interfaces
=> gluon-core: use uci:delete_all() instead of foreach()+delete()

docs/user/supported_devices.rst, targets/ramips-mt76x8
=> ramips-mt76x8: add support for RAVPower RP-WD009

package/gluon-core/Makefile, package/gluon-node-info/Makefile, package/gluon-setup-mode/Makefile, package/gluon-wan-dnsmasq/Makefile
Specify conffiles for our packages, so they aren't overwritten during
opkg updates. While this only matters during development, it is
unintended to have different behaviour for opkg update and full firmware
updates.
=> treewide: correctly specify conffiles

contrib/push_pkg.sh, contrib/run_qemu.sh, docs/dev/packages.rst
v2: In contrast to the last patches, this is now built on top of ssh
only, without using e.g. 9pfs. Furthermore it works also with
arbitary remote hosts on any target/architecture. Also the
scripts were renamed and moved to /scripts.
The aim of this commit is to allow fast rebuild cycles during the
development of gluon packages.
Currently the following workflow can be used:
scripts/run_qemu.sh output/images/factory/[...].img
vi package/gluon-ebtables/files/etc/init.d/gluon-ebtables
scripts/push_pkg.sh package/gluon-ebtables/
...
...
scripts/push_pkg.sh package/gluon-ebtables/
...
(and so on...)
Implementation details:
- Currently this is based on ssh/scp.
- Opkg is used to install/update the packages in the remote machine.
Benefits:
- This works with compiled and non-compiled packages.
- …
=> scripts: Add push_pkg.sh to enhance package development workflow (v2)

docs/user/supported_devices.rst, targets/ramips-mt76x8
TP-Link RE200 v2 is a wireless range extender with Ethernet and 2.4G and 5G
WiFi with internal antennas. It's based on MediaTek MT7628AN+MT7610EN.
- MediaTek MT7628AN (580 Mhz)
- 64 MB of RAM
- 8 MB of FLASH
- 2T2R 2.4 GHz and 1T1R 5 GHz
- 1x 10/100 Mbps Ethernet
- UART header on PCB (57600 8n1)
- 8x LED (GPIO-controlled), 2x button
There are 2.4G and 5G LEDs in red and green which are controlled
separately.
- led mapping
- radio leds
=> ramips-mt76x8: add support for TP-Link RE200 v2

docs/user/supported_devices.rst, targets/ath79-generic
- led mapping
- radio leds - none
=> ath79-generic: add support for Joy-IT JT-OR750i

docs/user/supported_devices.rst, package/gluon-core/luasrc/usr/lib/lua/gluon/platform.lua, targets/ipq40xx-generic
root@bc9fe4c21a3a:/# lua -e 'print(require("platform_info").get_image_name())'
aruba-ap-365
- led mapping
- radio leds *NONE*
- switchport leds *NONE*
=> ipq40xx: add support for Aruba AP-365 / InstantOn AP17

docs/user/supported_devices.rst, targets/ath79-generic
- led mapping
- radio leds
Only WDR3600 was checked, but it can be assumed that the WDR4300 is working fine as well due to the similarity of these two devices.
I have also tested a sysupgrade from Gluon v2019.1.x and haven't found any issues; no special migrations are necessary.
=> ath79-generic: add TP-Link TL-WDR3600/4300

docs/user/supported_devices.rst, package/gluon-core/luasrc/usr/lib/lua/gluon/platform.lua, targets/ath79-generic
Fix for #2281 
(cannot test this yet but should work)
- led mapping
- radio leds
=> Add support for tp-link CPE510 V3
