docs/site-example/site.conf
docs/user/site.rst

This PR documents functionality added by
https://github.com/freifunk-gluon/packages/pull/95

docs: skipping of setup mode

---

docs/site-example/site.conf
docs/user/site.rst

Signed-off-by: Daniel Golle <daniel@makrotopia.org>

docs: add mesh_vlan entry

---

docs/releases/v2015.1.rst
docs/site-example/site.conf

Companion-PR to freifunk-gluon/packages#108

Document changes to hostname_prefix field of site.conf

---

package/gluon-luci-wifi-config/Makefile
package/gluon-luci-wifi-config/files/usr/lib/lua/luci/controller/admin/wifi-config.lua
package/gluon-luci-wifi-config/files/usr/lib/lua/luci/model/cbi/admin/wifi-config.lua

This is the new Pull-Request for this Package.
This ist the old one:
https://github.com/freifunk-gluon/packages/pull/93
I know, that this doesn't survive Updates, but as @tcatm requested I will open a second Pull-Request which fixes the issue and also adds options for the site.conf.

Add the package gluon-luci-wifi-config

---

package/gluon-radvd/src/gluon-radvd.c

By introducing a new option -a in addition to -p this patch allows
controlling the on-link flag of announcements.
A prefix specified using -a will have the on-link flag set to zero
while a prefix specified using -p will retain its behaviour (i.e.
on-link flag set).
Example:
gluon-radvd -i local-node -p 2001:db8:aaaa:/64 -a 2001:db8:bbbb::/64
This will announce 2001:db8:aaaa::/64 with the on-link flag set and
2001:db8:bbbb::/64 with the flag unset.

gluon-radvd: on-link flag

---

patches/openwrt/0027-odhcp6c-minor-fixes.patch

This helps with multiple radvds.

odhcp6c: minor fixes

---

package/gluon-core/files/usr/lib/lua/gluon/util.lua

additional information for commit 2a93c580428d10724116b0d2d1238e2745715a14
mac group 5

add: info for 802.11s interface (mac)

---

targets/ar71xx-generic/profiles.mk

Tested wireless, meshing, config mode, reset switch, lan ports. Everything works fine.

Add support for WHR-HP-G300N

---

docs/site-example/site.conf
docs/user/site.rst
package/gluon-mesh-batman-adv-core/check_site.lua
package/gluon-mesh-batman-adv-core/files/lib/gluon/upgrade/310-gluon-mesh-batman-adv-core-mesh

gluon-mesh-batman-adv-core: make gateway selection class configurable

---

package/gluon-announce/files/usr/lib/lua/gluon/announce.lua
package/gluon-announced/files/usr/lib/lua/gluon/announced.lua

collect_dir() will now pre-load all files and return a function that will
collect all information.

gluon-announce: build a tree of functions first

---

docs/user/getting_started.rst

There was a duplicate article in the text. I removed theme.

doc: remove duplicate article in getting_started.rst

---

docs/features/wired-mesh.rst

Confusion auf WAN an LAN, that part of the file is about mesh-on-lan.

Confusion of WAN an LAN, this line is for mesh-on-lan

---

LICENSE

In line 2: indiviual -> individual

Fix typo in LICENSE

---

targets/ar71xx-generic/profiles.mk

Signed-off-by: Felix Kaechele <felix@kaechele.ca>

targets/ar71xx-generic: add WD MyNet N600/N750

---

docs/releases/v2015.2.rst

docs: add v2015.2 release notes

---

docs/user/site.rst

Corrected version of commit 4245baa from #580
@rubo77

docs: Improve documentation of fastd and autoupdater config in site.conf

---

Makefile
package/gluon-core/Makefile
package/gluon-core/files/usr/lib/lua/gluon/site_config.lua
package/gluon-site/Makefile
patches/openwrt/0046-lua-fix-installation-of-headers-for-host-build.patch
patches/packages/openwrt/0003-lua-cjson-add-host-build-support.patch
scripts/check_site.sh
scripts/site.sh
scripts/site_config.lua

Convert site.conf to JSON during build

---

patches/openwrt/0048-ar71xx-add-support-for-TP-Link-TL-WR1043ND-v3.patch
targets/ar71xx-generic/profiles.mk

add support for new revision v3 of TP-Link TL-WR1043ND
it seems to be exactly the same hardware

ar71xx: add support for TP-Link TL-WR1043ND v3

---

docs/features/autoupdater.rst

fix typo and express sentence regarding update priority clearer

docs: Update autoupdater.rst

---

patches/openwrt/0049-x86-generic-refresh-kernel-config.patch
patches/openwrt/0050-x86-generic-enable-pata_atiixp-driver.patch

Signed-off-by: Felix Kaechele <felix@kaechele.ca>
Fixes #490

backport: Futro support in x86-generic

---

scripts/update.sh

Possibility to work with git submodules

git submodules

---

docs/index.rst
targets/ar71xx-generic/profiles.mk

This CPE is supported by OpenWRT and already running in Chemnitz

Add support for TP-Link TL-WA7510N

---

package/gluon-status-page/src/js/lib/gui/statistics.js

gluon-status-page: sort gateways alphabetically

---

docs/features/autoupdater.rst

Update Gluon docs
Add missing parameter documentation --fallback

docs: autoupdater's fallback option

---

package/gluon-mesh-batman-adv-core/src/respondd.c

[batman-adv-core/respondd] add gateway_nexthop

---

targets/sunxi/profiles.mk

build- and run-tested with 2016.1.4, boots but some packet loss on eth0
omitted ata due to build errors

add Banana Pro

---

docs/package/gluon-ebtables-segment-mld.rst
package/gluon-ebtables-filter-multicast/files/lib/gluon/ebtables/100-mcast-chain
package/gluon-ebtables-filter-multicast/files/lib/gluon/ebtables/110-mcast-allow-icmpv6
package/gluon-ebtables-filter-multicast/files/lib/gluon/ebtables/300-mcast
package/gluon-ebtables-filter-multicast/files/lib/gluon/ebtables/355-mcast-drop
package/gluon-ebtables-segment-mld/Makefile
package/gluon-ebtables-segment-mld/files/lib/gluon/ebtables/100-mcast-in-chain
package/gluon-ebtables-segment-mld/files/lib/gluon/ebtables/101-mcast-in-rule
package/gluon-ebtables-segment-mld/files/lib/gluon/ebtables/105-mcast-drop-igmp
package/gluon-ebtables-segment-mld/files/lib/gluon/ebtables/105-mcast-drop-mld
package/gluon-ebtables/files/etc/init.d/gluon-ebtables
package/gluon-ebtables/files/lib/gluon/ebtables/100-dir-chain
package/gluon-ebtables/files/lib/gluon/ebtables/350-mcast-dir-rules

Addresses #553, prepares for #278 (#402).

Filter IGMP+MLD

---

targets/ar71xx-generic/profiles.mk

Have the Tube2H up and running well.
Can't see a problem yet.

Verified Tube2h, Removed BROKEN

---

docs/user/getting_started.rst
patches/openwrt/0123-ath10k-firmware-add-ath10k-firmware-qca988x-11s.patch
targets/ar71xx-generic/profiles.mk

Completely untested at the moment.

Add 11s-capable ath10k firmware

---

patches/openwrt/0013-fix-UBNT-XM-model-detection.patch

added the Ti version to the detection algo

added UBNT Rocket Ti versions

---

targets/ar71xx-generic/profiles.mk

as there is often the question if this version is supported as well

make UBNT image names consistent

---

package/gluon-mesh-batman-adv-core/src/respondd.c

Fixes #941
@mokkin: This is only compile tested, place check if this fixes your issue.

gluon-mesh-batman-adv-core: respondd: correctly detect lower interface types

---

targets/mvebu/profiles.mk
targets/targets.mk

This PR adds support for the Linksys WRT1200AC.

Add support for mvebu target

---

docs/dev/basics.rst

* use tabs instead of spaces
* use jsonfilter for speed

add rules for coding guide tabs, jsonfilter

---

package/gluon-core/luasrc/usr/lib/lua/gluon/util.lua

this can then be used by the statuspage et al.

gluon-core: add function to gluon.util that returns all active mesh-devices

---

package/gluon-luci-portconfig/luasrc/usr/lib/lua/luci/model/cbi/admin/portconfig.lua

as a preparation for adding a vxlan configuration option, change spaces to tabs in portconfig.lua
No functional change are made in this PR.

gluon-luci-portconfig: portconfig.lua: change spaces to tabs

---

docs/index.rst
targets/ar71xx-generic/profiles.mk

ar71xx-generic: TP-Link WBS210/510 remove BROKEN

---

package/gluon-respondd/files/etc/init.d/gluon-respondd

This provides one possible solution for #984 
This implies that the hopglass configuration is also changed in the meshes to use ff05:... instead of ff02:..
This is already working with a hopglass instance in FFM

have respondd work on ff05 in addition to ff02

---

package/gluon-status-page/src/js/lib/gui/neighbours.js
package/gluon-status-page/src/js/lib/gui/nodeinfo.js
package/gluon-status-page/src/js/lib/gui/statistics.js
package/gluon-status-page/src/js/lib/helper.js

gluon-status-page: JS translations

---

package/gluon-l3roamd/Makefile
package/gluon-l3roamd/files/etc/init.d/gluon-l3roamd
package/gluon-l3roamd/luasrc/lib/gluon/upgrade/380-gluon-l3roamd-route

this adds a package for configuring l3roamd for gluon.

gluon-l3roamd: add package containing basic l3roamd configuration

---

docs/features/monitoring.rst

Update outdated links of alfred and alfred-json

Update alfred README and alfred-json links

---

package/gluon-config-mode-mesh-vpn/luasrc/lib/gluon/config-mode/reboot/0100-mesh-vpn.lua

with tunneldigger the reboot page warned for disabled vpn

gluon-config-mode-mesh-vpn: add tunneldigger to reboot page

---

package/gluon-status-page/src/js/lib/gui/nodeinfo.js
package/gluon-status-page/src/js/lib/helper.js

The statuspage contains some contents that are not localized and german translations are missing.
This should address the issue.

localize the status page some more

---

patches/lede/0045-ar71xx-add-support-for-TP-Link-TL-WR1043N-v5.patch
targets/ar71xx-generic

This adds support for TL-WR1043N v5.
closes #1260

ar71xx: add support for TP-Link TL-WR1043N v5

---

docs/features/dns-cache.rst
package/gluon-core/check_site.lua

explain that not setting dns.servers makes no sense

---

Makefile
docs/index.rst
docs/user/getting_started.rst
targets/ar71xx-generic
targets/ipq806x
targets/targets.mk

List additional targets if GLUON_WLAN_MESH=11s (default is 11s)
Closes #1242

build: introduce GLUON_WLAN_MESH build variable

---

docs/user/getting_started.rst
docs/user/site.rst

fixes an error and removes the focus on ath10k
this way, it's also shorter without removing information

docs: move GLUON_WLAN_MESH to site.rst & improve text

---

targets/ar71xx-generic
targets/ar71xx-tiny
targets/ipq806x
targets/ramips-mt7621

this removes a check that was obsoleted and updates/cleans up the BROKEN comments

target files cleanup: variable checks and comments

---

package/gluon-core/Makefile
package/gluon-core/luasrc/lib/gluon/upgrade/200-wireless

Patch originally authored by @oleeander, tested and fixed by myself.
Fixes #424

Upgrade 11ac radios to VHT20

---

docs/index.rst
docs/package/gluon-ebtables-limit-arp.rst

based on package documentation, authored by T_X
https://github.com/freifunk-gluon/gluon/blob/84a6f65f02d7e36a073ba2839712f0c0bb1dda10/package/gluon-ebtables-limit-arp/Makefile#L18-L39
fixes #1383

docs: add package/gluon-ebtables-limit-arp

---

docs/features/wired-mesh.rst
docs/index.rst
docs/multidomain-site-example/domains/alpha_centauri.conf
docs/releases/v2018.1.rst
docs/site-example/site.conf
docs/user/site.rst

This is still WIP (I have not written the site config section yet), but the sooner we have reviewed this, the sooner we can release.

docs: add v2018.1 release notes and assorted docs

---

docs/index.rst
package/gluon-core/luasrc/lib/gluon/upgrade/010-primary-mac
patches/openwrt/0008-ar71xx-fix-TP-Link-Archer-C7-v5-switch-LEDs.patch
targets/ar71xx-generic

@rotanid testing
@blocktrron author
me? I'm just adding this pr so people can find the change and not start form scratch.

ar71xx: add support for Archer C7 v5

---

docs/releases/v2018.1.rst

docs: releases/v2018.1: add remark about GLUON_WLAN_MESH variable

---

package/gluon-mesh-babel/src/respondd.c
package/gluon-mesh-batman-adv/src/respondd.c

Only compile-tested so far, I won't be able to run-test it before tomorrow.
Fixes #1135.

Do not count clients inactive for more than 60s 

---

docs/user/site.rst

I also added this block in the batman wiki: https://www.open-mesh.org/projects/batman-adv/wiki/Gateways
If there are clarifications to do, please clarify in the wiki, I will adapt this PR then

docs: clarify routing_algo example for BATMAN_V

---

package/gluon-status-page/files/lib/gluon/status-page/view/status-page.html
package/gluon-status-page/i18n/de.po
package/gluon-status-page/i18n/gluon-status-page.pot

Fixes: #659
Signed-off-by: Martin Weinelt <martin@darmstadt.freifunk.net>

gluon-status-page: display position and link it with geo uri scheme

---

docs/index.rst
docs/releases/v2018.2.rst
docs/user/site.rst

docs: add v2018.2 release notes

---

package/gluon-mesh-batman-adv/files/lib/gluon/ebtables/250-next-node

Fixes #1659
@RalfJung Could you check if this is working as expected?

gluon-mesh-batman-adv: drop packets from mesh with next-node source or destination address

---

package/gluon-config-mode-mesh-vpn/i18n/de.po
package/gluon-config-mode-mesh-vpn/i18n/fr.po
package/gluon-config-mode-mesh-vpn/i18n/gluon-config-mode-mesh-vpn.pot
package/gluon-config-mode-mesh-vpn/luasrc/lib/gluon/config-mode/wizard/0300-mesh-vpn.lua
package/gluon-mesh-vpn-core/luasrc/lib/gluon/mesh-vpn/update-config
package/gluon-mesh-vpn-core/luasrc/lib/gluon/upgrade/500-mesh-vpn

untested as I currently lack a build env and it will be a few days before I will.

gluon-config-mode-mesh-vpn: display tc limits in Mbit/s

---

package/gluon-web-mesh-vpn-fastd/luasrc/lib/gluon/config-mode/model/admin/mesh_vpn_fastd.lua

Due to the fixes in 4249d65af73ee9228d827af913b7caf2aac00809 the comments have to change too

fix luacheck warnings : fix comments accordingly

---

docs/index.rst

docs: improve note on targets without IBSS support

---

docs/multidomain-site-example/site.mk
docs/site-example/site.mk
package/features

Fixes #1775
@christf Should this also be included for gluon-mesh-babel by default?

RFC: features: include gluon-radvd by default

---

targets/ar71xx-generic

see #1692 for tests and discussion.
build and run tested on a TL-WR1043ND v1

ar71xx-generic: add zram-swap to boards with 8M flash but only 32M memory

---

package/gluon-mesh-babel/src/neighbours-babel.c
package/gluon-mesh-babel/src/respondd.c

as discussed in #1799, selecting the two small commits into this PR to allow different review/merge cycle.

Fix Memory and adjust to new libbabelhelper interfac

---

package/gluon-status-page/files/lib/gluon/status-page/view/status-page.html
package/gluon-status-page/i18n/de.po
package/gluon-status-page/i18n/gluon-status-page.pot
package/gluon-status-page/luasrc/lib/gluon/status-page/controller/status-page.lua

gluon-status-page: add domain and site to status page

---

package/gluon-core/luasrc/lib/gluon/upgrade/010-primary-mac
targets/ar71xx-generic

Here are the neccessary changes to be made for #1837 (Add Support for TP-LINK Archer C60 v2)!

Add support archer c60v2

---

docs/features/multidomain.rst

reboot is not necessary anymore.

docs: features/multidomain.rst - instead of reboot use gluon-reload.

---

docs/package/gluon-radv-filterd.rst

docs: gluon-radv-filterd: enhance documentation with example

---

contrib/ci/Jenkinsfile

Fixes
```
Branch indexing
Connecting to https://api.github.com using gluon-jenkins/******
Obtained contrib/ci/Jenkinsfile from b25a05eec4cc17c5421db479bd1878fcaa42068b
Running in Durability level: MAX_SURVIVABILITY
GitHub has been notified of this commit’s build result
org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
WorkflowScript: 42: unexpected char: '#' @ line 42, column 1.
^
1 error
at org.codehaus.groovy.control.ErrorCollector.failIfErrors(ErrorCollector.java:310)
at org.codehaus.groovy.control.ErrorCollector.addFatalError(ErrorCollector.java:150)
at org.codehaus.groovy.control.ErrorCollector.addError(ErrorCollector.java:120)
at org.codehaus.groovy.control.ErrorCollector.addError(ErrorCollector.java:132)
at …
```

contrib/ci: fix commenting in Jenkinsfile

---

README.md
docs/conf.py
docs/index.rst
docs/releases/v2020.1.rst
docs/site-example/site.conf
docs/user/getting_started.rst

Release notes written by @blocktrron and @mweinelt. So everyone else is invited to review.
@christf If you have significant babel changes that need to be mentioned please speak up.

Gluon v2020.1

---

package/gluon-mesh-vpn-tunneldigger/luasrc/usr/bin/tunneldigger-watchdog

Fixes https://github.com/freifunk-gluon/gluon/issues/1952

tunneldigger-watchdog: only search for exactly the tunneldigger binary

---

.editorconfig
docs/dev/basics.rst

Resolves #1929
Not a big deal, mostly just codifying what we already agreed on.
Did I mess any exceptions?

add .editorconfig

---

README.md
docs/index.rst
docs/releases/v2020.1.2.rst
docs/site-example/site.conf
docs/user/getting_started.rst

Here are the preliminary release notes for Gluon v2020.1.2
Relates to #1981

docs: add v2020.1.2 release notes

---

docs/dev/hardware.rst

docs: dev: add link to device checklist

---

package/gluon-config-mode-outdoor/luasrc/lib/gluon/config-mode/wizard/0250-outdoor.lua
package/gluon-core/luasrc/lib/gluon/upgrade/180-outdoors
package/gluon-core/luasrc/usr/lib/lua/gluon/platform.lua
package/gluon-setup-mode/luasrc/lib/gluon/upgrade/320-setup-ifname

Opening as draft, as this is completely untested so far. I intend to try out this on a few devices tomorrow or on the weekend.

Reuse outdoor device logic for setup mode interface selection, plus some cleanup

---

README.md
docs/conf.py
docs/index.rst
docs/releases/v2020.1.3.rst
docs/site-example/site.conf
docs/user/getting_started.rst

This adds the Releasenotes for the Gluon v2020.1.3 release.

add Gluon v2020.1.3 releasenotes

---

package/gluon-web-model/files/lib/gluon/web/view/model/form.html
package/gluon-web-model/files/lib/gluon/web/view/model/section.html
package/gluon-web-model/luasrc/usr/lib/lua/gluon/web/model/classes.lua

- Fixes two bugs in gluon-web-model features that are currently unused
- Implements support for adding dependencies to whole sections, as requested in  #1349.

gluon-web-model: bugfixes and section depends

---

package/gluon-radv-filterd/src/gluon-radv-filterd.c
package/gluon-radv-filterd/src/mac.h

gluon-radv-filterd: minor cleanup

---

targets/ar71xx-generic

Clean up aliases (moving minor version strings to manifest_aliases) and add the new CPE210 3.1 and 3.20 strings to allow upgrades.
Closes: #2080

New CPE210/... v3 versions strings

---

.editorconfig
.github/workflows/lint.yml

Linting has until now been done by Jenkins, but the integration of actions is a bit more helpful and integrated here.

actions: add linter actions for lua and shell script

---

README.md
docs/conf.py
docs/index.rst
docs/releases/v2020.1.4.rst
docs/site-example/site.conf
docs/user/getting_started.rst

doc changes and release notes for release v2020.1.4

---

README.md
docs/conf.py
docs/index.rst
docs/releases/v2020.2.1.rst
docs/site-example/site.conf
docs/user/getting_started.rst

doc changes and release notes for release v2020.2.1

---

docs/user/supported_devices.rst

I forgot to include the docs in #2113

docs: Add Netgear EX3700 and EX3800

---

README.md
docs/conf.py
docs/index.rst
docs/releases/v2020.2.2.rst
docs/site-example/site.conf
docs/user/getting_started.rst

[2020.2.x] doc changes and release notes for release v2020.2.2

---

.github/workflows/build-gluon.yml
contrib/actions/generate-actions.py
contrib/actions/install-dependencies.sh
contrib/actions/sources.list

There should be no reason why our CI cannot run on the latest Ubuntu LTS.

Relax CI Runner version pin

---

README.md
docs/conf.py
docs/index.rst
docs/releases/v2020.2.3.rst
docs/site-example/site.conf
docs/user/getting_started.rst

Closes #2194
https://github.com/freifunk-gluon/gluon/wiki/Release-Process

docs: Add v2020.2.3 release notes

---

docs/user/getting_started.rst

@mweinelt  Regarding our discussion on IRC, hoping not to have identified a temporary or second hand location.

Mention names of opkg-keys in doc

---

docs/dev/basics.rst

docs: add 'make refresh-patches'

---

README.md

Preview here
https://github.com/freifunk-gluon/gluon/tree/badges

README.md: add some badges

---

.github/workflows/build-gluon.yml

Add the newly added mediatek-mt7622 to the firmware build-test matrix.

actions: add mediatek-mt7622 target

---

.readthedocs.yml
docs/_static/css/custom.css
docs/requirements.txt

Rendered version at https://gluon.readthedocs.io/en/doctheme/

docs: update Sphinx theme

---

package/gluon-state-check/Makefile
package/gluon-state-check/files/lib/gluon/state/check.d/has_default_gw6
package/gluon-state-check/files/usr/lib/micron.d/gluon-state-check
package/gluon-state-check/luasrc/usr/sbin/gluon-state-check

~This intends to eventually resolve 2228.~
This will no longer complete #2228.
It does it's job, but is still up for refactoring;
I just wanted to give a chance for early feedback and a forming discussion for this,
in case it's not what it's supposed to become.

gluon-state: implement ipv6 default route check

---

README.md
docs/conf.py
docs/index.rst
docs/releases/v2021.1.1.rst
docs/site-example/site.conf
docs/user/getting_started.rst

Currently soft-blocked by #2284

docs: add Gluon v2021.1.1 release notes

---

Makefile
scripts/update-modules.sh

Scripted workflow to check the modules for updates and, if available, commit them with a shortlog.
Example: #2293

scripts: add update-modules helper

---

package/gluon-neighbour-info/src/gluon-neighbour-info.c

Currently a buffer with a fixed size of 8192 bytes is used. However the
result can potentially be larger, which leads to a truncated JSON
output on stdout. UDP packets, without compression and with IP
fragmentation, can be up to 64KiB large.
Instead of using a fixed size buffer on the stack ask the kernel first
about the size of the UDP data and allocate a buffer of appropriate size
on the heap before receiving the UDP data.
The issue was observed with a custom respondd provider.

gluon-neighbour-info: fix broken output with large results

---

.github/dependabot.yml

Hello,
I have added a dependabot.yml configuration file. Dependabot will check for updates of the gh-actions used as well as the python requirements in the docs folder on a monthly basis.

Added: Dependabot.yml config

---

docs/dev/basics.rst
docs/user/getting_started.rst

Add some explanation when `make update` needs to be run again.
Supersedes #2215.

docs: user/getting_started: add a footnote regarding `make update`

---

package/gluon-status-page/files/lib/gluon/status-page/view/status-page.html

This completes f5163ac18b,
which introduced the bug and therefore resolves #2370.
@herbetom might review this. Thanks!

gluon-status-page: split bwlimit into two lines

---

docs/user/supported_devices.rst
targets/ath79-generic

This is a followup of #2428.
> I think the test of the AC Mesh is sufficient
_@neoraider in hackint#gluon_

ath79-generic: (re)add unifi-ac-{lite,lr}

---

package/gluon-setup-mode/files/etc/hotplug.d/button/50-gluon-setup-mode
package/gluon-setup-mode/files/usr/bin/gluon-enter-setup-mode

Script to enable config mode and reboot
Fixes #2412

gluon-setup-mode: add gluon-enter-setup-mode

---

package/gluon-mesh-vpn-core/Makefile
targets/generic

Reduce flash consumption by removing dependencies pulling in nftables as well as stripping parts of the kernel which are not required for Gluon.
```
OCEDO Raccoon
-------------
Before: 6226728
After: 6030120
```

generic: reduce flash consumption

---

.luacheckrc
contrib/ci/minimal-site/site.conf
package/gluon-autoupdater/check_site.lua
package/gluon-autoupdater/luasrc/lib/gluon/upgrade/500-autoupdater
package/gluon-core/luasrc/lib/gluon/check-site.lua

Closes #2519
Closes #2532
Checked build with:
- Valid branch: OK
- Unset branch: OK
- Invalid branch: Build failed as expected

gluon-autoupdater: check default branch name, check number of pubkeys, revert invalid branch on update/reconfigure

---

modules

83b0e20711 ramips: fix RT-AC57U button level

modules: update OpenWrt

---

docs/releases/index.rst
docs/releases/v2022.1.1.rst

(cherry picked from commit 59c5eb6866423b443f1de25bfe1632ae250e64fe)

docs: add Gluon 2022.1.1 release notes

---

docs/user/supported_devices.rst

affected:
- CPE510
- WBS210
- Archer C50

docs/supported_devices: regroup revisions

---

docs/releases/v2022.1.1.rst
docs/releases/v2022.1.rst

add link to issue #2672 in known issues section of the release notes

docs: update v2022.1.x release notes known issues section

---

.github/ISSUE_TEMPLATE/bug_report.md

issue_template/bug_report: fix indentation

---

.editorconfig
contrib/i18n-scan.pl
scripts/copy_output.lua
scripts/update.sh
targets/lantiq-xrx200
targets/ramips-mt7621

Just the next ballast, to make the linter PR smaller.

Fix targets, scripts & contrib

---

.editorconfig
package/gluon-config-mode-theme/files/lib/gluon/config-mode/view/theme/layout.html
package/gluon-web-admin/files/lib/gluon/config-mode/view/admin/upgrade_confirm.html
package/gluon-web-mesh-vpn-fastd/files/lib/gluon/config-mode/view/mesh-vpn-fastd.html
package/gluon-web-model/files/lib/gluon/web/view/model/warning.html
package/gluon-web/files/lib/gluon/web/view/error/404.html
package/gluon-web/files/lib/gluon/web/view/error/500.html

I'm not sure whether this breaks the layout or not; will test it later this afternoon.

html indentation

---

.github/ISSUE_TEMPLATE/bug_report.md
contrib/i18n-scan.pl
docs/dev/build.rst
docs/features/vpn.rst
docs/releases/v2020.2.3.rst
docs/releases/v2021.1.1.rst
docs/user/mtu.rst
package/gluon-config-mode-theme/sass/gluon.scss
package/gluon-core/luasrc/usr/lib/lua/gluon/wireless.lua
package/gluon-ebtables-limit-arp/src/lookup3.c
package/gluon-status-page/i18n/ru.README
package/gluon-status-page/sass/status-page.scss
package/gluon-web/luasrc/usr/lib/lua/gluon/web/http/protocol.lua

Signed-off-by: Stefan Weil <sw@weilnetz.de>

Fix some typos (found by codespell)

---

.editorconfig
package/gluon-autoupdater/src/respondd.c
package/gluon-mesh-babel/src/respondd.c
package/gluon-mesh-batman-adv/src/respondd-common.h
package/gluon-mesh-batman-adv/src/respondd-neighbours.c
package/gluon-mesh-batman-adv/src/respondd-nodeinfo.c
package/gluon-mesh-batman-adv/src/respondd-statistics.c
package/gluon-mesh-batman-adv/src/respondd.c
package/gluon-mesh-vpn-core/src/respondd.c
package/gluon-mesh-vpn-fastd/src/respondd.c
package/gluon-mesh-vpn-wireguard/src/respondd.c
package/gluon-neighbour-info/src/gluon-neighbour-info.c
package/gluon-node-info/src/respondd.c
package/gluon-radv-filterd/src/gluon-radv-filterd.c

This alone was rather painful to assemble.
I'd suggest, we let the action run through and if this does not break on compilation, we can assess how to go on with this monstrosity.

migrate several c files to spdx

---

docs/conf.py
package/gluon-respondd/src/respondd-common.h
package/gluon-respondd/src/respondd-neighbours.c
package/gluon-respondd/src/respondd-nodeinfo.c
package/gluon-respondd/src/respondd-statistics.c
package/gluon-respondd/src/respondd.c
package/gluon-setup-mode/files/etc/config/gluon-setup-mode
package/gluon-setup-mode/files/lib/gluon/setup-mode/rc.d/S20network
package/gluon-status-page/files/lib/gluon/status-page/www/cgi-bin/dyn/neighbours-nodeinfo
package/gluon-status-page/files/lib/gluon/status-page/www/cgi-bin/dyn/stations
package/gluon-wan-dnsmasq/files/etc/hotplug.d/iface/50-gluon-wan-dnsmasq
package/libgluonutil/src/libgluonutil.c
package/libgluonutil/src/libgluonutil.h

The last remnants that were either recently introduced, did not match a group before, or were overlooked.

Editorconfig leftovers

---

package/gluon-autoupdater/src/respondd.c
package/gluon-core/src/site.c
package/gluon-ebtables-limit-arp/src/addr_store.c
package/gluon-ebtables-limit-arp/src/addr_store.h
package/gluon-ebtables-limit-arp/src/gluon-arp-limiter.c
package/gluon-ebtables-limit-arp/src/lookup3.c
package/gluon-ebtables-limit-arp/src/mac.c
package/gluon-mesh-batman-adv/src/respondd-neighbours.c
package/gluon-mesh-batman-adv/src/respondd-nodeinfo.c
package/gluon-mesh-batman-adv/src/respondd-statistics.c
package/gluon-mesh-vpn-fastd/src/respondd.c
package/gluon-mesh-vpn-wireguard/src/respondd.c
package/gluon-neighbour-info/src/gluon-neighbour-info.c
package/gluon-radv-filterd/src/gluon-radv-filterd.c
package/gluon-radv-filterd/src/mac.h
package/gluon-respondd/src/respondd-neighbours.c
package/gluon-respondd/src/respondd-statistics.c
package/gluon-status-page-mesh-batman-adv/src/neighbours-batadv.c
package/gluon-status-page/src/stations.c
package/gluon-web/src/template_lmo.c
package/gluon-web/src/template_lualib.c
package/gluon-web/src/template_parser.c
package/gluon-web/src/template_utils.c
package/libbatadv/src/batadv-genl.c
package/libbatadv/src/batadv-genl.h

@lemoer suggested to break #2747 into two parts.
So this is the simple one, that should be about as easy (and annoying) to review as the PR's @rotanid reviewed in the last days. Thanks :/

C indentation

---

.editorconfig
.github/workflows/lint.yml
Makefile
contrib/docker/Dockerfile
scripts/lint-editorconfig.sh
targets/ramips-mt7621

Instead of pointing out those issues manually and finding them by chance, let's run the `editorconfig-checker`.

actions: add editorconfig checker

---

package/gluon-web-cellular/i18n/de.po

gluon-web-cellular: add German translation

---

LICENSE
docs/conf.py

This should be backported before we release anything in 2023, no?

docs,LICENSE: Drop copyright years

---

docs/releases/index.rst
docs/releases/v2022.1.3.rst

> (cherry picked from commit 190d7f87018cd7f4a5586fc344e4e535e8d8ca8d)

docs: Add v2022.1.3 release notes

---

.github/dependabot.yml
README.md
docs/releases/v2018.1.2.rst
docs/user/mtu.rst

Some external links changed slightly, this pull request updates those.

docs: Update external links

---

docs/user/supported_devices.rst
targets/ramips-mt76x8

Signed-off-by: Richard Fröhning <misanthropos@gmx.de>
(cherry picked from commit 5a6517425b1484cda727ecb870cd2b286d255c11)

[Backport v2022.1.x] targets/ramips-mt76x8: add device TP-Link RE200 V3

---

docs/user/supported_devices.rst
targets/ramips-mt7621

> Co-authored-by: Jan-Niklas Burfeind <git@aiyionpri.me>
> fixed commit title
> 
> (cherry picked from commit 84a76af8660a3a88b06c95d1bd8bb7a37defdab7)

[Backport v2022.1.x] ramips-mt7621: add Xiaomi Mi Router 3G

---

package/gluon-core/luasrc/usr/bin/gluon-info
package/gluon-core/luasrc/usr/lib/lua/gluon/ethernet.lua
package/gluon-core/luasrc/usr/lib/lua/gluon/info.lua
package/gluon-web-admin/files/lib/gluon/config-mode/view/admin/info.html
package/gluon-web-admin/i18n/de.po
package/gluon-web-admin/i18n/gluon-web-admin.pot

If wanted I can split the info modularization in it's own PR aswell

Add ethernet module, add get_switch_type, make info shared, display switch type in info

---

README.md
contrib/ci/minimal-site/site.conf
contrib/ci/olsr-site/site.conf
docs/conf.py
docs/features/dns-cache.rst
docs/features/vpn.rst
docs/releases/index.rst
docs/releases/v2023.1.rst
docs/site-example/site.conf
docs/user/getting_started.rst

See https://md.darmstadt.ccc.de/gluon-v2023.1-rn?edit#
Still needs description for the Wireguard-key-translation (@AiyionPrime) and Cellular features (myself).

docs: add v2023.1 release notes

---

docs/features/dns-cache.rst

Fix the example config for the dns upstreams.

docs: avoid DNS request loop

---

contrib/depdot.sh

Instead of poorly parsing Makefiles using grep, use OpenWrt's processed package info files. This fixes handling of DEPENDS fields spanning multiple lines and adds support for source packages building multiple binary packages.
Closes #2814
--- 
Output for current master:
... this might also need some filtering feature to be useful with the number of packages and dependencies in current Gluon, but at least it produces valid dot again.

contrib: depdot: use processed package info

---

modules
scripts/modules.sh

[v2023.1.x] Prefer packages from Gluon feeds to upstream feeds

---

package/gluon-core/luasrc/lib/gluon/upgrade/300-firewall-rules
package/gluon-status-page/luasrc/lib/gluon/upgrade/500-status-page

Remove old migrations which are due to be removed.

treewide: remove stale migrations

---

docs/user/supported_devices.rst

Pleasing the gods of alphabetical order

docs: apply sort in alphabetical order to supported devices

---

.github/workflows/build-container.yml

Build and release a docker container for the next branch.

github: release docker container for next branch

---

docs/user/site.rst

I was a bit unhappy with our current docs, as they didn't include an example. I've also reworded the section a bit and added a link to the example section.

Improvements to image customization docs

---

patches/openwrt/0009-mac80211-add-AQL-support-for-broadcast-multicast-packets.patch

Update the broadcast AQL patch to include two patches fixing issues with the initial revision.
Link: https://github.com/openwrt/openwrt/commit/1f5fd5cb971166ba57996d41b7ce71e697c186b2
Link: https://github.com/openwrt/openwrt/commit/163c87dfc20b1004be4e179fa5d59bb1c8925396

mac80211: update broadcast AQL patch

---

docs/user/supported_devices.rst
targets/ath79-generic

Backport ath79 NETGEAR WNDRMAC v2 to v2023.1.x with manifest alias.

[Backport v2023.1.x] re-add: ath79 NETGEAR WNDRMAC v2

---

.github/labeler.yml
.github/workflows/build-container.yml
.github/workflows/build-docs.yml
.github/workflows/build-gluon.yml
.github/workflows/labels.yml

This removes the warnings about Node 10 deprecation in the GitHub CI.

[v2023.2.x] github: update actions

---

scripts/update-modules.sh

A small improvement derived from work we are doing on our side

scripts: update-modules: read feeds from modules

---

package/gluon-wan-dnsmasq/files/etc/init.d/gluon-wan-dnsmasq

Run as dnsmasq user/group + restrict using ujail.
Fixes #3175

gluon-wan-dnsmasq privilege reduction

---

docs/features/autoupdater.rst
docs/user/site.rst

> and how to use them to sign manifests.
Eventually, this resolves #3247.

docs: Add info about ECDSA keys

---

package/gluon-mesh-vpn-core/luasrc/usr/bin/gluon-wan-dns

> to clarify its use-case
this resolves #2160 as suggested by @lemoer 
@neocturne Any objections?

mesh-vpn-core: rename gluon-wan to gluon-wan-dns
